### ISSUE TITLE
Nier:Automata - mouse pointer (524220)

### ISSUE THREAD

**Issue by X6205** [ValveSoftware/Proton#1368]
Nier:Automata is showing mouse pointer in the middle of the screen, but otherwise it's running great :)

There is probaply not much what can i try, but disabling Steam Overlay has no effect and game behaves the same also in the windowed mode. Moving pointer to the side of the screen is possible, but left stick on controller resets position to he center :( 

The same issue is present also under Windows since this game is not very good port. But there is a mod called FAR - fix automata resolution, which among other things, has ability to hide mouse pointer. Not sure if this feature can be somehow implemented to the Proton, but propably more games would benefit from it..
https://steamcommunity.com/groups/SpecialK_Mods/discussions/3/1334600128973500691/

I'm playing with XBOX One controller paired via Bluetooth, Ubuntu 16.04.5 with GTX 1060 + nvidia 396.54

**Comment by whizse** [comment]
You could give unclutter a try, something like:
unclutter -idle 0 -jitter 1000

**Comment by X6205** [comment]
If that is a launch option, then it has no effect. Btw. only time when mouse pointer is not visible is on the loading screen.

**Comment by zaps166** [comment]
If you do Alt+Tab or similar key combination, mouse cursor might go back to the center of the screen (because the key might be still pressed for the game - similar issue can happen on VNC/TeamViewer) - the press Alt, Win, Ctrl, Shift (or more keys if necessary) one after another and try again moving cursor to bottom-right corner. For me it is sufficient workaround when playing on gamepad.

**Comment by whizse** [comment]
No unclutter is a small command line utility that hides the pointer.

**Comment by X6205** [comment]
I see.. Reading manpages, this will propably not help since mouse pointer is not idle in this game. Moving your character with left stick also swings pointer on the screen, like some kind of mouse emulation. This behavior is not present in Windows where you can hide pointer into screen edge.

**Comment by rkfg-bc** [comment]
I had this once after some weird Alt-Tabbing in Big Picture. The game was put in the background and I have to click its window, after that the cursor was stuck in the screen center. However, a simple restart fixed it.

I wrote a little script to help with unclutter. It starts the utility before launching the game and correctly kills it when the game exits.
```bash
#!/bin/sh
unclutter -idle 1 -jitter 50 -grab&
PID=$!
CMD="$1"
shift
"$CMD" "$@"
kill $PID
```
`-grab` is important, without it the cursor appears in the main menu and doesn't go away until I Alt-Tab to another window and back. Put this script somewhere in your $PATH (`/usr/local/bin/hidecursor` for example), do a `chmod +x` on it, then put `hidecursor %command%` into NieR's launch options.

**Comment by cdr255** [comment]
Confirming that on my machine this issue was caused by the use of Alt-Tab, with the game thinking the Alt key was still being held down after returning to play. Tapping the Alt Key one time after giving the game window focus fixed the problem for me on Fedora 28 in Gnome.

(Interestingly, I have a very similar issue on Windows with a different game (Starcraft 2). I wonder if it's related to the way some games deal with losing focus?)

**Comment by rkfg-bc** [comment]
For me that wasn't actually Alt+Tab (just the window going into background and another window popping up) because I was playing with Steam Controller and not keyboard. I also returned to the game by clicking the window without any interacting with keyboard at all.

**Comment by N00byKing** [comment]
For me this happened because I use a PS4 controller, and the touchpad is recognized as a mouse causing every movement to display the mouse cursor (ANY Movement, not only using the touchpad).
Fixed with 
```
xinput --set-prop "Sony Computer Entertainment Wireless Controller Touchpad" "Device Enabled" 0
```

**Comment by N00byKing** [comment]
Issue fixed with Proton 3.16 Beta

**Comment by kisak-valve** [comment]
Is anyone else seeing this issue with Proton 3.16-1 Beta?

**Comment by doitsujin** [comment]
I just ran the game to test something else and yes, after alt-tabbing out of the game and switching back to it, the cursor appeared again.

Since this is a game bug that also affects Windows 10, I'm not sure if there's an awful lot that wine/Proton can do about it.

**Comment by darkpumpkins** [comment]
In my case, i do have less pointer issue on LxQt with openbox than i do have on Gnome-shell. The pointer still appear but i can move it outside on the screen, on gnome-shell the pointer does blink and stay at the center of the screen each and everytime i do touch to the stick on my xbox one controller.

edit : ok same cursor problem when i do alt + tab sequence.

**Comment by Wedge009** [comment]
I just started playing yesterday (August 2025) with vanilla Proton 9.0-4. I'm using borderless window display, so I don't appear to be affected - the mouse cursor appears if I have placed it so, but it is in the position where I placed it, it's not jumping to the centre of the display.
