### ISSUE TITLE
Galactic Civilizations III (226860)

### ISSUE THREAD

**Issue by Dygear** [ValveSoftware/Proton#1508]
# Whitelist Request
- Name of the game to be whitelisted: Galactic Civilizations III
- Steam AppID of the game: 226860

## System Information
- GPU: GTX 1060 Ti
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.15.0-34-generic
- Link to full system information report as Gist: [System Report](https://gist.github.com/Dygear/9a11806d74de54052fbd38dacf4277a9)
- Proton version: 3.7-6

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.

## Issues
- [x] I haven't experienced any issues.

## Experience
As a test I ran the application, that opened flawlessly the first time running it, and then started a new game with the highest settings. There was slight slow down in the video animation during the loading and generating of the map, but it's exactly the same as you would see on the Windows version.

**Comment by andrebadaia** [comment]
I had problems when I generate games with more than 28 players - the ships and planets tiles just disappear! I believe this issue is a memory allocation problem.

Distro: Linux Mint 19 Tara
Processor: AMD Ryzen 7 1700
GPU: GTX 1070, Nvidia proprietary driver 410.78
RAM: 32GB
Kernel (custom) - 4.19.8 (lowlatency, high responsibility)
Resolution: 1920x1080
Proton 3.16-4

**Comment by kisak-valve** [comment]
Hello @andrebadaia, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by Dygear** [comment]
Any movement on this @kisak-valve ? Seems to run ok on my system, can anyone else confirm?

**Comment by jbwyatt4** [comment]
Does not run well on my system.

Distro: Ubuntu 18.04 & Manjaro Cinnamon
Driver/LLVM version: nvidia 4.30.40 (also tested with 390)
Kernel version: 4.15.0-51-generic
Proton 4.11-2 & 4.2-9

GalCiv 3 launches with the Stardock dock launcher first. A small window with news and the play button.

On first run the Stardock dock appears a little dark.

Second run, even if restart or not, the dock's gui never updates (never paints) so whatever was under the window does not repaint. If you were to switch to another virtual desktop this section of the screen would still refuse to update even if the dock was not on that virtual desktop.

You can reproduce this by starting the dock, running the game, exiting, then relaunching the game from the steam client.
The dock should now refuse to paint.

4.11-2 Proton Log
https://gist.github.com/jbwyatt4/b187724fb43265b490bedc54803b16c6

***
Galactic Civilizations III Stardock window does not draw (update)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/2985.
@jbwyatt4 posted on 2019-08-17T06:14:30:

# Compatibility Report
- Name of the game with compatibility issues: Galactic Civilizations III
- Steam AppID of the game: 226860

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 4.30.40
- Kernel version: 4.15.0-51-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/jbwyatt4/b187724fb43265b490bedc54803b16c6
- Proton version: 4.11-2 (also tested with 4.2-9)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game. (I have Sep 2018, but they did not have this problem. https://github.com/ValveSoftware/Proton/issues/1508 )
- [X] that I have checked whether there are updates for my system available.



## Symptoms 
The Stardock window provides news and a button to play the game when you launch the game on Steam. You need to click a button to close the window and run the game.
The dock after the second launch refuses to paint itself on the GUI. Whatever was on the screen before the window was launch stays there despite that you click random parts and you may trigger a button.
Of note: If you were to switch to another virtual desktop this section of the screen would still refuse to update even if the dock was not on that virtual desktop. That section of the XWindows screen is grabbed by Proton and refuses to repaint.

## Reproduction

You can reproduce this by starting the dock, running the game, exiting, then relaunching the game from the steam client.
The dock should now refuse to paint.

This is reproducible even if you switch distros. Initially encountered on Manjaro Cinnamon, reproduced on Ubuntu 18.04.

**Comment by kisak-valve** [comment]
Hello @jbwyatt4, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the issue, and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by andrebadaia** [comment]
The new version of the game (3.96) is crashing after the launcher closes. It opens with Proton 4.2-9, but crashes in Research screen. I have tried with/without DXVK, turn off ESYNC, but the crash remains.

The same problem occurs with Wine-Staging 4.19/4.20 - but the game works with Wine Stable 4.0.2.

Correction: I deleted the user files of the game and the Proton 4.2-9 stop freezing at Research Screen. The 4.11-8 remains crashing.

Distro: Linux Mint 19 Tina
Processor: AMD Ryzen 7 1700
GPU: GTX 1070, Nvidia proprietary driver 440.26
RAM: 32GB
Kernel - 5.3.11-050311-generic
Resolution: 1920x1080
Proton 4.11-8

**Comment by BabylonAS** [comment]
I'm using the GloriousEggroll Proton 5.9-GE build now, the game runs but it's terribly slow on the shipyard screen, despite the fact that I'm no longer playing it on my integrated graphics (and even then it didn't slow that much down).

**Comment by kisak-valve** [comment]
Galactic Civilizations III: No mouse cursor painted in-game

Issue transferred from https://github.com/ValveSoftware/Proton/issues/4276.
@someg33zer posted on 2020-10-16T12:07:27:

# Compatibility Report
- Name of the game with compatibility issues: Galactic Civilizations III
- Steam AppID of the game: [226860](https://store.steampowered.com/app/226860/Galactic_Civilizations_III/)

## System Information

- GPU: custom Nvidia GPU based on the GeForce 860M (Dell Alienware Alpha R1)
- Driver/LLVM version: 4.6.0 NVIDIA 453.21
- Kernel version: 5.4.0-51-generic
- Link to full system information report as Gist: https://gist.github.com/someg33zer/be2456e36038175c8663687b02f27233
- Proton version: 4.2-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

NB: When adding PROTON_LOG=1, the game does not run.  The screen goes black as if the game is loading but then it disappears and the game is no longer running.  Removing PROTON_LOG=1 makes the game run OK.  Here is the the log anyway:

[steam-226860.log](https://github.com/ValveSoftware/Proton/files/5391249/steam-226860.log)

## Symptoms

When you start a new game, there is no mouse cursor painted on the screen although controls highlight and unhighlight while moving the mouse around.

Originally I created this issue to say that the screen freezes when clicking on ships.  However while collating all the information for the issue, the mouse cursor seems to have disappeared and I can't seem to get the game to run in a way that makes the mouse cursor visible.

Various issues persist using combinations of PROTON_USE_WINED3D=1, PROTON_NO_EFUSE=1 and all versions of Proton.  Sometimes the game will just crash on startup.  With the Glorious Eggroll version of Proton, sometimes the game starts eating up memory until it's killed by the kernel.

## Reproduction

Run game.  Click on "Quick start" in the main menu (with visible mouse cursor).  When the new game appears, no mouse cursor is visible.

**Comment by BabylonAS** [comment]
Looks like either disabling ESYNC or enabling low-res textures inside the game (or probably a combination of both) solved the issue with shipyards (and also with battle viewer).

I noticed Proton 5.13-1 reportedly runs Ashes of the Singularity again. I think the regression that was fixed also applies to GalCiv3, so probably GalCiv3 would run as well under 5.13?

**Comment by someg33zer** [comment]
My report [above](https://github.com/ValveSoftware/Proton/issues/1508#issuecomment-710017864) was in error.  I was running with an older 2.x version of the game.  The other issue I mentioned with the freezing of the display was still present with Proton 5.0-9 using the latest 4.x version of the game.

With the latest Proton, 5.13-1, the 4.x version of the game crashes in the tutorial but runs OK in a normal game for the most part.  Often though, the game will start eating RAM until it's killed by the OOM Killer, either before the video plays when the game is first run or while loading a saved game.

**Comment by disruptek** [comment]
> GalCiv 3 launches with the Stardock dock launcher first. A small window with news and the play button.
> 
> On first run the Stardock dock appears a little dark.
> 
> Second run, even if restart or not, the dock's gui never updates (never paints) so whatever was under the window does not repaint. If you were to switch to another virtual desktop this section of the screen would still refuse to update even if the dock was not on that virtual desktop.

I reproduce this on proton-5.13-6; a work-around is to mark `gamedata2.dat` as read-only -- this prevents the launcher from corrupting it and allows the game to run as usual.
