### ISSUE TITLE
Super Lucky's Tale (847360)

### ISSUE THREAD

**Issue by rcgamer29** [ValveSoftware/Proton#1570]
# Compatibility Report
- Name of the game with compatibility issues:Super Lucky's Tale
- Steam AppID of the game:847360

## System Information
- GPU: GTX 960
- Driver/LLVM version: nvidia 396.54.06
- Kernel version: 4.18.8
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/rcgamer29/344a01f7281127f87136d1fc1c8f8c76
[steam-847360.log](https://github.com/ValveSoftware/Proton/files/2409172/steam-847360.log)

- Proton version:3.76 beta

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

**Comment by rcgamer29** [comment]
[steam-847360.log](https://github.com/ValveSoftware/Proton/files/2409163/steam-847360.log)

**Comment by kode54** [comment]
Confirmed.

https://gist.github.com/kode54/3ff952f39b407d6f806a6779838f5335 (the RX480)

It's even worse if you try to run it with WineD3D11: The menus and in-game just display a black screen.

E: Issue does not occur with a fully Wine'd copy of Steam, running under wine-d3d9-staging (3.15~b) from ppa:commendsarnex/winedri3. All 3D objects appear to render correctly there.

E2: But the controller is completely unusable under Wine Staging, using SC-Controller.

**Comment by kode54** [comment]
This may be relevant to this issue, and why the game worked in wine-staging:

https://www.phoronix.com/scan.php?page=news_item&px=DXVK-0.90-Released

**Comment by kode54** [comment]
Not fixed by Proton 3.16-1 Beta.

Updated RX 480 stats:

https://gist.github.com/kode54/3ff952f39b407d6f806a6779838f5335

Updated log attached.
[steam-847360.log](https://github.com/ValveSoftware/Proton/files/2477010/steam-847360.log)

**Comment by kisak-valve** [comment]
Hello @kode54, the VK_EXT_transform_feedback patches haven't landed in mesa-git yet. You need https://patchwork.freedesktop.org/series/50968/ applied to git master to test the new behavior.

Alternatively, if you're feeling adventurous, you could give mesa from https://launchpad.net/~kisak/+archive/ubuntu/steamvr a try. That patch set has been and some backports to get it to build have been applied, but there hasn't been much testing with it so far.

**Comment by kode54** [comment]
Holy crap, it includes a kernel, too? I'll have to look into that tonight, or maybe now, if I feel like moving my call to my tablet. I see it also is compiled without ZFS. Good thing I've got zfs-dkms installed, because I'm on a ZFS root! (Also using the ZFS latest-stable PPA, because the stable 0.7.5 doesn't link against 4.18 kernels.)

**Comment by kode54** [comment]
Okay, that Mesa package is cursed or something. Running that kernel, or the mainline 4.18.14 generic kernel, those Mesa drivers, and Proton 3.16-1 Beta, Super Lucky's Tale gets ingame to just a black screen, plays sound for a while or looping, then locks up the entire machine.

E: New issue with 4.18.14-generic, and Padoka PPA: Steam Controller input, as well as keyboard input, seems to auto release repeatedly. This manifests as button presses being ignored, as well as moves like digging diving in and out of the ground repeatedly, when it's not deciding that you've stopped holding the joystick away from center. Changing the angle of the joystick seems to keep it happy temporarily.

**Comment by kisak-valve** [comment]
The kernel in that PPA has some patches for SteamVR, as that's the primary purpose of the PPA. It's an independent component from the mesa build and not needed for this.

**Comment by rcgamer29** [comment]
This issue is fixed in the newest beta using the newest beta Vulkan drivers from nvidia. Works perfectly.

**Comment by kode54** [comment]
Confirmed the above linked patch fixes the graphics for Proton 3.16-1 Beta. Too bad the Steam Controller support is totally broken. Need a PROTON_LOG again?

Also, LOL, apt wants to upgrade over my unsigned self-built mesa-vulkan-drivers with the identically versioned signed package from the PPA. It doesn't care about all the rest of the unsigned packages I also installed.

Here's a log:
[steam-847360.log](https://github.com/ValveSoftware/Proton/files/2481230/steam-847360.log)

I found out that the shoulder button used for digging only seems to release itself repeatedly in Proton 3.16-1 Beta if I actually move the analog stick. If I keep the analog stick perfectly angled to the same direction, none of the buttons release themselves repeatedly. The moment I change direction, *pop* it releases itself momentarily and the character pops out of the ground and dives back in again.

The controller issue does not occur with 3.7-8 or 3.7-8 Beta, but the graphical issue is not fixed by that version.

**Comment by kode54** [comment]
Confirmed the controller issue does not affect my Wireless Xbox 360 Controller. So far, it only appears to affect Steam Controllers.

**Comment by kode54** [comment]
Reporting that 3.16-2 Beta does not fix the Steam Controller issues.

**Comment by fsyy** [comment]
here it does affect my xbox controller too, proton 4.11-2
