### ISSUE TITLE
A Hat In Time (253230)

### ISSUE THREAD

**Issue by NanoSector** [ValveSoftware/Proton#173]
When installing this game via Steam it seems to work nearly perfectly apart from a few occasional graphical and sound glitches (most notably the sound effects in Mafia Town are broken). Controller support is better than in vanilla/staging Wine, using an Xbox 360 controller works. No additional tweaks were needed, framerate in the Hub is 120+ FPS, in in game areas it drops to around 60/70 FPS.

EDIT: The audio issues might be caused by https://github.com/ValveSoftware/Proton/issues/54.

* Fedora 28 64-bit
* Radeon RX 580
* Intel Core i5 6400
* Proton 3.7, default configuration (as said, no tweaks were used)

**Comment by leosilvapb** [comment]
How did you install Fedora 28? for me the following error appears:
Traceback (most recent call last):
   File "./build-runtime.py", line 13, in <module>
     from debian import deb822
ImportError: No module named debian

**Comment by NanoSector** [comment]
I installed the Steam package from rpmfusion and switched it to the Beta. That's pretty much all, it instantly worked for me.

**Comment by leosilvapb** [comment]
thanks, it worked here after reinstalling steam

**Comment by E100Beta** [comment]
Installing xact didn't fix sound for me for some reason. On the contrary, the game started crashing on launch. Couldn't figure out why. Aside from sound - yeah, game works pretty well. OS is Archlinux.

**Comment by NanoSector** [comment]
Do you perhaps have any logs from Wine/Proton?

**Comment by ghost** [comment]
@E100Beta Are you using steam-native or steam-runtime? Whichever it is, try the other one. Things were crashing for me a lot with steam-runtime but they run great with steam-native.

**Comment by NanoSector** [comment]
I believe I was using the Steam runtime as well in my tests. Will double check when I get home later.

**Comment by siramok** [comment]
Game installs and runs in a playable but imperfect state, IMO it's not yet ready to be whitelisted.

In the hub I sometimes get crackling audio that quickly goes away on it's own. In a stage, the music volume is either really loud or dialogue is very quiet, but either way, dialogue can barely be made out over the music. Adjusting the volume per the in-game sliders seems to have no effect.

Act 1 and 2 of Chapter 1 has minor graphical glitches, but nothing too distracting. In Act 3 of Chapter 1 however, the whole screen becomes white when the camera is moved in and out of certain positions (I'm thinking it has to do with light sources?). As you traverse the level, your screen will constantly flash white and it's very annoying.

Overall performance is pretty good while using the "standard" graphics preset.

- Solus 3.999 w/ latest updates
- Radeon RX 480
- Intel i5 7600K
- Proton 3.7

**Comment by NanoSector** [comment]
I do not share that same experience. The minor graphical glitches I experience are almost negligible (in the scale of a texture sometimes being a bit fuzzy) and the sound issues you describe can be fixed by installing xact, although I haven't had the crackling audio issue (yet).

**Comment by siramok** [comment]
I installed xact per your recommendation: crackling only happens for a brief moment during the chiming sound effect that plays when entering the hub. Sound sliders in the settings menu are still broken, but I concede that dialogue sounds more balanced with music/effects.

Having playing for two hours, it seems that Mafia Town is the only area to be plagued with any graphical glitches (negligible for the most part, yes). The later stages don't seem to have any graphical glitches at all.

**Comment by cjwijtmans** [comment]
#54

**Comment by ghost** [comment]
A Hat in Time isn't centered; it's screen is moved slightly offscreen to the bottom right. Also stuttering when you go to the hub but that goes away quickly.

Distro: Ubuntu 18.04.1
GPU: Intel Iris Pro 580
Resolution: 1280x720
RAM: 32GB
Proton 3.7-5 Beta

https://gist.github.com/daasuharo/cb605b8cd50227982a9bfa4dfcb1f635

**Comment by NanoSector** [comment]
Can you share a screenshot describing what you mean, because I don't think I suffer from that problem but I would like to double check.

**Comment by ghost** [comment]
![screenshot from 2018-08-30 17-18-36](https://user-images.githubusercontent.com/1419625/44884495-e0a89e00-ac78-11e8-9ec4-109dbdeeb02c.png)

**Comment by OrdinaryMagician** [comment]
Performance is pretty bad on my end, getting around 20 FPS with the same settings as on Windows (1920x1080, everything maxed out), where I would maintain a constant 60. Even on lowest possible settings it still has some slowdowns. I don't understand how it can run this badly.

Some of the graphical glitches mentioned in here seem to have gone away with 3.7-5 Beta (I'd see them with earlier versions).

PS: Enabling developer console causes the game to crash on launch.

Distro: Arch Linux
GPU: GTX 1060 6GB
RAM: 16GB
Proton 3.7-5 Beta

**Comment by Ghabry** [comment]
I also have sound issues (sliders not working and almost silent) and very low FPS, unplayable.

CPU: Core2Duo
Distro: Arch Linux
GPU: GTX 1050
RAM: 4GB
Proton 3.7-5 Beta

My PC has bad specs but the game it playable under Windows.

**Comment by NanoSector** [comment]
I have no sound issues in mafia town, but after revisiting it I do see the graphical glitches talked about.

As a side note, I've successfully completed the main quest on Linux now so at least the game is fully playable.

**Comment by tyisafk** [comment]
I'd also like to report that installing xact causes the game to crash at launch for me.  Used ProtonTricks.  Deleting the prefix fixes the issue since it rebuilds itself.  Shame, at least on my end, xact is the only thing that will make the game work 100%, but the game is totally playable with glitched sound.  For me, the music is way too loud and adjusting it in-game does nothing.  Framerate is pretty good as well.  Not as good as Windows, but as a 144hz display user, I just set the FPS cap in-game to 48 (1/3 of 144hz), then enable VSync.  (Still looking forward to the day FreeSync comes around for good) The only thing that performs less than optimal is the pause menu.  The game runs under DX9 so it's using Wine's built-in translator.

Specs:

- AMD Ryzen 1700
- AMD R9 390X
- 16GB DDR4
- AMDGPU Kernel Driver
- MESA 18.1.7
- LLVM 6

**Comment by NanoSector** [comment]
Seems like the latest update broke controller support, at least for me.

**Comment by Jibodeah** [comment]
Controller support still seems fine for me (Steam Controller, Proton 3.7-6).

Additionally I found a workaround for the audio bugs. I had tried installing xact via winetricks like is suggested in this thread but that caused the game to crash on launch. Instead you can just set a library override for `xaudio_2_7` to native, builtin and that fixed it for me. (It's good to hear the adaptive music in the Spaceship again!) Credit to [lavadrop on this other issue](https://github.com/ValveSoftware/Proton/issues/54#issuecomment-420124026).

**Comment by OrdinaryMagician** [comment]
Huh, setting just that instead of installing xact fixed the crash on launch with developer console enabled.

**Comment by lucifertdark** [comment]
I've got another strange bug
![20180919085630_1](https://user-images.githubusercontent.com/43232878/45739140-168ed180-bbea-11e8-9f74-84736038d63b.jpg) This happens when the camera is moved around, Chapter 1 Act 3, I've adjusted the graphics settings from high performance right through to very high quality & the results are the same, at certain angles the screen goes totally white. any ideas? 

https://gist.github.com/lucifertdark/584c14275612e8e3c4a8070d428d8a02

Nvidia drivers 396.54.05

Everything else is working just as it should after the xaudio2_7 tweak.

**Comment by OrdinaryMagician** [comment]
I've seen this graphics glitch too on some time rifts.

**Comment by rcgamer29** [comment]
There are graphic glitches and sound issues that need a workaround.

**Comment by flibitijibibo** [comment]
Compatibility should improve with FAudio, here’s a demo with the COM wrapper:

https://youtu.be/I9NEkqfhWDw

This still needs to be integrated into the official XAudio2 DLLs but we know the implementation works as of now.

**Comment by DragonFire168** [comment]
I've got the white artifacts in Ch1 when ever its raining and also in Ch2 Act 1 I've occasionally got white textures instead of what's supposed to be there. Also on nVidia [390.87] (using reverse PRIME). Sound works for me using protontricks xact.

**Comment by good-praxis** [comment]
There seem to be further regressions here. 

Tried with both nVidia[396.54] as well as [410.66]
On Proton [3.16-3 Beta]

on (abridged:)
```
Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD FX(tm)-8350 Eight-Core Processor           

Operating System Version:
    elementary OS 0.4.1 Loki (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-36-generic
    Steam Runtime Version:  steam-runtime-beta-release_2018-09-03

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1070/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.54
    OpenGL Version: 4.6
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Bus: PCI Express 16x
    Primary VRAM: 8192 MB

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  16063 Mb
```

Audio slows down and crackles with xact and xaudio2_7, this doesn't happen without xact and xaudio2_7, however then the sound settings again have no effect.

This worked fine at 3.7-6.

**Comment by ryao** [comment]
@kisak-valve This should be closed/renamed. This game is definitely not ready for the white list due to xaudio2 issues and visual corruption in act 3 of chapter 1.

**Comment by flibitijibibo** [comment]
@kisak-valve Requesting an XAudio2 label for this game...

**Comment by aljelly** [comment]
Game runs quite slow for me. The strange thing is that I'm using the same GPU as the OP, an AMD RX 580.

- Fedora 29 (Pantheon DE on XOrg)
- AMD RX 580 (AMDGPU)
- Proton 3.16-4 beta

**Comment by Ghabry** [comment]
Since the latest Proton update which improved Audio everything works fine for me

**Comment by lucifertdark** [comment]
> Since the latest Proton update which improved Audio everything works fine for me

How about the graphical glitches on Act3 of Chapter1? I'm still seeing the white screen here.

**Comment by nonamethanks** [comment]
> How about the graphical glitches on Act3 of Chapter1? I'm still seeing the white screen here.

Can confirm. And it's not just that, but also the rock textures in Alpine Skyline (Chapter 4) which are completely missing.

**Comment by chewi** [comment]
I heard that the white screen issue goes away with Gallium Nine and I verified this myself by using the new Gallium Nine Standalone against Proton. The performance is much better now.

Unfortunately, even before trying Gallium Nine, I have found the game to be much more unstable recently, possibly since a Proton update or adding Seal the Deal. I had just more or less finished the game without much trouble but it's now crashed 4 times in the last 24 hours. Unfortunately Gallium Nine doesn't seem to help here.

UPDATE: Okay, the combination of Gallium Nine and switching down to Very High seems to help but hard to say, it's quite random. Managed to do Act 1 of the cruise at least.

**Comment by Lightsockie** [comment]
Just finished full clearing the game on max settings. Only issue I had was the already mentioned problem with Chapter 1 Act 3's rain, which would sometimes make the level hard to navigate. Seems like the rain is causing massive white cylinders to appear (potentially the rain object is a cylinder and it's boundaries are erroneously showing up?).

I made no changes, just installed and ran.

- Arch Linux
- AMD Ryzen 5 2600X
- Radeon RX 580 (AMDGPU)
- Proton 3.16-6

Edit: If you go into `HatinTime/HatinTimeGame/Config/HatinTimeSystemSettings.ini` and set `FogVolumes=False`, the above mentioned graphical issues are fixed. Making the game 100% working flawlessly

**Comment by Francesco149** [comment]
**EDIT: fixed by using proton 3.7-8 and installing** ```protontricks 253230 -q d3dx9_43 d3dcompiler_43```

**EDIT2: also works on latest proton by installing the same protontricks verbs**

EDIT3: add ```protontricks 253230 galliumnine``` for near native performance on AMD, getting 60-150fps maxed out on a r9 270x

~~could anyone re-test this? I just tried with both proton 4.2-3 and 3.16-9 Beta and it crashes after the splashscreen. overriding xaudio2_7 or xaudio_2_7 doesn't help either. installing xact or faudio didn't help.~~

~~according to the log it's complaining about D3DXDisassembleShader not being implemented, but I'm not sure that's the cause of the crash, so I'd like to hear from people who got it running and see if they also get these errors or not~~

```
"CriticalError: 3D9Shader.cpp,D3D9CompileShader:293  Assertion failed: SUCCEEDED(D3D9SafeDisassembleShader((const DWORD*)ShaderByteCode->GetBufferPointer(),FALSE,NULL,&DisassemblyBuffer)) 'Failed to disassembly shader bytecode.'"
```

~~full log:~~ https://gist.githubusercontent.com/Francesco149/724f86f70195eac00632e4ea8f2599cd/raw/523c8d90ee780a7fd3ce1000fcc3636d54e58105/steam-253230.log

~~system info:~~ https://gist.github.com/082d7fb766ec4d346df20bad7b56851f

~~btw, in that log i had copied d3dcompiler_47.dll from another game into the game's directory (which silenced more errors about shader compilation), but the result was the same even before doing so~~

**Comment by Francesco149** [comment]
no graphical glitches as far as I can tell with gallium nine. I have played for over 100 hours on very high settings except for ambient occlusion which i lowered to get 120+fps

also, with faudio installed through protontricks I don't hear any audio glitches either.

only issue is that the steam overlay doesn't work with gallium nine, but that's normal. I don't even know if it's possible to hook gallium nine for the overlay

**Comment by hexadecatrienoic** [comment]
The game will not launch with the Nyakuza Metro DLC installed on Proton 4.2-3.

**Comment by kisak-valve** [comment]
Hello @hexadecatrienoic, with the DLC installed, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by Francesco149** [comment]
can confirm, in the proton log i can see the following:

```
23392.542:0028:0029:err:steamclient:create_win_interface Don't recognize interface name: SteamNetworkingSockets002
23392.542:0028:0029:err:steamclient:create_win_interface Don't recognize interface name: SteamNetworkingUtils001
```

will investigate later

**Comment by Francesco149** [comment]
here is the full log, don't mind the "translating..." messages as it's hooks for nfs compatibility I injected https://gist.github.com/fcddbdac95a79e9c854da1bce43628f8

**Comment by Francesco149** [comment]
I'm guessing we're gonna have to wait for a proton/steam update that adds support for the new steam networking api

EDIT: yeah it's in the steam works sdk 1.44 which is missing from lsteamclient. gonna see if i can add it myself

**Comment by serebit** [comment]
@Francesco149 I'm also having this issue, let me know if you've figured out a solution.

**Comment by SergioGlorias** [comment]
@kisak-valve my log the proton 4.2-3
ativate new dlc
https://gist.github.com/smglinuxl2g/115bd6989fc9545b89a53037cd5e56c0

**Comment by Francesco149** [comment]
turns out this is tricky to implement with the current wrapper generator used by proton because there's a lot more c++ isms in the networking headers like reference params.

hopefully valve will start working on this, ill still mess around with it to see if i can hack together a temporary solution

**Comment by Askannz** [comment]
Yeah, same here. Goddamit, I was really looking forward to this DLC. Here's the log : https://gist.github.com/Askannz/447e2f8247c6422198004e087a9edd0c

**Comment by Askannz** [comment]
Good news : the game at least launches with the Windows version of Steam running through Wine (haven't started playing yet, though).

![Screenshot_20190511_163800](https://user-images.githubusercontent.com/9202863/57566048-3b4ee800-740b-11e9-9ef8-c066daa24fc1.png)


EDIT : needs some audio overrides though. At least `xaudio2_7`, maybe `xact` too.

**Comment by SergioGlorias** [comment]
I can play! I just have to disable DLC in the DLC installed area. I wanted
to play the DLC but it does not give because it activates things that the
proton there is not

Em sáb, 11 de mai de 2019 07:40, Robin Lange <notifications@github.com>
escreveu:

**Comment by Francesco149** [comment]
yeah you can definitely use the "steam (windows)" installers from lutris to make it work for the time being https://lutris.net/games/a-hat-in-time/

**Comment by Johndeep** [comment]
Debian Unstable, Intel graphics, modesetting and proton 4.2-3 here.

After the update yesterday, I have noticed more crashes than before unfortunately. But they happened randomly, after seemingly starting to load something while being frozen. But one crash (among some maybe) I can not outrun is to load Chapter 3, Subact 2 The Subcon Well. I simply can not enter that level anymore, even after several tries. It always crashes while loading something or waiting for something.

The procedure from starting the game until the loading of the mentioned chapter is logged here:
[steam-253230.log](https://github.com/ValveSoftware/Proton/files/3169221/steam-253230.log)

**Comment by serebit** [comment]
I can't load Chapter 3 Act 2 either. That said, the game does manage to run an online party in the new DLC if I run the game via Steam in Wine, even outside of Lutris.

**Comment by Francesco149** [comment]
chapter 3 act 2 (subcon well) loads and plays fine for me on a non-proton wine prefix, using the runner ```ge-warframe-protonified-4.7-x86_64``` from lutris (but i configured my prefix manually)

wine prefix has ```corefonts vcrun6 steam d3dx9_43 d3dcompiler_43 galliumnine``` installed

haven't tested on proton though

**Comment by Johndeep** [comment]
I don't know if it is due to "A hat in Time" or the memory management of Proton (4.2-3), but in the Chapter 4 Alpine Skyline, the freeroam part (please no spoiler beyond this), I tend to run out of video memory it seems. Because after a while strolling around the Skyline, the game just freezes. After switching out of the game, I noticed that Wine/Proton had a Dialog Window with "Ran out of video memory". I hope it is a fixable memory leak.

But due to Steam, I want to wait patiently for an official update of Proton (to 4.8 or even newer if possible). I don't like to tinker around too much in the system.

**Comment by Francesco149** [comment]
@Johndeep my vram usage in that area hovers slightly above 1GB but doesn't grow, which is well within my 2GB of vram. other areas are slightly below 1GB. maybe you have  a 1GB card? i would try tweaking graphical options that can reduce vram usage if so

nyakuza metro is by far the most vram intensive area, at over 1.6gb sometimes spiking to 1.7, but still not running out of vram

**Comment by Johndeep** [comment]
@Francesco149 ah well, if that's the case, I have an Intel graphics 620 HD with shared VRAM. But since it is shared with the system RAM, and I can somehow configure the VRAM in the BIOS. I assume it is capped at 512MB RAM, but it would be nice to configure Proton to use more RAM for video, since I should have plenty.

Despite that, A hat in time was more stable before the nyakuza update (and I do not mean the DLC, but the huge 2.6GB update around 2-3 day prior today).

**Comment by Francesco149** [comment]
since the recent patches entering the snatcher boss fight completely locks up my system on gallium nine. d9vk runs ~20% worse than gallium nine but at least it still works.

**Comment by aeikum** [comment]
@Francesco149 Wow yeah that new API is a beast, isn't it?

The broken Steam API support will be fixed in an upcoming Proton release.

**Comment by ghost** [comment]
Thanks to everyone over in the gallium nine github tracker for figuring this out.

Run the game with `R600_DEBUG=mono %command%` in Steam launch options, or `AMD_DEBUG` instead of `R600_DEBUG` if you're on very recent versions of mesa.

Turn off "Dynamic Lights" in options too. Everything else could be max. This option would lock my game up in certain areas (like the bathroom in Chapter 1 Act 4).

I was unable to configure a controller after installing Gallium Nine, I needed to make a custom controller profile in the game for my PS4 controller first, then install Gallium Nine, and it works great.

**Comment by Francesco149** [comment]
@z0z0z thank you for debugging that! it's weird that it used to work before nyakuza, i wonder what happened. I'll probably try and put together a bug report

**Comment by kisak-valve** [comment]
Hello @z0z0z, your issue sounds like the issue being tracked at https://github.com/iXit/wine-nine-standalone/issues/35.

**Comment by serebit** [comment]
Do we have an ETA on the next Proton release, the one that fixes the issue with the new networking API?

**Comment by tomiga** [comment]
Running into the same issue as @Johndeep and @serebit above where loading Chapter 3 Act 2 (Subcon Well) crashes the game every time. Debian Stretch (stable), nVidia driver 418.56 from backports with Proton 4.2-4.

**Comment by Alex-gnzl** [comment]
The game seems to run with Nyakuza Metro as of Proton 4.2-5, as expected

**Comment by Francesco149** [comment]
I see that the new networking api has been implemented, good job to everyone involved!

**Comment by serebit** [comment]
Works for me as well, tysm!

**Comment by Johndeep** [comment]
@serebit, can you load Chapter 3 Act 2 without problems now? Because I still cannot load that level, even with Proton 4.2-5. At least Mods and achievements works again though. The freeze and insufficient vram might be due to Debian (unstable) with only Mesa 18.3.6 (still not 19.0+ due to freeze of Debian). I do hope a newer Mesa will give a boost in performance while fixing some more memory leaks.

**Comment by tomiga** [comment]
@Johndeep for what it's worth, I was able to eventually get past that level by turning on "skip all skippable cutscenes" (or whatever the option is, I can't remember at the moment) right before going to the part where it crashes. Not sure exactly why that helped. It seems like all of Chapter 3 is really unstable for the most part as that's where I experienced every single crash. There's even times when I can't load anything in Chapter 3 without completely restarting my system.

**Comment by serebit** [comment]
Which is bizarre, because Chapter 3 was rock-solid on Proton for me before the Nyakuza update. I managed to get through the entire chapter without crashing once, and now I can’t even start it up.

**Comment by serebit** [comment]
@Johndeep I managed to load into Chapter 3 Act 2, and ran around for a bit. Unfortunately, the online party functionality appears to still be somewhat broken-- when a friend and I join the same online party, I appear for a second for him, and then disappear. For me, I couldn't see him at all. Both of us could see the other as "Connecting" in the top right, but never actually connected.

**Comment by Francesco149** [comment]
@serebit check proton log for gnutls errors. I remember having to install some version of gnutls in my non-proton wine prefix to get party play properly working

**Comment by tomiga** [comment]
Party play doesn't appear to be working for me either, just got stuck at "Connecting" forever. I did try installing the i386 version of libgnutls30 but it didn't appear to make a difference. Log attached.
[steam-253230.log](https://github.com/ValveSoftware/Proton/files/3225736/steam-253230.log)

**Comment by serebit** [comment]
To be clear, online party does still work in normal wine (when using Steam through Wine), so this could be considered a regression.

**Comment by Francesco149** [comment]
hmm yeah I can confirm that I haven't seen it connect once under proton yet, so this could be an issue with proton or the linux version of steamworks, but this can also happen as a temporary unrelated problem, for example during peak hours on nyakuza launch sometimes it wasn't connecting even for windows users

**Comment by aeikum** [comment]
We've seen the same failure. I'm looking into it.

**Comment by aeikum** [comment]
I have what might be a fix for this, and I'd like some testing from some adventurous users.

To test this out, grab this file:
https://www.codeweavers.com/xfer/aeikum/proton/
Password: proton
Filename: lsteamclient.dll.so

Copy it into an existing Proton 4.2-5 installation, in the `dist/lib64/wine` directory. This is likely located at `~/.steam/steam/steamapps/common/Proton 4.2/dist/lib64/wine`. You should overwrite an existing file. All Linux users in a session will need to install this file.

Then try A Hat In Time's online multiplayer and let me know if it works for you. We had mixed results in the office. For us, it often worked, but every once in a while would get stuck on Connecting. It wasn't clear if this was a networking issue, or a remaining problem in our code, so I was hoping to get some results from other testers.

To restore your Proton installation back to its original state, just delete the file `dist/version` (or the entire `dist` directory) and launch any game which uses Proton 4.2.

**Comment by serebit** [comment]
Tested with both the `123` online party and another party with a friend, worked flawlessly both times with the replaced dll.

**Comment by Francesco149** [comment]
works great for me, tested with the party "peck"

thanks for the quick fix!

**Comment by tannisroot** [comment]
Works fine for me too! I can easily connect to party 12345. And I've had occasional connectivity issues even with Windows version of Steam so it's probably not your issue.

**Comment by tannisroot** [comment]
Unfortunately it also seems like this fix broke sticker collection (they item that can be traded on Steam market), they no longer spawn for some reason.

**Comment by sykhro** [comment]
That library fixes the problem for me as well.

**Comment by Francesco149** [comment]
@tannisroot sticker issue might be unrelated to the networking fix. other people report issues getting stickers to spawn. maybe there's just some randomness or the devs are breaking stuff

https://steamcommunity.com/app/253230/discussions/1/1651045226235108890/

**Comment by tannisroot** [comment]
@Francesco149 it's just weird that it immediately worked after I used Windows version of Steam running under Wine. However it seems like I experience this issue even after restoring the original .so file.

**Comment by aeikum** [comment]
Thanks for testing, all. It sounds like this may have fixed the problem. Happy to hear from more testers.

**Comment by Lightsockie** [comment]
Last night me and a buddy (who was also using your fix) were able to play together, and while I was streamin' I had probably around 16 or so random people come and go, none of which mentioned anything about connectivity issues. So yeah, I think ya fixed it. I get occasional crashes, but I think that's just the game.

~What did you change, @aeikum?~ Oh, you're a dev haha. I thought you were some guy reverse engineering. I was super curious how ya did it. Never mind you can keep your secrets :^)

**Comment by aeikum** [comment]
It's all public, check out `lsteamclient` in this repo. There are a number of problems with struct layout and calling conventions in the existing code, which I fixed. The changes will be in the next Proton release.

``` lsteamclient/cb_converters.dat                                        |   1 +
 lsteamclient/cb_converters.h                                          |   4 ++++
 lsteamclient/cb_getapi_sizes.dat                                      |   2 ++
 lsteamclient/cb_getapi_table.dat                                      |   6 ++++++
 lsteamclient/cppISteamNetworkingSockets_SteamNetworkingSockets002.cpp |  18 ------------------
 lsteamclient/gen_wrapper.py                                           |  41 ++++++++++++++++++++++++++++++++---------
 lsteamclient/steamclient_manual_144.cpp                               |  68 +++++++++++++++++++++++++++++++++++++++++++++++++++++---------------
 lsteamclient/steamclient_wrappers.c                                   |   2 +-
 lsteamclient/steamworks_sdk_144/isteamnetworkingsockets.h             |   2 +-
 lsteamclient/struct_converters.h                                      | 106 ++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------
 lsteamclient/struct_converters_144.cpp                                |  23 +++++++++++++++++++----
 11 files changed, 171 insertions(+), 102 deletions(-)```

**Comment by Johndeep** [comment]
@aeikum FIrst of all, we have to thank you for taking these issues seriously and making the effort to fix the issues. I cannot wait for the next Proton release! ... to try out if Chapter 3 is still crashing...

But wait, I did try the game without steam overlay. To my surprise, the game ran without problems, even chapter 3 loaded without problems, even at parts, where there are suspicious mini freezes (probably due to loading), which normally always ends in crashes, it won't crash at all!

Update:
Seemingly after some 0 bytes "Steamworks Common Redistributables" updates and several little Game updates and Mod updates (literally in the last 24 hours), the game works with overlay and without crashing (there are still hiccups, but fortunately no crashes, yet). I can even load Chap. 3 without issues. This totally confuses me. Until yesterday, the game crashed every time I loaded Chap. 3 (even with Mods disabled).

Besides this pleasing development of less to no crashes in the moment, the whitening area in Chap 1, Act 3 in rain in example (see above) is still present. Furthermore, there seems to be several areas with completely black textures (i.e. Chap 4 freeroam lava area), dunno if it is a game design choice (would be very irritating) or some texture issues though.

Update 2:
Never mind, almost everything seems to be more stable now, except the (now) infamous Chap 3 Act 2. It seems to be unstable as ever..

**Comment by tomiga** [comment]
Can confirm that the online multiplayer works perfectly now. I haven't tried out Chapter 3 to see if it's as crashy as before but the game does seem overall more stable than previously. Really the only thing that I noticed going between Linux and Windows at this point is that on Linux, the performance is much worse. I get about 30 FPS in Nyakuza Metro with my system (i7 5820K, 32GB RAM, Radeon VII on Mesa 18.3.4, Debian Buster) whereas on Windows 8.1 I stay consistently at 60.

Just thought I'd make note of it -- I'm very grateful for all the progress that's been made to get this game to work through Proton!

**Comment by serebit** [comment]
Performance is definitely worse for me in some areas than it is on Windows 10. I assume d9vk helps with this if shaders are cached, but I haven't tested recently.

**Comment by tomiga** [comment]
Also just tried out the infamous Chapter 3 Act 2 while it was fresh in my mind to do so -- unfortunately still crashes. :(

**Comment by tannisroot** [comment]
@tomiga Try D9VK. For me it doesn't crash on any of the maps and the game also runs faster than on Windows even.

**Comment by tomiga** [comment]
@tannisroot I'll give it a try once I get off work. Thanks for the tip!

**Comment by Francesco149** [comment]
@tomiga for AMD gpu's gallium nine performs even better than d9vk, try ```protontricks 253230 galliumnine```

**Comment by tomiga** [comment]
@Francesco149 tried out Gallium Nine but it appears that the performance actually became worse -- all it seemed to do for me was make loading screens take forever. Maybe there's something I'm doing wrong, but so far that's the result.

**Comment by Francesco149** [comment]
huh, I guess mileage varies with different gpu's. on my r9 270x and my rx 570 it runs like 50% better than on d9vk

**Comment by chewi** [comment]
@tomiga, anecdotally the loading screens do take longer but I think they're a bit faster on subsequent loads and the in-game performance is much better. That's what counts!

**Comment by OrdinaryMagician** [comment]
I do also see some considerable performance improvements with D9VK on my GTX 1060. Heck, I finally get 60 FPS on Nyakuza Metro, and can even max out all settings.

**Comment by sonic2kk** [comment]
At max settings with D9VK I get a pretty consistent 70-90fps. Galliumnine gave me about 120-140fps but had incredibly long loading times (sometimes up to 5 minutes), would crash if I completed a level and tried to enter another one (same as DXVK) and, the main kicker, no Steam Overlay support - This means no Steam Controller support.

D9VK locks up if I get the sunglasses in Dead Bird Studio and try to look at the camera. Outside of that, the game runs great with D9VK.

**Comment by Francesco149** [comment]
oh yeah i almost forgot, at the moment you have to use ```R600_DEBUG=mono AMD_DEBUG=mono %command%``` as the launch parameter with gallium nine to avoid gpu hangs in certain areas

yes, the first time you load an area with gallium nine is slow, but for me it's worth the increased performance. as for steam controller support, I've been using a ds3 so no problems there.

**Comment by tomiga** [comment]
I've had some time to test things out again in Linux and I found using D9VK offers the best in terms of performance and stability and I just want to give a bit of a report on how things seem to be with my setup.

tl;dr: game runs well save for a few areas like Nyakuza Metro; load times are a bit long the first time; Subcon Forest still crashes a lot

System I'm using to test on: Core i7 5820K @ 4.2, 32GB DDR4-2400, AMD Radeon VII. OS is Debian Buster with Linux 5.0.0 from the experimental repository and firmware-amd-graphics from sid (both needed to get the Radeon VII to work), plus D9VK 0.12 set up in Hat in Time's WINE prefix. I'm comparing to how the game runs between that setup and Windows 8.1, both set to the same graphical settings (max running at 2560x1440, framerate capped to 144 FPS). With that, here's what info I can provide.

I tested out previous scenarios where the game would reportedly crash (Subcon Forest levels, putting on sunglasses in Dead Bird Studio). Unfortunately it looks like all of Subcon Forest is still hit or miss for me and crashes a lot. However I wasn't able to replicate the sunglasses crash (@sonic2kk you may want to try this out again).

I also looked for previously mentioned graphical glitches, like the painful-to-look-at rain in Mafia Town and reflections in Dead Bird Studio, but it seems these graphical bugs are gone.

Performance is unfortunately far from native but is completely playable. On Windows 8.1 it consistently stays at 144 FPS wherever I'm at. On Linux, it averages about 100 FPS, with areas like Nyakuza Metro dropping down as low as 25 FPS at times. Load times are long any time you go to an area the first time and there are stutters as objects get loaded in the first time, but after that, it becomes far smoother. I have a feeling that performance can be fixed down the road however.

Everything else appears to work perfectly.

**Comment by Alex-gnzl** [comment]
Since Proton 4.11-1 the game seems to crash when enabling Online Party with an empty party name, and makes Steam use 100% of one CPU core as a result.
Happens even with no mods.
Using d9vk.
[steam-253230.log](https://github.com/ValveSoftware/Proton/files/3464063/steam-253230.log)

**Comment by DraconYale** [comment]
I'm using Proton 5.0-9 and the game uses nearly all of my RAM from startup (my Steam [Gist](https://gist.github.com/DraconYale/e44350e2260fd1fdd87c9ca16d13c86f))
My launch flags are:
`` PROTON_USE_D9VK=1 PROTON_NO_ESYNC=1 ``
Don't know if it's normal or a game/Proton bug.
![Schermata da 2020-06-26 13-09-41](https://user-images.githubusercontent.com/20669016/85854216-43571c00-b7b4-11ea-93eb-fce9ae6a71df.png)

In addition, if you open a menu the game audio starts crackling after some seconds. When you close the menu the audio is back to normal.
[steam-253230.log](https://github.com/ValveSoftware/Proton/files/4836700/steam-253230.log)

**Comment by Miuzore** [comment]
OS: Archlinux
CPU: Ryzen 5 1600x
GPU: GTX 1060 6GB
RAM: 8GB DDR4
Running on SSD
Tested with proton 6.3 and 5.13, latest (470) proprietary Nvidia drivers, also tried with v.465

The game works really well except for RAM usage, haven't encountered any glitches or audio bugs and it runs relatively smooth. However, the RAM usage is abnormally high, not sure if its proton or just the game itself. My system uses around 800mb-1gb of RAM when steam is running, but when I boot up the game and go into the hub area, it shoots up to 5gb. Loading into a level sometimes makes my machine go oom, requiring a reboot and if it loads into a level the RAM usage gets around 7.5-7.9GB.

**Comment by sonic2kk** [comment]
@Miuzore A Hat in Time uses a lot of ram for me as well, but the usage was not that different for me compared to Windows. Both used approximately 8gb ram, though with mods it went up to around 10gb. I'm also running Arch Linux and have about the same ram usage as you under regular system usage.

The recommended specs for the game do list 8gb, but for one reason or another it seems like this isn't enough. I have not ran the game on a system with 8gb ram, but even on Windows I remember ram usage being quite high.

**Comment by doesthisusername** [comment]
The game has started crashing on 6.3-8 and Proton Experimental recently (Proton Experimental before 6.3-8). Sometimes downgrading to 6.3-7 fixes it (but at the cost of online functionality being completely broken), but it isn't right now, for me. According to [protondb](https://www.protondb.com/app/253230) it may be dependent on Nvidia, but I don't know for sure.

If downgrading the game to a pre-Nyakuza Metro (pre-online) patch (version1.0 or (probably) pre_dlc1 in the betas tab), it works, even on newest 6.3-8 and Experimental, in my experience.

Mainly tested on Arch, 5.15.9, 5800X, 2080 Ti with Nvidia drivers, though I've also reproduced the (a?) crash on a Mint LiveUSB as well as a Ubuntu 20.04 LTS one. I can't rule out the LiveUSB causing those crashes, but log-wise they seemed similar enough.

Experimental logs from right now:
[version1.0_steam-253230.log](https://github.com/ValveSoftware/Proton/files/7762323/version1.0_steam-253230.log) - works
[public_steam-253230.log](https://github.com/ValveSoftware/Proton/files/7762355/public_steam-253230.log) - crashes

Hope this helps, I've been wanting to investigate more myself but am posting this just like this after realizing I wouldn't get anything done otherwise lol

**Comment by rnanua95** [comment]
The game also crashes for me. I'm using an AMD Vega 64. Switching to version 1.0 of the game fixes the crash, but there's a big warning saying that this will erase my saves. So, not sure if I should start the game with the 1.0 patch or not.

Here is the crash log: [steam-253230.log](https://github.com/ValveSoftware/Proton/files/7783004/steam-253230.log)

**Comment by doesthisusername** [comment]
@dashingderpderp Saves won't be compatible, so I would recommend against it, especially if you have any DLC, since 1.0 doesn't support them. Does Proton 5.13 work for you (on the newest patch)? Online probably won't work, but I think the rest will? I forgot to put that in my original comment, oops.

**Comment by rnanua95** [comment]
@doesthisusername, nope 5.13 has the same issue for me. I've also tried steam wine runner in lutris, and the latest update fails to launch there for me as well :/. Same with steam flatpak. No proton or wine version seems to work for me

**Comment by rnanua95** [comment]
Nevermind, I actually managed to fix my problem. I was previously loading discord-rpc-wine-git into every wine game (it's a library that gives rich discord presence for wine games). Removing that fixed the game for me. So, for now it seems like the issues with latest proton and this game are nvidia specific

**Comment by doesthisusername** [comment]
I saw a [post](https://www.protondb.com/app/253230#0Zq9BEMAW_) on ProtonDB positing that it might be Nvidia RTX cards in particular that don't work well, so I swapped in my 1070 and indeed the game launched perfectly fine, even on proton experimental, online working too. I then swapped back to my 2080 Ti, and on the first very launch it worked, and online worked too, but then after that it stopped working again. I did multiple launches on the 1070, and all of them worked. So it seems to either be newer versions of the game + RTX card, or newer versions of the game + some sort of GPU-dependent race condition? I don't know much about graphics, so that might be really wrong.

**Comment by doesthisusername** [comment]
It appears to be a DXVK regression? Copying in an old version of DXVK from an older (but probably not most recent) 6.3 to Experimental (until it verifies/updates the files) makes the game work fine for me on the newest game patch on my Turing GPU, including online.
e.g. `cp "$STEAM_COMMON/Proton 6.3/files/lib64/wine/dxvk/"* "$STEAM_COMMON/Proton - Experimental/files/lib64/wine/dxvk/"` (maybe)

Haven't pinned down the exact commit or anything, since I'm about to go sleep, but I hope this helps narrow it down. Would it be an idea to file an issue in the DXVK repo? I'm not sure whether Proton modifies anything to make it a "not-our-problem" environment for DXVK devs.

**Comment by alasky17** [comment]
@doesthisusername It would be ideal to file this in the DXVK repo - this sounds like some kind of hardware specific regression at a glance.  And nope, the DXVK in Proton 6.3-8 is only very slightly modified from upstream (not in a significant way), and DXVK in experimental is not modified at all  :)

**Comment by TiffanyNeat** [comment]
Heard people saying over on ProtonDB that it works for them on Proton Experimental (including here, it seems). However, it crashes for me on startup. I have tried both experimental & normal branches, and everytime it does the same thing: Opens up the short launcher, loads packages, then the launcher disappears, and the process stops entirely- the Stop button is replaced with a Play button.

I use an NVIDIA GeForce 1660 Ti GPU, 16 GB of ram, EndeavourOS (Arch), AMD Ryzen 5 2600X Six-Core CPU.

ALSO: I have _some_ mods loaded (just simple badges and a handful of maps- nothing that should, or has before, break anything) but on no version of wine does it ever load them, even after Validating them. I've tried all versions of wine, including the ones that work for people here.
Some help? I genuinely have no idea how to deal with this. I love mods too so I'd really hate to lose access to them on my Linux.

UPDATE: NEVERMIND. did the same as doesthisusername and it works perfectly, so sorry.

**Comment by XDM-Inc** [comment]
i cant get the game to  launch on matter what i try. I have been reading and trying launch options from everywhere and trying different wine proton versions and all i get is a black screen then close

**Comment by ryao** [comment]
Some change to DXVK to support Nvidia DLSS broke this (possibly due to a bug in the Nvidia driver). See doitsujin/dxvk#2504.

If you use an old enough version of Proton, it should work with Nvidia graphics.

**Comment by XDM-Inc** [comment]
> Some change to DXVK to support Nvidia DLSS broke this (possibly due to a bug in the Nvidia driver). See [doitsujin/dxvk#2504](https://github.com/doitsujin/dxvk/issues/2504).
> 
> If you use an old enough version of Proton, it should work with Nvidia graphics.

I indeed see issues with dxvk because I eventually did get it to work with poor performance by switching back to DirectX 9 to launch the game this is the only way it would work and it's slow. But if I'm not mistaken downgrading too far my break online capability (I think)

**Comment by ryao** [comment]
> > Some change to DXVK to support Nvidia DLSS broke this (possibly due to a bug in the Nvidia driver). See [doitsujin/dxvk#2504](https://github.com/doitsujin/dxvk/issues/2504).
> > If you use an old enough version of Proton, it should work with Nvidia graphics.
> 
> I indeed see issues with dxvk because I eventually did get it to work with poor performance by switching back to DirectX 9 to launch the game this is the only way it would work and it's slow. But if I'm not mistaken downgrading too far my break online capability (I think)

Only DXVK needs need to be downgraded to make it work. Alternatively, you could try getting the guys at Nvidia to fix the issue by reporting it to linux-bugs@nvidia.com.

**Comment by SeongGino** [comment]
Not so much needs to be downgraded as just the relevant DXVK commit needs to be changed out, which allegedly is also needed for Star Citizen. [gnusenpai's fork](https://github.com/gnusenpai/dxvk) works for AHIT - just grab the current release from that, put any desired version of Proton in `~/.local/share/Steam/compatibilitytools.d` and replace the DXVK libraries in `files/{lib|lib64}/wine/dxvk` (if you do this, might wanna change the `compatibilitytool.vdf` thing to distinguish this modified version from normal Proton).
Have been playing it this way for some time and it boots consistently without any special command line adds.

**Comment by frousties** [comment]
This issue is still present, and none of the fixes listed here work for me. The launcher flashes very quickly sometimes and then it stops.
I tried a lot of proton versions, including GE, along with the DXVK fix and at no point have I even seen the game launching.
I have also tried all of those arguments individually (with or without DXVK fix): ``PROTON_USE_D9VK=1 PROTON_NO_ESYNC=1 DXVK_ASYNC=1 PROTON_ENABLE_NVAPI=1 PROTON_USE_WINED3D=1 PROTON_FORCE_LARGE_ADDRESS_AWARE=1 WINE_LARGE_ADDRESS_AWARE=1``

I'm running on Arch Linux with an RTX 3070.
Also happens in both X11 and Wayland, not that it should matter.

**Comment by Bevan0** [comment]
![Screenshot from 2024-05-23 19-13-55](https://github.com/ValveSoftware/Proton/assets/43471745/884c507c-4c7f-4adf-b78e-884b5fd95fc4)
Encountering this error popping up in loading screens or in game every few minutes. Sometimes the game keeps running and I can just ignore the window but most of the time the game freezes at the same time.

On Arch Linux with RX 6400, tested with GE, Experimental, and 9.0-1. No mods or arguments.

I've had this game installed before working great on this same system and Linux install, this error has only started after installing it today. Also tried deleting the prefix (as suggested before).

**Comment by chewi** [comment]
I've been seeing that with different games under Proton on Gentoo recently, specifically Marvel's Guardians of the Galaxy and Chorus. I think it was triggered by a recent kernel or Mesa update. I'm not sure which, but my current guess is the kernel. I was on 6.8 before, but I haven't seen it since updating to 6.9. AMD's Harry Wentland reported the issue [here](https://lists.freedesktop.org/archives/amd-gfx/2024-May/108167.html), but I don't think he's had a chance to look into it yet.

**Comment by Bevan0** [comment]
@chewi That worked, thanks! I was on 6.8.9 but after upgrading to 6.9.1 I stopped seeing it.
