### ISSUE TITLE
Uplay do not recognize steam installation

### ISSUE THREAD

**Issue by juliotux** [ValveSoftware/Proton#1735]
# Compatibility Report
Anno 2205 (Uplay) - 375910

## System Information
- GPU: GTX 960M
- Driver/LLVM version: NVIDIA 410.57
- Kernel version: 4.18.12
- Link to full system information report as [Gist](https://gist.github.com/): [sys_info](https://gist.github.com/juliotux/3a0f54caaa38bb349fb2229d0d520157)
- Proton version: 3.16-1 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
This is not a game-specific problem, but a Uplay problem.

With Proton 3.16-1 Beta, apparently the old Uplay connection problem is solved. I could log in with my account and update to the lastest version of Uplay.

However, when I try to launch the game, Uplay do not recognize the Linux Steam installation and try to download and install the Windows version of Steam, inside the wine prefix.

## Reproduction
Launch the game, connect with Uplay and after the launcher's update, a Steam installation window appear. The installed games also do not appear in Uplay's installed games list.

**Comment by jomarocas** [comment]
ok i want see this is a priority all games of uplay no working fo this

**Comment by dreamer** [comment]
@jomarocas that's not true. Just let Uplay install Steam in some new directory (but don't let installer start Windows version of Steam) and that's all - it won't complain any more and you will be able to launch your game.

It is an issue, but not a critical one.

**Comment by zaggynl** [comment]
> @jomarocas that's not true. Just let Uplay install Steam in some new directory (but don't let installer start Windows version of Steam) and that's all - it won't complain any more and you will be able to launch your game.
> 
> It is an issue, but not a critical one.

I let it install Windows Steam to a different folder but after unchecking the "Run Steam" checkbox it still starts Windows Steam, updates and fails to connect to Steam network.

**Comment by juliotux** [comment]
> > @jomarocas that's not true. Just let Uplay install Steam in some new directory (but don't let installer start Windows version of Steam) and that's all - it won't complain any more and you will be able to launch your game.
> > It is an issue, but not a critical one.
> 
> I let it install Windows Steam to a different folder but after unchecking the "Run Steam" checkbox it still starts Windows Steam, updates and fails to connect to Steam network.

I installed the windows steam with uplay and replaced the steam dlls on steam windows installation with the proton ones. Now works fine.

**Comment by zaggynl** [comment]
> > > @jomarocas that's not true. Just let Uplay install Steam in some new directory (but don't let installer start Windows version of Steam) and that's all - it won't complain any more and you will be able to launch your game.
> > > It is an issue, but not a critical one.
> > 
> > 
> > I let it install Windows Steam to a different folder but after unchecking the "Run Steam" checkbox it still starts Windows Steam, updates and fails to connect to Steam network.
> 
> I installed the windows steam with uplay and replaced the steam dlls on steam windows installation with the proton ones. Now works fine.

Cool, could you provide a short howto?

**Comment by nsivov** [comment]
This should work now, in a sense that Uplay should not attempt to run Steam for Windows installer. Please retest with 3.16-5.

**Comment by juliotux** [comment]
I made new tests with fresh wineprefixes (deleted the old ones). Now Uplay do not try to install Steam, but, Uplay stars in background, not showing any window or tray icon, but not start 3 tested games at all. I will try more tests to give a better feedback.

**Comment by Shatrico** [comment]
can confirm it on Assassins Creed Rogue and Anno 2070 what @juliotux wrote

**Comment by ghost** [comment]
can confirm it on UNO still crashes but uplay recognize steam

**Comment by kisak-valve** [comment]
Thanks for retesting. Closing as the original issue has been resolved.
