### ISSUE TITLE
Hyperdimension Neptunia Re;Birth 1, 2 (282900 351710)

### ISSUE THREAD

**Issue by nyannoying1337** [ValveSoftware/Proton#189]
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3700 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-32-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2018-06-14

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.51
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1c82
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 21.42" x 11.93" (24.49" diag)
                                            54.4cm x 30.3cm (62.2cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7902 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Total Hard Disk Space Available:  18659 Mb
    Largest Free Hard Disk Block:  9069 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by nstgc** [comment]
My testing with Neptunia RB3 was less than Stella (pun). It is, in fact, unplayable. The intro loops. As soon as you hit the title screen it starts again. I have not tested RB1 or 2, but will since this has been requested.

**Comment by nyannoying1337** [comment]
@nstgc you should be able to to navigate through the menu and use it normally as long you dont do nothing. have you tried to spam quick enter to test out if you can access anything?

**Comment by nstgc** [comment]
Yes. I tested exit. If that is a necessary work around then the game is not ready for the white list.

**Comment by nstgc** [comment]
A cursory inspection shows that RB 1&2 seem to be fine (no in-game testing), but RB3 also throws a dsetup error at me. Perhaps 1&2 are ready for white listing, but RB3 is not.

**Comment by nyannoying1337** [comment]
iirc the intro bug is arround since mid 2015 however easy to work arround with just keep moving in the menu or enter the game and changing stuff afterwards. No idea what’s causing it

**Comment by nstgc** [comment]
I have never had this problem until now. Regardless, that isn't white list material. Its suppose to be for games that run like native save for a small performance penalty.

**Comment by mat8913** [comment]
3 works in a 32-bit prefix. #449

I followed instructions from [here](https://www.reddit.com/r/linux_gaming/comments/99e0kc/steam_playguide_create_custom_32bit_prefix_to/), except I ran `winetricks xact_jun2010 devenum quartz wmp10 windowscodecs`.

**Comment by kisak-valve** [comment]
Since the third game in the series has different behavior than the other two, I'm going to drop it from this whitelist request. Please open a separate issue report for that game.

**Comment by snarvaezsoft** [comment]
Hyper Dimension Neptunia re;birth 1   Working on Debian 10

My Specs: Distro Debian 10
Driver: NVIDIA Corporation GeForce GTX 1070 Ti/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 390.77

Tested with wired gamepad xbox 360.   On Linux the initial load is even faster than on Win7.
I was able to start a new game from the beginning, and also able to continue some previously saved games from the cloud.   The temperature of the video card was always below 50 C, so it is running smoothly, not even pushing the hardware.

Installed everything from Debian repository or default, I have not added any extra config or parameter.

Here is the link to my Steam system info:
https://gist.github.com/snarvaezsoft/dd0a970ce0b9ba8ed19a6c91022d2a50

**Comment by ghost** [comment]
This game has trouble with mods, specifically those created with neptools.
An easy example would be with the [Neptunia Re;Birth 2 Retranslation Patch](https://steamcommunity.com/sharedfiles/filedetails/?id=542831125https://steamcommunity.com/sharedfiles/filedetails/?id=542831125), although any neptools mods that relies on placing a user-created `dinput8.dll` will no work.

I can say from experience that they do work on native Windows but not in any of the two GNULinux installations that I have tried.

**Comment by der-coder** [comment]
Behaviour of Re;Brith 1 has not been as expected. Game loads perfectly, even plays the intro, but the game has no sound except for the opening video sequence.

[System specs](https://gist.github.com/der-coder/9dc509aac372235034ab13d907f73868)

**Comment by kisak-valve** [comment]
Hello @der-coder, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by der-coder** [comment]
Attached log file. Tested on Proton 3.7-8, I can provide test on 3.7-8 beta, and 3.16-4 beta if required.

[steam-282900.log](https://github.com/ValveSoftware/Proton/files/2630912/steam-282900.log)

**Comment by kisak-valve** [comment]
Do you use an alsa-only or pulseaudio setup (or other)?

**Comment by der-coder** [comment]
System is running ALSA exclusively. PulseAudio is also installed in the system, but no instance is running.

**Comment by der-coder** [comment]
ALSA is running on the system as a service for systemd. PulseAudio is also installed, but no instance is running currently.

**Comment by kisak-valve** [comment]
My hypothesis is that the intro video is either taking exclusive access of the audio device, then the main game engine gets blocked, or it is initializing the audio device to something that is incompatible with the main game engine. You could try to pointing the default alsa device to dmix before it goes to the audio chipset or run pulseaudio as the current user with `pulseaudio -D`.

**Comment by mat8913** [comment]
@der-coder The first time you launched the game, did Steam install DirectX? The Steam client has a bug where it sometimes wont install these dependencies. If you are experiencing this bug, try restarting the Steam client and launching the game again.

**Comment by der-coder** [comment]
It installed properly. 

The game ran perfectly with functional audio during September. I did not test during October with the newer updates, and just recently attempted to play again.

Is there a way to regress the Proton version on the client side to an earlier release? I'd like to test on an earlier version to see if the errors remain.

**Comment by unit73e** [comment]
Saves do not work for me at all.

EDIT:
I fixed it by creating "My Documents" directory manually like so:
```
$ mkdir ".local/share/Steam/steamapps/compatdata/282900/pfx/drive_c/users/steamuser/My Documents"
```

Apparently the game does not create this directory itself. Perhaps steam should always create this directory since it seems some games are expecting "My Documents" to exist.

**Comment by CygnusTerminal** [comment]
Since some days ago, i am observing problems with Proton and the neptunia re;birth franchise. OpenGL (which is the API used by the engine) is really lackluster, in battles: 17 FPS or less, when the characters transforms, it jumps to 60, and then goes back to 17 when the battle continues. Native OpenGL games (such as the Half Life collection and the Left 4 Dead collection) work as intended. This is on Arch LInux, but i also tried on Kubuntu 20.10, with the default drivers and kisak's ppa ones. Clean prefixes, Proton 5.0-10 and 5.13-4 show the same issues. RX 480/Ryzen 7 1700/16GB DDR4 3200MHz. It would also seem that games that use dxvk/d9vk are not affected. Clocks stay on the maximum (1326 for my 480/3.4GHz manual OC for my Ryzen 7). I also tried disabling KDE's compositor to no avail. 
I should also mention, the GPU usage jumps from 0% to 30-80% every second, VRAM clocks go from 1750 to 300 back and forth

---

Hyperdimension Neptunia Re;Birth2 Sisters Generation (351710)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/4549.
@CygnusTerminal posted on 2021-01-15T12:23:15:

# Compatibility Report
- Name of the game with compatibility issues: Hyperdimension Neptunia Re;Birth2 Sisters Generation
- Steam AppID of the game: 351710

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 20.3.2
- Kernel version: 5.10.6-110-tkg-bmq
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/CygnusTerminal/70e276f032863ea0f3f6337f7ef31b03
- Proton version: 5.0-10/5.13-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.


[steam-351710.log](https://github.com/ValveSoftware/Proton/files/5820461/steam-351710.log)


## Symptoms 
Since days ago, this game and the other two (Re;birth 1 and 3) have been running pretty bad on my machine, fights and dungeons are below the 20 FPS mark. In combat, when the characters transform, the FPS go up to my vsync limit, only to go back to 17~20 when it's over. They use OpenGL. Native OpenGL games work like a charm (tested the entire Half-Life 2 franchise and Left 4 Dead franchise). I could observe the GPU usage ranging from values between 0% and 90%, every second. I've tried clean prefixes, disabling compositor manually, gamemode, no gamemode, setting the governor to performance, closing all background apps. Nothing seems to work. On Windows the games work as intended. I have also recorded a video with my external capture card, so the issues can be understood better (https://youtu.be/0JaVWKphLz0). Also, aside from the low quality due to pulseaudio being pulseaudio, and ALSA sounding with enough reverb to blow my eardrums, the popping is very noticiable, this has been an issue i've benn having with Wine/Proton since a month ago.

## Reproduction
Start the game, enter a dungeon/fight/observe the performance.

**Comment by CygnusTerminal** [comment]
Thanks @kisak-valve, i should add that i tested across various distros and all show the same problem, regardless of the Mesa/amdgpu version they have.

**Comment by unit73e** [comment]
@CygnusTerminal I completed Neptunia without issues, always at 60fps. I'm using an R9 380 and Arch Linux as well. I may test this in the next days to see if there is anything wrong but it could be that you're not actually using Vulkan. I had that problem at first and had to install a few dependencies for Vulkan to actually work.

**Comment by CygnusTerminal** [comment]
> @CygnusTerminal I completed Neptunia without issues, always at 60fps. I'm using an R9 380 and Arch Linux as well. I may test this in the next days to see if there is anything wrong but it could be that you're not actually using Vulkan. I had that problem at first and had to install a few dependencies for Vulkan to actually work.

Hi, thanks for your reply!, i am consistengly having this issue on 3 different distros (Kubuntu 20.10, Arch and Garuda Linux). I recall the game working fine until weeks ago. I'll retest with older versions and see what the issue is.
Update: Still having issues. Proton GE 5.9-3 solves the popping issue, but the FPS still won't go over 17. Strange issue, i will reinstall Kubuntu and see if it helps.

**Comment by CygnusTerminal** [comment]
> @CygnusTerminal I completed Neptunia without issues, always at 60fps. I'm using an R9 380 and Arch Linux as well. I may test this in the next days to see if there is anything wrong but it could be that you're not actually using Vulkan. I had that problem at first and had to install a few dependencies for Vulkan to actually work.

Hey man, sorry to bother, have you been able to test? I'm still stuck on OpenGL, i have vulkan radeon and lib32-vulkan-radeon, i've even reinstalled the games and no dice.

**Comment by unit73e** [comment]
@CygnusTerminal I tested right now Rebirth1 and it worked 60fps the whole time. I used Proton 5.13-5 but Proton GE should behave the same. No issues found. You have vulkan-radeon, lib32-vulkan-radeon, vulkan-icd-loader and lib32-vulkan-icd-loader installed? AMD has several drivers but I usually use the MESA ones.

**Comment by CygnusTerminal** [comment]
> @CygnusTerminal I tested right now Rebirth1 and it worked 60fps the whole time. I used Proton 5.13-5 but Proton GE should behave the same. No issues found. You have vulkan-radeon, lib32-vulkan-radeon, vulkan-icd-loader and lib32-vulkan-icd-loader installed? AMD has several drivers but I usually use the MESA ones.

Hi Emanuel, first of all, thanks for taking the time to test, i really appreciate it! I do have vulkan-radeon/vulkan-icd-loader with their 32bit counterparts. I'll test Re;Birth 1 and see if i replicate the issues i got with Re;Birth 2. Thanks again!

**Comment by CygnusTerminal** [comment]
> > @CygnusTerminal I tested right now Rebirth1 and it worked 60fps the whole time. I used Proton 5.13-5 but Proton GE should behave the same. No issues found. You have vulkan-radeon, lib32-vulkan-radeon, vulkan-icd-loader and lib32-vulkan-icd-loader installed? AMD has several drivers but I usually use the MESA ones.
> 
> Hi Emanuel, first of all, thanks for taking the time to test, i really appreciate it! I do have vulkan-radeon/vulkan-icd-loader with their 32bit counterparts. I'll test Re;Birth 1 and see if i replicate the issues i got with Re;Birth 2. Thanks again!

Issues persist, sadly. I reinstalled Arch again, only to find the same problem. I don't know what to do at this point. Mangohud shows OpenGL as the default renderer still, on every proton version. I'll try mesa-git and see if it helps.

**Comment by unit73e** [comment]
@CygnusTerminal I tried using MangoHud but for me it simple crashes. With the simple proton overlay it shows 60fps all the time. Perhaps try changing to another GPU if you have one? Just to see.

EDIT: That's when I use MANGOHUD=1, the Vulkan option. With any other option it will simply not show anything.

**Comment by CygnusTerminal** [comment]
> @CygnusTerminal I tried using MangoHud but for me it simple crashes. With the simple proton overlay it shows 60fps all the time. Perhaps try changing to another GPU if you have one? Just to see.
> 
> EDIT: That's when I use MANGOHUD=1, the Vulkan option. With any other option it will simply not show anything.

Thanks! i use only "mangohud", with proton 5.9-GE-ST-3 and it shows 17 FPS, and the game is laggy and actually plays at said FPS. This is my third reinstall, i'll see if i can try on my Nvidia laptop.

**Comment by CygnusTerminal** [comment]
Update: Game is borked on Mesa, my laptop with dual graphics (intel+nvidia, in this case, i am using the propietary nvidia driver) works as intended. Link to the video: https://youtu.be/2tzPS_iTYiQ. Where do i report this @kisak-valve ?

**Comment by kisak-valve** [comment]
Hello @CygnusTerminal, right here is the best place for all feedback related to this game title. You might also have some luck mentioning driver-specific issues to the video driver vendor.

**Comment by ipr** [comment]
Updating that all three games are working fine on Mesa 22.2.0, Proton 7.0 on AMD Vega 56/64.

In 2 and 3 you need to use keyboard to enter config and select gamepad as controller instead of keyboard. Default gamepad config has A and B reversed (Nintendo-style).

People who had troubles before could re-test?

**Comment by LiquidLemming** [comment]
Fedora Silverblue 36
AMD Ryzen™ 5 5600X × 12
AMD Radeon™ RX 6600 XT
16 GB RAM
Proton Experimental

Updated flatpak Mesa to 22 this morning. Rebooted afterwards just for peace of mind.

I've only tested Re;Birth 1, and it's still running like 15fps while in dungeons/combat.

**Comment by ipr** [comment]
> I've only tested Re;Birth 1, and it's still running like 15fps while in dungeons/combat.

You should set framerate limit to 30 or higher to make it run with higher framerate (on Steam Deck). <s>Leaving it to zero will run it on lower framerate for some reason.</s>

I don't know what you could use on Fedora to get same effect as I'm not familiar how that setting on Deck does things (vsync? something else?).

Edit: I made a mistake at looking at setting, it wasn't zero but 15, leaving framecap "unlimited" runs it at 60fps. So no issues there.

**Comment by LinuxnoobR** [comment]
The game runs terribly on my Linux desktop (Pop os) but runs fine on my Steam Deck despite my desktop having stronger hardware.

**Comment by CygnusTerminal** [comment]
Mine just shows a black screen with sound. I have tested with VRR disabled and enabled to no effect.

**Comment by unit73e** [comment]
@CygnusTerminal I have a black screen with an RX 6600 now too, with MESA 22.3.2.

Here's my findings:
- One simple way to fix the problem is software mode `LIBGL_ALWAYS_SOFTWARE=true` but of course the game becomes a lot slower.
- This means it's a MESA problem and for that you can try: https://docs.mesa3d.org/envvars.html
- If I enable `MESA_DEBUG=1` it prints a `GL_INVALID_ENUM` but I don't understand the error
- Some option might make the game work, but I have no idea which option

**Comment by unit73e** [comment]
@CygnusTerminal after many attempts I finally got it working with these launch options:
```
PROTON_OLD_GL_STRING=1 %command%
```
So this works with hardware acceleration. Though with modern CPUs it doesn't really make that much of a difference, except the CPU doesn't go brrrr

**Comment by unit73e** [comment]
@CygnusTerminal I managed to get it working with `PROTON_OLD_GL_STRING=1` and initially I thought it was using software rendering, but no, it's using radeonsi (it's not radv, since it's OpenGL) with very slow performance.

I confirmed with this HUD:
```
GALLIUM_HUD=".w120.h56.c50fps,.w120.h56cpu+cpu0+cpu1+cpu2+cpu3:100,.w120.h56VRAM-usage+GTT-usage+requested-VRAM+requested-GTT,.h56.w120GPU-load,.h56.w120.dbuffer-wait-time"
```

My best guess is that it's one of the GL extensions breaking the game, because what that option does is disable extensions, but I have no clue which one it is.

EDIT:
So now that this is challenge, I checked what `PROTON_OLD_GL_STRING` does and all it does is activate `MESA_EXTENSION_MAX_YEAR=2003`. I found out 2005 works as well. Regardless that means one of the extensions is breaking the game, one after 2005, since 2006 does not work.

EDIT2:
Best I got so far are these launch options:
```sh
MESA_LOADER_DRIVER_OVERRIDE=zink PROTON_OLD_GL_STRING=1 GALLIUM_HUD=fps  %command%
```
This will enable the zink driver (opengl on vulkan) instead of radeonsi (amd driver), use old GL, and show FPS.
It's still slow, at 30fps, but at least it doesn't show a black screen.

**Comment by CygnusTerminal** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/189#issuecomment-1373002434

Thanks a lot for your hard work! I will try this tonight and check if it works on my system.

**Comment by dragonhunter056** [comment]
> ```shell
> MESA_LOADER_DRIVER_OVERRIDE=zink PROTON_OLD_GL_STRING=1 GALLIUM_HUD=fps  %command%
> ```

I'm having the same issues as CygnusTerminal. My distro is EndeavorOS with lib32-mesa 22.3.2-2 and when I use this command I get an error "Sorry! Application has crashed" seconds after loading into a dungeon.

![Screenshot from 2023-01-12 16-03-09](https://user-images.githubusercontent.com/48330094/212210954-a432a93d-457d-4251-bbb1-e7ba7fbda2d2.png)

I've tried installing lib32-mesa-git version 23.1.0_devel from the AUR and while I don't have a black screen anymore I also get less then 15FPS in dungeons and combat.

**Comment by unit73e** [comment]
@dragonhunter056 you don't get a black screen without any options? If that's the case MESA fixed something in version 23. The 15fps can probably be fixed with environment options.

Oddly software mode runs faster than radeonsi with `PROTON_OLD_GL_STRING=1`, so that would be `LIBGL_ALWAYS_SOFTWARE=true`. The CPU will be in full power but it is playable that way.

Perhaps the MESA guys might have an explanation for the slow performance, if logs are sent running the latest MESA.

**Comment by CygnusTerminal** [comment]
I can confirm the game no longer shows a black screen, but it's still slow, less than 20 FPS. Thankfully due to the turn based nature it's still playable but i would like to play it at full performance. Mesa version in Arch as of today is  22.3.3-1

**Comment by unit73e** [comment]
Since this is getting beyond my skills, I've opened an issue in MESA: https://gitlab.freedesktop.org/mesa/mesa/-/issues/8176

Also, the game now works in MESA 22.3.3-3 on Arch Linux, without any options, but it will be super slow, at 10fps. Apparently using `LIBGL_ALWAYS_SOFTWARE=true` still runs faster, at 20fps.

**Comment by unit73e** [comment]
So in that MESA issue I posted in the previous comment, we managed to get it running at 60fps:
- REBAR/SAM must be disabled in UEFI.
- `AMDGPU_DEBUG=nowc` must be enabled.

With MESA 22.3.3 it should work. There's some kind of issue with memory in this game, because GTT is the memory the GPU can get from the system.

EDIT:
I found out you don't need to disable SAM in the BIOS. This works as well:

```
radeonsi_disable_sam=true AMD_DEBUG=nowc %command%
```

**Comment by dragonhunter056** [comment]
`radeonsi_disable_sam=true AMD_DEBUG=nowc %command%`
That works for me, using `WINEDLLONERRIDES="opengl32.DLL=n,b"` makes it so that the neptastic mod works and I'm now getting 165 FPS most the time. Thanks for the help @unit73e!
