### ISSUE TITLE
CLANNAD (324160)

### ISSUE THREAD

**Issue by aljelly** [ValveSoftware/Proton#1991]
# Compatibility Report
- Name of the game with compatibility issues: CLANNAD
- Steam AppID of the game: 324160

## System Information
- GPU: Intel HD Graphics
- Driver/LLVM version: 2.1 Mesa 18.2.4 - padoka PPA
- Kernel version: 4.15.0-39-lowlatency
- Proton version: 3.16-4 beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Nearly everything about the visual novel works, except the opening movie. I wouldn't say the opening movie is absolutely crucial to reading the novel but it's still an issue, someone else may want to see it or find it odd that no movie plays.

There are 3 movie playing methods that the novel makes available: MCI, DirectShow and WindowsMediaPlayer. MCI is the default option. Without attempting any workarounds, this is what happens:

- With MCI, the novel will either:
  - Show a dialog full of question marks (probably saying that playback method failed), or
  - Stay on a black screen for a certain amount of time and then skip the movie, or
  - Instantly skip the movie
- With DirectShow the question mark dialog seems to always be shown.
- With WindowsMediaPlayer either the dialog is shown or the novel just crashes.

I thought it might be a codec issue so I tried allcodecs via winetricks. Before installing the codes MCI was showing the question mark dialog. After installing the codecs MCI just waits a while and then skips the movie, meanwhile DirectShow still doesn't work. (IIRC wmp is not installable in a 64-bit prefix so that playback method probably has no workaround)

I should note that the movies are easily accessible from the game's directory and can be played manually. There are 3 movie files, a .mpg file and 2 .wmv files. With my distro's movie player, I can play the 2 .wmv files but not the .mpg file.

Log: [steam-324160.log](https://github.com/ValveSoftware/Proton/files/2592327/steam-324160.log)

In this log I think I tried (in this order) DirectShow, MCI (might've tried this more than once) and then WMP. Trying WMP crashed CLANNAD. Hopefully you can tell from the DLLs loaded what I tried doing at what point. This was with allcodecs installed via winetricks.

## Reproduction

1. Launch the game
2. Click "CONFIG" (you can click on the screen while it's fading in/out to skip the transitions)
3. In the bottom right, click "Play opening movie on the title screen"
4. Right click or click "EXIT" in the bottom right corner to go back to the title screen.
5. Wait until the screen fades out (don't move the mouse). It will try to play the movie using MCI. It will either (eventually) skip the movie or show a dialog full of question marks (probably Japanese that failed to show correctly).
6. If you get the dialog full of question marks, click the left most button to see the Movie Settings dialog. If you didn't, go back to "CONFIG" on the title screen and click "Movie Settings" in the bottom right.
7. At the Movie Settings dialog, try DirectShow or WindowsMediaPlayer and repeat step 4 onward to test the other methods (they won't work either).

**Comment by ghost** [comment]
Codec likely won't fix it. Wine doesn't really support most to all of Microsoft's video player interfaces such as DirectShow or WMP. It looks like MCI might be another or its just not implemented as well.

You might be able to get WMP 11 to work here maybe if WMP option is using WMP itself and not a dll that Proton/Wine doesn't implement. It is possible to install WMP 11 (IF 11 will do the trick and 12 isn't needed) but totally annoying and personally I just don't recommend it. Proton is supposed to make things simple.

I didn't look at the log with this one so don't know if its actually WMP or a dll that isn't installed with WMP.

**Comment by aqxa1** [comment]
I believe you'll need a 32-bit prefix to get this working (and other visual novels with the same issue). I don't think Proton supports that yet so you'd need to create a new prefix in the same location in 32-bit form (WINEARCH=win32).

Then:
    `winetricks -q wmp10 quartz`

I'm not sure if anyone has been able to workaround this problem with a 64-bit version of WMP as yet.

**Comment by ipr** [comment]
> I believe you'll need a 32-bit prefix to get this working (and other visual novels with the same issue). I don't think Proton supports that yet so you'd need to create a new prefix in the same location in 32-bit form (WINEARCH=win32).
> 
> Then:
> `winetricks -q wmp10 quartz`
> 
> I'm not sure if anyone has been able to workaround this problem with a 64-bit version of WMP as yet.

It works with Proton 5.13. Note that Proton 6.3 has regression where framerate is much lower for some reason.

Edit: possibly related bug in DXVK that seems to have a fix in DXVK 1.9.1: https://github.com/doitsujin/dxvk/issues/2168

Edit2: This is working fine on Proton 6.3-7 for me.

**Comment by MateusRodCosta** [comment]
So, I have tested recently the opening movie with Clannad with both Proton-GE 9-27 and Proton 10.0-1, I got the following results by only switching Proton version without any workarounds:

Proton-GE 9-27:
MCI - Stays in a black screen for a while with no audio
DirectShow - Stays in a black screen for a while with no audio
WMP - Immediately goes back to main menu

Proton 10.0-1:
MCI - Black screen but does play the audio
DirectShow - Black screen but does play the audio
WMP - Immediately goes back to main menu

So, essentially whatever changed in 10.0-1 gets us a bit closer to having the opening video play without even having to change from the default of MCI. But DirectShow seems like a close second option for now.

**Comment by MateusRodCosta** [comment]
Aside from a bunch of `wrong ELF class: ELFCLASS64` related to the gstreamer files from Proton, I only have this when I let the opening play via MCI:

```
mai 02 11:45:50 centauro steam[9219]: (wine:17983): GStreamer-Video-CRITICAL **: 11:45:50.540: gst_video_info_from_caps: assertion 'gst_caps_is_fixed (caps)' failed
mai 02 11:45:50 centauro steam[9219]: (wine:17983): GStreamer-Audio-CRITICAL **: 11:45:50.553: gst_audio_info_from_caps: assertion 'gst_caps_is_fixed (caps)' failed
mai 02 11:45:50 centauro steam[9219]: (wine:17983): GStreamer-Base-WARNING **: 11:45:50.569: gldownloadelement0: transform_caps returned caps which are not a real subset of the filter caps
mai 02 11:45:50 centauro steam[9219]: (wine:17983): GStreamer-Base-WARNING **: 11:45:50.569: glcolorconvertelement1: transform_caps returned caps which are not a real subset of the filter caps
mai 02 11:45:50 centauro steam[9219]: (wine:17983): GStreamer-Base-WARNING **: 11:45:50.569: gldeinterlace0: transform_caps returned caps which are not a real subset of the filter caps
mai 02 11:45:50 centauro steam[9219]: (wine:17983): GStreamer-Base-WARNING **: 11:45:50.569: capsfilter1: transform_caps returned caps which are not a real subset of the filter caps
```

and from a second play:

```
mai 02 11:46:40 centauro steam[9219]: GameScope focus changed to appID 0
mai 02 11:46:40 centauro steam[9219]: Window title set to CLANNAD [English HD Edition] Main menu
mai 02 11:46:47 centauro steam[9219]: Window title set to
mai 02 11:46:47 centauro steam[9219]: GameScope focus changed to appID 0
mai 02 11:47:20 centauro steam[9219]: Audio mix: start=4209714774, returned=8640033
mai 02 11:47:20 centauro steam[9219]: Audio source [System Pulse]: init=4209755473, adjustment=0, through=8640513, last_start=8640033, mixed=2880000, drop_before=0, drop_after=0
mai 02 11:47:20 centauro steam[9219]: Audio source [System Pulse]: Signal levels: -35.9dB, -29.0dB
mai 02 11:47:56 centauro steam[9219]: (wine:17983): GStreamer-Video-CRITICAL **: 11:47:56.969: gst_video_info_from_caps: assertion 'gst_caps_is_fixed (caps)' failed
mai 02 11:47:56 centauro steam[9219]: (wine:17983): GStreamer-Audio-CRITICAL **: 11:47:56.981: gst_audio_info_from_caps: assertion 'gst_caps_is_fixed (caps)' failed
mai 02 11:47:57 centauro steam[9219]: (wine:17983): GStreamer-Base-WARNING **: 11:47:57.008: gldownloadelement1: transform_caps returned caps which are not a real subset of the filter caps
mai 02 11:47:57 centauro steam[9219]: (wine:17983): GStreamer-Base-WARNING **: 11:47:57.008: glcolorconvertelement3: transform_caps returned caps which are not a real subset of the filter caps
mai 02 11:47:57 centauro steam[9219]: (wine:17983): GStreamer-Base-WARNING **: 11:47:57.008: gldeinterlace1: transform_caps returned caps which are not a real subset of the filter caps
mai 02 11:47:57 centauro steam[9219]: (wine:17983): GStreamer-Base-WARNING **: 11:47:57.009: capsfilter3: transform_caps returned caps which are not a real subset of the filter caps
```

**Comment by layercak3** [comment]
The black screen issue should be fixed if a Proton dev cherry picks https://gitlab.winehq.org/wine/wine/-/merge_requests/8848 assuming you don't have codec issues (you probably don't if audio works and log snippet seems ok).

**Comment by MateusRodCosta** [comment]
Just a head up, tested today again with latest official Proton 10 and latest Proton-GE:

Proton 10.0-2:

MCI - Black screen with audio
DirectShow - Black screen with audio
WMP - Untested

Proton-GE 10-17:

MCI - Black screen with audio
DirectShow - Black screen with audio
WMP - Untested

I would guess we should try getting GE to backport the fix from https://github.com/ValveSoftware/Proton/issues/1991#issuecomment-3290016563 first and see what happens.

**Comment by Lintsu** [comment]
Were you guys able to figure out a solution? I'm using Proton GE, and only the audio works for the opening movie. I've tried configuring the movie files, like converting them to a mp4 file, but it doesn't seem to fix the issue.

**Comment by Lintsu** [comment]
I finally fixed it after like a million trials and errors. (I'm on debian linux btw) At first the opening movie would just get completely skipped/ or there would be not visual or audio output whatsoever while it plays. And switching to proton GE fixes the audio issue, but there's still no video playback. For that, you gotta rename your op00.mpg file to op00.wpx in the .mov directory, and then the delete the other two files in that directory. After doing so, restart your device and then your opening movie should play without any issues

**Comment by Lintsu** [comment]
*Deleted a comment where my instructions on how to fix it was false, sorry about that.
What worked for me is, going to the mov files in the clannad directory and deleting the video files except for the one that 
ends with a .mpg, you want to keep that one. After deleting the files, you just restart your game and the opening movie should play. (Make sure you're using MCI as your movie setting)

**Comment by MateusRodCosta** [comment]
For now the recommendation is to use the latest Proton-GE (currently 10-32)...

**Comment by qingtian805** [comment]
Hi everyone, since Proton 11 is rebased on Wine 11.0, the [upstream patch](https://gitlab.winehq.org/wine/wine/-/merge_requests/8848) is included. So I tested again with Proton Experimental 11. End up with result below:

1. MCI: Will show a blank video which is located at `steamapps/common/Proton - Experimental/files/share/media/blank.mkv`
2. WMP: Video is skipped, game continues.
3. I didn\`t find a way to use DirectShow, so it\`s untested

I captured log with parameter `PROTON_LOG=+quartz %command%`  [steam-324160.log](https://github.com/user-attachments/files/26976421/steam-324160.log)

I find that my environment is missing codec for Advanced Streaming Format in the log (line 4280), but installing it (gst-plugins-ugly) in my system does no help.

> Missing decoder: Advanced Streaming Format (ASF) (video/x-ms-asf)

I am agreed with:

> For now the recommendation is to use the latest Proton-GE (currently 10-32)...

since proton-ge has ASF [enabled](https://github.com/GloriousEggroll/proton-ge-custom/blob/master/Makefile.in#L587C1-L590C29) in ffmpeg: 

> 	--enable-demuxer=asf \\
>	--enable-demuxer=xwma \\
>	--enable-muxer=asf \\
>	--enable-muxer=asf_stream \\
