### ISSUE TITLE
Yomawari: Midnight Shadows (625980)

### ISSUE THREAD

**Issue by sat3ll** [ValveSoftware/Proton#2157]
# Compatibility Report
- Name of the game with compatibility issues: Yomawari: Midnight Shadows / 深夜廻
- Steam AppID of the game: 625980

## System Information
- GPU: AMD Fury X
- Driver/LLVM version: Mesa 18.3.1
- Kernel version: 4.19.10-300.fc29.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/sat3ll/06369e3c36fccc66765803b52acdf5a3
- Proton version: Steam Default
![unknown](https://user-images.githubusercontent.com/37741639/50533674-6acd1a00-0b26-11e9-8bac-f3c87f64bd36.jpg)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-625980.log](https://github.com/ValveSoftware/Proton/files/2716067/steam-625980.log)

## Symptoms 
Launching the game results in a black window for 1 second then closes.

## Reproduction

Launch the game.

**Comment by kisak-valve** [comment]
Hello @sat3ll, looks like a D3D10 issue. Please retest with Proton 3.16-6.

**Comment by sat3ll** [comment]
> Please retest with Proton 3.16-6.

Nothing changed. Still crashes like previously reported.
With _Proton 3.16-6 Beta_: [steam-625980.log](https://github.com/ValveSoftware/Proton/files/2716617/steam-625980.log)

**Comment by sat3ll** [comment]
Status: unchanged compared to original report
Proton version: _Proton 4.2-1_
**PROTON_LOG=1** Output: [steam-625980.log](https://github.com/ValveSoftware/Proton/files/3011032/steam-625980.log)

## System Information
- GPU: AMD Fury X
- Driver/LLVM version: Mesa 18.3.2
- Kernel version: 4.20.15-200.fc29.x86_64
- Link to full system information report as Gist: https://gist.github.com/sat3ll/d3b6dc4115ecb88fe4a56577f19a64c0

**Comment by sat3ll** [comment]
Status: unchanged compared to original report
Proton version: _Proton 4.2-3_
**PROTON_LOG=1** Output: [steam-625980.log](https://github.com/ValveSoftware/Proton/files/3102077/steam-625980.log)


## System Information
- GPU: AMD Fury X
- Driver/LLVM version: Mesa 18.3.5
- Kernel version: 5.0.7-200.fc29.x86_64
- Link to full system information report as Gist: https://gist.github.com/sat3ll/eb5471b5d8f21c2474e0b2c130bb434d

**Comment by sat3ll** [comment]
Status: unchanged compared to original report
Proton version: _Proton 4.2-5_
**PROTON_LOG=1** Output: [steam-625980.log](https://github.com/ValveSoftware/Proton/files/3217873/steam-625980.log)

## System Information

-   GPU: AMD Fury X
-   Driver/LLVM version: Mesa 18.3.6 / LLVM 7.0.1
-   Kernel version:  5.0.16-300.fc30.x86_64
-   Link to full system information report as Gist: https://gist.github.com/sat3ll/6fbd6f2b4993baeb810fdd86581011b9

**Comment by sat3ll** [comment]
Status: unchanged compared to original report
Proton version: _Proton 4.2-9_
__PROTON_LOG=1__ Output: [steam-625980.log](https://github.com/ValveSoftware/Proton/files/3364861/steam-625980.log)

# System Information
- GPU: AMD Fury X
- Driver/LLVM version: Mesa 19.1.1 / LLVM 7.0.1
- Kernel version:  5.1.15-300.fc30.x86_64
- Link to full system information report as Gist: https://gist.github.com/sat3ll/d26ced86d6ba50c2f0f52fcec7757805

**Comment by sat3ll** [comment]
Status: unchanged compared to original report
Proton version: _Proton 5.0-4_
__PROTON_LOG=1__ Output: [steam-625980.log](https://github.com/ValveSoftware/Proton/files/4318941/steam-625980.log)


# System Information
- GPU: AMD Fury X
- Driver/LLVM version: Mesa 19.3.3 / LLVM 9.0.0
- Kernel version:  5.5.5-200.fc31.x86_64

**Comment by Sbte** [comment]
It seems to work fine with `PROTON_USE_WINED3D=1`

**Comment by sat3ll** [comment]
> It seems to work fine with `PROTON_USE_WINED3D=1`

Can confirm.
Interestingly, before proton defaulted to DXVK, it didn't work. I assume something changed with wine/wined3d between pre-dxvk/post-dxvk proton.

**Comment by doitsujin** [comment]
Fixed in DXVK as of https://github.com/doitsujin/dxvk/commit/33b0d4c9915983b6a2bb068c50f5274708061655.

**Comment by sat3ll** [comment]
Working as of Proton 5.0-7

**Comment by Galcian79** [comment]
I have two issues with this game.
Minor issue: game starts windowed, if i change to fullscreen mode it loses focus and i have to force close it. When i restart the game it goes fullscreen, but if i restart the system it goes windowed again.
Major issue: game crashes very randomly with log message 

`wine: Unhandled page fault on write access to 00000000 at address 1000F20C (thread 00c8)`

[steam-625980.log](https://github.com/ValveSoftware/Proton/files/4925423/steam-625980.log)

**Comment by Galcian79** [comment]
Another crash, this time log says

`wine: Unhandled page fault on read access to 903BFFFD at address 1000F473 (thread 00c8)`

Note: it seems it crashes very often with official proton. More stable on proton GE 5.9 ST, but still crashes sometimes.

[steam-625980.log](https://github.com/ValveSoftware/Proton/files/4925464/steam-625980.log)
