### ISSUE TITLE
Catherine Classic (893180)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#2207]
# Compatibility Report
- Name of the game with compatibility issues: Catherine Classic
- Steam AppID of the game: 893180

## System Information
- GPU: GTX 970
- Driver/LLVM version: 415.25
- Kernel version: 4.14.83
- Full system info: [Gist](https://gist.github.com/fureloka/6439cdfefefc94bed0e52cc6adf73c5e)
- Proton version: 3.16-6 Beta
- Proton log: [steam-893180.log](https://github.com/ValveSoftware/Proton/files/2746701/steam-893180.log)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
When starting Catherine Classic, only the version number, a white mouse cursor and some music is played against a black background. Button/Key mashing does nothing.
Haven't played the orginal, but I'm quite sure there's supposed to be a logo with a prompt of some sort being rendered.

## Reproduction
1. Install Catherine Classic
2. Start Catherine Classic
3. Enjoy black screen?

**Comment by aqxa1** [comment]
Doesn't appear to work with vanilla Wine/Staging or Wine + Gallium Nine either. Same symptoms, Vega 56 card.

I also tried with ESYNC disabled and PROTON_FORCE_LARGE_ADDRESS_AWARE=1 with no change.

**Comment by ghost** [comment]
Looking a bit closer at the log file;
> fixme:mfplat:MFStartup (131184, 1): stub
> fixme:mfplat:mfsession_BeginGetEvent (0xf44d920)->(0x6e4ea88, (nil))

This opens up a whole can of worms, mfplat is still largly unimplemented, which could explain why it doesn't work with vanilla wine or staging. Catherine has similar symptoms to Akiba's Trip #651

**Comment by Cxpher** [comment]
Same experience on NVIDIA card.

Added my log.

Disabling Esync, Disabling D3d11 and using Wine D3d11 still cause the same scenario to occur. No effect.

[steam-893180.log](https://github.com/ValveSoftware/Proton/files/2751841/steam-893180.log)

**Comment by Cxpher** [comment]
Disabling Esync, Disabling D3d11 and using Wine D3d11 still cause the same scenario to occur. No effect.

**Comment by Melon-Bread** [comment]
I wonder if it has something to do with #1464. Since most of the video files for the game are .wmv. Is it failing to load a video for the main menu?

EDIT: After playing through the game on Windows I can confirm the game "locks up" at anytime it tries to play a wmv.

**Comment by ahmed-elsayed2017** [comment]
https://github.com/ValveSoftware/Proton/issues/1464

**Comment by ghost** [comment]
Catherine is now able to get to the main menu with Proton 4.2-2, hit a key/button to get past the black screen during startup (it takes a few seconds for it to react).

Changing settings seem to work fine, though trying to initiate any game-play will result in an infinite loading screen.

Proton Version: 4.2-2
Proton Log: [steam-893180.log](https://github.com/ValveSoftware/Proton/files/3093169/steam-893180.log)

**Comment by Cxpher** [comment]
Same with 4.2-3. Menu works perfectly.

Settings are saved etc.

Any game play will result in a looped loading screen. If this bit is resolved, i suspect it will jump straight to gold or platinum likely.

**Comment by TT-Hipster1941** [comment]
# Compatibility Report
* Name of the game with compatibility issues: Catherine Classic
* Steam AppID of the game: 893180

## System Information
* GPU: GTX 1080 Ti/PCIe/SSE2
* Processor : AMD Ryzen 7 2700 Eight-Core Pro
* Memory : 31GiB System memory
* OpenGL core profile version string: 4.6.0 NVIDIA 430.64

 
 ## I confirm:
* [x]  that I haven't found an existing compatibility report for this game.
* [x]  that I have checked whether there are updates for my system available.
 
## Symptoms
When starting Catherine Classic, getting the full menu options, 3d animations, sound and everything else. Once choose a difficulty level, getting infinite loading screen.
I have play the Original on console normally should bet loading status then getting loaded.
 
## Reproduction
1. Install Catherine Classic
2. Start Catherine Classic
3. Enjoy black screen? (Enjoy infinite beautiful animated loading screen)

*Also tried 4.11 and 4.2.9 version of proton, getting the same results

**Comment by Cxpher** [comment]
Does not work with `<Workaround removed by moderator>` either. Screws with the renderer i guess. Game crashes with this before even starting and with regular proton version, it shows an error with renderer.

Same with Proton-GE 5.0 (no error message with renderer if `<Previously mentioned workaround>` is done). Without `<Previously mentioned workaround>`, you also get the same infinite black screen when starting arcade mode or trial.

**Comment by Cxpher** [comment]
Anyone can figure this out?

This does not launch btw with Proton 5.07 (GA) - regressed - or with Proton-5.6-GE-2.

**Comment by GloriousEggroll** [comment]
user32-window-activation in staging causes the tiny-window + freeze problem. now i can get in game but it freezes when I go into the configuration. still working on seeing what else is causing issues.

-edit-
the configuration freeze is something in the proton custom patches, still digging to figure out which one, but i was able to disable it and get the game at least running. vitorhnn is also looking into the wmv playback issue

-edit 2- this patch causes the configuration menu to freeze, and freeze on alt+tab:

```
From a4310c0cf1e27f0a90f737c2e7cfe9cdbde07522 Mon Sep 17 00:00:00 2001
From: Andrew Eikum <aeikum@codeweavers.com>
Date: Mon, 20 Jan 2020 10:36:48 -0600
Subject: [PATCH] xaudio2: Stop engine thread in IXAudio2::StopEngine
```

![cc](https://user-images.githubusercontent.com/11287837/84581762-00ec1300-ada2-11ea-96d0-b18b232e7ab7.png)

**Comment by Hans-Rubenecia** [comment]
> # Compatibility Report
> * Name of the game with compatibility issues: Catherine Classic
> * Steam AppID of the game: 893180
> 
> ## System Information
> * GPU: GTX 1080 Ti/PCIe/SSE2
> * Processor : AMD Ryzen 7 2700 Eight-Core Pro
> * Memory : 31GiB System memory
> * OpenGL core profile version string: 4.6.0 NVIDIA 430.64
> 
> ## I confirm:
> * [x]   that I haven't found an existing compatibility report for this game.
> * [x]   that I have checked whether there are updates for my system available.
> 
> ## Symptoms
> When starting Catherine Classic, getting the full menu options, 3d animations, sound and everything else. Once choose a difficulty level, getting infinite loading screen.
> I have play the Original on console normally should bet loading status then getting loaded.
> 
> ## Reproduction
> 1. Install Catherine Classic
> 2. Start Catherine Classic
> 3. Enjoy black screen? (Enjoy infinite beautiful animated loading screen)
> 
> *Also tried 4.11 and 4.2.9 version of proton, getting the same results








The game can't run video cutscenes but it's possible to play it by downloading save files and loading it,everything works fine even the rendered cutscene unless you talk to the sheep that teach you techniques and when you encounter video cutscene and eventually black screen and unlimited loading occurs

**Comment by AniLeo** [comment]
Tested it on Proton 5.13-1, the issue still remains and it still doesn't work on Proton 5, works on Proton 4.

![image](https://user-images.githubusercontent.com/10283761/96354839-1e741500-10d3-11eb-9673-9aa20c667fe8.png)

![image](https://user-images.githubusercontent.com/10283761/96354827-ec62b300-10d2-11eb-840f-3b4fb2ecfb75.png)

**Comment by PickMeNow** [comment]
Hello,

Having the same issues as above using Proton Experimental or Proton 5.13-4. 
Does anyone know a workaround?

I remember entering the main menu in older versions, but once I pressed  "New Game" it would fall into infinite black screen.

Would be really amazing to play this game on Linux.

**Comment by AniLeo** [comment]
The workaround is starting a new game on a Windows system and create a save data then load it and proceed playing the game from Linux.

I've also been postponing this one in my backlog until issues are sorted out, would be great if it was fixed.

**Comment by CarnageDevs** [comment]
Managed to get videos working on **Pop!_OS 20.10** with **Proton 5.13-6** (on an NVIDIA RTX 2080 Ti and Ryzen 3900X) all thanks to a Reddit user, binaryfail! 

`<Workaround removed by moderator>`

That's it, you should have videos working now. If my instructions were unclear, I recommend checking out binary's comment, he has also provided a video of the setup process and the game (with working movies) in action here`<Link to video removed>`, though with Proton GE 6.1 instead (setup process is identical for this minus step 6). 

It is recommended to do this with Proton 5.13-6 as Proton 6.x seems to cause video/audio desync in the first cutscene at least, and from my own testing, Proton 4.11 results in the menu buttons in the pause menu during cutscenes to be unselectable with ENTER, only LMB.

Ideally, I hope someone can make a setup script or something similar out of this to make this solution easier to share on ProtonDB, given that it requires external sources for DLLs etc.

**Comment by kisak-valve** [comment]
Hello @Carnage555, the workaround you shared is legally problematic and has been removed. Please do not promote its use.

**Comment by chewi** [comment]
Rather than dig around for untrusted/illegal binaries, I managed to source the aforementioned files from my own Windows 10 system. It actually did work although the game still completely fails to start with DXVK. It only started after setting `PROTON_USE_WINED3D=1`. However, the video performance is very bad. I thought Gallium Nine might help but it's almost impossible to make that work since Proton started running under the Soldier runtime.

**Comment by CarnageDevs** [comment]
Indeed, WineD3D is necessary for the game to work fine with videos as of now. What is your setup? I haven't encountered any performance issues with the videos as of yet.

**Comment by chewi** [comment]
Ryzen 5 3600 with a Radeon RX 480. Should be more than enough. The 3D is (probably) fine, it's just the videos are too jumpy to comfortably watch. I've tried a few other things but no luck. Maybe the Windows 7 DLLs would work better but I'll leave it be for now. I really hope this gets fixed in Wine properly. So many other MF-based games are working now, this must be one of the last ones.

**Comment by GloriousEggroll** [comment]
It seems the offending staging patch was upstreamed, but still causes catherine classic to open in a tiny window, then close immediately.

-edit-
resolved after adding d3dcompiler_43 and _47. movies still have issues but that at least allows the game to open again.

**Comment by Cxpher** [comment]
This is surprisingly one of the few games, without anti-cheat, that still does not work properly.

What does it do with videos that makes it impossible to play them?

**Comment by ipr** [comment]
> This is surprisingly one of the few games, without anti-cheat, that still does not work properly.
> 
> What does it do with videos that makes it impossible to play them?

Just the missing decoder plugin. Log does not mention which plugin specifically, but it might be wmf or some other. And that is just basically a licensing thing.

[steam-893180.log](https://github.com/ValveSoftware/Proton/files/7608112/steam-893180.log)

**Comment by linux4life1** [comment]
I got the game to work (passed the infinite loading screen, and first cutscene) with no issues. I did the following
delete the PFX from other failed attempts to run
run the game with proton version 4.11-13 
after it sets up the new PFX close it and pop open a terminal
please note I did not write the following code nor audit it just ran it as is (hat tip Materus on protonDB)

`<Workaround removed by moderator>`
steam launch options PROTON_USE_WINED3D=1 
continue to use proton version 4.11-13 and game will launch and run fine

ubuntu 22.04 devel
AMD RX 5700XT

**Comment by kisak-valve** [comment]
Hello @linux4life1, the workaround you posted is legally problematic and has been removed.

**Comment by kisak-valve** [comment]
Catherine Classic (893180)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6527.
@ItsRogueRen posted on 2023-02-12T22:50:49:

# Compatibility Report
- Name of the game with compatibility issues: Catherine Classic
- Steam AppID of the game: 893180

## System Information
- GPU: AMD RX 6650 XT
- Driver/LLVM version: Mesa 22.3.5
- Kernel version: 6.0.12-76060006-generic
- Link to full system information report as [Gist](https://gist.github.com/ItsRogueRen/c83bdf594c13af2622438c21bd5b3ab2): 
- Proton version: 7.0-6

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.


[steam-893180.log](https://github.com/ValveSoftware/Proton/files/10717522/steam-893180.log)


## Symptoms 
Completely unplayable. Game SOMETIMES loads the main menu on some GE builds of proton, but hangs on loading the game. Standard Proton usually results in the game immediately crashing or freezing. Some users report being able to play somewhat after significant tweaking but typically with some sort of drawback such as skipping all cutscenes. The furthest I personally have been able to get to is the loading screen even after creating a new file, which resulted in an endless loading screen even after waiting upwards of 45 minutes.

## Reproduction
1) Install Catherine
2) Start game
3) Game crashes

UPDATE: Added system info gist

**Comment by 3DMicks** [comment]
I thought that maybe Proton 8 would fix this game, but it didn't. Still unplayable, even with the rebase and all.
Here is a log of the game getting stuck on the quote:

[steam-893180-hangOnQuote.log](https://github.com/ValveSoftware/Proton/files/11425896/steam-893180-hangOnQuote.log)

**Comment by AJuujarvi** [comment]
As of the latest Proton Experimental, experimental-8.0-20231219, the loading screen after starting a new game should no longer be hanging indefinitely. You may experience intermittent crashes however during video playback. It is unknown at the moment what is causing the crashes, however if you trigger said videos it should help improve it for everyone. Alternatively, running the game with `PROTON_USE_WINED3D=1 %command%` will avoid the crashes in our experience but will have flicker during video playback.

**Comment by ItsRogueRen** [comment]
I've gotten the game to run with Proton-GE, however animated cut scenes flicker sometimes and in-engine cut scenes are blurry as if a camera is out of focus. Gameplay itself is fine.

**Comment by AJuujarvi** [comment]
> I've gotten the game to run with Proton-GE, however animated cut scenes flicker sometimes and in-engine cut scenes are blurry as if a camera is out of focus. Gameplay itself is fine.

For in-engine cutscenes, I have noticed this as well with experimental-8.0-20231219. I've had instances where in game cutscenes are in focus on one machine, and on another it is out of focus. If you could try experimental-8.0-20231219 and attach a log created by running `PROTON_LOG=1 %command%` while playing the game that would be appreciated. Along with a link to full system information report as a gist. This could help narrow down where exactly the blurriness happens from.

Edit: the intro where it focuses on Trish is where I can intermittently see the blurriness. When she is centered, staring at the camera.

**Comment by trevyn** [comment]
Are the videos now eligible for the transcoding pipeline? I’m still getting the color bars placeholder.

**Comment by AJuujarvi** [comment]
Unfortunately, it will take some amount of time for the transcoding to occur. Hopefully with the popularity of this game, this will be soon.

**Comment by trevyn** [comment]
Huh, I actually got through the intro scene with Trish, then hit this:

<img src="https://github.com/ValveSoftware/Proton/assets/230691/b586d99b-b52a-4b43-b328-8083e1b48486" width="300">

**Comment by GloriousEggroll** [comment]
Got game fully working with videos in next proton-ge
needs the following winetricks/tweaks:

```
    util.protontricks('directshow')
    util.protontricks('cinepak')
    util.protontricks('lavfilters')
    util.protontricks('d3dcompiler_43')
    util.protontricks('d3dcompiler_47')
    util.disable_protonaudioconverter()
    util.winedll_override('winegstreamer', '')
```

**Comment by kisak-valve** [comment]
Catherine Classic various video related crashes (even with the latest GE-Proton fixes)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/7461.
@AnonymerNiklasistanonym posted on 2024-01-31T11:26:09:

# Compatibility Report
- Name of the game with compatibility issues: Catherine Classic
- Steam AppID of the game: 893180

## System Information
- GPU: NVIDIA GeForce RTX 3060 Ti
- Video driver version: nvidia 545.29.06
- Kernel version: 6.7.1-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/AnonymerNiklasistanonym/bbe3543f7f956ac5211b1c174923121f
- Proton version: GE-Proton8-29 / Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available. (GE-Proton8-30 was released but only contains EAC fixes)



## Symptoms 

- Videos are
  - experimental: not playing and crash the game
  - GE-Proton8-29: sometimes not playing
- Game crash (maybe memory allocation bug):

```
...
8684.019:00d4:034c:fixme:dxva2:device_manager_processor_service_GetVideoProcessorDeviceGuids 0CA41F54, 0EC6FA78, 0EC6FA38, 0EC6FA3C semi-stub.
8684.019:00d4:034c:fixme:dxva2:device_manager_processor_service_GetVideoProcessorDeviceGuids 0CA41F54, 0EC6FA78, 0EC6FA38, 0EC6FA3C semi-stub.
8684.023:00d4:034c:fixme:dxva2:device_manager_processor_service_GetVideoProcessorDeviceGuids 0CA41F54, 0EC6FC58, 0EC6FC18, 0EC6FC1C semi-stub.
8684.023:00d4:034c:fixme:dxva2:device_manager_processor_service_CreateVideoProcessor 0CA41F54, {5a54a0c9-c7ec-4bd9-8ede-f3c75dc4393b}, 0EC6FB78, 22, 15, 1827999C.
8684.024:00d4:034c:fixme:mfplat:audio_renderer_get_service_GetService Unsupported service {866fa297-b802-4bf8-9dc9-5e3b6a9f53c9}, interface {0a9ccdbc-d797-4563-9667-94ec5d79292d}.
8684.025:00d4:034c:fixme:mfplat:media_source_QueryInterface {6ef2a662-47c0-4666-b13d-cbb717f2fa2c}, 0EC6FCAC.
err:   DxvkMemoryAllocator: Memory allocation failed
err:     Size:      4194304
err:     Alignment: 16
err:     Mem types: 0,1,2,3,4
err:   Heap  Size (MiB)  Allocated   Used        Reserved    Budget
err:    0:     8192          89          57         478        6386      
err:    1:    23451          16           1          92       23451      
8684.119:00d4:034c:trace:seh:raise (22)
...
```

```
...
10960.762:00d4:00d8:fixme:dxva2:device_manager_processor_service_CreateVideoProcessor 143B6544, {5a54a0c9-c7ec-4bd9-8ede-f3c75dc4393b}, 0427FA88, 22, 15, 139EB384.
err:   DxvkMemoryAllocator: Memory allocation failed
err:     Size:      4194304
err:     Alignment: 16
err:     Mem types: 0,1,2,3,4
err:   Heap  Size (MiB)  Allocated   Used        Reserved    Budget
err:    0:     8192          75          43         467        6428      
err:    1:    23451          12           9          99       23451      
10960.883:00d4:0318:trace:seh:raise (22)
...
```

Proton log of the second, third and fourth GE-Proton8-29 play: https://gist.github.com/AnonymerNiklasistanonym/059e6bfadf3d89a9170c0a062c35e50d

## Reproduction

I played it one on Proton experimental and 4 times on GE-Proton8-29 and there were 4 separate issues:

1. After beating the final boss the video: [timestamp of that part](https://youtu.be/KgfqHXolPS0?feature=shared&t=31387)

- Proton Experimental crashes and doesn't play it
- GE-Proton8-29 1,4: Doesn't play it but was skippable and no crash
- GE-Proton8-29 2,3: Played it and no crash

2-4. Then some cutscenes come up until "A few months later" appears on screen: [timestamp of that part](https://youtu.be/KgfqHXolPS0?feature=shared&t=32137)

- GE-Proton8-29 1: A random wine error dialog popped up (start debugger or close game - but the game was still running fine so I didn't touch it) during the cutscenes and then soon when the text showed up it looped forever with no options to escape
- GE-Proton8-29 2: (2.) It played the video and when I skipped that one it crashed with a out of memory crash
- GE-Proton8-29 3: (3.) It crashed exactly the same way after skipping but the video was just a frame from the actual video while the audio was playing in the background
- GE-Proton8-29 4: (4.) It played the video the same way as in the third run but just froze since I didn't skip it, when I then skipped it since nothing was happening I got a wine error dialog: ![Screenshot_20240131_125853](https://github.com/ValveSoftware/Proton/assets/22764031/6b8c755e-a977-42fd-987d-cc627416a649)

Video recording of the crash (the third GE-Proton8-29 run): https://youtu.be/jMamOmRMKCw?si=ezcQteWr-FyswDBp

Video recording of the crash with the wine error dialog (the fourth GE-Proton8-29 run): https://youtu.be/CPR6KwwHbKM

**Comment by MasterTJ123** [comment]
> Got game fully working with videos in next proton-ge needs the following winetricks/tweaks:
> 
> ```
>     util.protontricks('directshow')
>     util.protontricks('cinepak')
>     util.protontricks('lavfilters')
>     util.protontricks('d3dcompiler_43')
>     util.protontricks('d3dcompiler_47')
>     util.disable_protonaudioconverter()
>     util.winedll_override('winegstreamer', '')
> ```

How do I use this on Steam? I am trying to run the game under Proton 7.0-6, but the cutscenes are freezing the game. Besides that, I am using these initialization parameters: `PROTON_USE_WINE3D=1 gamemoderun %command%`

**Comment by AnonymerNiklasistanonym** [comment]
> How do I use this on Steam? I am trying to run the game under Proton 7.0-6, but the cutscenes are freezing the game. Besides that, I am using these initialization parameters: `PROTON_USE_WINE3D=1 gamemoderun %command%`

@MasterTJ123 Follow these instructions to install GE-Proton: https://github.com/GloriousEggroll/proton-ge-custom?tab=readme-ov-file#installation (e.g. download & copy the latest release and then restart steam, then change the Proton version in game properties compatibility). 

I just tried to play the last level for the 5th time with GE-Proton 9-11 and did not crash (finally got the achievement to complete the story).

(I used no start parameters and am on Wayland)

**Comment by MasterTJ123** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/2207#issuecomment-2280856987

I tried using this version of Proton GE, but the application keeps "running' endlessly on Steam and nothing appears.

**Comment by AnonymerNiklasistanonym** [comment]
> > Replying to [#2207 (comment)](https://github.com/ValveSoftware/Proton/issues/2207#issuecomment-2280856987)
> 
> I tried using this version of Proton GE, but the application keeps "running' endlessly on Steam and nothing appears.

idk what the reason could be, maybe try GE-Proton with another installed game to find out if you are missing something (or clear your launch options, or use as launch options `PROTON_LOG=1 %command%` and then link your `~/steam-893180.log` file if it is created).
I didn't see related issues on protondb.com but the latest review said the cutscenes worked on experimental so maybe give proton experimental a try which should be bundled with Steam.
