### ISSUE TITLE
Tokyo Dark (687260)

### ISSUE THREAD

**Issue by Awlexus** [ValveSoftware/Proton#2405]
# Compatibility Report
- Name of the game with compatibility issues:
Tokyo Dark
- Steam AppID of the game:
687260
## System Information
- GPU: GTX 980m
- Driver/LLVM version: mesa 18.3.4-1
- Kernel version: 5.0.0-arch1-1-ARCH
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 3.7 & 3.16.4 (Couldn't start the game with 3.16 beta)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[Error log](https://gist.github.com/Awlexus/a6a1bc6b2a552b13f56636df0f18b251)
## Symptoms 
Game crashes on the first plot event in the game

## Reproduction
Open the game and inspect the face in the right window

**Comment by kisak-valve** [comment]
Hello @Awlexus, are you using an optimus laptop? Does adding `PROTON_USE_WINED3D=1 %command%` to the game's launch options make a difference?

**Comment by Awlexus** [comment]
@kisak-valve That seem to help a lot. The game is not crashing at that part anymore, but unfortunatelly a bit unstable in the beginning and over not so good in performance

**Comment by kisak-valve** [comment]
Tokyo Dark (687260) Game installs, shows "running", then stops

Issue transferred from https://github.com/ValveSoftware/Proton/issues/4337.
@benbrockn posted on 2020-11-02T00:16:01:

# Compatibility Report
- Name of the game with compatibility issues: **Tokyo Dark**
- Steam AppID of the game: **687260**

## System Information
- GPU: **GTX-1080**
- Driver/LLVM version: **455.28**
- Kernel version: **5.9.1-arch1-1**
- Link to full system information report as **[System Info Gist here](https://gist.github.com/benbrockn/d10cb8c5e3affbcb180f57e38ede13d9#file-steam_system_info)**
- Proton version: **5.0-9**

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms

Game installs, shows "Running", then stops the game

**[Tokyo Dark Gist here](https://gist.github.com/benbrockn/d10cb8c5e3affbcb180f57e38ede13d9#file-steam-687260-log)**

These commands (each separately & together) won't allow the game to load

    `PROTON_USE_WINED3D=1 PROTON_NO_ESYNC=1 PROTON_LOG=1 %command%`

**[This other issue](https://github.com/ValveSoftware/Proton/issues/2405)** might be related

**My specs:**

OS: EndeavourOS Linux x86_64
Kernel: 5.9.1-arch1-1
Shell: bash 5.0.18
Resolution: 2560x1440 @ 144Hz, 1920x1080 @ 60Hz
DE: Xfce
WM: Xfwm4
CPU: AMD Ryzen 7 2700 (16) @ 3.966GHz
GPU: NVIDIA GeForce GTX 1080
Memory: 32125MiB

## Reproduction

N/A

**Comment by kisak-valve** [comment]
Hello @benbrockn, can you check if the game runs with Proton 4.11? If it does, then please retest with Proton 5.0 as well.

Some possible lines of interest from the log:
`err:ole:CoGetClassObject class {54e211b6-3650-4f75-8334-fa359598e1c5} not registered`
`err:ole:CoGetClassObject no class object {54e211b6-3650-4f75-8334-fa359598e1c5} could be created for context 0x1`
`[200:204:1101/184141.552:FATAL:direct_manipulation.cc(38)] Check failed: SUCCEEDED(hr).`

**Comment by benbrockn** [comment]
> Hello @benbrockn, can you check if the game runs with Proton 4.11? If it does, then please retest with Proton 5.0 as well.

Thanks for the quick reply @kisak-valve . Using 4.11-13 doesn't change anything:

[Gist here](https://gist.github.com/benbrockn/c25e50abcbea90496ea6fb56fbb85c83)

**Comment by benbrockn** [comment]
Oh wait!

Running 4.11-13 with `PROTON_USE_WINED3D=1 PROTON_NO_ESYNC=1 PROTON_LOG=1 %command%` seems to work, I'll update you if there are any graphical/audio glitches or crashing

**Comment by kisak-valve** [comment]
The direct_manipulation issue might already be fixed in Proton 5.13. Upstream bug report https://bugs.winehq.org/show_bug.cgi?id=44865.

**Comment by benbrockn** [comment]
Looks like Proton 5.13-1 works, and works better without these options `PROTON_USE_WINED3D=1 PROTON_NO_ESYNC=1 PROTON_LOG=1 %command%`

**Comment by benbrockn** [comment]
@kisak-valve , recommend close

**Comment by BillFleming** [comment]
With the latest Proton 9.0-4 RC branch this game still gets stuck at a black screen.
With a GE proton like 9-20 the same issue occurs.
When using WineD3D, disabling ESync and Fsync the game still doesn't work on these newer protons, so the issue should remain open.

I have attached a log from the 9.0-4-RC. In addition to seeing the directmanipulation.dll I also see references to powrprof.dll, Kerberos dll and a long list of other special dlls because the game appears to embed the Chrome browser.
[steam-687260.log.zip](https://github.com/user-attachments/files/18295937/steam-687260.log.zip)

Edit: After installing the corefonts package and setting windows version to 7 (not sure if that helps) I am able to launch and get in game on Proton 9.0-4-RC. Everything appears to render correctly during the first few minutes of game play with no crashes.
Valve could try shipping an alternate font to courier that is installed as courier. Note that the game has a large text setting but I can't seem to select it. So there may be a second font that we need to install.
```
PROTON_USE_WINED3D=1 PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 PROTON_LOG=1 %command%
```
[steam-687260.log_withFont.zip](https://github.com/user-attachments/files/18296008/steam-687260.log_withFont.zip)

**Comment by kvoqkki** [comment]
> I played the game with Proton 5.13-6 for 20 hours, then there is a bug would occur at `香寿美のバー` scene ( I don't know its original English name ).
> 
> The game would render the graphic, but the conversation would not pop up. At first I thought it's a puzzle and tried to click all over the place, but still nothing triggered. Then I checked walkthrough which told me there should be a conversation.
> 
> Then I tried Proton Experimental, the game would stay as a black screen on load. However switch to Windows 7 as @BillFleming 's comment would help. It seems the game only works on elder Windows. But still, the _conversation won't pop up_ game bug is still there.
> 
> It's a dead end as the game can not progress any more.


Edited. I tried to load the game on real Windows 11, it stuck at  `香寿美のバー` scene  either.
Then I checked support forums to see it's a game bug, not proton bug: https://steamcommunity.com/app/687260/discussions/1/1484358860941884201/

The game devs know the bug but didn't repair it.
