### ISSUE TITLE
Zero Escape: Zero Time Dilemma (311240)

### ISSUE THREAD

**Issue by rudi4463** [ValveSoftware/Proton#2526]
# Compatibility Report
- Name of the game with compatibility issues: Zero Escape: Zero Time Dilemma
- Steam AppID of the game: 311240

## System Information
- GPU: Nvidia GTX 1080
- Driver/LLVM version: Nvidia 418.43
- Kernel version: 4.19.32-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/rudi4463/3ab686d32df5b035bd22cccc2b980129
- Proton version: 4.2-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-311240.log](https://github.com/ValveSoftware/Proton/files/3069807/steam-311240.log)

## Symptoms 

The game won't launch. You can open the game configuration tool but from there the game still cannot be launched. When trying to launch the game steam says that the game is running but nothing appears and to get rid of it the game has to be force closed.

**Comment by exolyte** [comment]
The game actually seems to work fine on vanilla wine 4.6 with a small patch. (https://bugs.winehq.org/show_bug.cgi?id=47038)
The issue I was having on vanilla wine doesn't seem to be a problem on proton so whatever issue proton is having might have been fixed between wine 4.3 and 4.6.

**Comment by petreeftime** [comment]
This is still an issue with Proton 4.11-2. I've tried changing most of the options in user_setting.py. The threads just get stuck waiting on one thread.
The error message I see in the logs is: 
```
8590.448:0027:0028:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
```

I think this means thread 28 dies in a critical section and all at others are waiting for it to release the lock, which is what causes the messages at the end of the log:
```
8660.750:0027:0039:err:ntdll:RtlpWaitForCriticalSection section 0x7bd2bb60 "../../../../proton/wine/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0039, blocked by 0028, retrying (60 sec)
```

**Comment by petreeftime** [comment]
It now works with Proton 4.11-3.

**Comment by robzombie91** [comment]
Error when launched after 4.12

wine: Unhandled page fault on read access to 0000000F at address 7EA5C849 (thread 0024), starting debugger...
Unhandled exception: page fault on read access to 0x0000000f in 32-bit code (0x7ea5c849).

**Comment by robzombie91** [comment]
https://pastebin.com/j4sbBbAs

**Comment by LittleStinky123** [comment]
The game runs fine on 0d8ab95 on ubuntu kernel 5.4.0-89-generic and rtx 3060 ti with driver version 470.74, controllers aren't recognized though. I tried with my SN30Pro+ in XInput and Switch Pro mode via bluetooth and wired as well as my DS4 via bluetooth. I tried steam-input activated and deactivated as well as the default settings for controllers. It just doesn't recognize it at all so the game can only be played with mouse and keyboard at the moment.
Edit:
It's pretty strange as I use the recommendations for mounting NTFS drives and using compatdata in the steam home directory, but after moving the game to a drive that is formatted as ext4 the controllers started working. I saw the same thing happening with giana sisters twisted dreams.

**Comment by marissa999** [comment]
Even though this game is Deck Verified I struggle with running it on my Deck. Either the game does not start at all, or it starts, but it does not detect any input (besides touchscreen). I have a hard time understanding, why this game is Deck Verified as of now.

It seems that with the latest Proton-GE (7.51) version it is the most stable for me, both the game and the launcher starts and everything is displayed properly. But I can not interact with the game at all, besides touchscreen. (A lot of people on https://www.protondb.com/app/311240 mentioned, that the game would crash after a short time, but I did not get far enough to test this)

I tried to use the default settings (not selecting any compatibility layer), manually selected the latest Proton-Ge version (7.51), manually selecting Proton Experimental or 4.11 but the game is just not working the way it should. With most versions I tested the game or the launcher wont work at all. 

> It's pretty strange as I use the recommendations for mounting NTFS drives and using compatdata in the steam home directory, but after moving the game to a drive that is formatted as ext4 the controllers started working. I saw the same thing happening with giana sisters twisted dreams.

I do have my Deck converted to BTRFS, but moving the game to my SD Card which is still Ext4 did not help me.

**Comment by kisak-valve** [comment]
Hello @marissa999, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by marissa999** [comment]
In Gamemode on my Deck, I de-selected the "Force Compatibility Tool" option so that it would use the default again, I also used the "Delete Proton files" option and the "Clear Selected Controller layout" option and also re-verified the game files, just to be totally sure, so that the installation of the game is as clear and default as possible.

I then launched the game and once I was asked if I wanna launch the game or the games launcher, I selected the first option (launching the game without the launcher)

[steam-311240.log](https://github.com/ValveSoftware/Proton/files/11068777/steam-311240.log)

Steam Report:
https://gist.github.com/marissa999/a815b128972e64d584ff1a55838f5419

**Comment by marissa999** [comment]
A friend of mine figured out a workaround/solution, which also worked for me on my Deck. Ill copy their message:

> How to fix the controls:
Change the layout to a layout called "Official Layout" with the author being "chime".
If you go back and see that the game's official layout (from chunsoft) is selected, do not worry, it seems to be a bug. Just go to "View layout" and check if all the buttons are set to "UL", "UR", "LR" etc.
At this point you should just be able to run the game and everything should work.
I think steam gets the layouts confused because they have the same name.
I also think the chime layout works because it seems like steam added a very clever feature where the steam client can read all the SDL2 inputs from a game and let you directly bind them to a button

It feels like the default controller layout should work too. But using the chimes one works for me.
