### ISSUE TITLE
The Witcher 1 (20900)

### ISSUE THREAD

**Issue by MordragT** [ValveSoftware/Proton#255]
Steam Play is enabled for all titles.
My System:
Manjaro 17.1.12
Mesa 18.1.6 with R9 270x
Console Output:

> GameAction [AppID 20900, ActionID 2] : LaunchApp changed task to ShowLaunchOption with ""
> GameAction [AppID 20900, ActionID 2] : LaunchApp waiting for user response to ShowLaunchOption ""
> GameAction [AppID 20900, ActionID 2] : LaunchApp continues with user response "0"
> GameAction [AppID 20900, ActionID 2] : LaunchApp changed task to GettingLegacyKey with ""
> GameAction [AppID 20900, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
> GameAction [AppID 20900, ActionID 2] : LaunchApp changed task to RunningInstallScript with ""
> GameAction [AppID 20900, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
> GameAction [AppID 20900, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
> GameAction [AppID 20900, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
> GameAction [AppID 20900, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
> GameAction [AppID 20900, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
> Opted-in Controller Mask: 70
> Game update: AppID 20900 "", ProcID 10174, IP 0.0.0.0:0
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 10174 for game ID 20900
> GameAction [AppID 20900, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
> >>> Adding process 10175 for game ID 20900
> GameAction [AppID 20900, ActionID 2] : LaunchApp changed task to Completed with ""
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 10176 for game ID 20900
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 10187 for game ID 20900
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 10188 for game ID 20900
> >>> Adding process 10191 for game ID 20900
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 10193 for game ID 20900
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 10196 for game ID 20900
> >>> Adding process 10207 for game ID 20900
> >>> Adding process 10212 for game ID 20900
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> ERROR: ld.so: object '/home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 10221 for game ID 20900
> Game update: AppID 20900 "", ProcID 10187, IP 0.0.0.0:0
> wine: Unhandled page fault on read access to 0x43020837 at address 0x7e94c3 (thread 0029), starting debugger...
> Game removed: AppID 20900 "", ProcID 10187 
> No cached sticky mapping in ActivateActionSet.pid 10189 != 10188, skipping destruction (fork without exec?)

**Comment by MordragT** [comment]
It does start now but there are no fonts displayed and the video scenes wont work

**Comment by mmolch** [comment]
Runs without any issues for me with Proton 3.7 on Ubuntu 18.04

System Specs:
Ubuntu 18.04
Core i7-4790K, 16GB Ram
GeForce GTX 1060 (396.51)

**Comment by lineber** [comment]
OS: Fedora release 28 (Twenty Eight) x86_64
Kernel: 4.17.14-202.fc28.x86_64
Resolution: 1920x1080, 1280x1024
DE: GNOME 3.28.3
WM: GNOME Shell
WM Theme: Adwaita
Theme: Adwaita [GTK2/3]
CPU: Intel Pentium G4620 (4) @ 3.700GHz
GPU: NVIDIA GeForce GTX 1060 3GB
Nivida Driver Version: 396.45
Memory: 4540MiB / 15492MiB

Works without any issues, no need to set anything up. This game can probably be whitelisted.  +MordragT I would suggest loading winetricks, deleting all data in the prefix and then creating a new "fresh one". I did this for another game and got it working. But Witcher seems to work without any problems (NOTE: I have the Director's Cut DLC). *Of course someone else with AMD needs to confirm that this isn't an issue with the GPU, as the two working versions seem to have Nvidia GTX 1060's.

Also, I wish there was a way to no play the long video at the beginning.

EDITED (only after I commented I noticed that you are running a non-Nvidia GPU)

**Comment by BLaDZer** [comment]
```
System:    Host: blad-pc Kernel: 4.18.3-1-MANJARO x86_64 bits: 64 Desktop: Xfce 4.12.4 
           Distro: Manjaro Linux 
CPU:       Topology: 6-Core model: AMD FX-6100 bits: 64 type: MCP L2 cache: 2048 KiB 
           Speed: 1541 MHz min/max: 1400/3300 MHz Core speeds (MHz): 1: 1554 2: 1806 3: 1527 4: 1529 
           5: 1535 6: 1529 
Graphics:  Card-1: AMD Pitcairn PRO [Radeon HD 7850 / R7 265 / R9 270 1024SP] driver: amdgpu v: kernel 
           Display: x11 server: X.Org 1.20.1 driver: amdgpu unloaded: modesetting 
           resolution: 1360x768~60Hz 
           OpenGL: 
           renderer: AMD Radeon HD 7800 Series (PITCAIRN DRM 3.26.0 4.18.3-1-MANJARO LLVM 6.0.1) 
           v: 4.5 Mesa 18.1.6
```

> *Of course someone else with AMD needs to confirm that this isn't an issue with the GPU, as the two working versions seem to have Nvidia GTX 1060's.

There was some fps drops and missing mouse cursor in in-game menu(not main menu) which fixed with ALT+TAB(maybe cuz steam overlay or something else). Everything else was fine(but I'm only played prologue).

**Comment by Playinthegames** [comment]
Installed the game and played the prologue. So far it has worked perfectly.

**Comment by swick** [comment]
Works perfectly fine. Tested a few savegames. Performance is… not great. Works much better with gallium nine.

    flatpak
    OpenGL renderer string: AMD Radeon(TM) HD 8800 Series (PITCAIRN, DRM 3.26.0, 4.18.0, LLVM 6.0.1)
    OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.1.6

**Comment by swick** [comment]
@MordragT can you please test again with Proton 3.7-4 Beta?

**Comment by OMTDesign** [comment]
This game runs near flawlessly for me using Proton 3.7-4 Beta. There is an issue when moving the mouse during the intro video causes it to lag, but there are no issues with the actual gameplay.

**Comment by CaioCSdev** [comment]
@swick for me it was working on 3.7-3 but now at 3.7-4 Beta it has some issues. mainly there's no skin :skull: 

![20180829013635_1](https://user-images.githubusercontent.com/1172532/44765855-1b052480-ab2d-11e8-9de4-a92153ad23bb.jpg)

![20180829015006_1](https://user-images.githubusercontent.com/1172532/44766076-1f7e0d00-ab2e-11e8-86d2-a074b6e17d85.jpg)


I'm runnig on:
 - Ubuntu 18.04.1
 - AMD FX(tm)-6100 Six-Core Processor
 - GF116 [GeForce GTX 550 Ti]
 - nvidia-driver-390

Many thanks

**Comment by noammor** [comment]
The no skin bug can be solved by setting a registry key in wine: https://bugs.winehq.org/show_bug.cgi?id=34052

In my testing, the no skin bug appears randomly and will appear and disappear on game restart.

**Comment by grabmateusz** [comment]
# Compatibility Report
- Name of the game with compatibility issues:
The Witcher: Enhanced Edition
- Steam AppID of the game:
20900

## System Information
- GPU: GeForce GT 540M
- Driver/LLVM version: NVidia driver 384.130
- Kernel version: 4.13.0-46-generic
- Link to full system information: https://gist.github.com/grabmateusz/b38a08528372b6856d5805e169884c64
- Proton version: 3.7-6 Beta

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. (N/A)
- [ ] that I have checked whether there are updates for my system available. (I will check the game with newest Ubuntu release and newest NVidia Driver, this report IS NOT generated based on newest OS and GPU driver version)

## Game log
https://gist.github.com/grabmateusz/d8289ff0b86269092ce1139fd140d665

## Symptoms
- Game has known bug with missing people except eyeballs and teeth:
![screenshot from 2018-09-09 15-23-13](https://user-images.githubusercontent.com/13624002/45265306-ff611e80-b448-11e8-9a29-5de8711a49ad.png)

- It is impossible to move and look around (mouse and keyboard seems not to work at the same time) 

## Reproduction
1) Run a new game and use mouse + keyboard control variant
2) Watch how it looks
3) Try to move Geralt and look around

**Comment by Waddlen** [comment]
I've played the game for about an hour. Worked out-of-the-box perfectly. 
Ubuntu 18.04
Linux 4.15.0-34-generic
R7 1700
GTX 1080 Nvidia 396.54
Proton 3.7-3 and 3.7-6

@grabmateusz 
READ: [Nvidia 396.54 is the MINIMUM driver necessary for Proton](https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md), and you should always test with the latest.
Also, Ubuntu 17.10 has been end-of-life for a few months now. Upgrade to 18.04 LTS, it will be supported for 5 years.

**Comment by swick** [comment]
Performance is good enough for me to consider it playable now. The visual problem has a workaround.

@MordragT can you try to test again?

**Comment by noammor** [comment]
I "tested" the game for around 40 hours in the last 2 weeks. Ubuntu 18.04, GTX 660, Nvidia 396.54, beta client. Default Proton versions (haven't changed any settings). I manually set the registry key using wine regedit on the wineprefix.

Performance is good with some slowdowns on medium graphics. I've been playing exclusively using a Steam Controller through a Steam Link. I encounter only one issue worth mentioning - 

 * the in-game mouse cursor is visible after a left click in mouse+WASD mode (third person view).

This is a particular bizarre one - when I input a left click using the Steam controller, the mouse cursor becomes visible and sort of suck on screen (it should be invisible in this mode). When I input a left click using the mouse, it doesn't happen.

After the mouse cursor appears, it will stay stuck on screen until some dialog comes up. When the dialog is closed, the mouse cursor will not be visible until the next time I input a left click using the controller.

For mouse/keyboard players, I'd certainly white-list this game.

**Comment by kisak-valve** [comment]
Witcher 1 When  set language as Chinese and save game will cause crash

Issue transferred from https://github.com/ValveSoftware/Proton/issues/2094.
@spphinslove posted on 2018-12-15T12:35:53:

# Compatibility Report
The game work fine unless you set the language as chinese.when save the game it will crash and wont save. 

- Steam AppID of the game:
20900
## System Information
- GPU: gtx960m hd 4600
- Driver/LLVM version:  Mesa 18.3.1 or nvidia 415.23 
- Kernel version: 4.19.8
- Link to full system information report as [Gist](https://gist.github.com/):
https://gist.github.com/spphinslove/9d3ec6a3b82f63e855e98f8372da67a5
I use bumblebee to switch videocard between intel and nvidia.
- Proton version:
3.16-5Beta
## I confirm:
- [] that I haven't found an existing compatibility report for this game.
- [YES] that I have checked whether there are updates for my system available.

## PROTON_LOG

[steam-20900.log](https://github.com/ValveSoftware/Proton/files/2682604/steam-20900.log)
## Symptoms 
Crash
## Reproduction
option->subtitles->chinese
run game and save game or wait autosave.

**Comment by ghost** [comment]
When game set language as Chinese,and the map name also Chinese.save game will cause crash.
if map name was English or other non-chinese，save game will work fine.
You can see the picture below,the document name is based on map name.(when loading map,you can see the map name)
![2018-12-17_22-54](https://user-images.githubusercontent.com/11383988/50094720-cf4ac800-024e-11e9-93a0-ae2d0a5f100c.png)

**Comment by ghost** [comment]
# Compatibility Report
The Witcher: Enhanced Edition Director's Cut
- Steam AppID of the game: 20900

## System Information
Proton:Beta (3.16-5)
Distro:Debian GNU/Linux 9.6 (stretch) (64 bits)
Kernel:4.20.0-rc7
RAM:6 GB
GPU Driver:NVIDIA 415.22.01
GPU:NVIDIA GeForce GTX 750
CPU:AMD Phenom II X6 1090T


the game work well for me but ,i need to disable steam overlay (in steam game property);otherwise i "loose" the mouse device: in the menu game go to steam overlay ("shift"+"tab") and leave it (again "shift"+"tab"),you will see you can't use keyboard or mouse to browse.

**Comment by kisak-valve** [comment]
The Witcher: Enhanced Edition (20900)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/2118.
@ItsDaFaz posted on 2018-12-22T10:28:02:

# Compatibility Report
- Name of the game with compatibility issues: The Witcher: Enhanced Edition
- Steam AppID of the game: 20900

## System Information
- GPU: NVIDIA GTX 750
- Driver/LLVM version: 
- Kernel version: Linux 4.18.0-13-generic
- Link to full system information report as <a href="https://gist.github.com/ItsDaFaz/63014ef5da7583358f8deeeb4d24cada#file-sysinfo-txt">GIST</a>
- Proton version: 3.16-4

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.



## Symptoms 
When I try to run the game which is installed in an ext4 partition, the game closes right after the DirectX install dialog pops up. There is no other message that pops up afterwards.
I do have Python 2.7+ installed. I believe installing the game on a separate HDD formatted to ext4 is an issue


## Reproduction
Just clicking play

**Comment by gasinvein** [comment]
The Witcher crashes on save just like https://github.com/ValveSoftware/Proton/issues/255#issuecomment-447584408 stated, with language set to russian (probably this would reproduce with any non-ASCII locale).
This is likely a proton-specific bug, as on vanilla wine 4.0-rc5 the game saves and loads just fine.

**Comment by Spiffyk** [comment]
# Compatibility Report
- Name of the game with compatibility issues: The Witcher: Enhanced Edition
- Steam AppID of the game: 20900

## System Information
- GPU: GTX 960M
- Driver/LLVM version: NVIDIA 415.25
- Kernel version: 4.18.20-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Spiffyk/065f6235ad92525f06de911e1a119d17
- Proton version: 3.16-6 Beta vs 3.7-8

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

The game crashes when I try to save with Proton 3.16-6 Beta. With Proton 3.7-8 it seems to be working fine. I tried `PROTON_NO_ESYNC=1` to see if that causes the issue but it did not change anything.

## Reproduction

Try saving the game once it allows you (right after the first fight).

**Comment by Leopard1907** [comment]
Game regressed. It was working perfect on 3.16-4 but not on 3.16-7. 

It crashes when you start a new game. I tried disabling esync , adding large adress aware variable and old gl strings variable but result was same every time.

Proton log:

[steam-20900.log](https://github.com/ValveSoftware/Proton/files/2919758/steam-20900.log)

**Comment by aeikum** [comment]
Hi all. The problem with saving games in non-English languages should be fixed in 3.16-7.

@Leopard1907 Thank you for providing the log. Unfortunately we haven't been able to reproduce your failure. Are you using a non-English language for Witcher 1? Does Witcher 1 still work in 3.16-4 for you?

**Comment by Leopard1907** [comment]
@aeikum 

I'm using English language , on a Turkish client and OS.

Yes , Witcher 1 still works on 3.16-4. And i also didn't have any save issues on 3.16-4. Saving and loading works just fine.

I assume that is the fix you mentioned?

https://github.com/ValveSoftware/Proton/commit/2ae0d898eb1d6279cc705307a459f920bc7c921e

I had language related problems before on Steam Client but those are mostly fixed.

https://github.com/ValveSoftware/steam-for-linux/issues/5827

https://github.com/ValveSoftware/steam-for-linux/issues/4792

I still have a keyboard problem though , on some games.

https://bugs.winehq.org/show_bug.cgi?id=46102

So 3.16-7 broke things for me on Witcher 1 and also somehow Dirt 3 regressed on it. Both still works fine with 3.16-4. Games like Witcher 3, Quake Champions etc still works on 3.16-7.

**Comment by aeikum** [comment]
@Leopard1907 Thanks for explaining. This seems to be a problem specific to using Wine with the Turkish locale. I will look into the problem. As a workaround in the meantime, I think you can set `LC_ALL=en_US.UTF-8 %command%` in the game's Launch Options in Steam to get the game running again.

**Comment by Leopard1907** [comment]
Hi @aeikum 

I just tried with that launch option on 3.16-8.

Game still crashes when you start a new game.

3.16-4 still works flawless.

**Comment by aeikum** [comment]
Hi again, @Leopard1907. Strange that the workaround didn't work. One of our developers found that this seems to be related to this glibc issue: https://sourceware.org/bugzilla/show_bug.cgi?id=23393 We are investigating a workaround for Proton/Wine.

**Comment by Leopard1907** [comment]
@aeikum Thanks for the answer. Was it supposed to solve loading issue or keyboard issue?

Because with 3.16-8 i can't boot a new game ( probably loading a saved one will also end up with crash ) , so i didn't test keyboard related problem if that is the case workaround intends to solve.

**Comment by aeikum** [comment]
Probably only the loading issue.

**Comment by Leopard1907** [comment]
So i tested the right one :)

Strangely 3.16-8 and 7 caused regressions for me on various titles. They all seem to be related.

Skyrim SE infinite loading screen , Dirt 3 doesn't boot , Grid 1 crash after first Codemasters scene.

I already reported them and attached logs , if there are anymore tests i can do on my end i would gladly do it. They all seems to work fine on 3.16-4.

**Comment by aeikum** [comment]
Yes, thank you for reporting. I'm surprised the LC_ALL thing didn't work. Maybe try with `LC_CTYPE=C` or `LC_CTYPE=en_US.UTF-8` or `LC_ALL=C`?

**Comment by Leopard1907** [comment]
@aeikum Sorry for late reply.

Both `LC_CTYPE` workarounds worked on 3.16-8  , `LC_ALL=C` didn't work.

**Comment by aeikum** [comment]
Great, thanks. I guess I misunderstand some part of those variables (read locale(7) sometime, it's a bit complicated). Anyway, I will let you know when we have a real fix for this in Proton. In the meantime, using that workaround should be safe, I think.

**Comment by Leopard1907** [comment]
Thanks for your interest. Have a good day.

**Comment by Leopard1907** [comment]
@kisak-valve 

Proton 4.2-2 fixed that regression for me on Witcher 1. Skyrim SE and Dirt 3 also seems fixed. However Grid 1 still keeps crashing on 4.2-2.

`Fixed some games failing or crashing in certain locales like Turkish.`

@aeikum Thanks for your interest. One more thing to ask ; do i have to open a seperate issue on Proton tracker for keyboard locale problem i mentioned and linked the Wine bug report or is it visible enough?

**Comment by aeikum** [comment]
@Leopard1907 Great, glad it's working for you! I don't think opening another report for the keyboard problem is needed. Probably you'll get the best results by being active on the Wine bug. We'll take a quick look at Grid, it's likely it just needs a small correction to some other part of Wine (see Piotr's recent str* related patches on wine-devel if you're interested).

**Comment by Leopard1907** [comment]
@aeikum I will , thanks again!

**Comment by Leopard1907** [comment]
Despite game works very well ; there are two issues. I don't know if they are exist on Windows or not.

1-) Alt tabbing and getting back into game introduces graphical issues. Weirdly , fps counter of Steam overlay disappears too when that happened. Changing location or alt tabbing and getting back into game fixes that.

![Ekran Görüntüsü - 2019-05-18 01-23-12](https://user-images.githubusercontent.com/24878978/57959360-162b0f80-790c-11e9-9f4b-252f028e5961.png)

2-) Game crashes after alt tabbing and getting back in game at crowded places like Vizima streets.

Log of it:

[steam-20900.log](https://github.com/ValveSoftware/Proton/files/3193303/steam-20900.log)

**Comment by Newbytee** [comment]
I can confirm that this game exhibits the same issue I detailed regarding The Witcher 3 [here](https://github.com/ValveSoftware/Proton/issues/607#issuecomment-507560155). I've yet to find anything that differs, aside from that instead of merely going back to normal framerate after the brief freeze, Witcher 1 (sometimes?) plays the missed frames at fast-forward rather than skipping them. Can look a bit humorous.

**Comment by Newbytee** [comment]
Running this game with PROTON_USE_D9VK set to 1 causes visual artefacts. They are a bit hard to catch, but here's one:

![20190731091019_3](https://user-images.githubusercontent.com/4428753/62191120-3008ba00-b373-11e9-9c3b-6e84dfa2bd2d.jpg)

nvidia 430.26
Linux 5.1.20
Fedora 30
GTX 970

**Comment by AntipovDen** [comment]
Hi! First of all, thank you, Valve, for starting and developing the Proton project, it's awesome.

I have troubles with running The Witcher Enhanced Edition with Derictor's cut DLC. When I run the game, nothing happens, no window appears, however I can see the process witcher.exe in the list of processes (and the time while this process is running counts as "hours played" for this game)

Sometimes after a system update the game runs perfectly, with no bugs or any graphical problems (I have finished the prologue when it happened). But another system update returns me to the situation described above (in which I am now).

I do not see any clues in the logs of the game or in the  console output of the Steam (both are attached). I have found an issue with quite similar symptoms for Witcher 3 here
https://steamcommunity.com/app/221410/discussions/0/1640915206462889040/
However, turning off the shaders pre-caching hasn't worked out for me.

OS: ArchLinux, kernel 5.3.1
CPU: Intel Core i5-7200U CPU 2.50GHz
GPU: Intel HD Graphics 620
GPU driver: mesa 19.1.7
vulkaninfo output is also attached

[steam.log](https://github.com/ValveSoftware/Proton/files/3659614/steam.log)
[steam-20900.log](https://github.com/ValveSoftware/Proton/files/3659615/steam-20900.log)
[vulkaninfo.txt](https://github.com/ValveSoftware/Proton/files/3659616/vulkaninfo.txt)

**Comment by lavadrop** [comment]
- I'm getting red spots around the lab at the beginning, don't know if they're supposed to be flying embers since I never played it before.
- Quest text is cutoff.
- Without enabling D9VK, in-game dialogue videos are static pictures of the first frame.
- Intro movie is played at my ultrawide resolution but zoomed in.
![20191229223348_1](https://user-images.githubusercontent.com/6760790/71568503-6fa41100-2a8d-11ea-9a4b-3088dd633520.jpg)
![20191229224005_1](https://user-images.githubusercontent.com/6760790/71568505-7468c500-2a8d-11ea-9ea4-0df46fb74aa6.jpg)

**Comment by Newbytee** [comment]
>     * I'm getting red spots around the lab at the beginning, don't know if they're supposed to be flying embers since I never played it before.

They are due to high toxicity. Intentional.

**Comment by soredake** [comment]
>Intro movie is played at my ultrawide resolution but zoomed in.

It's a game bug.
>Quest text is cutoff.

I don't experience this with 4.11-11.

**Comment by soredake** [comment]
@kisak-valve can this be converted to whitelist request?

**Comment by kisak-valve** [comment]
Hello @soredake, you can grab the [whitelist request template](https://github.com/ValveSoftware/Proton/issues/new?template=whitelist-request.md), copy it over to the comment box here and fill it out to request that a compatibility report get converted. We will have a holding period for anyone else to give feedback if they're seeing any issues that would block the game from being whitelisted.

**Comment by soredake** [comment]
# Whitelist Request
- Name of the game to be whitelisted: The Witcher 1
- Steam AppID of the game: 20900

## System Information
- GPU: RX 560
- Driver/LLVM version: Mesa 19.3.2
- Distro version: ArchLinux
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/soredake/ed1fa30f885371dda5f331815920a3ae
- Proton version: 4.11-12

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [X] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [X] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [X] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [X] Although I consider the gaming experience equal to Windows there are remaining issues:
Needs d3d9 from dxvk for good performance.

**Comment by kisak-valve** [comment]
Is anyone seeing any issues with this game and Proton 4.11 with `PROTON_USE_D9VK=1 %command%` that would block it from being whitelisted?

@lavadrop, can you check if the cut off text is limited to ultrawide desktop resolutions?

**Comment by lavadrop** [comment]
Nothing changed.
![Screenshot from 2020-01-20 17-31-52](https://user-images.githubusercontent.com/6760790/72763801-12dad880-3bab-11ea-9a64-cb459452d500.jpg)

**Comment by kisak-valve** [comment]
Your screenshot is 2560x1080, the same as your previous report. Can you easily check 1920x1080?

**Comment by lavadrop** [comment]
Yeah, 16:9 ratio shows proper text.

**Comment by kisak-valve** [comment]
Looking around a bit, you're not alone at least https://www.reddit.com/r/witcher/comments/epap40/witcher_1_text_is_being_cut_off_or_truncated/.

**Comment by soredake** [comment]
I play in 21:9, but in russian and quest text is fine

**Comment by soredake** [comment]
Can you test this in Windows? Maybe it's game bug and not related to proton

**Comment by Leopard1907** [comment]
https://www.pcgamingwiki.com/wiki/The_Witcher

According to pcgamingwiki thread about this game , game has various problems at non 16:9 resolutions.

https://www.pcgamingwiki.com/wiki/The_Witcher

Which also leads to such a page.

https://www.wsgf.org/dr/witcher

Looks like those woes are game related.

**Comment by soredake** [comment]
Finished game, 39 hours, zero problems.

**Comment by Newbytee** [comment]
The is actually one issue left in this game: the sky does not render when set to max visibility if DXVK is used. It was, however, fixed in DXVK 1.5.4. 

https://github.com/doitsujin/dxvk/issues/1402

**Comment by CSahajdacny** [comment]
Is there a way to enable Vsync?

**Comment by Newbytee** [comment]
> Is there a way to enable Vsync?

I remember I looked quite thoroughly for a way to do this when I played this game in Windows many years ago, but not finding any.

**Comment by shoober420** [comment]
# Whitelist Request
- Name of the game to be whitelisted: The Witcher: Enhanced Edition
- Steam AppID of the game: https://steamdb.info/app/20900/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.59
- Distro version: Arch
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 5.0-3

Works great out of the box.

**Comment by LinAGKar** [comment]
There is a graphical glitch at the beginning of dialogues. Normally, when you start a dialog, the image starts out letter boxed, and then gradually fills the screen. This works correctly when using wined3d, but when using DXVK, the image is at the top of the screen instead of centered, and the bottom of the screen is filled with garbage.

I'm playing the GOG version in Lutris, but people are reporting the same issue for SteamPlay/Proton on [protondb](https://www.protondb.com/app/20900). So currently, this needs PROTON_USE_WINED3D=1.

I am running at 1920x1080.

**Comment by rtentser** [comment]
> missing mouse cursor

Can reproduce it in main menu by pressing Shift there or at intro videos. Holding Shift brings mouse cursor back. Loading a save solves the problem (everything is back to normal). Didn't test with a new game.

Probably related to OTS mode, where holding Shift activate "free camera" with a mouse cursor.

**Comment by Newbytee** [comment]
> > missing mouse cursor
> 
> Can reproduce it in main menu by pressing Shift there or at intro videos. Holding Shift brings mouse cursor back. Loading a save solves the problem (everything is back to normal). Didn't test with a new game.

This is a game bug. It happens in Windows too. I remember being very annoyed by it.

**Comment by rtentser** [comment]
Don't have orange trail with group steel fighting style. Probably a game bug too, but i'm not sure.

**Comment by sebaro** [comment]
Proton 5.13-5 breaks full-screen, fine with 5.0-10.

**Comment by kisak-valve** [comment]
Hello @sebaro, how exactly is the game misbehaving? Please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by sebaro** [comment]
@kisak-valve
My display resolution is 1280x1024 and game resolution is set to 800x600.
The game doesn't start in full-screen but windowed mode (maximized).
Also the mouse position is not detected correctly, I have to click above game's clickable items/buttons.

If I change the game resolution to 1280x1024, the game flickers on start and it gets in full-screen but not correctly, I can see parts of the desktop. Toggling full-screen off/on in game setting fixes this issue but I have to do it every time I start the game.

Attached logs for both 5.0 and 5.13:
[steam-20900.tar.gz](https://github.com/ValveSoftware/Proton/files/5936442/steam-20900.tar.gz)

Thanks.

**Comment by sebaro** [comment]
I'm having the same issues with other games (Railroad Tycoon II: Platinum [7620]) and Proton 5.13, so it's not game related. Should I open a new bug?

**Comment by AkioET** [comment]
I've been having a similar issue to the original on this thread. Can't make much sense out of my launch logs. I'm attaching it here, can someone help?
[steam-20900.log](https://github.com/ValveSoftware/Proton/files/7664115/steam-20900.log)

**Comment by kisak-valve** [comment]
The Witcher: Enhanced Edition wont launch

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5431.
@glag15 posted on 2021-12-21T15:44:42:

# Compatibility Report
- Name of the game with compatibility issues: The Witcher: Enhanced Edition 
- Steam AppID of the game: 20900

## System Information
- GPU:  rtx 3080 ti
- Driver/LLVM version:  495.46
- Kernel version:  5.15.10-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/glag15/7e56710611d3f97780eca00efa2fd4d0
- Proton version: 6.3.8 (i did try with all available version as well as the GE and TKG)

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. i did but the problem wasn't the same and the solution didn't help
- [ ] that I have checked whether there are updates for my system available. system is updated


[steam-20900.log](https://github.com/ValveSoftware/Proton/files/7756430/steam-20900.log)

## Symptoms  game won't launch


## Reproduction
press play
nothing happends

did try to look around and tried a few solutions to similar problems (from different games) also tried to diagnose with this https://wiki.archlinux.org/title/Steam/Troubleshooting but i am a linux newbie and couldn't solve it
also tried reinstalling the game/proton/steam/drivers

**Comment by vilasfe** [comment]
I was fighting the same issue for the last 2 weeks on KDE Neon based on Focal LTS. I finally fixed it by installing "OpenVR Benchmark" and running it even though I have no VR equipment attached. That installed the MS Runtime redistributables. Then I uninstalled that and attempted to relaunch Witcher. That updated the MS DirectX installation and the game started working. It was a long shot based on the only error in the log being related to not opening libopenvr_api.so and it just happened to work. Hope this helps others running the game, and even better if it helps the proton/wine devs.

**Comment by spirritus** [comment]
Witcher not starting CommonLib.dll is missing
[steam-20900.log](https://github.com/ValveSoftware/Proton/files/8459403/steam-20900.log)

**Comment by spirritus** [comment]
update: my steam library for witcher is located on a NTFS disk that is mounted with ntfs-3g.
According to this link:
https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows
sometimes there can be issues with the case sensitivity leading to data not found.
I remounted with lowntfs-3g and now it seems to work.

**Comment by Jacajack** [comment]
@vilasfe I've been struggling to get the game running on my fresh Manjaro KDE installation since yesterday. During the installation I noticed that Steam did not run the MS Runtime installer for some reason. Later on, I saw the OpenVR error, but assumed that it was just a red herring. Today, I followed your instructions and installed "OpenVR Benchamrk" on Steam. As you said, it triggered the installation of all the necessary MS stuff. Now the Witcher works just fine. Thanks!

**Comment by kisak-valve** [comment]
The Witcher Enhanced Edition (20900)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6089.
@b1zzu posted on 2022-08-13T19:29:17:

# Compatibility Report
- Name of the game with compatibility issues: The Witcher Enhanced Edition 
- Steam AppID of the game: 20900

## System Information
- GPU: NVIDIA GeForce GTX 960
- Driver/LLVM version: 4.6.0 NVIDIA 515.65.01
- Kernel version: 5.18.16-200.fc36.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/b1zzu/80f5ed85bc12c353e4dfba8ab1899314
- Proton version: 1659678174 experimental-7.0-20220805

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.



[steam-20900.log](https://github.com/ValveSoftware/Proton/files/9332044/steam-20900.log)

## Symptoms 

The game doesn't start

## Reproduction

Run `The Witcher Enhanced Edition` from Steam with Proton Experimental 

## Additional Info

- I've tried with different Proton version but none seems to work for me
- From protondb other users have a similar problem

**Comment by kisak-valve** [comment]
The witcher enhanced edition won't start

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6283.
@fbenedett posted on 2022-11-01T18:07:53:

# Compatibility Report
- Name of the game with compatibility issues: The Witcher enhanced edition
- Steam AppID of the game: 20900

## System Information
- GPU: NVIDIA GeForce RTX 3050 Laptop GPU
- Driver/LLVM version: Driver Version: 520.56.06
- Kernel version: 5.15.0-52-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:
Experimental
7.0-4
and I tried many others

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.


[steam-20900.log](https://github.com/ValveSoftware/Proton/files/9912901/steam-20900.log)


## Symptoms 
The game does NOT launch at all.

**Comment by kisak-valve** [comment]
Hello @LinAGKar, based on the note at https://github.com/doitsujin/dxvk/issues/1684#issuecomment-1071502836, are you able to reproduce the misrendering you mentioned at https://github.com/ValveSoftware/Proton/issues/255#issuecomment-644312220 with newer Proton/DXVK?

**Comment by LinAGKar** [comment]
Did a quick test with DXVK v2.1, and didn't see that issue

**Comment by Wedge009** [comment]
Proton 7 is the last release Witcher 1 is working for my system. It looks like when I checked Proton 8 at its release, I neglected to report the only regression in my library. Retesting with the release of Proton 9, it seems Witcher 1 is still broken. The only hint I get from the log is that it can't find MSVC libraries, but retesting in Proton 7 they seem to be installed just fine.

[steam-20900-proton7.log](https://github.com/ValveSoftware/Proton/files/15214612/steam-20900-proton7.log)
[steam-20900-proton9.log](https://github.com/ValveSoftware/Proton/files/15214615/steam-20900-proton9.log)

I have no command-line options other than logging and am just using the standard Proton releases.

**Comment by Wedge009** [comment]
Hmm, I had a quick look at ProtonDB, doesn't appear that people are having problems running on Proton 8, so what might I be missing for my system?

**Comment by marmitar** [comment]
Game works even full of mods for me. I'm using `MESA_VK_WSI_PRESENT_MODE=fifo` to force V-Sync, and `DXVK_FRAME_RATE=144` to also force FPS cap. Besides that, I made the following Python script for the [4GB Memory Patch](https://www.nexusmods.com/witcher/mods/954), using [pefile](https://pypi.org/project/pefile/):

```python
﻿from pathlib import Path
import pefile

# works with any 32-bit Windows executable
file_path = Path.home() / '.local/share/Steam/steamapps/common/The Witcher Enhanced Edition/System/witcher.exe'
pe = pefile.PE(file_path)

pe.OPTIONAL_HEADER.DllCharacteristics |= 0x0020

pe.write(file_path)
pe.close()
print(f"Patched file {file_path}")
```

**Comment by Wedge009** [comment]
I didn't retest Proton 8 or 9 but testing Proton 10 just now, seems to be okay.
