### ISSUE TITLE
SpaceEngine (314650)

### ISSUE THREAD

**Issue by f1ow03** [ValveSoftware/Proton#2842]
# Compatibility Report
- Name of the game with compatibility issues: Space Engine
- Steam AppID of the game: 314650

## System Information
- GPU: Radeon RX580
- Driver/LLVM version: amdgpu-pro 18.40-676022
- Kernel version: 4.15
- Link to full system information report as[ GIST](https://gist.github.com/f1ow03/7fb9b73c1a6a138e27cf7cb848db171d) 
- Proton version: 4.2-9

## I confirm:
- [+ ] that I haven't found an existing compatibility report for this game.
- [+ ] that I have checked whether there are updates for my system available.

## Symptoms 
![2311s23](https://user-images.githubusercontent.com/52285610/60301515-48338680-993a-11e9-9729-f7dba11e7064.jpg)
[steam-314650.log](https://github.com/ValveSoftware/Proton/files/3336653/steam-314650.log)

**Comment by Dexter9313** [comment]
For what it's worth, I can't reproduce the problem with nvidia graphics cards (GTX 1080 and RTX 2080 Ti), it might be AMD related.

**Comment by f1ow03** [comment]
Okay, I installed newest Mesa drivers (19.2.0) and problem is no longer presist. I suppose issue is solely in amdgpu-pro driver. Besides, most dx10 and dx11 games work fine on amdgpu-pro, but such problem appeared on OpenGL game....strange, very strange.

**Comment by kisak-valve** [comment]
Space Engine on Steam Linux

Issue transferred from https://github.com/ValveSoftware/Proton/issues/2931.
@Spacesteve451 posted on 2019-07-31T21:20:50:

`<Blank template omitted>`

***
@Spacesteve451 commented on 2019-07-31T21:23:03:

Hello, I recently switched from Windows to Linux. I have enabled SteamPlay and Proton for all games. I previously bought Space Engine and Space Engine Pro. I also upgraded to Steam beta. I have upgraded linux software. After all of that I am still unable to load Space Engine. The closest i've gotten is a white screen window loading and music but nothing more. Please help me with this issue. I have previously downloaded previous versions of Space Engine and I don't want to miss out on this program. Thank you.The error message i'm getting is as follows: "Error loading texture generator shaders. Press yes to run program with procedural planets disabled. Press no to exit." When I press yes the program loads but only with a blank white screen and I can hear music. Nothing more. When I press no the program closes. Does anyone else have this issue?

**Comment by laichiaheng** [comment]
The game crashes immediately, no matter if ACO is enabled.
[log](https://gist.github.com/laichiaheng/c29019ba480eef66634c416f542ff830)
[System Information](https://gist.github.com/laichiaheng/e22b0c04d575f9f172e8cbdfd2b77121)

However, if I open the game at the 3rd or 4th time, it runs successfully.

**Comment by kisak-valve** [comment]
Hello @laichiaheng, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by laichiaheng** [comment]
> Hello @laichiaheng, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Done.

**Comment by laichiaheng** [comment]
> Hello @laichiaheng, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

I was wrong, it happens to the game without ACO, too.
This game crashes a lot.

**Comment by laichiaheng** [comment]
The XBOX ONE controller doesn't work with remote play.
https://gist.github.com/laichiaheng/e22b0c04d575f9f172e8cbdfd2b77121

**Comment by iraklisg** [comment]
> Space Engine on Steam Linux
> 
> Issue transferred from #2931.
> @Spacesteve451 posted on 2019-07-31T21:20:50:
> 
> `<Blank template omitted>`
> 
> @Spacesteve451 commented on 2019-07-31T21:23:03:
> 
> Hello, I recently switched from Windows to Linux. I have enabled SteamPlay and Proton for all games. I previously bought Space Engine and Space Engine Pro. I also upgraded to Steam beta. I have upgraded linux software. After all of that I am still unable to load Space Engine. The closest i've gotten is a white screen window loading and music but nothing more. Please help me with this issue. I have previously downloaded previous versions of Space Engine and I don't want to miss out on this program. Thank you.The error message i'm getting is as follows: "Error loading texture generator shaders. Press yes to run program with procedural planets disabled. Press no to exit." When I press yes the program loads but only with a blank white screen and I can hear music. Nothing more. When I press no the program closes. Does anyone else have this issue?

Yes I do have this issue using Proton 5.0.5
As A result I cannot launch SpaceEngine :cry:

**Comment by Dexter9313** [comment]
> > Space Engine on Steam Linux
> > Issue transferred from #2931.
> > @Spacesteve451 posted on 2019-07-31T21:20:50:
> > `<Blank template omitted>`
> > @Spacesteve451 commented on 2019-07-31T21:23:03:
> > Hello, I recently switched from Windows to Linux. I have enabled SteamPlay and Proton for all games. I previously bought Space Engine and Space Engine Pro. I also upgraded to Steam beta. I have upgraded linux software. After all of that I am still unable to load Space Engine. The closest i've gotten is a white screen window loading and music but nothing more. Please help me with this issue. I have previously downloaded previous versions of Space Engine and I don't want to miss out on this program. Thank you.The error message i'm getting is as follows: "Error loading texture generator shaders. Press yes to run program with procedural planets disabled. Press no to exit." When I press yes the program loads but only with a blank white screen and I can hear music. Nothing more. When I press no the program closes. Does anyone else have this issue?
> 
> Yes I do have this issue using Proton 5.0.5
> As A result I cannot launch SpaceEngine cry

Once again, cannot reproduce on my system. I guess they'll need to know your system information because it seems to be system specific.

**Comment by iraklisg** [comment]
@Dexter9313 please find below a detailed report of my system information

```
  ~ inxi -F
System:    Host: home Kernel: 5.4.30-1-MANJARO x86_64 bits: 64 Desktop: Xfce 4.14.2 Distro: Manjaro Linux 
Machine:   Type: Desktop System: Gigabyte product: H57M-USB3 v: N/A serial: <root required> 
           Mobo: Gigabyte model: H57M-USB3 serial: <root required> BIOS: Award v: F6 date: 05/04/2010 
CPU:       Topology: Dual Core model: Intel Core i3 540 bits: 64 type: MT MCP L2 cache: 4096 KiB 
           Speed: 1426 MHz min/max: 1197/3059 MHz Core speeds (MHz): 1: 1233 2: 1242 3: 1236 4: 1255 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] RV710 [Radeon HD 4550] driver: radeon v: kernel 
           Display: x11 server: X.Org 1.20.8 driver: ati,radeon unloaded: modesetting 
           resolution: 1280x1024~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: AMD RV710 (DRM 2.50.0 / 5.4.30-1-MANJARO LLVM 9.0.1) v: 3.3 Mesa 20.0.4 
Audio:     Device-1: Intel 5 Series/3400 Series High Definition Audio driver: snd_hda_intel 
           Device-2: Advanced Micro Devices [AMD/ATI] RV710/730 HDMI Audio [Radeon HD 4000 series] driver: snd_hda_intel 
           Sound Server: ALSA v: k5.4.30-1-MANJARO 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           IF: enp3s0 state: up speed: 100 Mbps duplex: full mac: 1c:6f:65:28:85:d1 
           IF-ID-1: docker0 state: down mac: 02:42:a4:1b:c5:e1 
Drives:    Local Storage: total: 585.00 GiB used: 71.30 GiB (12.2%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 830 Series size: 119.24 GiB 
           ID-2: /dev/sdb vendor: Western Digital model: WD5002ABYS-02B1B0 size: 465.76 GiB 
Partition: ID-1: / size: 75.53 GiB used: 52.13 GiB (69.0%) fs: ext4 dev: /dev/sda5 
           ID-2: swap-1 size: 2.00 GiB used: 4.5 MiB (0.2%) fs: swap dev: /dev/sda6 
Sensors:   System Temperatures: cpu: 46.0 C mobo: N/A gpu: radeon temp: 61 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 200 Uptime: 10h 32m Memory: 7.71 GiB used: 2.13 GiB (27.6%) Shell: zsh inxi: 3.0.37 
```

I am using `steam-manjaro-1.0.0.61-7` engine with `Proton 5.0-5` enabled and the error I am getting when trying to launch SpaceEngine is well described by @Spacesteve451 [here](https://github.com/ValveSoftware/Proton/issues/2842#issuecomment-520856056)

Please let me know If you need any further information, thank you very much for your time

**Comment by Elara6331** [comment]
I fixed 0xb7 on Arch after trying for months by installing the newest amdgpu-pro drivers (version 20.10). I required amdgpu-pro drivers for another program so I could not switch to open source drivers. The ones in the AUR were too old and I couldn't figure out how to update the PKGBUILD (all attempts resulted in broken Xorg), so I ran the [bedrock linux hijack script](https://bedrocklinux.org) and added an Ubuntu Bionic stratum (the newest Ubuntu does not support the driver). After installing [amdgpu-pro from AMD's website](https://www.amd.com/en/support) into ubuntu, even though the DKMS module failed to build for Arch's kernel, after a reboot arch picked the driver up (even without xf86-video-amdgpu package), although interestingly enough, it gave no signs of doing so, and it works without issue now. No errors, and graphics look great. Some system info: Arch Linux, Kernel 5.6.10, Proton 5.0-6, AMD Radeon RX 5700 XT, and AMD 3800X.

![scr00001](https://user-images.githubusercontent.com/41810442/81377398-3e31f680-90ba-11ea-833c-920bcb1e700d.jpg)

**Comment by kisak-valve** [comment]
SpaceEngine (314650) crashes with Mesa 20.3.x and an AMD GPU

Issue transferred from https://github.com/ValveSoftware/Proton/issues/4507.
@Anonymous1157 posted on 2020-12-28T09:25:58:

# Compatibility Report
- Name of the game with compatibility issues: SpaceEngine
- Steam AppID of the game: 314650

## System Information
- GPU: Strix RX 580 4GB
- Driver/LLVM version: Mesa 20.3.1, LLVM 11.0.0
- Kernel version: 5.10.1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Anonymous1157/9e409e8ec41df03ef25596476e1228b3
- Proton version: 5.13-4

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.



[steam-314650.log](https://github.com/ValveSoftware/Proton/files/5746542/steam-314650.log)

## Symptoms 

SpaceEngine crashes from the splash screen very early in the loading process if the system has an AMD GPU and Mesa is version 20.3.1. Downgrading to Mesa 20.2.6 allows the game to run normally.

This is also happening to an Arch Linux user with newer hardware, and they were able to reproduce the downgrade workaround: https://steamcommunity.com/app/314650/discussions/1/5242718027649464482/

## Reproduction

1. Switch the system Mesa version to 20.2.x
2. Start Steam, launch SpaceEngine, watch it run normally
3. Switch to Mesa 20.3.x
4. Restart Steam, launch SpaceEngine, watch it crash

**Comment by MagicD3VIL** [comment]
Greetings, I've read through issue #4507 and I think my problem might be related. I have mesa 21.0.0-devel, but the game crashes even before the splash screen appears. Feel free to check out the info below:

System info: https://gist.github.com/MagicD3VIL/1e7ea72efbc5c1f6dd0daf34d5349893
Log: https://gist.github.com/MagicD3VIL/df63bd0d216c4d40a309dc9f01812262

**Comment by Anonymous1157** [comment]
This is still not working with Proton Experimental and Mesa 21 RC3. I don't know how long Gentoo will hold on to 20.2.6.

**Comment by HadetTheUndying** [comment]
Rolling back Mesa also didn't appear to solve the problem for me. Not sure what's going on here. Rolled all the way back to 20.1 still doesn't launch.

**Comment by Anonymous1157** [comment]
It was dramatically more productive to open a bug on Mesa's tracker and talk to them directly. I have a workaround for the crash on Mesa 20.3.x or newer:

Change SE's launch options to `force_gl_vendor=X.Org %command%` then delete the shader cache if you get "Error loading texture generator shaders".

**Comment by krompus** [comment]
@Anonymous1157 Thank you very much!

**Comment by p4block** [comment]
I couldn't get it to work even with the workaround, managed to get it to launch editing the game's `main-user.cfg` and setting `	CoreContext             false`

I recall not being able to run the game in the past in the "high" graphics setting, unrelated to mesa versions (years in the past) but with this, I can.

**Comment by MayeulC** [comment]
<details><summary>

@p4block just doing this change in `steamapps/common/SpaceEngine/config/main-user.cfg` gives me the following crash:

</summary><p>

```
wine: Unhandled page fault on execute access to 0000000000000000 at address 0000000000000000 (thread 0118), starting debugger...
ERROR: ld.so: object '/home/mayeul/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 2795 for game ID 314650
Unhandled exception: page fault on execute access to 0x00000000 in 64-bit code (0x0000000000000000).
Register dump:
 rip:0000000000000000 rsp:000000000022f798 rbp:0000000000000001 eflags:00210246 (  R- --  I  Z- -P- )
 rax:0000000000000001 rbx:0000000140d0efd8 rcx:0000000000000000 rdx:0000000000000000
 rsi:0000000000000000 rdi:0000000000000001  r8:0000000000000000  r9:ffffffffffffffff r10:00000000000000
00
 r11:0000000000200246 r12:00000001407781d0 r13:0000000140000000 r14:000000014066b040 r15:00000000000000
00
Stack dump:
0x000000000022f798:  00000001402dd7a5 0000000000000000
0x000000000022f7a8:  0000000140163a8b 0000000000ecff50
0x000000000022f7b8:  0000000140163b96 0000000000ecff50
0x000000000022f7c8:  000000000022f800 0000000000000000
0x000000000022f7d8:  0000000000000000 0000000000000000
0x000000000022f7e8:  00000001401522da 000000000000000b
0x000000000022f7f8:  0000000000000000 000000000000000b
0x000000000022f808:  000000010000000b 000000000000001d
0x000000000022f818:  0000000140152346 0000000000ecff50
0x000000000022f828:  000000000022f860 0000000000ecff50
0x000000000022f838:  0000000000000000 000000000000001d
0x000000000022f848:  000000014026ab80 0000000000ecff50
Backtrace:
=>0 0x0000000000000000 (0x0000000000000001)
0x0000000000000000: -- no code accessible --
Modules:
Module  Address                                 Debug info      Name (65 modules)
PE                230000-          35f000       Deferred        sdl2
PE                360000-          417000       Deferred        winmm
PE                420000-          437000       Deferred        vcruntime140
PE                440000-          448000       Deferred        api-ms-win-crt-heap-l1-1-0
PE                450000-          458000       Deferred        api-ms-win-crt-utility-l1-1-0
PE                460000-          46e000       Deferred        libvorbisfile
PE                470000-          52e000       Deferred        libvorbis
PE                530000-          5c7000       Deferred        openvr_api
PE                5d0000-          604000       Deferred        libpng16
PE                610000-          62b000       Deferred        zlib
PE                630000-          6b3000       Deferred        tiff
PE               1220000-         13fa000       Deferred        gameoverlayrenderer64
PE               3fc0000-         4443000       Deferred        wrap_oal
PE              10000000-        10021000       Deferred        openal32
PE              61540000-        6157f000       Deferred        advapi32
PE              61d00000-        61d09000       Deferred        api-ms-win-crt-convert-l1-1-0
PE              61d80000-        61d8a000       Deferred        api-ms-win-crt-math-l1-1-0
PE              62980000-        62988000       Deferred        api-ms-win-core-localization-l1-2-1
PE              62dc0000-        62e42000       Deferred        rpcrt4
PE              63280000-        6328d000       Deferred        version
PE              63540000-        63549000       Deferred        api-ms-win-crt-runtime-l1-1-0
PE              639c0000-        639d9000       Deferred        shcore
PE              64840000-        64891000       Deferred        shlwapi
PE              64cc0000-        64df2000       Deferred        oleaut32
PE              65b40000-        65b48000       Deferred        api-ms-win-crt-filesystem-l1-1-0
PE              664c0000-        664cf000       Deferred        hid
PE              67600000-        67607000       Deferred        api-ms-win-core-string-l1-1-0
PE              67b40000-        67b6a000       Deferred        mmdevapi
PE              680c0000-        68119000       Deferred        dsound
PE              68300000-        68352000       Deferred        combase
PE              68500000-        6852d000       Deferred        uxtheme
PE              69e40000-        69e60000       Deferred        msacm32
PE              6a080000-        6a10d000       Deferred        msvcrt
PE              6a200000-        6a314000       Deferred        ole32
PE              6a680000-        6a690000       Deferred        xinput1_4
PE              6aa80000-        6aa87000       Deferred        api-ms-win-core-fibers-l1-1-1
PE              6b300000-        6b307000       Deferred        api-ms-win-core-localization-obsolete-l
1-2-0
PE              6b5c0000-        6b5c9000       Deferred        api-ms-win-crt-stdio-l1-1-0
PE              6ba00000-        6ba28000       Deferred        sechost
PE              6bac0000-        6bb34000       Deferred        setupapi
PE              6c7c0000-        6c943000       Deferred        gdi32
PE              6ca40000-        6cb84000       Deferred        comctl32
PE              6cd40000-        6cd47000       Deferred        api-ms-win-crt-time-l1-1-0
PE              6dc80000-        6dc88000       Deferred        api-ms-win-core-synch-l1-2-0
PE              6eb00000-        6ed27000       Deferred        user32
PE              6fd00000-        6fd09000       Deferred        api-ms-win-crt-string-l1-1-0
PE              6fd80000-        6fd87000       Deferred        api-ms-win-core-datetime-l1-1-1
PE              6fec0000-        6fec8000       Deferred        api-ms-win-core-sysinfo-l1-2-1
PE              70940000-        709f8000       Deferred        ucrtbase
PE              70b00000-        70bff000       Deferred        comdlg32
PE              71000000-        7101a000       Deferred        imm32
PE              7a850000-        7a854000       Deferred        opengl32
PE              7b000000-        7b0d3000       Deferred        kernelbase
PE              7b600000-        7b812000       Deferred        kernel32
PE              7bc00000-        7bc99000       Deferred        ntdll
PE             138000000-       13944b000       Deferred        steamclient64
PE             13b400000-       13b44b000       Deferred        steam_api64
PE             140000000-       14196d000       Deferred        spaceengine
PE             180000000-       180021000       Deferred        zlibwapi
PE          7f0f142a0000-    7f0f142a3000       Deferred        winepulse
PE          7f0f144f0000-    7f0f144fb000       Deferred        dinput8
PE          7f0f5c0e0000-    7f0f5c0e4000       Deferred        xaudio2_7
PE          7f0f65a10000-    7f0f65a14000       Deferred        winex11
PE          7f0f66640000-    7f0f6664b000       Deferred        winspool
PE          7f0f667a0000-    7f0f67077000       Deferred        shell32
Threads:
process  tid      prio (all id:s are in hex)
00000020 steam.exe
        00000024    0
        000000c0    0
00000030 services.exe
        00000034    0
        00000038    0
        00000044    0
        00000048    0
        00000054    0
        00000064    0
        0000007c    0
        00000088    0
        000000ac    0
        000000ec    0
        000000f0    0
0000003c winedevice.exe
        00000040    0
        0000004c    0
        00000050    0
        00000058    0
0000005c plugplay.exe
        00000060    0
        00000068    0
        0000006c    0
        00000070    0
        00000090    0
        00000094    0
        0000012c    0
00000074 winedevice.exe
        00000078    0
        00000080    0
        00000084    0
        0000008c    0
        00000098    0
        0000009c    0
        000000a0    0
000000a4 svchost.exe
        000000a8    0
        000000b0    0
        000000b4    0
000000b8 conhost.exe
        000000bc    0
000000c4 explorer.exe
        000000c8    0
        000000d0    0
        000000dc    0
000000e4 rpcss.exe
        000000e8    0
        000000f4    0
        000000f8    0
        000000fc    0
        00000100    0
        00000104    0
        00000108    0
00000114 (D) Z:\data\SteamLibrary\steamapps\common\SpaceEngine\system\SpaceEngine.exe
        00000118    0 <==
        0000011c    0
        00000120    0
        00000124    0
        00000128    0
        00000130    0
        00000134    0
        00000138   15
        0000014c    0
        00000150   15
System information:
    Wine build: wine-6.3
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 5.12.3-zen1-1-zen
```

</p></details>

However, @Anonymous1157's fix made the game work for me (Proton GE flatpak build 1620223514):
> `force_gl_vendor=X.Org %command%`

**Comment by HadetTheUndying** [comment]
Game is not properly detecting SteamVR in any version of Proton.

**Comment by markonius** [comment]
> I recall not being able to run the game in the past in the "high" graphics setting, unrelated to mesa versions (years in the past) but with this, I can.

Confirming this fixed the 0xb7 error on Radeon RX 580 wih Mesa 21.1.4

**Comment by Adriankhl** [comment]
Perhaps because I am using wayland (sway), the `force_gl_vendor=X.Org %command%` does not work for me, setting CoreContext false in `main-user.cfg` works for me.

**Comment by kisak-valve** [comment]
Space Engine (314650)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/9038.
@AlexeySFdot posted on 2025-09-08T18:57:40:

# Compatibility Report
- Name of the game with compatibility issues: Space Engine
- Steam AppID of the game:314650

## System Information
- GPU: RTX 4060 Ti
- Video driver version: 580.82.07
- Kernel version: Linux 6.16.5-1
- Proton version: latest experimental

[steam-314650.log](https://github.com/user-attachments/files/22217433/steam-314650.log)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.


## Symptoms 
Run space engine on latest proton exp games hungs on startup


## Reproduction
Select latest proton
Select proton 8.0-5 game works

**Comment by kisak-valve** [comment]
Hello @AlexeySFdot, can you also check how the game behaves with Proton 9 and Proton 10? there's a couple years worth of changes between Proton 8.0 and the current Proton Experimental.

`warn:seh:handle_syscall_fault backtrace: --- Exception 0xc0000005 at 0x7ffa87fc9028: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libnvidia-glcore.so.580.82.07 + 0xadf028.` in your Proton log hints towards a video driver issue.

**Comment by AlexeySFdot** [comment]
> Hello [@AlexeySFdot](https://github.com/AlexeySFdot), can you also check how the game behaves with Proton 9 and Proton 10? there's a couple years worth of changes between Proton 8.0 and the current Proton Experimental.
> 
> `warn:seh:handle_syscall_fault backtrace: --- Exception 0xc0000005 at 0x7ffa87fc9028: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libnvidia-glcore.so.580.82.07 + 0xadf028.` in your Proton log hints towards a video driver issue.

Hello i tested on latest proton 9 and this works fine too
Logs

[steam-314650.log](https://github.com/user-attachments/files/22218098/steam-314650.log)

UPD latest proton beta works too, exp not

**Comment by kisak-valve** [comment]
SpaceEngine (314650)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/9426.
@bczhc posted on 2026-01-23T18:24:55:

# Compatibility Report
- Name of the game with compatibility issues: SpaceEngine
- Steam AppID of the game: 314650

## System Information
- GPU: NVIDIA GeForce RTX 3060 Mobile
- Video driver version: nvidia 590.48.01
- Kernel version: 6.18.2
- Link to full system information report as [Gist](https://gist.github.com/bczhc/9d6ee2ae5e2db635420440f1d2d15291):
- Proton version: 10 & hotfix & experimental
- DE: Hyprland

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[log.gz](https://github.com/user-attachments/files/24826276/log.gz)

## Symptoms

At the game starting, the whole desktop and graphics freezes and a kernel panic triggers. Mouse and keyboard get no response. Switching to tty via Ctrl+alt+FN also won't work. This happens mostly at a specific game loading progress shown in img1; but exceptions can also happen.

## Reproduction

Start the game and then when it's loading move the mouse around or switch between workspaces or do something.

## Additional info

This bug is not 100% reproducible. From my tests and experience, when it's loading, moving mouse around and letting the window focus keep changing, or switching between workspaces etc, will make it more likely reproducible. Most of the time when it freezes, the game loading window is out of focus. When you click Steam "Start game" and keep the mouse at the screen center, making the game loading window always be focused, this bug won't reproduce and may be able to launch successfully.

When kernel panic occurs in this case, REISUB may work, or may not work. All is random. For the game SpaceEngine there are so many quirks with Xwayland. No issue on X11 from my previous X11 experience. This kernel panic bug is only one of these quirks - crashing on loading page, crashing after loaded, crashing when fullscreen, and being stuck at the loading page - all can happen, and randomly. From my experience these quirks all won't happen with X11. This issue only lists the kernel panic phenomena.

---

<details><summary>Kernel panic dmesg:</summary>

```log
[ 1451.733186] NVRM: nvAssertFailedNoLog: Assertion failed: NULL != pNode @ list.c:304
[ 1451.733196] BUG: kernel NULL pointer dereference, address: 0000000000000110
[ 1451.733216] #PF: supervisor read access in kernel mode
[ 1451.733220] #PF: error_code(0x0000) - not-present page
[ 1451.733221] PGD 5c2a3d067 P4D 5c2a3d067 PUD 5f02c1067 PMD 5d8145067 PTE 0
[ 1451.733224] Oops: Oops: 0000 [#1] SMP NOPTI
[ 1451.733227] CPU: 3 UID: 1000 PID: 35233 Comm: SpaceEngine.exe Tainted: G           OE       6.18.2-bczhc-dirty #96 PREEMPT(full)  43181e04771a83f506b955b9fa6abbc526dd07b7
[ 1451.733230] Tainted: [O]=OOT_MODULE, [E]=UNSIGNED_MODULE
[ 1451.733230] Hardware name: THUNDEROBOT ZERO/NLZA, BIOS TP118 05/18/2021
[ 1451.733231] RIP: 0010:rmclientPostProcessPendingFreeList_IMPL+0x6a/0x130 [nvidia]
[ 1451.733414] Code: 49 89 c4 66 90 66 66 2e 0f 1f 84 00 00 00 00 00 4c 39 e3 74 3b 4c 89 e6 49 8d bf c0 00 00 00 4d 89 e6 e8 b9 0c 06 00 49 89 c4 <49> 8b 86 10 01 00 00 83 78 20 01 75 d9 b9 01 00 00 00 4c 89 f2 4c
[ 1451.733416] RSP: 0018:ffffd30c8ce47728 EFLAGS: 00010246
[ 1451.733417] RAX: 0000000000000000 RBX: ffff89f4d6a05430 RCX: 0000000000000020
[ 1451.733418] RDX: 00000000b76000a1 RSI: 000000000000001f RDI: 0000000000000001
[ 1451.733419] RBP: ffffd30c8ce47768 R08: 0000000000000000 R09: 0000000000000000
[ 1451.733420] R10: 0000000000000000 R11: ffff89f0dbf08008 R12: 0000000000000000
[ 1451.733421] R13: ffffffffc085d620 R14: 0000000000000000 R15: ffff89f4f4ce0c10
[ 1451.733421] FS:  0000000100cff6c0(0000) GS:ffff8a0056fcf000(0000) knlGS:000000007ff00000
[ 1451.733423] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1451.733424] CR2: 0000000000000110 CR3: 0000000601b8d005 CR4: 0000000000f72ef0
[ 1451.733425] PKRU: 55555554
[ 1451.733426] Call Trace:
[ 1451.733427]  <TASK>
[ 1451.733430]  serverFreeResourceTree+0x2de/0x980 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.733531]  ? portSyncSpinlockAcquire+0x18/0x30 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.733640]  ? os_alloc_mem+0x104/0x120 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.733758]  ? _raw_spin_lock_irqsave+0x3d/0x50
[ 1451.733775]  ? os_acquire_spinlock+0x12/0x30 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.733951]  ? _raw_spin_lock_irqsave+0x3d/0x50
[ 1451.733956]  ? os_acquire_spinlock+0x12/0x30 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.734086]  ? portSyncSpinlockAcquire+0x18/0x30 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.734231]  ? _tlsThreadEntryGet+0x82/0x90 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.734339]  ? tlsEntryGet+0x1f/0x60 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.734478]  ? rmapiInitLockInfo+0x26/0x200 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.734611]  ? os_acquire_rwlock_write+0x2b/0x40 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.734699]  rmapiFreeWithSecInfo+0x124/0x2a0 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.734840]  rmapiFreeWithSecInfoTls+0x57/0x80 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.734972]  Nv01FreeWithSecInfo+0x4e/0x60 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.735106]  ? security_capable+0x5d/0x1a0
[ 1451.735110]  RmIoctl+0x41b/0xdc0 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.735284]  ? os_get_monotonic_time_ns+0x3a/0xa0 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.735364]  ? os_acquire_spinlock+0x12/0x30 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.735444]  ? portSyncSpinlockAcquire+0x18/0x30 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.735545]  rm_ioctl+0x78/0x5f0 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.735720]  ? __check_object_size+0x1d2/0x1f0
[ 1451.735723]  nvidia_unlocked_ioctl+0x439/0x950 [nvidia f33650217f15c417ea5cb78304ff68bb373bd0ce]
[ 1451.735798]  __x64_sys_ioctl+0x97/0xe0
[ 1451.735802]  do_syscall_64+0x81/0x7f0
[ 1451.735805]  ? __sys_recvmsg+0xca/0xe0
[ 1451.735809]  ? do_syscall_64+0x81/0x7f0
[ 1451.735811]  ? __x64_sys_ioctl+0xb1/0xe0
[ 1451.735813]  ? clear_bhb_loop+0x50/0xa0
[ 1451.735815]  ? clear_bhb_loop+0x50/0xa0
[ 1451.735817]  ? clear_bhb_loop+0x50/0xa0
[ 1451.735818]  entry_SYSCALL_64_after_hwframe+0x76/0x7e
[ 1451.735821] RIP: 0033:0x7fa4ff91674d
[ 1451.735856] Code: 04 25 28 00 00 00 48 89 45 c8 31 c0 48 8d 45 10 c7 45 b0 10 00 00 00 48 89 45 b8 48 8d 45 d0 48 89 45 c0 b8 10 00 00 00 0f 05 <89> c2 3d 00 f0 ff ff 77 1a 48 8b 45 c8 64 48 2b 04 25 28 00 00 00
[ 1451.735857] RSP: 002b:0000000100cfd370 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
[ 1451.735859] RAX: ffffffffffffffda RBX: 0000000100cfd420 RCX: 00007fa4ff91674d
[ 1451.735860] RDX: 0000000100cfd420 RSI: 00000000c0104629 RDI: 0000000000000027
[ 1451.735861] RBP: 0000000100cfd3c0 R08: 0000000100cfd420 R09: 0000000100cfd42c
[ 1451.735862] R10: 00007fa4f4082f60 R11: 0000000000000246 R12: 0000000000000027
[ 1451.735863] R13: 0000000100cfd42c R14: 000000006973b67e R15: 0000000100cfd3d0
[ 1451.735865]  </TASK>
[ 1451.735865] Modules linked in: tun rfcomm snd_seq_dummy snd_hrtimer snd_seq snd_usb_audio snd_usbmidi_lib snd_ump snd_rawmidi snd_seq_device uhid xt_conntrack xt_MASQUERADE bridge stp llc xfrm_user xfrm_algo ip6table_nat ip6table_filter ip6_tables xt_set ip_set iptable_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 xt_addrtype iptable_filter ip_tables x_tables nf_tables overlay ccm algif_aead des3_ede_x86_64 snd_ctl_led des_generic libdes algif_skcipher cmac md4 algif_hash uinput af_alg bnep uvcvideo videobuf2_vmalloc btusb uvc btmtk videobuf2_memops btrtl videobuf2_v4l2 btbcm videobuf2_common btintel videodev bluetooth mc exfat vfat fat snd_sof_pci_intel_tgl snd_sof_pci_intel_cnl snd_sof_intel_hda_generic soundwire_intel snd_sof_intel_hda_sdw_bpt snd_sof_intel_hda_common snd_soc_hdac_hda snd_sof_intel_hda_mlink snd_sof_intel_hda intel_uncore_frequency soundwire_cadence snd_hda_codec_intelhdmi intel_uncore_frequency_common snd_sof_pci snd_sof_xtensa_dsp snd_sof snd_sof_utils snd_soc_acpi_intel_match
[ 1451.735904]  snd_soc_acpi_intel_sdca_quirks soundwire_generic_allocation snd_soc_acpi x86_pkg_temp_thermal snd_hda_codec_alc269 soundwire_bus intel_powerclamp snd_hda_scodec_component iwlmvm snd_soc_sdca coretemp snd_hda_codec_realtek_lib crc8 snd_hda_codec_nvhdmi snd_hda_codec_generic snd_soc_avs snd_hda_codec_hdmi mac80211 kvm_intel snd_soc_hda_codec snd_hda_intel snd_hda_ext_core ptp processor_thermal_device_pci_legacy snd_hda_codec pps_core processor_thermal_device libarc4 snd_hda_core kvm joydev processor_thermal_wt_hint mousedev platform_temperature_control snd_soc_core processor_thermal_soc_slider intel_rapl_msr snd_intel_dspcfg iTCO_wdt irqbypass platform_profile iwlwifi ee1004 intel_pmc_bxt snd_compress snd_intel_sdw_acpi processor_thermal_rfim polyval_clmulni ac97_bus iTCO_vendor_support processor_thermal_rapl snd_hwdep ghash_clmulni_intel snd_pcm_dmaengine intel_rapl_common mei_pxp aesni_intel snd_pcm i2c_i801 rapl mei_hdcp processor_thermal_wt_req cfg80211 intel_cstate spi_nor snd_timer
[ 1451.735949]  processor_thermal_power_floor i2c_smbus mei_me hid_multitouch intel_uncore mtd pcspkr psmouse i2c_mux wmi_bmof thunderbolt snd processor_thermal_mbox mei rfkill i2c_hid_acpi intel_soc_dts_iosf soundcore int3403_thermal intel_oc_wdt i2c_hid int340x_thermal_zone intel_pmc_core int3400_thermal pmt_telemetry pmt_discovery acpi_thermal_rel pinctrl_tigerlake pmt_class intel_pmc_ssram_telemetry acpi_pad acpi_tad mac_hid usbip_host usbip_core ntsync dm_mod pkcs8_key_parser sg crypto_user nfnetlink zram 842_decompress 842_compress lz4hc_compress lz4_compress xe intel_vsec drm_suballoc_helper gpu_sched drm_gpuvm drm_exec drm_gpusvm_helper i915 i2c_algo_bit nvme drm_buddy nvme_core intel_gtt serio_raw nvme_keyring drm_display_helper intel_lpss_pci nvme_auth spi_intel_pci intel_lpss hkdf cec spi_intel idma64 nvidia_drm(OE) drm_ttm_helper ttm nvidia_uvm(OE) nvidia_modeset(OE) video wmi nvidia(OE)
[ 1451.735984] CR2: 0000000000000110
[ 1451.735986] ---[ end trace 0000000000000000 ]---
[ 1451.735987] RIP: 0010:rmclientPostProcessPendingFreeList_IMPL+0x6a/0x130 [nvidia]
[ 1451.736114] Code: 49 89 c4 66 90 66 66 2e 0f 1f 84 00 00 00 00 00 4c 39 e3 74 3b 4c 89 e6 49 8d bf c0 00 00 00 4d 89 e6 e8 b9 0c 06 00 49 89 c4 <49> 8b 86 10 01 00 00 83 78 20 01 75 d9 b9 01 00 00 00 4c 89 f2 4c
[ 1451.736115] RSP: 0018:ffffd30c8ce47728 EFLAGS: 00010246
[ 1451.736117] RAX: 0000000000000000 RBX: ffff89f4d6a05430 RCX: 0000000000000020
[ 1451.736117] RDX: 00000000b76000a1 RSI: 000000000000001f RDI: 0000000000000001
[ 1451.736118] RBP: ffffd30c8ce47768 R08: 0000000000000000 R09: 0000000000000000
[ 1451.736119] R10: 0000000000000000 R11: ffff89f0dbf08008 R12: 0000000000000000
[ 1451.736120] R13: ffffffffc085d620 R14: 0000000000000000 R15: ffff89f4f4ce0c10
[ 1451.736121] FS:  0000000100cff6c0(0000) GS:ffff8a0056fcf000(0000) knlGS:000000007ff00000
[ 1451.736122] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1451.736123] CR2: 0000000000000110 CR3: 0000000601b8d005 CR4: 0000000000f72ef0
[ 1451.736124] PKRU: 55555554
[ 1451.736125] note: SpaceEngine.exe[35233] exited with irqs disabled
[ 1451.746360] NVRM: Xid (PCI:0000:01:00): 31, pid=35097, name=SpaceEngine.exe, channel 0x00000038, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC1 GPCCLIENT_PROP_0 faulted @ 0x0_00000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
[ 1451.785035] NVRM: Xid (PCI:0000:01:00): 31, pid=35097, name=SpaceEngine.exe, channel 0x0000005c, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC2 GPCCLIENT_PROP_0 faulted @ 0x0_00000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
[ 1454.883346] sysrq: Keyboard mode set to system default
[ 1455.114783] sysrq: Terminate All Tasks
```

</details>

[full dmesg.log](https://github.com/user-attachments/files/24826589/dmesg.log)

---

img1:

<img width="300" alt="Image" src="https://github.com/user-attachments/assets/d81e6d49-d3fc-458e-ace6-c9d0614f5353" />

**Comment by bczhc** [comment]
> SpaceEngine (314650)
> 
> Issue transferred from [#9426](https://github.com/ValveSoftware/Proton/issues/9426).
> [@bczhc](https://github.com/bczhc) posted on 2026-01-23T18:24:55:

Worth a mention: I can no long replicate the issue now.

Any of my environment change can be the fix of the issue (driver update, kernel update, game update, compositor switching, etc..), anyway.

- GPU: NVIDIA GeForce RTX 3060 Mobile
- Video driver version: nvidia 595.71.05
- Kernel version: 7.0.0
- Proton version: 10 & experimental & Proton-EM-10.0-37
- Compositor: niri (x11 via xwayland-satellite)

**Comment by yshui** [comment]
SpaceEngine is not able to start for me. The splash shows then the game immediately exits.

Looks like it jumped to NULL:

```
7875.974:0164:0168:warn:seh:dispatch_exception backtrace: --- Exception 0xc0000005.
7875.974:0164:0168:trace:seh:dispatch_exception code=c0000005 (EXCEPTION_ACCESS_VIOLATION) flags=0 addr=0000000000000000
7875.974:0164:0168:trace:seh:dispatch_exception  info[0]=0000000000000008
7875.974:0164:0168:trace:seh:dispatch_exception  info[1]=0000000000000000
7875.974:0164:0168:trace:seh:dispatch_exception rip=0000000000000000 rsp=000000000010fbb8 rbp=0000000000000003 eflags=00010246
7875.974:0164:0168:trace:seh:dispatch_exception rax=0000000000000000 rbx=ffffffffffffffff rcx=0000000000000000 rdx=0000000000000000
7875.974:0164:0168:trace:seh:dispatch_exception rsi=0000000000000000 rdi=000000000000001e  r8=00000000ffffffff  r9=0000000000000000
7875.974:0164:0168:trace:seh:dispatch_exception r10=0000762dba9567a0 r11=0000000000000000 r12=0000000000000001 r13=0000000140d93868
7875.974:0164:0168:trace:seh:dispatch_exception r14=0000000000000004 r15=ffffffffffffffff mxcsr=00001fa8 cs=0033 ss=002b
7875.974:0148:014c:trace:seh:EnumProcessModulesEx (000000000000020C, 000000000010C7D0, 8, 000000000010C7CC, 0)
7875.974:0164:0168:warn:seh:virtual_unwind backtrace: 0000000000000000: unknown module.
7875.974:0164:0168:trace:unwind:RtlVirtualUnwind2 type 1 base 0 rip 0 rva 0 rsp 10fbb8
7875.974:0164:0168:warn:seh:virtual_unwind backtrace: 000000014030A446: L"SpaceEngine.exe" + 000000000030A446.
7875.974:0164:0168:trace:unwind:RtlVirtualUnwind2 type 1 base 140000000 rip 14030a446 rva 30a446 rsp 10fbc0
7875.974:0164:0168:trace:unwind:dump_unwind_info **** func 30a390-30a7ce
7875.974:0164:0168:trace:unwind:dump_unwind_info unwind info at 00000001407211E4 flags 3 prolog 0x29 bytes function 000000014030A390-000000014030A7CE
7875.974:0164:0168:trace:unwind:dump_unwind_info     0x1a: movq %rdi,0x78(%rsp)
7875.974:0164:0168:trace:unwind:dump_unwind_info     0x1a: movq %rsi,0x70(%rsp)
7875.974:0164:0168:trace:unwind:dump_unwind_info     0x1a: movq %rbp,0x68(%rsp)
7875.974:0164:0168:trace:unwind:dump_unwind_info     0x1a: movq %rbx,0x60(%rsp)
7875.974:0164:0168:trace:unwind:dump_unwind_info     0x1a: subq $0x50,%rsp
7875.974:0164:0168:trace:unwind:dump_unwind_info     0x16: pushq %r14
7875.974:0164:0168:trace:unwind:dump_unwind_info     handler 00000001400CADC4 data at 0000000140721200
7875.974:0164:0168:trace:seh:call_seh_handlers calling handler 00000001400CADC4 (rec=000000000010F330, frame=10fbc0 context=000000000010EE40, dispatch=000000000010E5D0)
```
