### ISSUE TITLE
Serious Sam: The Random Encounter (201480)

### ISSUE THREAD

**Issue by kwahoo2** [ValveSoftware/Proton#2996]
# Compatibility Report
- Name of the game with compatibility issues: Serious Sam: The Random Encounter
- Steam AppID of the game: 201480

## System Information
- GPU: RX 580
- Driver/LLVM version: Mesa 19.2.0-devel/LLVM 8.0.0
- Kernel version: 5.2.8
- Link to full system information report as [Gist](https://gist.github.com/kwahoo2/5b2df08a0e3ae3fd8c799f71cea98894)
- Proton version: 4.11-2

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.
https://gist.github.com/kwahoo2/a6d40a77b12927c5ec09449a7ac0d5ef

## Symptoms 

Lack of sound. Log shows a lot of:
4104.247:0027:0028:fixme:dmime:IDirectMusicSegment8Impl_Download (06483950, 06455268): stub
4104.247:0027:0028:fixme:dmime:IDirectMusicAudioPathImpl_SetVolume (06483598, 0, 0): stub
4104.247:0027:0028:fixme:dmime:IDirectMusicAudioPathImpl_GetObjectInPath (06483598, -5, 24576, 0,

**Comment by alesliehughes** [comment]
Existing wine bug
https://bugs.winehq.org/show_bug.cgi?id=32896

**Comment by kisak-valve** [comment]
Serious Sam: The Random Encounter (201480)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/3675.
@shoober420 posted on 2020-03-21T22:35:17:

# Compatibility Report
- Name of the game with compatibility issues: Serious Sam: The Random Encounter
- Steam AppID of the game: https://steamdb.info/app/201480/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.64
- Kernel version: 5.5.10
- https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341
- Proton version: 5.0-5

LOG:
[steam-201480.log](https://github.com/ValveSoftware/Proton/files/4364380/steam-201480.log)

## Symptoms
Game plays, but there is no sound

**Comment by waspennator** [comment]
Trying it on my oled deck with Proton Experimental, the sound does seem to work on my end now, but I'm noticing another audio problem. I don't think it's how it is on windows, but the background music doesn't seem to transition properly, just overlapping one after another on top of itself into a mess of noise until it ends.

[steam-201480.log](https://github.com/ValveSoftware/Proton/files/14661529/steam-201480.log)

Update: I think this is why none of the audio tracks actually end, they just overlap ontop of each other.

fixme:dmime:wave_track_Play segment_state 09E11BA8 not implemented

fixme:dmime:performance_IsPlaying (01FB5CD0, 0B750698, 00000000): stub

fixme:dmime:wave_track_EndPlay (0A26F208, CFAAE71A): stub

**Comment by kwahoo2** [comment]
I can confirm @waspennator observations. This does not happen on Windows.
[steam-hardware.log](https://github.com/ValveSoftware/Proton/files/14811967/steam-hardware.log)
[steam-runtime.log](https://github.com/ValveSoftware/Proton/files/14811968/steam-runtime.log)

**Comment by shoober420** [comment]
Here is a updated System Information gist.

https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia

**Comment by kwahoo2** [comment]
This seems to be really the game issue, not Proton implementation issue. Even if music is disabled in `Serious Sam The Random Encounter/config.txt` (the biggest config file ever: first number is fullscreen on/off, second music on/off) the menu music returns after exiting mission.

But, the issue is fixed in this Proton-GE release (not sure about earlier releases) https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton9-21

**Comment by simifor** [comment]
@kwahoo2 ~~Have you tried to use proton experimental? I saw that proton stable had issues with muting the audio but it works just fine on experimental, also finished 1-1 and it didn't turn itself on.~~
I had failed to wipe the prefix when testing experimental. The issue is still there with a clean prefix.

**Comment by waspennator** [comment]
Music still seems to overlap ontop of each other with proton Experimental

**Comment by kwahoo2** [comment]
@simifor ~~Thanks, it is fixed for me with Experimental. @waspennator please double check if you are using Experimental, not Hotfix (I did that mistake).~~

**Comment by simifor** [comment]
@waspennator did you try on desktop or deck? I now see that deck is still affected even on experimental

**Comment by kwahoo2** [comment]
Ok, it is NOT fixed with experimental. The remaining files in prefix make the difference.
1. Deleted compatdate, installed Experimental - issue exists
2. Replaced Experimental with GE - fixed
3. Replaced GE with Experimental without removing compatdata - still "fixed"

**Comment by waspennator** [comment]
Still a problem with latest Experimental proton
