### ISSUE TITLE
GRID 2019 (703860)

### ISSUE THREAD

**Issue by Bednar87** [ValveSoftware/Proton#3143]
# Compatibility Report
- Name of the game with compatibility issues: **GRID (2019)**
- Steam AppID of the game: **703860**

## System Information
- GPU: 
- Driver/LLVM version: **Mesa 19.2.1/LLVM 9.0.0**
- Kernel version: **latest mainline + AMDGPU staging-next**
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Bednar87/daaf883537c8fe55bb3078f637d46d8e
- Proton version: **4.11-7**

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

The game crashes on start-up:

https://gist.github.com/Bednar87/20e7a36d752b9767b29457eeb1681b17

## Reproduction

Launch the game from the steam library

**Comment by kisak-valve** [comment]
Looks like this game needs vkd3d support.

**Comment by Bednar87** [comment]
yup, looks like codemasters have removed the dx11 executable in a patch... Will try wine staging + vkd3d to see if I can get the game to start. No idea if there's a plan for PROTON to support vkd3d.

**Comment by rafalcieslak** [comment]
Proton 4.11-8 now includes vkd3d. Does it help with this game?

**Comment by Bednar87** [comment]
crashes with a dx12 related 'access violation' see full log
[steam-703860.log](https://github.com/ValveSoftware/Proton/files/3828357/steam-703860.log)

**Comment by 200Puls** [comment]
The crashes are actually fixed and the game loads correctlymon vk3d. 
However this is incredible slow when loading races. It almost feels like a leak getting slower and slower. The benchmark actually doesn't start at all on my system. I managed to play a race which was OK but stuttered. 
Using rx 5500xt 4gb ryzen 3600 16GB ram on gamer-os (arch based with Mesa 19.3, kernel 5.4).  Using 1080p medium settings.
It seems this game would be a good candidate if the slowness can be fixed.

**Comment by mozo78** [comment]
This won't happen any time soon. There is no D12VK yet...

**Comment by Arsconyl** [comment]
> The crashes are actually fixed and the game loads correctlymon vk3d.
> However this is incredible slow when loading races. It almost feels like a leak getting slower and slower. The benchmark actually doesn't start at all on my system. I managed to play a race which was OK but stuttered.
> Using rx 5500xt 4gb ryzen 3600 16GB ram on gamer-os (arch based with Mesa 19.3, kernel 5.4). Using 1080p medium settings.
> It seems this game would be a good candidate if the slowness can be fixed.

Can you elaborate on your config ? I have almost same specs (Ryzen 7 3700, RX 5700 XT) but I get a black screen with proton 5.0-5. Do you use other proton builds ?

**Comment by 200Puls** [comment]
Hey Im using the new Proton next beta. You can select it in the properties
of Proton in the library. Maybe that contained some fixes...

SmileEdge <notifications@github.com> schrieb am Fr., 10. Apr. 2020, 15:10:

**Comment by Arsconyl** [comment]
@200Puls Thanks. Unfortunately, the game doesn't lauch, even with proton next.

**Comment by rafalcieslak** [comment]
For the record, a Linux port might be in the works: https://steamdb.info/app/703860/history/?changeid=8142299

**Comment by guustflater** [comment]
> For the record, a Linux port might be in the works: https://steamdb.info/app/703860/history/?changeid=8142299

I'm afraid not.. after 6 months. The bad thing is.. It was working perfect with a gamecopyworld dx11 exe, but I can't get it to run anymore now S3 is out..

**Comment by morbit85** [comment]
Yes, DX12 version works very slow on min settings or even can't load a race at all. The mentioned earlier dx11 exe stopped working for me after the "Logitech" update.

**Comment by kisak-valve** [comment]
GRID (2019) Crashing When Changing Graphics Presets - 5.13-1

Issue transferred from https://github.com/ValveSoftware/Proton/issues/4280.
@cow-killer posted on 2020-10-16T16:56:43:

# Compatibility Report
- Name of the game with compatibility issues: [GRID (2019)](https://store.steampowered.com/app/703860/GRID/)
- Steam AppID of the game: 703860

## System Information
- GPU: GTX 1660
- Driver/LLVM version: 455.28
- Kernel version: 5.9
- System information report at [Gist](https://gist.github.com/cow-killer/e97b983728e2f391627c04ee40e5c5de)
- Proton version: 5.13-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.


Proton log posted [here](https://gist.github.com/cow-killer/dc81614808d1018751c73a4d83754103)

## Symptoms 
GRID (2019) now works with Proton 5.13-1, including video playback. However, changing the graphics preset and applying the changes causes the game to hang. Resolution can still be changed without hanging. Graphics can also be changed manually in the `hardware_settings_config.xml` located at `~/.steam/root/steamapps/compatdata/703860/pfx/drive_c/users/steamuser/My Documents/My Games/GRID (2019)/hardwaresettings`.

If it helps I managed to get a couple of crash reports from the crash dialog box that appears whenever the preset is changed: https://www.dropbox.com/s/sixpxzgejnfl9e2/a10b7d18-f261-4f9c-ac24-615bb0be0b87.zip?dl=0

**Comment by leillo1975** [comment]
I don't understand what happens. Some weeks ago, I could play this game without problems, and now don't work. I push play button and after loading some seconds, it backs to again to "Play".

Here is a log:
[steam-703860.log](https://github.com/ValveSoftware/Proton/files/5394708/steam-703860.log)

If I back to 5.0-9 I have the same problem:
[steam-703860.log](https://github.com/ValveSoftware/Proton/files/5394712/steam-703860.log)

**Comment by leillo1975** [comment]
Finally, I made a integrity verification of the game files, and now the game starts, but when you try to load a race, the game gets stucked on the loading screen (yo see the animation of loading but nothing happens). Here is the log:
[steam-703860.zip](https://github.com/ValveSoftware/Proton/files/5396431/steam-703860.zip)

**Comment by leillo1975** [comment]
Really, the game don't get stucked. It takes a looong time to load. (minutes) I made a benchmark and the results of DX12 (VKD3D) are disappointing compared with the DX11 mode (DXVK). **I can say that the difference was the double of FPS with DXVK**. This is a screenshot of the results of the DX12 mode:
![DX12-VKD3D-test](https://user-images.githubusercontent.com/551821/96352975-3b571b00-10c8-11eb-8cd3-33c385077ed1.png)

**I noticed that it says I have 18GB of RAM when I'm only 16**. Seems that this problem is usual, as I see in this Boiling Steam article:
https://boilingsteam.com/grid-2019-works-on-proton-5-13/

I can't share the results with the DX11 executable bacouse it actually don't work

**Comment by gudvinr** [comment]
Does not work with RADV. Hangs at seizure warning screen and that's it.

[System information](https://gist.github.com/gudvinr/cb7e4a448c27ca6723e7a210589cdb9a)

**Comment by kisak-valve** [comment]
Hello @gudvinr, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by gudvinr** [comment]
@kisak-valve [Here](https://gist.github.com/gudvinr/cb7e4a448c27ca6723e7a210589cdb9a)

Proton: 5.13

**Comment by leillo1975** [comment]
> GRID (2019) now works with Proton 5.13-1, including video playback. However, changing the graphics preset and applying the changes causes the game to hang. Resolution can still be changed without hanging. Graphics can also be changed manually in the `hardware_settings_config.xml` located at `~/.steam/root/steamapps/compatdata/703860/pfx/drive_c/users/steamuser/My Documents/My Games/GRID (2019)/hardwaresettings`.
> 
> If it helps I managed to get a couple of crash reports from the crash dialog box that appears whenever the preset is changed: https://www.dropbox.com/s/sixpxzgejnfl9e2/a10b7d18-f261-4f9c-ac24-615bb0be0b87.zip?dl=0

I have the same problem. Please devs, take a look

**Comment by MagicD3VIL** [comment]
Launching the game with Proton 5.13-2. Few seconds after the seizure warning screen appears (sometimes with glitching white texture blinking over it) the game makes amdgpu hang thus crashing Xorg.

[System Information](https://gist.github.com/MagicD3VIL/1e7ea72efbc5c1f6dd0daf34d5349893/59055cca57bd7b7f07f5a2e1d6b4ba8c44c2bf8b)

**Comment by NoXPhasma** [comment]
Game worked great with proton 5.13-1 but now with Proton 5.13-2 it hangs and crashes at the legal screen.

Sysinfo: https://gist.github.com/NoXPhasma/520d48e21d83fd10b7dc5340bf4a427c
Proton Log: [steam-703860.log](https://github.com/ValveSoftware/Proton/files/5559229/steam-703860.log)

**Comment by NoXPhasma** [comment]
I was able to bisect the issue to https://github.com/HansKristian-Work/vkd3d-proton/commit/49d3fa30a79d65e69d3f39d3b4cccf06d0e512a8

**Comment by leillo1975** [comment]
> Game worked great with proton 5.13-1 but now with Proton 5.13-2 it hangs and crashes at the legal screen.
> 
> Sysinfo: https://gist.github.com/NoXPhasma/520d48e21d83fd10b7dc5340bf4a427c
> Proton Log: [steam-703860.log](https://github.com/ValveSoftware/Proton/files/5559229/steam-703860.log)

I have exactly the same problem

**Comment by 200Puls** [comment]
> > Game worked great with proton 5.13-1 but now with Proton 5.13-2 it hangs and crashes at the legal screen.
> > Sysinfo: https://gist.github.com/NoXPhasma/520d48e21d83fd10b7dc5340bf4a427c
> > Proton Log: [steam-703860.log](https://github.com/ValveSoftware/Proton/files/5559229/steam-703860.log)
> 
> I have exactly the same problem

Same problem for me...

**Comment by santasemilla** [comment]
> Game worked great with proton 5.13-1 but now with Proton 5.13-2 it hangs and crashes at the legal screen.
> 
> Sysinfo: https://gist.github.com/NoXPhasma/520d48e21d83fd10b7dc5340bf4a427c
> Proton Log: [steam-703860.log](https://github.com/ValveSoftware/Proton/files/5559229/steam-703860.log)

Same here. Appreciate your time and help with this problem!

**Comment by santasemilla** [comment]
> > Game worked great with proton 5.13-1 but now with Proton 5.13-2 it hangs and crashes at the legal screen.
> > Sysinfo: https://gist.github.com/NoXPhasma/520d48e21d83fd10b7dc5340bf4a427c
> > Proton Log: [steam-703860.log](https://github.com/ValveSoftware/Proton/files/5559229/steam-703860.log)
> 
> Same here. Appreciate your time and help with this problem!

Just stopped by to confirm the issue is persistent after Proton updated to 5.13.4. I still get the crash at the beginning, right after health issues warnings. I can't tell if it's related to DX12, but is there a way to run the game on DX11?  ...does anybody ever reads this?? ...hope so. Thanks!

**Comment by NoXPhasma** [comment]
@santasemilla Try to set this as launch parameter for the game: `VKD3D_CONFIG=force_bindless_texel_buffer %command%`

**Comment by morbit85** [comment]
Thanks, @NoXPhasma,  `force_bindless_texel_buffer` helps to get to the main menu but the game still hangs on race loading. For me, it was working the same way on pre-5.13 proton versions. I was only able to run a couple of races on the "low" graphics preset with minimum opponents. So DX12 version was never working well on my PC (Mint 20, RX-580, kisak-mesa ppa).

**Comment by leillo1975** [comment]
> @santasemilla Try to set this as launch parameter for the game: `VKD3D_CONFIG=force_bindless_texel_buffer %command%`

With this parameter the game works, but the performance is much worst than the last time the game runs without problems. I think developers should focus as much on supporting new games as on maintaining and improving existing ones. I also believe that this is not a minority game and I find it a bit sad that since November there has been no solution, or at least no communication.

**Comment by ZereoX** [comment]
Hey @kisak-valve,

The RADV / Mesa Drivers labels can be removed from this ticket. As described in one of the comment above (https://github.com/ValveSoftware/Proton/issues/3143#issuecomment-729570593), the launch failure was caused by a change in VKD3D-Proton from 5.13-1 to 5.13-2. The user has reported the issue on the appropriate tracker: https://github.com/HansKristian-Work/vkd3d-proton/issues/402

Although the issue status is not resolved, changes to `force_bindless_texel_buffer` have been addressed in the latest 2.2 release (https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.2) and should make its way into a future Proton release. For what's it worth, we re-tested the title on Polaris, Vega, and Navi and have been able to launch and get into game (DX12) on the latest Proton version (5.13-6) without any launch options on the latest mesa-git (https://gitlab.freedesktop.org/mesa/mesa/-/commit/8a3dbf1ca6b082251896beceb5e57d6368d95624).

**Comment by leillo1975** [comment]
The game still doesn't work with the latest version of proton (6.3-1). When you hit play, the game shows the dialog to send a crash report. This is the log:
[steam-703860.log](https://github.com/ValveSoftware/Proton/files/6249780/steam-703860.log)

**Comment by leillo1975** [comment]
The same with 6.3-2 and Proton Experimental... money wasted

**Comment by fagnerln** [comment]
It's working here on Proton Experimental, 60fps on high.

AMD Ryzen 5 1600
Radeon RX 580

openSUSE Tumbleweed 20210420
5.11.15-1-default x86_64
Mesa 21.0.2

**Comment by MagicD3VIL** [comment]
I can also confirm that the game is running perfectly fine for me. No startup parameters, Proton 6.3-2.

AMD Ryzen 9 5900X
Radeon RX 580

Mageia 8 x86_64
5.10.30-desktop-1.mga8
Mesa 21.0.2

**Comment by leillo1975** [comment]
You are right, is not a Proton problem. I upgraded my graphics from 450 to 460 (Nvidia GTX1060) and now works great!

It's a pity that this driver version have a bug with [rFactor 2](https://github.com/ValveSoftware/Proton/issues/245#issuecomment-757020531).

https://forums.developer.nvidia.com/t/regression-low-fps-on-rfactor-2-proton-with-460-linux-driver/166910/16

**Comment by fagnerln** [comment]
> You are right, is not a Proton problem. I upgraded my graphics from 450 to 460 (Nvidia GTX1060) and now works great!
> 
> It's a pity that this driver version have a bug with [rFactor 2](https://github.com/ValveSoftware/Proton/issues/245#issuecomment-757020531).
> 
> https://forums.developer.nvidia.com/t/regression-low-fps-on-rfactor-2-proton-with-460-linux-driver/166910/16

Bizarre this bug with rFactor, try to force opengl (wined3d) on it as it's an old game, maybe it's a bug on Vulkan.

**Comment by kisak-valve** [comment]
Hello @fagnerln, @leillo1975, let's keep the rFactor 2 discussion on #245.

**Comment by gudvinr** [comment]
It kinda works for me too. I was able to finish tutorial races but game hangs when I try to start new one from menu.

**Comment by cazzoo** [comment]
I got the game working with proton 5.13-6 and VKD3D_CONFIG=force_bindless_texel_buffer but trying with higher version (with or without ENV var) didn't work at all...

**Comment by leillo1975** [comment]
The game don't work again on my [system](https://gist.github.com/leillo1975/d84559b2959dd6825a56c5483906f17b). I tried with the last version of Proton, with Experimental and the @GloriousEggroll's Proton-6.13-GE-1. This is the Steam Log:
[steam-703860.log](https://github.com/ValveSoftware/Proton/files/6944904/steam-703860.log)

**Comment by GaultGame** [comment]
GRID is running very well again with the latest version of Proton Experimental.

**Comment by cazzoo** [comment]
Using the latest version provided by steam (experimental) the game crashed. Same goes with the `VKD3D_CONFIG=force_bindless_texel_buffer %command%`. I cannot make it run with GE 7.1 neither.

**Comment by SaulGoodman1337** [comment]
game crashed at startup. steamdeck

**Comment by leillo1975** [comment]
Don't work with Proton 7.0-2 and Experimental. With 6.3-8 everything seems normal. This is the 7.0-2 log:

[steam-703860.log](https://github.com/ValveSoftware/Proton/files/8709934/steam-703860.log)

**Comment by alasky17** [comment]
@leillo1975 I can't reproduce the failure with 7.0-x.  Could you try unplugging any peripherals in case the crash is related to something you have plugged in to help narrow it down?

**Comment by leillo1975** [comment]
Sorry, I just saw the message. Tonight when I get home I will try it

**Comment by leillo1975** [comment]
I unplugged my steam controller and my G29 wheel, and with 7.0-2, I only have a black screen. This is the log
[steam-703860.log](https://github.com/ValveSoftware/Proton/files/8800865/steam-703860.log)

**Comment by cazzoo** [comment]
Running the game with proton 7 (and beta) work fine, but I have game crashing often when completing a race, when it tries to save... It doesn't occur every time.
