### ISSUE TITLE
Disco Elysium (632470)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3167]
# Compatibility Report
- Name of the game with compatibility issues: Disco Elysium
- Steam AppID of the game: 632470

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nvidia 440.26
- Kernel version: 5.3.0-19
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/HungOverOnATues/8712767939837564867600b4bed3dac1
- Proton version: 4.11-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-632470.log](https://github.com/ValveSoftware/Proton/files/3764482/steam-632470.log)

## Symptoms 

Keys on either a physical keyboard or emulated with the Steam Controller do not have any effect in the game. Mapping keyboard keys to an Xbox One controller and using that with the Steam Controller turned off does work, so it appears to be specific to the Steam Controller. 

## Reproduction

Connect a Steam Controller and leave the overlay enabled. Attempt to use the keyboard or mapped keys on the controller.

**Comment by ghost** [comment]
As a workaround for anyone else dealing with this, if you disable the Steam Overlay in the game properties you'll be able to still use your desktop config. At the moment, at least in the current Steam client beta (haven't tested stable) the "Steam Input Per-Game Setting" doesn't seem to do anything - forcing it off still loads a controller config which breaks the game, so disabling the overlay seems to be necessary.

**Comment by kisak-valve** [comment]
Hello @HungOverOnATues, can you go to Steam -> Settings -> In-Game and check if `Use the Big Picture Overlay when using a Steam Input enabled controller...` is enabled, and if it is, then test if disabling that option makes a difference.

This looks like a line of interest from the log: `err:rawinput:find_hid_devices Failed to open device file L"\\\\?\\HID#VID_045E&PID_028E&IG_0#1&03000000DE280000FF11000001000000&1&3#{4D1E55B2-F16F-11CF-88CB-001111000030}", error 2.`

**Comment by ghost** [comment]
I have that option disabled as enabling it and launching the game from the desktop client breaks controller support in all games. Pressing buttons on the controller has no effect in game - instead, I can hear the sounds of the big picture mode menus in the background. I have to launch the game from big picture mode in order to get the BPM overlay. I'd assumed that this bug was already known/reported, but I hadn't actually looked yet.

**Comment by kisak-valve** [comment]
Thanks for checking, and it is https://github.com/ValveSoftware/steam-for-linux/issues/6495.

**Comment by kisak-valve** [comment]
Disco Elysium (632470)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/3169.
@albertzdic posted on 2019-10-24T10:24:33:

# Compatibility Report
- Name of the game with compatibility issues: Disco Elysium
- Steam AppID of the game: 632470

## System Information
- GPU: NVIDIA Corporation GM107M [GeForce 940M] (rev a2)
-2nd GPU: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
- Driver/LLVM version: 3.0 Mesa 19.2.1 and 4.6.0 NVIDIA 435.21
[steam-632470.log](https://github.com/ValveSoftware/Proton/files/3766943/steam-632470.log)

- Kernel version: 5.3.0-19-generic
- Link to full system information report as 
intel --> https://gist.github.com/albertzdic/313790853635fed421648eeaf4754966
nvidia ---> https://gist.github.com/albertzdic/b597d0e8c26596fae5ed56ad08e5b551
- Proton version: 4.11-7

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.


## Symptoms
I can play with the integrated intel graphics card without problem (with the PROTON_USE_WINED3D=1) but if i try to play 
 with the nvidia 940M the game start but fails to render background texture, in game, the background in the menu is normal.

## Reproduction
1. start the game with <PROTON_USE_WINED3D=1 %command%> option

this is a sceenshot: 
![Screenshot from 2019-10-24 12-06-39](https://user-images.githubusercontent.com/36342370/67476343-650d6b80-f647-11e9-8be6-34d4487642ef.png)

![Screenshot from 2019-10-24 12-01-16](https://user-images.githubusercontent.com/36342370/67476788-3e9c0000-f648-11e9-9fc5-c961b1a0de02.png)

**Comment by jhaand** [comment]
# Compatibility Report
- Name of the game with compatibility issues: Disco Elysium
- Steam AppID of the game: 632470

## System Information
- GPU: GTX 970
- Driver/LLVM version: NVIDIA 418.74
- Kernel version: 4.19.0-6-amd64
- Link to full system information report as [Gist]: https://gist.github.com/jhaand/058b7952dae15022b316b0b81937e9f3
- Proton version: 4.11-7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Steam proton log: 
[steam-632470.log](https://github.com/ValveSoftware/Proton/files/3774611/steam-632470.log)

## Symptoms 
The game crashes within 20 minutes. Tried several times. 
The steam logs mentions "eventfd: Too many open files" but the hard fd limit is high enough (ulimit -Hn: 565535) 

## Reproduction
Install the game without any changes. 
Start the game and play a while.

**Comment by mozo78** [comment]
You should rise your hard limits to 1048576. The game is working fine.

**Comment by jhaand** [comment]
> You should rise your hard limits to 1048576. The game is working fine.

It now only worked a little bit longer. 25 minutes in total.  Exited with the same error message. 
I find it very strange that an isometric RPG needs more than a million open files. So this looks like a defect to me. 
But it's hard to tell if this is a problem of Proton or DE.

**Comment by albertzdic** [comment]
try to put <PROTON_USE_WINED3D=1 PROTON_NO_ESYNC=1 %command%> in the launch options. It worked for me.

**Comment by doitsujin** [comment]
@jhaand

> So this looks like a defect to me.

Some games leak file descriptors with esync; usually those are game bugs. Either try `PROTON_NO_ESYNC=1`, or if you're feeling adventurous, try fsync (which needs a custom kernel, but offers the performance benefits of esync without relying on file descriptors).

@albertzdic why enable wined3d? I'm aware that this game is broken on some older Nvidia GPUs with DXVK right now (already fixed in upstream dxvk), but other than that, it should work?

**Comment by albertzdic** [comment]
yes sorry this are my launch options. Only esync should work.

**Comment by jhaand** [comment]
> Either try `PROTON_NO_ESYNC=1`, or if you're feeling adventurous,

Well the PROTON_NO_ESYNC =1seemed to work. I could even lower the hard limit back to 4096. The game ran fine for more than an hour. 
This was after checking the new patch that was installed last evening. That still crashed. So, esync remains still an issue with the new patch. 

Thank you for helping out.

**Comment by matthew-piziak** [comment]
My _Disco Elysium_ crashes reliably even with `PROTON_NO_ESYNC=1`. I am using Proton 4.11-11.

[Game Log](https://github.com/ValveSoftware/Proton/files/4057216/steam-632470.log)

**Comment by matthew-piziak** [comment]
I have done some detective work (and in the game). First of all, I have added `DefaultLimitNOFILE=1048576` to my `systemd` config. Watching `/proc/sys/fs/file-nr` while playing shows the file count climbing to `1048576` and then crashing the game.

While ESYNC does increase the rate at which files are open, I find that removing it causes _Disco Elysium_ to crash X server entirely…or something, I'm not sure since it takes down my whole system and forces a hard reboot, and I'm not sure how to characterize the crash. Foregoing `PROTON_NO_ESYNC=1` crashes the game but keeps my session alive.

I will now try `DefaultLimitNOFILE=infinity` (a.k.a 1073741816) to see if that allows me to continue playing after 1048576 files have been opened.

NixOS users can apply this configuration declaratively by putting the following in their `configuration.nix`:
```
systemd.extraConfig = ''
    DefaultLimitNOFILE=infinity
  '';
```

**Comment by matthew-piziak** [comment]
1110000+ files open, and the game is still humming along. For some reason when I set `DefaultLimitNOFILE=infinity` the game did not start. `DefaultLimitNOFILE=2097152`, though, works.

**Comment by wilbefast** [comment]
I have the same issue as @albertzdic : a whole bunch of textures are missing, so basically I see only characters models floating above water. Bizarrely **this started happening only after I died for the first time and loaded my auto-save**, after a couple of hours of play. Following that, no ground textures. I tried:

- [x] Loading different saves
- [x] Entering and exiting buildings to prompt a reload
- [x] Starting a new game
- [x] Reinstalling the game
- [x] Running with PROTON_USE_WINED3D=1
- [x] Full system update

Updating and rebooting seemed to work, but only temporarily: a few hours later the problem reappeared. I'm thinking now that this may be due to overheating or some other "load" that builds up when the machine is run for longer periods of time. Perhaps the graphics card has measures that kick in when it gets too hot?

My system information:

- OS: Arch Linux
- KERNEL: 5.3.11-arch1-1
- CPU: Intel Core i5-4200H @ 2.80GHz
- GPU: NVIDIA GeForce GTX 850M
- GPU DRIVER: NVIDIA 440.31
- RAM: 8 GB

I'm running the game with PROTON_NO_ESYNC=1 %command% as per recommendations on ProtonDB.

**Comment by ghost** [comment]
An update on the keyboard issue described in the original post: My assumption that it affects only the Steam Controller was faulty. While playing another game, Voxelgram, I ran in to the same issue as here and discovered that the issue occurred when the key bindings were purely keyboard & mouse. If you use any gamepad bindings in your config, then the keyboard bindings will work correctly. When testing with the Xbox controller I had a mix of keyboard/mouse and gamepad controls which is why I didn't have problems when initially testing it.

I noticed that both games effected were Unity games so I did a bit more testing with a couple of more Unity games, Dusk and Hollow Knight, both of which have native linux ports. In addition, I tried a few games that do not use Unity: Amid Evil (Windows only), Garou: Mark of the Wolves (Windows only), and Baba is You (native port).

- Dusk (proton 5.0-3): Mouse worked in menus, but not the keyboard. Both keyboard keys and mouse movement do not work when in-game but the mouse buttons work. Adding a gamepad mapping to the config allows the keyboard/mouse bindings to work correctly.
- Dusk (native): No issues with pure keyboard/mouse config.
- Hollow Knight (proton 5.0-3): Only the mouse worked with keyboard/mouse only config. Adding a gamepad binding allowed the keyboard bindings to function.
- Hollow Knight (native): No issues with pure keyboard/mouse config.
- Amid Evil (proton 5.0-3): No issues with pure keyboard/mouse config.
- Garou (proton 5.0-3): No issues with pure keyboard/mouse config.
- Baba is You (native / proton 5.0-3): No issues with pure keyboard/mouse config.

Pretty limited testing, but it does look like it's specifically an issue with Unity games running in proton when using only keyboard & mouse bindings on a controller. Not sure if I should be opening separate issues for each game with the issue or a more generic one for Unity titles. @kisak-valve, any thoughts?

**Comment by soredake** [comment]
Proton 5.0-4, overlay is not working, and game is crashed after an hour.
https://gist.github.com/soredake/ed1fa30f885371dda5f331815920a3ae

[steam-632470.log](https://github.com/ValveSoftware/Proton/files/4332909/steam-632470.log)

**Comment by zelmor** [comment]
Game worked earlier, but now encounters 
```
25991.891:00cc:00d0:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
25991.891:00cc:00d0:err:winediag:nodrv_CreateWindow The explorer process failed to start.

```
[steam-632470.log](https://github.com/ValveSoftware/Proton/files/7213185/steam-632470.log)

**Comment by kisak-valve** [comment]
Hello @zelmor, your issue is one line earlier: `C:\windows\system32\explorer.exe: symbol lookup error: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/vulkan/libvulkan_radeon.so: undefined symbol: amdgpu_query_video_caps_info` We've seen similar at #4959. Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by zelmor** [comment]
@kisak-valve https://gist.github.com/zelmor/e96cd3e62aad431bf37629c14b174773

amdgpu is in fact installed on the system, mainline and LTS kernel had a buggy patch previously that made certain AMD cards only bootable in nomodeset. 

Let me know what you need tested and I can provide.

**Comment by zelmor** [comment]
I can confirm that this is an amdgpu issue. I managed to start the game with Proton Experimental.

Steps taken:

1. purge amdgpu drivers
2. restart system
3. start game.

@kisak-valve let me know if you need amdgpu testing under debian-sid in the future.

**Comment by kisak-valve** [comment]
The issue would be between mesa/RADV and libdrm, not your kernel. It looks like you grabbed the system information a bit too quickly for the extended diagnostics information to be gathered, but since you've figured out how to get it working, there's not much point in digging further.

Your usage of the term "amdgpu" is ambiguous in this context, but if you were using an amdgpu-pro installer that was not made or tested with Debian Sid, then that would explain your issue. This reads like https://github.com/ValveSoftware/steam-runtime/issues/309#issuecomment-740989870, which is bad packaging choices by the driver.

**Comment by zelmor** [comment]
I apologise, I was, in fact, referring to the amdgpu-pro drivers. It does appear to be an issue with those drivers. 

As a side-note, maybe the warning during system-information gathering could be put on the top of the window instead of the bottom where people might miss it if they don't scroll and copy-paste too fast.

**Comment by rexhent** [comment]
Game still consistantly crashes for me. Tried Proton Experimental and Proton-7.0rc2-GE-1.
Running Manjaro with Nvidia Optimus GTX 1050 mobile. Using proprietary drivers.

**Comment by alastairgould** [comment]
Getting some artefacts with a Radeon 7900 XTX. Happens only outside zoomed out. mesa-22.3.3, on proton experimental.

![Screenshot from 2023-01-16 11-53-43](https://user-images.githubusercontent.com/4039359/212672627-b1ba20f2-c02c-4170-8587-fa7b25e3d1fb.png)

**Comment by hakzsam** [comment]
@alastairgould Would you be able to try again with Mesa from Git? I landed a fix that might help for your Radeon 7900 XTX issue, thanks!

**Comment by hakzsam** [comment]
I confirmed myself that https://gitlab.freedesktop.org/mesa/mesa/-/commit/5d41d8258a71fa352d8129bf33ce877046a9313c fixed the issue.

**Comment by alastairgould** [comment]
I can confirm this has fixed the issue on the latest mesa. Thank you @hakzsam
