### ISSUE TITLE
Noita (881100)

### ISSUE THREAD

**Issue by SeanRamey** [ValveSoftware/Proton#3176]
# Compatibility Report
- Name of the game with compatibility issues: Noita
- Steam AppID of the game: 881100

## System Information
- GPU: GTX 970
- Driver version: Nvidia 435.21
- Kernel version: 5.4.2-arch1-1-ARCH
- Link to full system information report: https://gist.github.com/SeanRamey/907d867e1cfd0debebfb783db6f87547
- Proton version: 4.11-7

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
[steam-881100.log](https://github.com/ValveSoftware/Proton/files/3776732/steam-881100.log)

Game just has very poor performance when you move the mouse.

## Reproduction
Just play the game. 
I'm sure performance will probably be better with a faster system, but it would be nice if we could get close to native performance.

EDIT:
I have attempted to install the linux-fsync kernel, but couldn't get it to boot. I have also noticed that the performance hits only happen when you move the mouse in game, so I changed the symptoms to reflect that. If you leave the mouse still, it has perfect performance. Not sure if it's a game bug, or due to proton.

PS: Found another compatibility report for Noita, but it was closed and not for this issue. Wasn't sure if I should comment my issue there or not.

**Comment by kisak-valve** [comment]
Hello @SeanRamey, you could give [fsync](https://aur.archlinux.org/packages/linux-fsync/) a try and see if that has a significant effect on performance for this game.

**Comment by TTimo** [comment]
Unlikely to be Proton/Steam specific. This game gets very CPU intensive and does this on Windows as well.

**Comment by SeanRamey** [comment]
@Ttimo I don't have these same slowdowns in Windows 10 on the same PC. The only variables are Linux/Proton.
@kisak-valve I've never done a kernel swap before, but I'll give it a try.

**Comment by TTimo** [comment]
I had these slowdown problems as well, they seem to have disappeared (or at least drastically improved) in the last few days. But I can't tell if it's due to Arch kernel updates, Noita update or something else .. (still using Proton 4.11).

**Comment by kisak-valve** [comment]
Noita (881100)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/3221.
@TehCorwiz posted on 2019-11-14T23:43:18:

# Compatibility Report
- Name of the game with compatibility issues: Noita
- Steam AppID of the game: 881100

## System Information
- GPU: Nvidia GTX 1080
- Driver/LLVM version: Nvidia 440.31
- Kernel version: 5.3.0-22-generic
- Link to full system information report as [Gist](https://gist.github.com/TehCorwiz/fff9358141d13962f1fd58ecc8518075):
- Proton version: 4.11-8

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

There are two other reports for the game:
- The first was a user file-system issue: https://github.com/ValveSoftware/Proton/issues/3105
  - I've already verified that my directories have the correct ownership and permissions.
- The second is an in-game performance issue: https://github.com/ValveSoftware/Proton/issues/3176

[steam-881100.log](https://github.com/ValveSoftware/Proton/files/3849131/steam-881100.log)

## Symptoms
Game does not launch. No window, No sound. Crash occurs within 2 seconds of starting.

## Reproduction
1. Open Steam
1. Enable Steam Play
1. Install Noita
1. Click 'Play'
1. Crash

**Comment by kisak-valve** [comment]
Looks like the game hits `fixme:process:GetNumaHighestNodeNumber (0x32eed0): semi-stub` and immediately segfaults with an access violation (c0000005) after that.

**Comment by Underknowledge** [comment]
I leave this here - maybe it helps somebody 
`I was able to get this game running on wine without much trouble.`

`The only special thing I needed to do was add an override for msvcr120.dll to use the native .dll instead of the built in one, otherwise you'll get a crash right after the title screen ` 

https://steamcommunity.com/app/881100/discussions/0/1630790506927916240/#c1608274347716189260

**Comment by gverm** [comment]
@Underknowledge That should be fixed in 4.11-8 already.

**Comment by SeanRamey** [comment]
> Hello @SeanRamey, you could give [fsync](https://aur.archlinux.org/packages/linux-fsync/) a try and see if that has a significant effect on performance for this game.

@kisak-valve I tried to use the fsync kernel, but it wouldn't boot. Or at least, it seemed to get stuck while booting. Basically, it just took an abnormally long time, and I got tired of waiting over 10 minutes for it to boot, so I just reverted.

> I had these slowdown problems as well, they seem to have disappeared (or at least drastically improved) in the last few days. But I can't tell if it's due to Arch kernel updates, Noita update or something else .. (still using Proton 4.11).

@TTimo I'm using the latest proton and the issue is still there. I have noticed that the issue isn't general performance issues, and is actually somehow linked to mouse movement. I've updated the report to reflect that.

**Comment by tuxayo** [comment]
Does anyone have made a performance comparison with Windows? To confirm that it's not an issue from the game itself.

**Comment by volca02** [comment]
Playing this on proton `5.13-1` with an fsync patched kernel `5.9.6-95-tkg-upds` and nvidia `455.38-5`.

This game plays mostly without any issues on my system. Had to add `PULSE_LATENCY_MSEC=10` to the game's command in order to fix crackling sound.

A problem with this game is that you can't switch from it and back - at least on some window managers, as seen reported on protondb.com.

On i3, as soon as I do that, this happens in console:

```
OnFocusWindowChanged to window type: k_nGameIDControllerConfigs_Desktop, AppID 413080
Loaded Config for Local Override Path for App ID 413080, Controller 0: /home/volca/.local/share/Steam//controller_base/empty.vdf
wine: Unhandled stack overflow at address 7E70053E (thread 00d8), starting debugger...
```

And the game stops displaying anything and just freezes.

Edit: The problem with fullscreen freeze goes away when using Window mode: Windowed in game.

**Comment by Northcode** [comment]
Tried running with various proton versions including experimental and GE. Does not start.
PROTON_LOG=1 gives me this error:
`21270.303:0008:0009:err:ntdll:RtlLeaveCriticalSection section 0x3d0440 is not acquired`

**Comment by tombh** [comment]
Happy that Noita works at least, but it too often grinds to be unplayable slow 😢
```
Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Zen kernel with fsync patches: 5.12.14-zen1-1-zen
Proton 6.3-5
```

**Comment by kkartaltepe** [comment]
> Does anyone have made a performance comparison with Windows? To confirm that it's not an issue from the game itself.

Yes on my machine this game plays flawlessly on windows, on wine you get continuous slowdowns.

- CPU: 6700K
- GPU: nvidia 1070
- Driver/LLVM version: 495.29.05
- Kernel version: 5.14.12

It seems to me that that Proton 4.2-9 is the most performant, versions since then are relatively worse performing but no version actually performs "well". I dont have a fsync enabled kernel to test that.

**Comment by kkartaltepe** [comment]
At least for me it seems I was affected by https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-739441559 which resulted in the reduced performance of the game as I happened to have the vulkan drivers for intel and my igpu enabled. After removing the intel vulkan drivers the game performs as well as on windows.

**Comment by servel333** [comment]
I'd like to report a UI scaling issue. I have a 4k monitor on my laptop. I have Ubuntu set to 200% UI scaling in the system settings. When I run the game, the game window is tiny and hard to see. I can't find any UI scaling settings in the [Proton runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options). When I run the game full-screen, it's very slow and proton does not appear to respect the games resolution settings in both of the full-screen modes that Noita provides.

I can't find anyway to do scaling of this application alone, or to have a resolution where I can actually see the game and also have it play at a reasonable frame rate.

Adding my PC specs:

Ubuntu 21.04
HP - Spectre x360 2-in-1 15.6" 4K Ultra HD Touch-Screen Laptop - Intel
Core i7 - 16GB Memory - 512GB Solid State Drive - Dark Ash Silver
NVIDIA GeForce MX150 graphics

To add, the game runs at a good speed when the game window is tiny, and it looks good at larger resolutions. I just happen to need both big and fast.

**Comment by kisak-valve** [comment]
Noita doesn't start (881100)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5889.
@arouene posted on 2022-06-06T15:04:28:

# Compatibility Report
- Name of the game with compatibility issues: Noita
- Steam AppID of the game: 881100

## System Information
- GPU: Radeon RX 6800 XT
- Driver/LLVM version: Mesa 21.1.8
- Kernel version: 5.17.11
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 7.0-2

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

I have found an issue for Noita (#3176) but it's about performance.



[steam-881100.log](https://github.com/ValveSoftware/Proton/files/8845310/steam-881100.log)

## Symptoms 

Game doesn't start at all.
I tried various Proton options and various Proton versions (GE, experimental, 6.3) without a change. 

## Reproduction

1. Install Noita
2. Try to launch
3. Doesn't start

I have an AMD ThreadRipper, tried gamemode and multithreading disabled without amelioration.

**Comment by kisak-valve** [comment]
Noita not starting

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6541.
@Brulijam posted on 2023-02-16T04:01:37:

# Compatibility Report
- Name of the game with compatibility issues: Noita
- Steam AppID of the game: 881100

## System Information
- GPU: NVIDIA GeForce RTX 4080
- Driver/LLVM version: nvidia 525.89.02
- Kernel version: 6.1.12-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/Brulijam/7539dc9b89b175eed8ed3ae7f86c3281):
- Proton version: 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.



## Symptoms 
Game not launching.

## Reproduction
I don't know. Tried reinstalling Game, Steam, OS, home dir (in that order).

**Comment by kisak-valve** [comment]
Hello @Brulijam, looking at your system information, it looks like your NVIDIA driver install is missing the driver's 32 bit userspace libraries and Steam is forced to fallback to llvmpipe (mesa's faster CPU renderer) to run at all.

I would check if the `lib32-nvidia-utils` system package is installed.

**Comment by Brulijam** [comment]
> I would check if the `lib32-nvidia-utils` system package is installed.

Yup, that did the trick. Thanks for your quick help :)

**Comment by obj-obj** [comment]
Noita also won't launch for me (on both a system with an intel iGPU and dedicated AMD graphics)

I remember playing Noita a while ago, so it's a regression with a game update (since older versions of proton don't work)

**Comment by obj-obj** [comment]
Turns out it was because I had `SDL_VIDEODRIVER=wayland` set for Factorio, and it causes Noita to crash

**Comment by Vaxeral** [comment]
# Compatibility Report
Game: Noita
AppID: 881100


## System Information
Graphics Card: GeForce GT 730
Driver: Nvidia 390.157
Kernal: Linux 5.19.0-38-generic x86_64

[System Information](https://gist.github.com/Vaxeral/35eaf155ce84c45a37fd0d690186ce8a)
Proton Version: Proton Experimental, Proton 7.0-6

## I confirm:
- [YES] that I haven't found an existing compatibility report for this game.
- [YES] that I have checked whether there are updates for my system available.

Here yee LOGS
[steam-881100.log](https://github.com/ValveSoftware/Proton/files/11186786/steam-881100.log)

## Symptoms 
Game does not launch.

## Reproduction
New install of ubuntu 22.04.
switch to Nividia driver supported for my graphics card ie 390.
already downloaded noita.
configure noita to force install with proton.
click play not a fun day.

**Comment by Vaxeral** [comment]
How do i run steam / noita / proton within a terminal so that i may see errors if any are output?  `steam steam://rungameid/881100
` this and its variants do not work.  Just opens steam and detactches the steam process from the terminal.

**Comment by kisak-valve** [comment]
Hello @Vaxeral, the Vulkan implementation provided by the NVIDIA 390 series is unserviceable and the driver in general is older than the support cutoff for Proton.

Looking at your system information https://gist.github.com/Vaxeral/35eaf155ce84c45a37fd0d690186ce8a#file-system_information-L347-L358 is curious. There's 3 variants of the NVIDIA GT 730. Some of them are Fermi generation, and some of them are Kepler generation. There was no vendor support for running Vulkan on Fermi, so that section of your system information hints that you have a Kepler generation video card. Can you check `lspci | grep VGA` and on the NVIDIA card's line, check if there's something like `GK208` (the K in that would indicate Kepler)?

If you have a Kepler variant of the GT 730, then you should be able to try to update to the NVIDIA 470 series video driver, which is the last series to support that generation, along with Proton 7.0 (and older).

**Comment by Vaxeral** [comment]
Hey thanks for reaching out.
01:00.0 VGA compatible controller: NVIDIA Corporation GK208B [GeForce GT 730] (rev a1)

**Comment by Vaxeral** [comment]
A google search says that should be the kepler arch

**Comment by Vaxeral** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/3176#issuecomment-1501287400

Hey Thanks so much you are a wizard :D

**Comment by japhir** [comment]
# Compatibility Report
- Name of the game with compatibility issues: Noita
- Steam AppID of the game: 881100

## System Information
- GPU: Intel HD Graphics 620 
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 23.0.3
- Kernel version: 6.2.12-arch1-1 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.0 NOTE: I've also tried it on the experimental one and on 8.0-1

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.


[steam-881100.log](https://github.com/ValveSoftware/Proton/files/11350545/steam-881100.log)

## Symptoms 

Cursor moves erratically to side of screen since latest game update.

## Reproduction

1. Launch the game
2. Cursor seems normal but doesn't highlight menu items
3. in menu, use the arrow keys to go to options, select "game renders the cursor"
4. this shows that the cursor is glued to a corner/side of a screen, sometimes moves normally for a second, then jumps to the side again.

**Comment by kkartaltepe** [comment]
You didnt provide much system information, but if you are using wayland you may have configured your monitors to be placed in -x or -y coordinates which are not supported in xwayland/x11 that most games run in. Check your monitor configuration to ensure all coordinates are positive.

**Comment by japhir** [comment]
Thanks! I had recently gotten a new monitor and didn't realize I had moved it to negative space rather than moving everything around! This resolves my cursor issue. ~~Is there any way to make the game render at higher resolution than 1920x1080? Or to have the pixels stretch out to my bigger display?~~ EDIT: I've found [this ultrawide mod](https://community.pcgamingwiki.com/files/file/1447-noita-ultrawide-mod/) that resolves this issue!

**Comment by kisak-valve** [comment]
Noita not launching

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6743.
@flan7 posted on 2023-05-04T22:27:19:

# Compatibility Report
- Name of the game with compatibility issues: Noita
- Steam AppID of the game: 881100

## System Information
- GPU: AMD 6600XT
- Driver/LLVM version:  4.6 (Compatibility Profile) Mesa 23.0.3
- Kernel version: linux-6.3.1.arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): [gist](https://gist.github.com/flan7/7009bdc3a9de1973a1fdb64b4169b19f)
- Proton version: Experimental

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.


[steam-881100.log](https://github.com/ValveSoftware/Proton/files/11402032/steam-881100.log)

## Symptoms 
Game does not launch, I click play and it immediately crashes.


## Reproduction

This happened on nvidia-dkms, I switched to a new AMD gpu and am still facing this issue.

**Comment by alasky17** [comment]
@flan7 Is Noita launching on any Proton version?  Could you also try 7.0-6 and 8.0-2?

**Comment by HeinsKetchup** [comment]
> I would check if the lib32-nvidia-utils system package is installed.

Thank you!!

**Comment by HeinsKetchup** [comment]
>it looks like your NVIDIA driver install is missing the driver's 32 bit userspace libraries and Steam is forced to fallback to llvmpipe (mesa's faster CPU renderer) to run at all.

>I would check if the lib32-nvidia->utils system package is installed.

Thank you!!

**Comment by kisak-valve** [comment]
Noita on Wayland crashes one second after window is created.

Issue transferred from https://github.com/ValveSoftware/Proton/issues/7205.
@Blazing-Blast posted on 2023-10-26T18:23:08:

# Compatibility Report
- Name of the game with compatibility issues: Noita
- Steam AppID of the game: 881100

## System Information
- GPU: AMD Radeon 7900 XTX
- Video driver version: Mesa-git 1:23.3.0_devel.179456.3de5da7a5d6-1
- Kernel version: 6.6.0-rc4-00284-gb9ddbb0cde2a (custom config)
- Link to full system information report as [Gist](https://gist.github.com/Blazing-Blast/6aa4dc842400508688e91ce184ea0768):
- Proton version: I tried 8, Experimental and Hotfix.

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
  - I have found one: https://github.com/ValveSoftware/Proton/issues/3176
- [x] that I have checked whether there are updates for my system available.

[logs](https://gist.github.com/Blazing-Blast/0ae993f324fa31de2033604c92279e06)

## Symptoms
The game crashes just after the window opens.

## Reproduction

Install Arch with Hyprland.
Launch the game.
Crash!

**Comment by kainz** [comment]
Crashing on wayland also happens on gamescope-3.3.19 with Xwayland-23.2.3.

**Comment by reportingsjr** [comment]
Noita does not launch on my system as well.

**Compatibility Report**
Name of the game with compatibility issues: Noita
Steam AppID of the game: 881100
**System Information**
GPU: AMD Radeon RX 6500 XT
Video driver version: 4.6 (Compatibility Profile) Mesa 23.0.3
Kernel version: 6.5.5-100.fc37.x86_64
Link to full system information report as Gist: https://gist.github.com/reportingsjr/2e9901199da99c8e63e65531f3ad31b6
Proton version: I tried 8 and Experimental

**Symptoms**
The game crashes just after the window opens.
Full proton/steam log here: https://gist.github.com/reportingsjr/5d32678c5e9c816112425424030d3cb9


**Reproduction**
Launch the game.
Nothing happens
Crash!

EDIT: I saw someone mention that running Noita from command line with proton directly works. I tried that and lo and behold, it does work! Not sure what steam is adding to the launch command that it is failing.

**Comment by ghost** [comment]
If you are under wayland, setting `env --unset=SDL_VIDEODRIVER %command%` launch option works for me

**Comment by spikespaz** [comment]
Launching without forcing SDL to use Wayland does fix, but causes scaling problems on HiDPI displays (nobody is surprised). It also can't seem to change the resolution in the game, no matter what the option says, it won't use any 16:10 resolutions.

**Comment by CubeTheThird** [comment]
I have a strange issue where keyboard input seems to have latency issues. Mouse tracking is normal, and the game seems to be running at full performance, but I sometimes have delayed inputs, or dropped inputs entirely. Anyone know what'd cause this? (Using an AMD GPU on X11)

**Comment by dextercd** [comment]
Hey there! Noita itself runs fine, but I can't upload workshop mods on Proton 9.0-2. If I try, the resulting workshop item appears to be empty (0.000 B).

Proton 8.0-5 and 7.0-6 works fine.

Two other people in the Noita Discord confirmed that switching to Proton 7/8 fixed this same issue for them.

Here are two test uploads.
- Proton 8:
  - https://steamcommunity.com/sharedfiles/filedetails/?id=3267836991
  - Logs: https://gist.github.com/dextercd/944984c8c0a1ef3445b5e0d9ac1a81e0
- Proton 9:
  - https://steamcommunity.com/sharedfiles/filedetails/?id=3267839017
    - Not publicly accessible. There's no option to adjust visibility unlike the Proton 8 upload, probably because it's empty.
  - Logs: https://gist.github.com/dextercd/206ea5e3d537429d43e1dbf4d1c332c8

Proton Experimental also doesn't work, same as Proton 9.

## System Information
* GPU: Radeon RX 6800 XT
* Video driver version: lib32-mesa 1:24.1.1-1
* Kernel version: linux 6.9.4.arch1-1
* Link to full system information report as Gist: https://gist.github.com/dextercd/83ded6a9d1cf5c2dde3e812b44467a28
* Proton version: 9.0-2

## Symptoms 

The upload appears to succeed but the resulting workshop entry is empty and unusable.

## Reproduction

Run `noita_dev -workshop_upload "Test Mod"`

**Comment by CubeTheThird** [comment]
Thanks! I actually just figured out the issue myself. It turns out the latest version of ibus (1.5.30) was the culprit, so I've downgraded it for the time being.

**Comment by alasky17** [comment]
@dextercd Thank you for the report! I tried to look into this, but I've never modded Noita before so I wasn't able to get this working on 8.0 either ... I'm assuming this is some failure on my part, so I'm hoping you can give me some more instructions to help me out :)  

I tried just copying the daily_practice mod files that come with the game in the mods folder, and then renaming the folder, adding a workshop.xml file that I *think* I wrote correctly, and then putting many combinations of "noita_dev -workshop_upload" in the launch options for the game with Proton 8 selected.  I had my mod in the common/Noita/mods folder.  It would also be super great if you could upload your test mod folder or tell me where to find it (so I can use it instead of daily_practice) - I looked in compatdata/881100/pfx/drive_c/users/steamuser/AppData/LocalLow/Nolla_Games_Noita which I got from the Noita wiki, but I couldn't find your workshop data (even though the workshop is showing up in the mods area in-game after I subscribed to it).

**Comment by dextercd** [comment]
Hey @alasky17,

My reproduction steps could've been more complete, sorry about that!

Here's the test mod I made: https://github.com/dextercd/Test-Mod I have it located at `/home/dexter/.local/share/Steam/steamapps/common/Noita/mods/Test Mod` but the exact mod folder name doesn't really matter from what I could tell, so test_mod or Test-Mod will work the same. (Just remember to adjust the upload command)

noita_dev is actually a separate executable you need to launch. There are a couple ways to do this that I know of:

<details>
<summary>1. Add noita_dev.exe as a non-Steam game into Steam</summary>

Some people add noita_dev.exe as a non-steam game into Steam, I had some Steam UI issues when I tried this but I was eventually able to reproduce the issue using this method
</details>

<details>
<summary>2. Shell script using the Proton install and Noita prefix</summary>
Other people use a script like this:

```bash
#!/bin/bash

# This script invokes noita.exe with the specified arguments (if any)

# This script is intended for use on Linux with Steam Proton.
# Change any of the following variables if your setup is different.

STEAM="$HOME/.local/share/Steam"
NOITA="$STEAM/steamapps/common/Noita"
WINE="$STEAM/steamapps/common/Proton - Experimental/files/bin/wine"

export WINEPREFIX="$STEAM/steamapps/compatdata/881100/pfx"
cd "$NOITA" && "$WINE" noita_dev.exe "$@"
```

`./launch-dev -workshop_upload "Test Mod"`

With the WINE program path changed appropriately to the version of Proton you want to use.
</details>

<details>
<summary>3. Launching noita_dev.exe through noita.exe</summary>

I use yet another way of launching noita_dev, which is to have a mod to launch a cmd window from noita.exe and then run noita_dev.exe through that. (My reasoning behind this method is that the cmd and noita_dev processes will inherit all the environment variables and proton config from the noita.exe process, so it should be the most compatible).

I've uploaded a mod that launches a cmd windows as soon as you start a run with it enabled: https://github.com/dextercd/LaunchCmd . You need to enable unsafe mode in the mod menu in the top right to enable the mod, because Noita prevents mods from launching other programs normally. The mod doesn't do anything unsafe though, it's pretty easy to verify the one line of code in `init.lua` :^)

You can't upload this mod to the workshop, you still need the Test Mod linked above.
</details>

The Proton 9 issue happens with all three methods, so I don't think it matters much which you pick. Note that after uploading a mod, it creates these three files: `workshop_id.txt`, `mod_id.txt`, and `compatibility.xml`. You need to remove them to create a fresh workshop entry, otherwise it'll try to update a previous upload.

**Comment by dextercd** [comment]
Oh also, workshop mods are located in `/home/dexter/.local/share/Steam/steamapps/workshop/content/881100/<mod_id>`, but you shouldn't need this with the GitHub repo linked above.

Let me know if you need anything else! It'd be great if this issue can be resolved :slightly_smiling_face:

**Comment by alasky17** [comment]
@dextercd Thank you! These new steps were very clear, and I immediately see where I went wrong.  I'm glad now that I didn't waste too much time before asking for some help :) 

I see the regression between Proton 8 and 9 and will investigate further now.  Again, thank you for the instructions!!

**Comment by dextercd** [comment]
Hmm, seems like the uploader started working at some point.
Experimental but also 9.0-2 works now. Not sure if it was from changes on Valve's side or something else.

Just wanted to let you know in case this is unexpected and helps shed light on the issue.

If it was because of changes made on Valve's side then many, many thanks for that, @alasky17

**Comment by alasky17** [comment]
@dextercd Whoops - I forgot to update when we fixed this 😅  We ended up doing a Proton 9.0-2 incremental bump (from -c to -d) and snuck the fix in there.  Thank you for following up!!

**Comment by dextercd** [comment]
Awesome! Many thanks to you and the rest of the team
