### ISSUE TITLE
GUILTY GEAR XX ACCENT CORE PLUS R (348550)

### ISSUE THREAD

**Issue by Yukari-Kuramoto** [ValveSoftware/Proton#328]
-  Manjaro 17.1.12 (testing) kernel 4.18.4
-  GTX 1080 (Nvidia 396.54)
-  R7 1700X
- default Proton 3.7

[Steam log](https://gist.github.com/Yuri-Makina/b358a9efc38866934f04be6a1439a956)

**Comment by Yukari-Kuramoto** [comment]
Just noticed that the game fails to close correctly similar to Monster Hunter World.

**Comment by AwesamLinux** [comment]
Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version: 5.1.0-050100-lowlatency
Proton version: 4.2-3

Game worked fine including Nintendo Switch Pro controller support, but the intro video was skipped (this did not prevent this game from be played).

[media_info.txt](https://github.com/ValveSoftware/Proton/files/3163064/media_info.txt)
[steam-348550.log](https://github.com/ValveSoftware/Proton/files/3163065/steam-348550.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3163066/system_info.txt)

In the log I see "78885.287:0028:0029:err:quartz:GetClassMediaFile Media class not found"

So game uses quartz and the videos are: WMV, VC-1 + WMA
(another for the list #1464)

**Comment by GoLD-ReaVeR** [comment]
I'm unable to connect to other players since proton 5.13. This is regression over 5.0 where I was able to play 1 game. Any proton version I have access to from before also allowed me to play 1 game. I saw nothing useful in the logs. I do not have these issues in Guilty Gear Xrd by the way; though I think they are using different netcode.

There will be a GGPO patch on the 28th of october, could someone look into this game working online after the 28th?

**Comment by kisak-valve** [comment]
Hello @GoLD-ReaVeR, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by GoLD-ReaVeR** [comment]
[steam-348550.log.gz](https://github.com/ValveSoftware/Proton/files/5434693/steam-348550.log.gz)
Here you go.
 I started the game, entered network -> player match, invited a player and when he joined I pushed ready. After connection failed I exited back to title and exited the game.

**Comment by GoLD-ReaVeR** [comment]
Good news! The new netcode works like a charm. There's a bit of a slowdown post match however and I'm unsure what's the source of that problem. Once things settle down over there a little I'll try to ask the developers if they could help me chase down the root of it.

**Comment by namtsui** [comment]
There may be a regression. I was able to launch the game before and played for an hour several weeks ago. After a recent steam update the game now crashes soon after starting. The game both with and without rollback beta crashes:
- Now loading
- displays arc systems logo
- displays black box and sidebars and crashes

nouveau gtx 770 with PROTON_USE_WINED3D=1 PROTON_LOG=1 %command%

log: https://gist.github.com/namtsui/4dc51f4c5a0ebad1232fc49e5a389677

offending line:
Unhandled exception: page fault on read access to 0x00000009 in 32-bit code (0x00548598).

**Comment by GoLD-ReaVeR** [comment]
Run winecfg for the prefix and set quartz.dll to native.

**Comment by namtsui** [comment]
> Run winecfg for the prefix and set quartz.dll to native.

I tried this after your suggestion but it still crashes in the same manner with blackscreen and sidebars. Can you try PROTON_USE_WINED3D=1?

```
launch options: PROTON_DUMP_DEBUG_COMMANDS=1 PROTON_USE_WINED3D=1 PROTON_LOG=1 %command%
cd ~/.steam/steam/steamapps/compatdata/348550/pfx
/tmp/proton_namtsui/run winecfg
set quartz.dll to native
```

**Comment by GoLD-ReaVeR** [comment]
I can try, but you don't need to use wined3d. Launched to menu just fine for me.

Eh, you would need to run winecfg using WINEPREFIX=~/.steam/steam/steamapps/compatdata/348550/pfx winecfg or the proton variant of that (of which I completely forgot the syntax). If you just run winecfg you're running it in your ~/.wine folder which is not what you want.

**Comment by namtsui** [comment]
> I can try, but you don't need to use wined3d. Launched to menu just fine for me.
> 
nouveau does not support dxvk so wined3d is what used to work for me until recently. I am not able to try the proprietary nvidia driver, which does support dxvk.

Proton uses dxvk by default now since version 5.
source: https://github.com/ValveSoftware/Proton/issues/271#issuecomment-692303975

> Eh, you would need to run winecfg using WINEPREFIX=~/.steam/steam/steamapps/compatdata/348550/pfx winecfg or the proton variant of that (of which I completely forgot the syntax). If you just run winecfg you're running it in your ~/.wine folder which is not what you want.

I think I did the proton variant of that based on this source, since I use proton's wrapper script, `/tmp/proton_namtsui/run`

source: https://steamcommunity.com/app/221410/discussions/0/1734336452578488603/?ctp=2

> as mentioned by user Random,
> proton has winecfg support. you can use /tmp/proton_run winecfg on a prefix for protons own winecfg.

**Comment by GoLD-ReaVeR** [comment]
I'm not even getting that proton_run file. I highly recommend using the syntax as I provided it. It is safe to run and if you make changes your settings will be saved correctly. If you did it correctly previously you should see the quartz.dll set to native.

**Comment by namtsui** [comment]
> I'm not even getting that proton_run file.

PROTON_DUMP_DEBUG_COMMANDS=1 in launch options will produce that run file.

**Comment by hajnal-endot** [comment]
I'm unable to copy lobby links.  That is, when I hit the button, the lobby link doesn't go to my clipboard on GNOME.  I don't know if this is a GNOME issue or just a general problem with Xorg or what's going on.  This and the opening video bug are the only things keeping me from calling this whitelistable on AMDGPU.

Also, to help people browsing: if you can't get matches with the new beta (like, it keeps saying the lobby you tried to join is unavailable), turn off vsync and antialiasing.  It's not exclusive to Proton, it's affecting everyone.  Differences in either setting seem to change who you can match with, and most players have converged to those settings.

**Comment by namtsui** [comment]
There is an issue on linux with a delay after each ranked match. It takes 10 seconds to get to "send data to rankings" then it stalls there for 40 seconds. The opponent has to wait, too.

https://steamcommunity.com/app/348550/discussions/0/3084376689325732989/
https://steamcommunity.com/app/348550/discussions/0/3117032860256634682/

**Comment by Siam-Lights** [comment]
There seems to be a recent regression, probably related to Mesa 23.1.1. Changing Proton versions doesn't seem to change anything.
The game seems to be rendering at a lower internal resolution than 480p, and the colors look washed out.
I'm attaching a log and screenshots.
[steam-348550.log](https://github.com/ValveSoftware/Proton/files/11641830/steam-348550.log)
![Screenshot from 2023-06-02 22-24-54](https://github.com/ValveSoftware/Proton/assets/97821031/4839f124-6bd0-44f8-8e9f-492ea34bf560)
![Screenshot from 2023-06-02 22-30-04](https://github.com/ValveSoftware/Proton/assets/97821031/1eaa5bb8-9c82-4cf9-8c99-303d3beca581)

**Comment by Siam-Lights** [comment]
> There seems to be a recent regression, probably related to Mesa 23.1.1. 

The issue also seems to be present in Guilty Gear Xrd and Under Night In-Birth. I also tried Ninja Gaiden Sigma, Deep Rock Galactic and Tales of Symphonia from my library, none showed any issues.
![Screenshot from 2023-06-02 23-06-13](https://github.com/ValveSoftware/Proton/assets/97821031/ab52fead-8c63-46ef-b9c8-d004817a2aa7)
![Screenshot from 2023-06-02 23-10-39](https://github.com/ValveSoftware/Proton/assets/97821031/24e333a9-9461-4485-833e-78c8fdf7d7ad)
