### ISSUE TITLE
River City Girls (1049320)

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/Proton#3345]
# Compatibility Report
- Name of the game with compatibility issues: River City Girls
- Steam AppID of the game: 1049320

## System Information
- GPU: AMD Radeon VII
- Driver/LLVM version: Mesa 20.0/10.0.0
- Kernel version: 5.2 RC2
- Link to full system information report as [Gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)
- Proton version: 4.11-11

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1049320.log](https://github.com/ValveSoftware/Proton/files/3991364/steam-1049320.log)

## Symptoms 
After showing copyright notes the game demonstrates only a black screen.

![Screenshot from 2019-12-21 15-12-10](https://user-images.githubusercontent.com/200750/71307772-f9f8cf00-2414-11ea-93f7-ac9032be5261.png)

![Screenshot from 2019-12-21 15-12-18](https://user-images.githubusercontent.com/200750/71307774-04b36400-2415-11ea-9594-cdb49302abc1.png)

## Reproduction
Just launch the game.

**Comment by kisak-valve** [comment]
Looks like this game would benefit from support for Media Foundation maturing.

**Comment by nightsky30** [comment]
Seems like a lot of games are waiting on #1464 

Proton 5.0.4

Latest logs: 
[steam-1049320.log](https://github.com/ValveSoftware/Proton/files/4335052/steam-1049320.log)

**Comment by nightsky30** [comment]
It seems the latest Linux Steam client update (not Proton) broke the game further.  Prior to the update you would at least have the game start and show a black logo/info screen.  There is no longer any visible game started, and the game is not stoppable by selecting Stop in the Library.  The game just continues to run in the background until you exit Steam completely.

![image](https://user-images.githubusercontent.com/6024315/77125557-2e7c2700-6a14-11ea-929c-f9cbc320d5af.png)

Linux
 - Steam runtime 0.20200318.1:
 - Updated to latest version of libvulkan, exporting more WSI functions for Proton
 - Runtime diagnostic tool improvements

**Comment by kisak-valve** [comment]
Hello @nightsky30, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by nightsky30** [comment]
> Hello @nightsky30, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

Hmmm it "ran" (initial game screen showed) once after an uninstall and reinstall of the game, but subsequent attempts seen to fail with the above behavior (no game screen, can't stop process).  This is the **entire** log after the Steam client update.  You may compare it to my previous upload:

```
======================
Proton: 1583767778 proton-5.0-4
SteamGameId: 1049320
Command: ['/home/user/.local/share/Steam/steamapps/common/River City Girls/RiverCityGirls.exe']
Options: {'forcelgadd'}
======================
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

**Comment by nightsky30** [comment]
The crashing I experienced appears fixed with Proton 5.0.5.  The original issue with the game requiring Windows Media Foundation/Framework support still remains.

**Comment by nightsky30** [comment]
Here's an updated log for Proton 5.0.8: 
[steam-1049320.log](https://github.com/ValveSoftware/Proton/files/4742151/steam-1049320.log)

Nothing different that I can see. Though, it looks like there was some work done in Wine 5.10 that includes mention of mfmediaengine and mfplat. :)

**Comment by nightsky30** [comment]
Latest log with:
Proton: 1602710188 proton-5.13-1b
[steam-1049320.log](https://github.com/ValveSoftware/Proton/files/5393205/steam-1049320.log)

**Comment by nightsky30** [comment]
Seems to be playable now with Proton Experimental. The videos only display the test patterns, but that is not a huge deal.

**Comment by AwesamLinux** [comment]
## System Information
- GPU: AMD Radeon RX 5700
- Driver/LLVM version: Mesa 23.0.0-git
- Kernel version:  5.18.8-200.fsync.fc36.x86_64
- Proton Version: proton-7.0-3 / GE-Proton7-24 / experimental-bleeding-edge-7.0
[system_info.txt](https://github.com/ValveSoftware/Proton/files/9066973/system_info.txt)

**proton-7.0-3 and experimental-bleeding-edge-7.0:**
The Boss introduction videos do not play. The screen is just black (not even a test pattern). You can hold a button to skip the video to continue playing. Other videos like the games intro work fine. 

**GE-Proton7-24:**
the boss introduction videos play but without audio.

**Proton-6.3-8:**
All the videos work, so this seems to be a **regression**

[steam-1049320-experimental-bleeding-edge-7.0.log](https://github.com/ValveSoftware/Proton/files/9066975/steam-1049320-experimental-bleeding-edge-7.0.log)
[steam-1049320-GE-Proton7-24.log](https://github.com/ValveSoftware/Proton/files/9066976/steam-1049320-GE-Proton7-24.log)
[steam-1049320-proton-6.3-8.log](https://github.com/ValveSoftware/Proton/files/9066978/steam-1049320-proton-6.3-8.log)
[steam-1049320-proton-7.0-3.log](https://github.com/ValveSoftware/Proton/files/9066979/steam-1049320-proton-7.0-3.log)


Steps to replicate:
- Play the game until you reach a boss

The boss videos are MPEG-4 AVC video / AAC LC Audio
[media_info.txt](https://github.com/ValveSoftware/Proton/files/9066971/media_info.txt)

**Comment by opal1974** [comment]
For me, the videos play with audio - but not all of them.

I beat the 'secret bosses' but both movies for this only showed the test patterns.  Very strange all the others movies would play (went through entire game) but not those 2.

**Comment by daikaiser** [comment]
Just tried the game and the boss introduction videos do not display properly.

Proton Experimental and Proton 7.0-4
- Black screen and no audio

GE-Proton7-35
- Videos play but no audio

Proton-6.3-8
- The videos all play fine.

**Comment by waspennator** [comment]
Testing on deck with the latest version of Proton Experimental, boss intro cutscenes still seem to result in a black screen with no audio that you manually have to skip unless you downgrade to 6.3-8. Confused at why this game is still marked as deck verified.

[steam-1049320.log](https://github.com/ValveSoftware/Proton/files/12076915/steam-1049320.log)

**Comment by waspennator** [comment]
Tested on latest Experimental and boss fmvs still aren't playing and still marked as deck verified.

@kisak-valve sorry for the ping, but is there a way to tell the verification team to mark this as temporarily unsupported due to broken fmvs?

**Comment by Reonu** [comment]
@kisak-valve this is still verified despite the FMVs literally not working out of the box. Can you at least change the verification status until this is fixed?

**Comment by ghost** [comment]
I've tested and can confirm that I had the same issues that @AwesamLinux had, plus the weird artifacts at the manga pages cutscenes. With the newer versions of Proton-GE the boss videos are just a black screen.

**Comment by Ruedii** [comment]
I'm getting on Proton 6.x and earlier, I just get black screens for the cutscenes with a crash.   For 7.x, 8.x and 9.x I'm getting a placeholder image. 

Otherwise the game works well.  Should be demoted to be listed as mostly functioning, since this doesn't prevent playing the game.   

Does anyone have information on the source of the regression.  Is it possible to cherry-pick and make a build that would work?

**Comment by waspennator** [comment]
On my oled deck, I just get the visual black screens during boss scenes even on proton Experimental. As soon as I drop to 6.3-8, Misuzus boss cutscene plays normally, so it's not like it isn't there.

**Comment by Realploot** [comment]
I just purchased the bundle of all three games. The boss intros show only black but are skippable. This should not be Deck Verified. On Proton 6.3-8 I get a test pattern for the intro video and some music skips. There has to be a perfect fix for this.

**Comment by waspennator** [comment]
> I just purchased the bundle of all three games. The boss intros show only black but are skippable. This should not be Deck Verified. On Proton 6.3-8 I get a test pattern for the intro video and some music skips. There has to be a perfect fix for this.

Are you using an lcd or an oled deck, still confused why others are getting test patterns while I'm not.

I think I remembered seeing reports saying using proton ge should fix the issue, but it would be nice to see this fixed on default proton. Dunno if staff noticed this is an issue or not. Very least it would be helpful if they bumped it down to unsupported or pinned the proton version to 6.3-8

**Comment by Realploot** [comment]
> > I just purchased the bundle of all three games. The boss intros show only black but are skippable. This should not be Deck Verified. On Proton 6.3-8 I get a test pattern for the intro video and some music skips. There has to be a perfect fix for this.
> 
> Are you using an lcd or an oled deck, still confused why others are getting test patterns while I'm not.
> 

I am playing on an older LCD model. I’m actually getting test patterns on all FMVs using 6.3-8. Ugh. What a pain. This should 100% not be listed as verified in this condition. I know it’s just videos, and the game plays fine, but verified should mean fully functional. 
I’m going to download ge and see if it works. Thanks for the tip. 

Edit - ge did not fix the black screen issue on my LCD Deck.

**Comment by Ruedii** [comment]
GE fixes SOME of the videos, but not all of them.  

It should be listed as verified "partially functioning".   A recent patch in the game caused it to go from fully functioning to partially function.   Valve should probably look into what this change was.

I'm certain it was something to do with how the videos are encoded, as I've seen this with a lot of MPEG videos.  GE-Proton gets more of them to work, but not all of them.   Each revision of GE-Proton lately is getting more and more to work.

As a note, browsing to the game directories on Linux, I found that the videos all play fine on my computer's video player.   It must be how Valve built their video codec that it is inflexible.  I am suspecting that it only supports MPEG4 standard defined modes, and not "custom" modes.  I wish everyone could just use WebM-AV1.

**Comment by EpicureanGit** [comment]
Slackware64 Current
NVIDIA GTX 1070 with NVIDIA Driver Version 555.58.02
Steam Build: Steam Beta Branch: Stable Client
Steam Version: 1721173382
Steam Client Build Date: Tue, Jul 16 7:22 PM UTC -08:00
Steam Web Build Date: Mon, Jun 24 3:16 PM UTC -08:00
Proton: 1722351075 experimental-9.0-20240730
System Information: https://gist.github.com/EpicureanGit/0695fbde6dfc7bcf5b8fabcd62f94341
System Runtime Diagnostics: https://gist.github.com/EpicureanGit/9932edeb591ba63cfbcd29b921e0629f
System Report: https://gist.github.com/EpicureanGit/9aed3fd6cc1c5dc87af5477d6ff4e194

PROTON_LOG=1 https://gist.github.com/EpicureanGit/8c7baebdc9d85fd8f3557d498f27449b

Controllers/Joysticks connected to the PC:
Bus 001 Device 005: ID 0925:0005 Lakeview Research Gamtec.,Ltd SmartJoy PLUS Adapter
Bus 001 Device 006: ID 0079:187c DragonRise Inc. FightStick
Bus 002 Device 004: ID 044f:b10a ThrustMaster, Inc. T.16000M Joystick

Symptoms: 
After loading the game, the game responds to the controller I've set to first controller in the Steam client which is my PS2 controller using the SmartJoy PLUS Adapter. I set the game to be one player. I get to the Player Select screen and the PS2 controller automatically becomes Player 2 on that screen, and my keyboard becomes Player 1 in the game from that moment on.

Reproduction:
Have multiple controllers/joysticks connected to your PC.  Press "Play" in the Steam client. Select one of the controllers in the Steam client as the first controller using Shift+Tab. Then start the game using it, set the number of players to 1, and on the player select screen you have to press "H" on the keyboard to select Player 1. In the game, Player 1 is controlled by the keyboard.

**Comment by simifor** [comment]
@EpicureanGit if you have more than one controller connected, only the first controller can be player 1 in this game. It's the same on Windows, so that's just how the game was configured to work. A workaround is that when steam input is enabled, you get the option to change the controller order.

**Comment by EpicureanGit** [comment]
> @EpicureanGit if you have more than one controller connected, only the first controller can be player 1 in this game. It's the same on Windows, so that's just how the game was configured to work. A workaround is that when steam input is enabled, you get the option to change the controller order.

Thank you for the reply! I was trying to explain what happens with using "steam input enabled" and "changing controller" in my post. The game responds to my first controller until the player select screen where you pick the character you want to use. There the first controller magically becomes Player 2 and my keyboard becomes Player 1 with no way to change it. This is after setting the game to one player on the previous screen

I'm not sure where the game's input programming begins and Steam's input ends. It could be a game feature since it affects Windows as you pointed out. I just reported it. It is up to the Proton and Steam client developers to decide if it is something worth investigating on their end.

**Comment by simifor** [comment]
@EpicureanGit I may have misunderstood your original report. To make sure we're on the same page, I'll try to be as unambiguous as possible.

Scenario 1 - a single controller is connected: This controller can select player one as expected.
Scenario 2 - two or more controllers are connected: Let's say we have a xbox and a ps controller, the xbox controller is the first one and the playstation one is the second. In this scenario, the xbox controller can select player 1 as expected, but if the playstation controller is used, it will instead choose the second player - even when the game is configured for single player.

In scenario 2, steam input can be used to reorder the controllers and make the playstation controller the first one and use it to select player 1.

Are you unable to select player 1 with the controller that is recognized as the first one?

**Comment by EpicureanGit** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/3345#issuecomment-2289521097

In Scenario 2, I reorder my controllers so the one I am using is listed as the first one. I navigate through the menus with it. I reach the "Player Select" screen. At this point the controller I am using automatically becomes Player 2 and the keyboard becomes Player 1 from that point on in the game. I am unable to use controller 1 for Player 1 at this point on.

**Comment by waspennator** [comment]
Good news: the latest proton Experimental update that includes the new media source seems to make the boss cutscenes work finally.

Bad news: The audio is crackly as hell, noticed it a bit during the intro, then it got real noticable during Misuzus cutscene when I get blasted with ungodly static.

[steam-1049320.log](https://github.com/user-attachments/files/17499339/steam-1049320.log)

**Comment by waspennator** [comment]
Game seems to have finally been bumped down to unsupported, audio issues still present on current proton Experimental

**Comment by waspennator** [comment]
https://gitlab.winehq.org/wine/wine/-/merge_requests/7987

Guessing this pr should improve the cutscene audio situation

**Comment by waspennator** [comment]
Retested it now that it's hit proton Experimental bleeding edge, can confirm all the crackling and static is finally gone on my end during the intro and Mizusus boss scene. Once this hits regular experimental it should be enough to bump it out of unsupported

**Comment by kisak-valve** [comment]
River City Girls (Zero) VK_ERROR_OUT_OF_HOST_MEMORY

Issue transferred from https://github.com/ValveSoftware/gamescope/issues/1998.
@rijnhard posted on 2025-10-25T07:37:14:

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [x] The issue occurs on upstream gamescope without any modifications

### Current Behavior

Installed via heroic.

This was working perfectly about 7 months ago with no tweaks at all, but SteamOS updates and Proton updates have also happened since then. Trying different versions of Proton for the most part just changed the errors somewhat, but this was the most common and is on Proton-Experimental. 

Black screen after loading with Proton-experimental (not GE).

Older versions of Proton (only tested GE versions, including last known working) crash in different ways, but the same error on 10-8+.

### Steps To Reproduce

1. Launch via steam big picture with no special configuration (calls heroic to launch underneath). 

### Hardware information

```markdown
- Distro: SteamOS 3.7.15
- CPU: AMD Custom APU 0932
- GPU: AMD Custom GPU 0405
- Driver Version: Mesa 24.3.4
- Device: SteamDeck OLED 512GB
```

### Software information

```markdown
- Desktop environment: Steam Big Picture
- Session type: (default?)
- Gamescope version: (OS default)
- Gamescope launch command(s): 
- Heroic: 2.18.1 (flatpak)
```

### Which gamescope backends have the issue you are reporting?

- [ ] Wayland (default for nested gamescope)
- [ ] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

### Logging, screenshots, or anything else

* [general heroic logs](https://0x0.st/K22r.log) 
* [heroic RCG logs](https://0x0.st/K2eF.log)

**Comment by simifor** [comment]
@rijnhard I don't know if I'll be able to help you given that the steam version of the game works normally, but you should provide more information.

First off, you need to bring proton logs to have more information about what's going on with the launch of the game.
Secondly, you need to try with upstream proton because that's what this issue tracker is for. Additionally, proton 9 hasn't been updated this year, so if it worked then, it should work now.

**Comment by rijnhard** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/3345#issuecomment-3448906350

I will provide more info later today, like I said it was working perfectly, but getting the Gamescope out of host memory errors now and playing Proton version poker just changes the errors somewhat. I'm pretty sure it was working with 10.8 GE (about 7-4 months ago, but lots of updates have since happened). The logs provided are on official valve Proton Experimental.

**Comment by rijnhard** [comment]
Ironically as I finally get to this, it works on Proton-10, Proton-Experimental and GE-10.27 (there's been another steam update since my last update).

**Comment by metafarion** [comment]
I experienced the blank screen boss cutscenes described above on Proton 9.0-4.  Nvidia GTX 1080, driver 580.95.05.
Switching to Proton GE 10-28 solved it, and I haven't seen any other glitches.

**Comment by simifor** [comment]
just checked on deck and desktop and found that the video is working normally with both proton 10 and experimental. Note that some videos in this game need to be transcoded, if you have shader cache disabled this won't be available to you.
