### ISSUE TITLE
No games launch, button goes right back to "play" from launching.

### ISSUE THREAD

**Issue by Xenotta-Alt** [ValveSoftware/Proton#3859]
Hi!
I'm trying to run some games on Proton 5.0-7. However, I'm having some problems (and i've been dealing with this for almost two months)
Whenever I go to launch a game (on an NTFS drive, i have not tried on any other one as my SSD is too small), after the "Launching ___" pop-up closes, nothing happens and the "play" button goes green again.
I'm very confused as to what's happening, and as the games are not even launching I don't think I'll be able to capture any logs.
I've tried launching steam via a terminal, modified my fstab many times, but right now i'm just using Wine (which runs my processor at very high temps).

**Comment by Nocifer** [comment]
Have you tried completely uninstalling Proton and re-installing it? The only time I've experienced something like this, ended up being the result of Proton's binaries having lost their executable bit permission as a result of me moving them between drives.

Maybe your Proton is installed on that same NTFS drive? If so, maybe it's an issue with wrong permissions setup? Have you checked the instructions for NTFS at the [wiki](https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows)? NTFS on Linux is by default mounted as read and write only, which means Linux binaries like Proton can't be run from it because they lack the execute permission.

Also, do try to capture some Proton logs, doing so could verify if Proton isn't launching at all (e.g. due to permissions) or if it's launching but then crashing for some reason, and this could point you to the right direction.

**Comment by UltraBlackLinux** [comment]
When this happens, the game propably crashed - try out other versions

**Comment by CDAGaming** [comment]
I had this issue yesterday, though it was fixed via creating a symlink highlighted on the wiki, not sure if this might be the same issue.

**Comment by Xenotta-Alt** [comment]
I'll see. I've moved the games to an EXT4 partition I've just made, I'll reinstall proton and check

**Comment by domainzero** [comment]
> Hi!
> I'm trying to run some games on Proton 5.0-7. However, I'm having some problems (and i've been dealing with this for almost two months)
> Whenever I go to launch a game (on an NTFS drive, i have not tried on any other one as my SSD is too small), after the "Launching ___" pop-up closes, nothing happens and the "play" button goes green again.
> I'm very confused as to what's happening, and as the games are not even launching I don't think I'll be able to capture any logs.
> I've tried launching steam via a terminal, modified my fstab many times, but right now i'm just using Wine (which runs my processor at very high temps).

@Xenotta-Alt Did you mount the NTFS drive with your user and group IDs as described [here?](https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows)

**Comment by Xenotta-Alt** [comment]
> > Hi!
> > I'm trying to run some games on Proton 5.0-7. However, I'm having some problems (and i've been dealing with this for almost two months)
> > Whenever I go to launch a game (on an NTFS drive, i have not tried on any other one as my SSD is too small), after the "Launching ___" pop-up closes, nothing happens and the "play" button goes green again.
> > I'm very confused as to what's happening, and as the games are not even launching I don't think I'll be able to capture any logs.
> > I've tried launching steam via a terminal, modified my fstab many times, but right now i'm just using Wine (which runs my processor at very high temps).
> 
> @Xenotta-Alt Did you mount the NTFS drive with your user and group IDs as described [here?](https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows)

Yup, I did. I gave up on NTFS today and decided to make an EXT4 partition. Still having the same error. Installing an older version of Proton as we speak

**Comment by Xenotta-Alt** [comment]
Now I'm having an "invalid app configuration" error. I'll deal with it later as I have to go

**Comment by Xenotta-Alt** [comment]
The error is gone, but the issue still persists

**Comment by ZelphirKaltstahl** [comment]
+1

Cannot run any Proton requiring game, mostly they are worthless, sitting in my Steam library …

> I had this issue yesterday, though it was fixed via creating a symlink highlighted on the wiki, not sure if this might be the same issue.

@CDAGaming What wiki? And what symlink?

**Comment by CDAGaming** [comment]
@ZelphirKaltstahl In the [wiki](https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows) there is a second part to it relating to creating a Symlink to compatdata (At the bottom of the page). Although the reasoning on the wiki didn't define my exact circumstances, it did end up resolving my issue without any noticeable data loss.

**Comment by ZelphirKaltstahl** [comment]
@CDAGaming Hmmm, I wrote the "+1", because of the title of this issue and @Xenotta-Alt writing, that the error disappeared but the problem persists, so I assume, that the error is not necessarily about using NTFS partitions, but a more general issue with how Steam makes use of Proton. That issue seems to lie in how Steam makes the call to Proton and the game executables. I can start at least one game manually, by simply making the correct call myself, on command line. Only Steam cannot do it for some reason.

Games, which always worked for me since Proton was introduced, stopped working, like Age of Empires 2. Some of the games I cannot even start manually, because they now require being started from Steam, or else, they will complain that Steam needs to be started, even if Steam is actually running. One of such games is Age of Empires 2. Another game, which I can start manually, but also does not run when started via Steam, is Street Fighter 30th Anniversary Edition.

I do not actually use Steam on an NTFS partition, but natively on Ubuntu. I am not sure what in my case is the equivalent of the mounted drive for the symlink.
