### ISSUE TITLE
EA Origin crashes with several games

### ISSUE THREAD

**Issue by frostworx** [ValveSoftware/Proton#3937]
# Compatibility Report
- Name of the game with compatibility issues: Mirrors Edge Catalyst 
(with todays EA launch of several games I bought Unravel, Unravel2, Burnout Paradise Remastered and Mirrors Edge Catalyst. haven't tested Unravel2 yet, but very likely all have the same Origin crash.)
- Steam AppID of the game: 1233570
( also tested 1238080 and 1225560 )

## System Information
- GPU: GeForce RTX 2080
- Driver/LLVM version: nvidia 440.66.15
- Kernel version: 5.6.15-arch1-1
- Proton version: 5.0-7

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

[steam-1233570.log](https://github.com/ValveSoftware/Proton/files/4732188/steam-1233570.log)

## Symptoms 
when launching the game the origin launcher is installed (fine?) initially. after entering the creds (they are saved) the gui pops up multiple times with an unreadable (closes too fast) error and both  the launcher and the game quit/don't start

## Reproduction
install a (new released(?)) EA game using EA launcher/drm and try to launch the game

other notices:
origins own debug.log has multiple
WARNING:resource_bundle_qt.cpp(114)] locale_file_path.empty() for locale 
lines
I installed origin under lutris: it works and my 4 games above from steam are listed in my library. can't start a game though, as steam/proton wants to open its own origin instance. haven't checked lutris settings, but as it works there it looks like the issue could be workarounded with some additional tweak (protontricks maybe?)

edit: also tried a "beta" version which was offered from the origin installer - didn't change anything

**Comment by vjr2** [comment]
I can confirm to have the same issue, with Mirror's edge catalyst and dragon age inquisition, its like, the launcher loads and crashes many times

**Comment by t1764722** [comment]
Also none of the EA games on Steam are disclosing if they're using additional DRM on top of Origin (ie Denuvo). Some of the less scrupulous publishers will hide it in the EULA rather than put it on the Steam page but EA don't even do that.

I know that's not _strictly_ a Proton issue but certain revisions of Denuvo are known to cause issues with Proton and I don't know why EA are getting special treatment when it comes to DRM disclosure.

**Comment by parkerlreed** [comment]
The launcher comes up here (with Burnout) but throws up an error saying this install location cant be used and then exits.

**Comment by NTMan** [comment]
I confirm the issue: 
[steam-1233570.log](https://github.com/ValveSoftware/Proton/files/4734166/steam-1233570.log)

**Comment by frostworx** [comment]
just found 
```
  310    [2020-06-04 20:31:45.393]     Event     Origin::Escalation::IEscalationClient::quickEscalate                        584       Elevation requested.  UAC Reason: createFolderElevated (Z:\Program Files (x86)\Origin Games)
  311    [2020-06-04 20:31:45.476]     Event     Origin::Escalation::IEscalationClient::quickEscalate                        584       Elevation successful.  UAC Reason: createFolderElevated (Z:\Program Files (x86)\Origin Games)
**312    [2020-06-04 20:31:45.477]     Error     Origin::Escalation::IEscalationClient::evaluateEscalationResult             584       Escalation failure: kCommandErrorCommandFailed System Error: 3 Command: createDirectory UAC Reason: **createFolderElevated (Z:\Program Files (x86)\Origin Games)**
**313    [2020-06-04 20:31:47.146]     Error     Origin::Services::ProcessWin::waitForExit                                   2484      ProcessWin: 0xa00    Exit result: 0
```
in 
`./pfx/drive_c/users/steamuser/Local Settings/Application Data/Origin/Logs/Client_Log.txt`

which probably is the reason for the crash
edit:
no, it isn't - at least not directly. creating, chowning the dir in / didn't workaround the crash, also symlinking the game installation dir into that dir didn't change anything.

**Comment by JacoG-RH** [comment]
On my system (Manjaro/NVIDIA/Gnome/PaperWM), Mirror's Edge Catalyst did actually seem to open Origin, albeit with a blank content area, just the menus were visible. Not sure if it was missing wine-gecko or similar.

**Comment by screwylightbulb** [comment]
On my system (Manjaro/NVIDIA/Gnome/PaperWM), Mirror's Edge Catalyst did actually seem to open Origin, albeit with a blank content area, just the menus were visible. Not sure if it was missing wine-gecko or similar.

This seems like it should be a priority bug. What's the best way to debug this?

**Comment by NerosTie** [comment]
From PCGamingWiki, all games require Denuvo...

There is a repport for Need for Speed Heat (https://www.protondb.com/app/1222680) where there is no issue with Origin.

Why would it crash with some games and not others?

**Comment by VortexAcherontic** [comment]
Mirrors Edge is working for me just fine.
Proton: 5.8-GE-1-MF
Launch Option: PROTON_NO_ESYNC=1 %command%
OS: openSUSE Tumbleweed
GPU: NVidia GTX 1080 (440.86)
CPU: AMD Ryzen 7 1800X
RAM: 16GB

**Comment by vjr2** [comment]
> Mirrors Edge is working for me just fine.
> Proton: 5.8-GE-1-MF
> Launch Option: PROTON_NO_ESYNC=1 %command%
> OS: openSUSE Tumbleweed
> GPU: NVidia GTX 1080 (440.86)
> CPU: AMD Ryzen 7 1800X
> RAM: 16GB

You mean regular one or catalyst? Because I have this issue with Mirror's Catalyst and Dragon Age Inquisition. It's like origin is trying to attempt to install the game inside wine prefix, pretty weird

**Comment by lostpolaris** [comment]
Bump on the issue for NFS: HEAT

**Comment by VortexAcherontic** [comment]
> > Mirrors Edge is working for me just fine.
> > Proton: 5.8-GE-1-MF
> > Launch Option: PROTON_NO_ESYNC=1 %command%
> > OS: openSUSE Tumbleweed
> > GPU: NVidia GTX 1080 (440.86)
> > CPU: AMD Ryzen 7 1800X
> > RAM: 16GB
> 
> You mean regular one or catalyst? Because I have this issue with Mirror's Catalyst and Dragon Age Inquisition. It's like origin is trying to attempt to install the game inside wine prefix, pretty weird

I missed that I was talking about the classic Mirros Edge, you're right that one doesn use Origin as well NFS Undercover doesn't. My bad ^^"

**Comment by TheDunkShot** [comment]
Same issue as everyone else, running the game through _Wine Steam_ gave me an actual error message rather than closing all together. [pastebin](https://pastebin.com/mD07aM4Y)
Hoping for this issue to be resolved, hope that my pastebin would help anyone trying to figure this out.
EDIT: This error message came from the crysis 3 error program and not steam, (maybe origin.)
> Unhandled exception: page fault on read access to 0xffffffff in 32-bit code (0x7b428180)

**Comment by massatt212** [comment]
im getting infinite loading screen with Burnout Paradise, (with TKG Proton tho) normal Proton just crashes after they ask me to choose a default game folder to install games

**Comment by vjr2** [comment]
There are some people that says Mirror's edge catalyst actually works, but I don't know how to reproduce that outcome

**Comment by GottaSlay** [comment]
NFS: Rivals also has the same issue.

**Comment by gofman** [comment]
I've tested the EA Origin issue with "Mirror's Edge Catalyst" as an example and found the reason of failure. The temporary workaround which allowed me to start the game is deleting steamapps/compatdata/[game id]/pfx/drive_c/windows/system32\kernel32.dll in Steam Proton prefix (don't delete kernel32.dll.so in Proton files). Origin still shows the message that the "games cannot be installed in this folder", but launches the game regardless.

**Comment by NerosTie** [comment]
Nice! For Burnout Paradise Remastered, I had to delete/rename kernel32.dll in the **syswow64** folder. Unfortunately, the game crashes after the first logo... (also tested with wined3d, so it's probably not an issue with dxvk)

[steam-1238080.log](https://github.com/ValveSoftware/Proton/files/4748489/steam-1238080.log)

**Comment by kisak-valve** [comment]
Hello @NerosTie, please open a new compatibility report to track issues with that game.

That set aside, looks like a missing dependency: `err:module:load_so_dll failed to load .so lib "/run/media/neros/Kingston240/Steam/steamapps/common/Proton 5.0/dist/bin/../lib/wine/winegstreamer.dll.so": libffi.so.6: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type`

**Comment by pierovera** [comment]
As per Burnout Paradise Remastered, I had the same issue as @NerosTie . This WineHQ report might be relevant.

https://appdb.winehq.org/objectManager.php?sClass=version&iId=37441

I can't figure out how to pass options to the Origin launcher, I tried putting it in directly on Steam but it didn't seem to do anything.

[steam-1238080.log](https://github.com/ValveSoftware/Proton/files/4748644/steam-1238080.log)

**Comment by kisak-valve** [comment]
Hello @pierovera, your log has the same missing dependency: `err:module:load_so_dll failed to load .so lib "/home/piero/Media/Steam/steamapps/common/Proton 5.0/dist/bin/../lib/wine/winegstreamer.dll.so": libffi.so.6: cannot open shared object file: No such file or directory`

**Comment by pierovera** [comment]
@kisak-valve It seems to be that whatever called libffi was built against an older version (6, instead of 7). I installed the older version (both 64 and 32 bit, not sure which one it was). It no longer displays that error, but the game still crashes. Log attached.

[steam-1238080.log](https://github.com/ValveSoftware/Proton/files/4748750/steam-1238080.log)

**Comment by frostworx** [comment]
nice find @gofman this doesn't fix it entirely for me though.
origin stays open and I can configure its settings, so it looks working, but I get an additional requester
complaining that ME: C couldn't be activated on this computer because the EA servers couldn't be reached.
clean wineprefix didn't fix this.

**Comment by frostworx** [comment]
looks like all games using origin fail with an error like this (after the kernel32.dll remove workaround):
`<tr style='style:none; background:#FFFFFF' class='Err'><td>4</td><td id='logEntryTimeStampCol'>[06:11:14 GMT]</td><td id='logEntryLogTypeCol'>Error</td><td id='logEntryClassCol'></td><td id='logEntryFunctionCol'></td><td>Problem encountered obtaining license. Server code 408, OS error code 12002</td></tr>`
which is logged in
pfx/drive_c/ProgramData/Origin/Logs/$gamename_[0-9]_OnlineActivation_Log.html

I was able to start unravel (with removed kernel32.dll) (got stuck with a black screen, but this is a different issue) initially, but it failed later (even with clean wineprefix), so I guess EA/origin might have blocked access to the game later (maybe that's the 408 above?).

probably not related to the "main crash", but as there are dxvk warnings and errors for the origin launcher these logs might be interesting as well:
[EALink_d3d9.log](https://github.com/ValveSoftware/Proton/files/4750308/EALink_d3d9.log)
[EALink_d3d11.log](https://github.com/ValveSoftware/Proton/files/4750309/EALink_d3d11.log)
[Origin_d3d9.log](https://github.com/ValveSoftware/Proton/files/4750310/Origin_d3d9.log)
[Origin_d3d11.log](https://github.com/ValveSoftware/Proton/files/4750311/Origin_d3d11.log)

**Comment by dantob** [comment]
I can get Burnout Paradise Remastered slightly further by..
- removing ....../Steam/steamapps/compatdata/1238080/pfx/drive_c/windows/syswow64/kernel32.dll
- right click game in origin launcher and select game properties. go to advanced launch options and add -skipvideos

Game gets to 'press any key to continue' and crashes shortly after
[steam-1238080.log](https://github.com/ValveSoftware/Proton/files/4750843/steam-1238080.log)

**Comment by gofman** [comment]
Error 408 is request timeout, could it be the servers are plainly not available? I tested again now, "Mirror's Edge Catalyst" still works. I also tested with Jedi: Fallen Order, started just fine for me   with deleted dll. I don't know if that makes any difference, but I have those games on Steam account, not Origin.

**Comment by frostworx** [comment]
heh, the reason for 408 was my pihole. as it worked before I guess it messed up the ea dns cache. I can confirm Mirrors Edge Catalyst works fine with @gofman s workaround. sorry for the confusion, this is both the first time I use origin and the first time I have pihole problems ever...

**Comment by massatt212** [comment]
I use tkg proton 5.10 and the game is stuck at loading screen, so even if u get it to boot u ain't getting pass that infinite boot loop, burnout paradise

**Comment by XaeroVincent** [comment]
I'd like to point out that at least Mirror's Edge Catalyst will run with vanilla Wine 5.10 when using Steam via Wine. Only with staging, tkg, proton, and proton-ge does Origin crash when invoked by Steam (at least for me). Other Origin games purchased from Steam might also work with vanilla / unmodified Wine 5.10?

Perhaps some change to the kernel32.dll code in the staging and proton patches is the culprit?

https://www.reddit.com/r/linux_gaming/comments/gzfuhz/mirrors_edge_catalyst_steam_version_workaround/

**Comment by TheDunkShot** [comment]
Crysis 3 works great with deleting the kernel32.dll in SYSWOW64!

**Comment by GottaSlay** [comment]
NFS Rivals launches after deleting kernel32.dll, I didn't have much time to do playtesting.

**Comment by frostworx** [comment]
https://github.com/ValveSoftware/Proton/releases/tag/proton-5.0-9

**"Fix running games that require the EA Origin client."**

haven't tested it yet

**Comment by kisak-valve** [comment]
Indeed, please retest this issue with Proton 5.0-9. Any issues with individual games past the Origin crash reported should be tracked separately, but please use one compatibility report per unofficially supported game title.

**Comment by frostworx** [comment]
tried Mirror's Edge Catalyst with a clean wineprefix and proton-5.0-9:
after the installation of the dependencies including origin
the launch hung with

[steam-1233570.log](https://github.com/ValveSoftware/Proton/files/4766326/steam-1233570.log)

I restarted steam and tried again, and the game started without any errors!
thanks a lot for the quick fix!

**Comment by NerosTie** [comment]
Tested with Burnout Paradise Remastered and a new prefix and Origin doesn't crash anymore!
However, Origin still shows an error saying this install location cant be used.

**Comment by frostworx** [comment]
I can confirm that Unravel gets past the origin-problem with proton-5.0-9, but the non related blackscreen issue remains: https://github.com/ValveSoftware/Proton/issues/3961

**Comment by polarina** [comment]
The changes introduced with 5.0-9 breaks Origin's auto-updater -- the update fails to install. Origin also got a new mandatory update today; as a result, I'm unable to launch Mirror's Edge Catalyst.

The workaround is the same as with 5.0-8, delete kernel32.dll from system32 and syswow64.

**Comment by frostworx** [comment]
@polarina , tried with a clean wineprefix?
https://github.com/ValveSoftware/Proton/issues/3937#issuecomment-642829376

**Comment by tuxtergames** [comment]
> Crysis 3 works great with deleting the kernel32.dll in SYSWOW64!

Need for Speed Rivals work with this, with some lags with proton 5.0.9

**Comment by XaeroVincent** [comment]
I can confirm that Proton 5.0.9 fixes Mirror's Edge Catalyst for me. Also DXVK is working much better with Proton and I'm getting 60 FPS, unlike with vanilla Wine 5.10 which stuck at 25 FPS.

Hopefully this gets backported into Proton-GE.

**Comment by XaeroVincent** [comment]
@polarina 

You mean Origin's auto updater actually worked?

I have never gotten the auto updater it to ever work with any version/variant of Wine.

This is how I do it:

https://github.com/DrDoctor13/wine-origin-updater/blob/master/updateorigin.sh

Just pass the specific Origin game's Proton prefix directory to the script via WINEPREFIX. Works well for me.

**Comment by dantob** [comment]
Burnout Paradise Remastered gets past the origin launcher without workarounds, thanks! (game still doesn't work, but there's a new bug for that here https://github.com/ValveSoftware/Proton/issues/3960)

Origin updater worked for me second try, first try failed

**Comment by tuxtergames** [comment]
> > Crysis 3 works great with deleting the kernel32.dll in SYSWOW64!
> 
> Need for Speed Rivals work with this, with some lags with proton 5.0.9

To stop lags, don't disable Esync, I've played for 2 hours last night

**Comment by Martexte** [comment]
With the latest Steam Proton release (version 5.0.9), it's launched perfectly (Mirror's Edge Catalyst)! Thank you, and good work to all the devs!

Although, I did see some errors being mentioned and the way the game properly launched afterwards:

1. First installation and first startup, the Origin launcher didn't launch and closed immediately.
2. At second startup, Steam downloaded and installed the Vulkan shaders. Then, Origin launcher was able to launch.

Some minor inconveniences as well, but not something that'll affect the gaming experience; though can be considered for any future fixes:

1. Unable to copy and paste text in the Origin launcher.
2. Mentions something about unable to find the folder of the game, pops up file explorer, but still manages to run the game anyway.

**Comment by kakra** [comment]
For me, the Origin Client installs, but doesn't launch or closes immediately. During the process, it opens some amount of small tiny windows with logos and a window that looks like a context menu.

After a second start, it seems to get further, it shows a tray icon, then it complains it failed to connect EA servers and couldn't activate the game for my account.

So probably similar to @SixteenAlpha tho my games don't launch at all, they fail to activate. I never ran Origin in Windows, so the games need to activate for my account the first time. Maybe that's the difference?

I tried both the stable and the beta Origin Client. I also bought multiple games during the EA launch and hope this gets fixed soon.

Maybe this is another SSL problem in Wine?

**Update:** I checked my account via Origin Web UI and the games have been activated. So at least that part of the activation worked. Still, I get an error that the game could not be activated.

**Comment by tuxtergames** [comment]
Origin Client update today and don't finish instalation, anybody get it?

**Comment by tuxtergames** [comment]
> Origin Client update today and don't finish instalation, anybody get it?

Every time that the Origin client update, just delete kernel32.dll from system32 and syswow64 again to  install update.

**Comment by NerosTie** [comment]
@tuxtergames Origin didn't finished installation on my side too. But all I had to do was quit and restart, and it was fine. No need to delete kernel32.dll.

**Comment by Arucard1983** [comment]
I just brought Crysis 3 to run on my two computers, where one runs Ubuntu 20.04 and another Debian 10. The funny thing is the fact that all Crysis games fails to run on Debian due to an activation error (including on Origin, which said that failed to connect to EA servers.)
 On Ubuntu, all games was activated, and runs fine.
 Related to Uplay, both machines activates fine.

**Comment by Martexte** [comment]
@kakra 
> So probably similar to @SixteenAlpha tho my games don't launch at all, they fail to activate. I never ran Origin in Windows, so the games need to activate for my account the first time. Maybe that's the difference?

Funnily enough, the launcher and the game ran fine without any activation failures. Keeping in mind, I had to create an Origin account after installing Mirror's Edge; I have never touched Origin on Windows.

Just for some additional info, I am running Steam (installed with pamac) on a Manjaro system.

**Comment by mijofa** [comment]
I can't get Mirror's Edge Catalyst to run with the latest version of Proton (5.0-9), even with deleting kernel32.dll and after the latest update to Origin Launcher.
The Origin launcher starts, sometimes gives me a warning about not being able to save games in the configured directory, regardless of whether I cancel that or choos another directory, it tries to launch Mirror's Edge Catalyst, at which point I get an error stating "We are unable to connect to EA servers to activate Mirror's Edge Catalyst on this computer using your account. Please try again later"

I tried increasing Proton/Wine's debug output, and it's not helped shed any light on the matter

**Comment by WaldoTheRanger** [comment]
I also can't get it to run.
whenever I try to start, origin setup blips on for a second, appears to complete, and then everything hangs for a long time doing nothing. even stopping the game takes a long time to register. so long that's it's faster to restart steam.

I have also tried deleting kernel32, though I'm not sure if I'm finding the correct folder. how do you find out which game Id corresponds to each game?

**Comment by kakra** [comment]
> how do you find out which game Id corresponds to each game?

It would be very cool if Steam showed this in the info drawer of the library. Until it does, use https://protondb.com/

**Comment by kakra** [comment]
> > So probably similar to @SixteenAlpha tho my games don't launch at all, they fail to activate. I never ran Origin in Windows, so the games need to activate for my account the first time. Maybe that's the difference?
> 
> Funnily enough, the launcher and the game ran fine without any activation failures. Keeping in mind, I had to create an Origin account after installing Mirror's Edge; I have never touched Origin on Windows.
> 
> Just for some additional info, I am running Steam (installed with pamac) on a Manjaro system.

Yeah, I think that's probably some SSL issue with the libs from the Steam runtime or using system-native libs. The thing is, I need to use "prefer system libs" otherwise many games fail to run because the runtime linker deps are missing in the Steam runtime (or are just incompatible as Debian-based distros do some strange thing with libcurl and libssl-gnutls).

**Comment by WaldoTheRanger** [comment]
Update. I deleted the Kernel32 from both places in all my games (3 of them :), and it still doesn't work.
I'll check protondb in the future though.

Also I'm using a fully updated manjaro install if that makes a difference.

**Comment by kisak-valve** [comment]
Closing as fixed in Proton 5.0-9.

To reiterate https://github.com/ValveSoftware/Proton/issues/3937#issuecomment-642827197, any issues with individual games past the Origin crash that was tracked here should be tracked separately. Please search for existing compatibility reports before opening a new one because we are using one report per unofficially supported game title.

**Comment by joeldacuma** [comment]
my game is crashing and unable to launch Dragon Age Inquisition with error log WARNING:resource_bundle_qt.cpp(114)] locale_file_path.empty() for locale

**Comment by intelligentgaming** [comment]
Origin client is extremely temperamental at launching games, and when it eventually works, great, until you exit the game and then it crashes on exit, in this case with Dragon Age Inquisition. 

Ubuntu 21.04
Ryzen 5 3600
nVidia GTX 1080 - 470 drivers.

Tried with latest versions of Proton and Proton-GE.

**Comment by kewinshah25** [comment]
I am having the same issue with FIFA 22. Not able to find any solution online. Even the DPI fix doesn't solve this issue.

**Comment by devmasterbob** [comment]
> I am having the same issue with FIFA 22. Not able to find any solution online. Even the DPI fix doesn't solve this issue.

Same here with FIFA 22. Any solution?

**Comment by kewinshah25** [comment]
I think I did find the issue. It was related to Windows defender. You might have a notification while launching FIFA 22 in the notification bar. Click on it and try to disable something. ( I actually forgot how it goes because it was a long time ago )

**Comment by massatt212** [comment]
When I play the game in Wayland it works in xorg it freezes my PC.

**Comment by PercentBoat4164** [comment]
Just for general awareness, I encountered a problem with installing Battlefront II (2017) from Steam through Proton. It would hang on the OriginThinSetup step displaying only a black screen. I was overcame this bug and sucessfully installed and ran Battlefront II (2017) by downgrading my graphics drivers. It failed on NVIDIA's driver version 515.43.04, and worked on 510.73.05. I don't know why the newer drivers would break the installer. If anyone does please share. Perhaps we can spare someone the hours of pain I went through before I thought to try the older drivers.

Ubuntu 22.04
Ryzen 5 3600
NVIDIA RTX 2060 SUPER
GE-Proton7-20

**Comment by damo901** [comment]
i cant get nfs heat working at all. im running nobara os 
my problem is origin keeps wanting to be installed every time i try launch the game

**Comment by centrivical2** [comment]
Those of us that enjoy the Battlefield series whether its multiplayer or solo campaigns, but dislike the EA app & Origin launchers makes me question is there a way to bypass it?

My cousin gave me Battlefield Hardline over the Thanksgiving holiday and after installing it I was unable to play because he just gave me the disc, he didn't hold on to the case meaning there's no registration key number.

**Comment by jiiiijiij** [comment]
Anyone know how to fix the problem. I'm stuck to :((
