### ISSUE TITLE
Burnout Paradise Remastered (1238080)

### ISSUE THREAD

**Issue by frostworx** [ValveSoftware/Proton#3960]
# Compatibility Report
- Name of the game with compatibility issues: Burnout Paradise Remastered
- Steam AppID of the game: 1238080

## System Information
- GPU: RTX 2080
- Driver/LLVM version: nvidia-vulkan-440.66.15
- Kernel version: 5.6.15-arch1-1
- Proton version: 5.0-8

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

[steam-1238080.log](https://github.com/ValveSoftware/Proton/files/4753263/steam-1238080.log)

## Symptoms 
The game fails to start. this has multiple sources
1) origin fails to start correctly and crashes: https://github.com/ValveSoftware/Proton/issues/3937
( current workaround is to remove kernel32.dll in the games wineprefix in either system32 or syswow64 - depends on the game)
2) the game still would crash because of the intro video.
this can be workarounded by adding "-skipvideos" parameter to the game from within origin:
see post from above issue 3937 for the workound:
https://github.com/ValveSoftware/Proton/issues/3937#issuecomment-641121544

with both workarounds you see a loading screen which crashes as well
maybe changing some settings in
.....1238080/pfx/drive_c/users/steamuser/Local Settings/Application Data/Criterion Games/Burnout Paradise Remastered/*.ini
could fix that as well

**Comment by frostworx** [comment]
a steam log from another user:
https://github.com/ValveSoftware/Proton/issues/3937#issuecomment-640875228

**Comment by kisak-valve** [comment]
Hello @frostworx, looks like this game would benefit from support for Media Foundation maturing.

More specifically: `fixme:mfplat:MFTEnumEx ({d6c02d4b-6833-45b4-971a-05a4b04bab91}, 51, 21F6FB9C, 21F6FBBC, 21F6FB90, 21F6FB8C): stub` lead to an access violation and `wine: Unhandled page fault on read access to 00000000 at address 058C5B9A (thread 0bb4), starting debugger...`

**Comment by frostworx** [comment]
hi @kisak-valve
thought so too, but the known dirty hack didn't fix it (maybe I applied it at the wrong testing state though). No big deal for me personally, pretty sure the game is almost the same as the ultimate box version. just wanted to open a "proper" bug report

**Comment by frostworx** [comment]
hm, I'm afraid I was wrong with the "-skipvideos" commandline parameter working on steam. so likely the change directly in origin is the only option:
https://github.com/ValveSoftware/Proton/issues/3937#issuecomment-641121544
updating initial post as well...

**Comment by frostworx** [comment]
yes, with skipvideos correctly applied you get further. it crashes when you select "start game" in the main title. attached is the new log
[steam-1238080.log](https://github.com/ValveSoftware/Proton/files/4753805/steam-1238080.log)

sorry for the noise...

**Comment by Berinth** [comment]
How do you get origin open long enough to set launch options for a game in it? When I click play in steam, it just railroads in to opening origin, then the game and crashing.

**Comment by frostworx** [comment]
there might be an easier way, but I used PROTON_DUMP_DEBUG_COMMANDS to get a runfile, and adjusted it to just launch the launcher instead of the game.

**Comment by kisak-valve** [comment]
Burnout Paradise Remaster can't run in Debian 10.4

Issue transferred from https://github.com/ValveSoftware/Proton/issues/4012.
@SandHilt posted on 2020-06-22T04:02:48:

# Compatibility Report
- Name of the game with compatibility issues: Burnout Paradise Remaster Edition
- Steam AppID of the game: 1238080

## System Information
- GPU: GTX 1050 Ti 
- Driver/LLVM version: nvidia 418.113 
- Kernel version: 4.19.0-9-amd64 
- Link to full system information report as [Gist](https://gist.github.com/): [Link](https://gist.github.com/SandHilt/777c8b4de520443bd282418fdd891e13)
- Proton version: 5.0-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.



## Symptoms 
Origin install but can't open game like this guys https://www.protondb.com/app/1238080

## Reproduction
1, Install origin setup.
2. Log in origin.
3. Try start (game appear installed) but can't open.

## Extra
- This guy appear can run the game via lutris: https://youtu.be/dezNtc9ZNhs
- I try this method without success. https://lutris.net/games/burnout-paradise-remastered/

**Comment by HavoxYT** [comment]
After trying the -skipvideos parameter, the game still gets stuck on the loading screen and never loads. The newer proton versions fix the origin crash but the game still refuses to start

**Comment by dantob** [comment]
Here is a log from proton 5.0-9 with `WINEDEBUG="+timestamp,+pid,+tid,+seh,+debugstr,+module" %command%`

`-skipvideos` is set in origin launcher, game gets passed the loading screen, and up to `press and key to start/continue`

(Log is 88Mb uncompressed)
[steam-1238080.log.tar.gz](https://github.com/ValveSoftware/Proton/files/4861791/steam-1238080.log.tar.gz)

**Comment by qsniyg** [comment]
@dantob Maybe I'm looking at this wrong, but I can't really find what the cause of the crash is from the log:

<details>
<summary>Relevant (I think) section of the log</summary>

```
3203.974:075c:07b8:trace:module:map_image mapped PE file at 0x96a0000-0x96a4000
3203.974:075c:07b8:trace:module:map_image mapping section .text at 0x96a1000 off 200 size e8c virt 1000 flags 60000020
3203.974:075c:07b8:trace:module:map_image mapping section .data at 0x96a2000 off 1200 size e0 virt 1000 flags c0000040
3203.974:075c:07b8:trace:module:map_image clearing 0x96a2200 - 0x96a3000
3203.974:075c:07b8:trace:module:map_image mapping section .reloc at 0x96a3000 off 1400 size 8 virt 1000 flags 42000040
3203.974:075c:07b8:trace:module:map_image clearing 0x96a3200 - 0x96a4000
3203.974:075c:07b8:trace:module:LdrGetDllHandle L"C:\\windows\\system32\\steamclient.dll" -> (nil) (load path L"C:\\Program Files (x86)\\Origin;C:\\windows\\system32;C:\\windows\\system;C:\\windows;C:\\Program Files (x86)\\Steam;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem;C:\\windows\\system32\\WindowsPowershell\\v1.0")
3203.974:075c:07b8:trace:module:GetModuleFileNameW L"C:\\Program Files (x86)\\Origin\\Origin.exe"
3203.974:0030:07ec:trace:module:alloc_thread_tls thread 07ec slot 0: 8/0 bytes at 0x5dd070
3203.974:0030:07ec:trace:module:MODULE_InitDLL (0x7f61c2b00000 L"msvcrt.dll",THREAD_ATTACH,(nil)) - CALL
3203.974:0030:07ec:trace:module:MODULE_InitDLL (0x7f61c2b00000,THREAD_ATTACH,(nil)) - RETURN 1
3203.974:0030:07ec:trace:module:MODULE_InitDLL (0x6fbc0000 L"rpcrt4.dll",THREAD_ATTACH,(nil)) - CALL
3203.974:0030:07ec:trace:module:MODULE_InitDLL (0x6fbc0000,THREAD_ATTACH,(nil)) - RETURN 1
3203.974:075c:0760:trace:module:map_image mapped PE file at 0x96a0000-0x96a4000
3203.974:075c:0760:trace:module:map_image mapping section .text at 0x96a1000 off 200 size e8c virt 1000 flags 60000020
3203.974:075c:0760:trace:module:map_image mapping section .data at 0x96a2000 off 1200 size e0 virt 1000 flags c0000040
3203.974:075c:0760:trace:module:map_image clearing 0x96a2200 - 0x96a3000
3203.974:075c:0760:trace:module:map_image mapping section .reloc at 0x96a3000 off 1400 size 8 virt 1000 flags 42000040
3203.974:075c:0760:trace:module:map_image clearing 0x96a3200 - 0x96a4000
3203.974:075c:0760:trace:module:LdrGetDllHandle L"C:\\windows\\system32\\steamclient.dll" -> (nil) (load path L"C:\\Program Files (x86)\\Origin;C:\\windows\\system32;C:\\windows\\system;C:\\windows;C:\\Program Files (x86)\\Steam;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem;C:\\windows\\system32\\WindowsPowershell\\v1.0")
3203.974:075c:0760:trace:module:LdrGetDllHandle L"ole32.dll" -> 0x65200000 (load path L"C:\\Program Files (x86)\\Origin;C:\\windows\\system32;C:\\windows\\system;C:\\windows;C:\\Program Files (x86)\\Steam;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem;C:\\windows\\system32\\WindowsPowershell\\v1.0")
3203.975:075c:0760:trace:module:map_image mapped PE file at 0x96a0000-0x96a4000
3203.975:075c:0760:trace:module:map_image mapping section .text at 0x96a1000 off 200 size e8c virt 1000 flags 60000020
3203.975:075c:0760:trace:module:map_image mapping section .data at 0x96a2000 off 1200 size e0 virt 1000 flags c0000040
3203.975:075c:0760:trace:module:map_image clearing 0x96a2200 - 0x96a3000
3203.975:075c:0760:trace:module:map_image mapping section .reloc at 0x96a3000 off 1400 size 8 virt 1000 flags 42000040
3203.975:075c:0760:trace:module:map_image clearing 0x96a3200 - 0x96a4000
3203.975:075c:0760:trace:module:LdrGetDllHandle L"C:\\windows\\system32\\steamclient.dll" -> (nil) (load path L"C:\\Program Files (x86)\\Origin;C:\\windows\\system32;C:\\windows\\system;C:\\windows;C:\\Program Files (x86)\\Steam;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem;C:\\windows\\system32\\WindowsPowershell\\v1.0")
3203.975:075c:0760:trace:module:GetModuleFileNameW L"C:\\windows\\system32\\ole32.dll"
3203.975:075c:0760:trace:seh:raise_exception code=c0000005 flags=0 addr=0x7abe005 ip=07abe005 tid=0760
3203.975:075c:0760:trace:seh:raise_exception  info[0]=00000000
3203.975:075c:0760:trace:seh:raise_exception  info[1]=0bba1020
3203.975:075c:0760:trace:seh:raise_exception  eax=00101000 ebx=00042340 ecx=fffff000 edx=65200178 esi=001024c8 edi=0baa0000
3203.975:075c:0760:trace:seh:raise_exception  ebp=0031df00 esp=0031deb4 cs=0023 ds=002b es=002b fs=0063 gs=006b flags=00010287
```

</details>

Would you mind sending a full log? (`WINEDEBUG=+all,-heap`) Hopefully it will shine more light on this

**Comment by dantob** [comment]
I created a new prefix and can no longer get origin to 'wait' long enough to add the `-skipvideos` option (so the game doesn't make it passed the into video atm)

`WINEDEBUG=+all,-heap %command%` just crashes right away and wont even launch origin

here's what it logged though (157Mb uncompressed)
[steam-1238080.log.tar.gz](https://github.com/ValveSoftware/Proton/files/4997192/steam-1238080.log.tar.gz)

**Comment by Galcian79** [comment]
With Proton 5.9-GE-5-ST i managed to get past the loading screen. Then i was presented with a mouse pointer and a black screen. No sound.
[steam-1238080.log](https://github.com/ValveSoftware/Proton/files/5177888/steam-1238080.log)

**Comment by shyam-s00** [comment]
I managed to make this work via Lutris and I have Origin version of the game. You need to have `-skipvideos` option and copy your save game post initial intro video (may be copy from a windows machine if you have one). Apparently -skipvideo option doesn't skip the intro video and the game crashes.

**Comment by Galcian79** [comment]
> I managed to make this work via Lutris and I have Origin version of the game. You need to have `-skipvideos` option and copy your save game post initial intro video (may be copy from a windows machine if you have one). Apparently -skipvideo option doesn't skip the intro video and the game crashes.

Every solution that entails borrowing a savefile from Windows is not a solution at all. Still i'm glad to hear that mf is the only issue with the game.

**Comment by gigabz666** [comment]
I've noticed recently that the game has stopped working with any version of proton newer than 5.13-6. It gets to the loading screen with the spinning icon but then freezes and crashes to desktop before it gets to the "start" screen.

**Comment by kisak-valve** [comment]
Hello @gigabz666, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by gigabz666** [comment]
> Hello @gigabz666, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

https://gist.github.com/gigabz666/3dd732807d0d684f24a919d7ac3e710e
[steam-1238080.log](https://github.com/ValveSoftware/Proton/files/6282303/steam-1238080.log)

Hope this helps. I guess two things I should add. I try to run native and also I run the games from an NVME SSD rather than my home directory. I don't know if that's possibly causing issues.

**Comment by alasky17** [comment]
@gigabz666 I'm getting the same crash with 5.13-6 as with 6.3-2.  Could you confirm if there is a Proton version that is currently working, and if so, which version?  Otherwise, it is possible the game updated in a way that broke with Proton :/

**Comment by gigabz666** [comment]
> @gigabz666 I'm getting the same crash with 5.13-6 as with 6.3-2. Could you confirm if there is a Proton version that is currently working, and if so, which version? Otherwise, it is possible the game updated in a way that broke with Proton :/

The game still works fine for me on 5.13-6. I have --skipvideos set within Origin and I also had a save file in place from when I briefly played it on Windows (although funnily, last time I tried to play it on Windows it won't run, so win for Linux). It also crashes if I have OBS open and it's using my webcams so there is also some weird thing going on with webcams too.

**Comment by alasky17** [comment]
@gigabz666 I think --skipvideos is probably the key.  Do you have a trick for getting that into the origin settings before origin closes?

**Comment by gigabz666** [comment]
@alasky17 There is probably a better method to this but I wasn't able to find it or figure it out but I stumbled across this post on the steamcommunity forums that I was able to work with which let me change options within Origin before actually running the game.

https://steamcommunity.com/app/221410/discussions/0/3104638636521148019/

**Comment by gigabz666** [comment]
Just wanted to add that the game now runs again with the latest version of Proton Experimental.

**Comment by NerosTie** [comment]
> Just wanted to add that the game now runs again with the latest version of Proton Experimental.

With `-skipvideos` within Origin, I guess?

edit: tested and it crashes on the first screen with "Loading".

**Comment by gigabz666** [comment]
> > Just wanted to add that the game now runs again with the latest version of Proton Experimental.
> 
> With `-skipvideos` within Origin, I guess?
> 
> edit: tested and it crashes on the first screen with "Loading".

Correct, I hadn't changed any of my options in Origin so I still had that flag.

**Comment by manhnt9** [comment]
The game runs with Proton Experimental or Proton 6.3 but crashes at the Loading screen after a while. I tried to add a save file downloaded from [here](https://www.protondb.com/app/1238080#POVg3HG5IP) but still didn't work. Could someone provide another Save file so I can test?

**Comment by manhnt9** [comment]
Finally runs !

![image](https://user-images.githubusercontent.com/11463928/122678998-3cba8380-d213-11eb-9672-2500120c70b1.png)

To verify, run Steam via Terminal, run the game and see output.

If having `libv4l2: error setting pixformat: Device or resource busy`

Unplug your webcam !

This should be the game's bug itself preventing it to load if webcam is detected (not Proton's bug).

**Comment by gbdrbob** [comment]
I got the game working on my Steam Deck by adding -skipvideos to the launch options in the EA App beta ([installed within steam as a non-steam app](https://github.com/kageurufu/steamdeck-tricks/blob/main/ea-app.md)). On first launch for a new player even with skipvideos configured the game plays an unskippable video that crashes the game (black screen with white mouse pointer, no way to progress). That can be worked around by using a save game file from just after the video has played, as described [here](https://gist.github.com/Decclo/da097b504ccbc61514926ae2d96350ef#file-profile-burnoutparadisesave).

I can only play by launching the game from within the EA App. When trying to launch the game exe directly it seems to ignore the -skipvideos setting in the EA Play app and I get a hang on a blank screen.

**Comment by mdsitton** [comment]
I would like to note you will have issues with doing the -skipvideos workaround if you're on a steamdeck and you have the game installed to the microsd card. Origin will refuse to find the game files. Reinstalling the game on the internal storage allows you to go through the process as expected.

Finally once you get past the video issue I've found that online doesn't work, as soon as you try to drop into an online lobby the game freezes. Audio keeps playing but it seems like the main game thread just gets frozen.

**Comment by gbdrbob** [comment]
> Finally once you get past the video issue I've found that online doesn't work, as soon as you try to drop into an online lobby the game freezes. Audio keeps playing but it seems like the main game thread just gets frozen.

I can confirm this. I've also once had it crash on just opening the quick menu for on-line play (D-Pad right in the default controller layout). Other times the menu load and I've been able to view leaderboards, but actually dropping into a game results in a frozen screen with audio continuing to play. This is with GE- Proton-7-24 and Proton Experimental

**Comment by gbdrbob** [comment]
> I would like to note you will have issues with doing the -skipvideos workaround if you're on a steamdeck and you have the game installed to the microsd card.

This isn't the issue I had, game is installed on the internal SSD, however -skipvideos only works when launching the game manually from within the EA App (with -skipvideos set as an "Advanced Launch Option"). Launching BurnoutPR.exe directly with -skipvideos set as a launch option in the Steam shortcut settings doesn't work.

**Comment by Jademalo** [comment]
Slightly easier way of getting `-skipvideos` where it needs to be;

Go into `compatdata/1238080/pfx/drive_c/users/steamuser/AppData/Roaming/Origin/`, and there should be a file `local_xxxxxx.xml`, with a string of numbers that I believe corresponds to your user ID.

Edit this file, and add 
```
  <Setting key="GameCommandLineArguments" type="10" value="#//Origin.OFR.50.0002541_-skipvideos"/>
``` 
to line 14, directly above `HotKeyString`. This is where Origin saves it's launch args, so you can just edit it in manually there. This saves having to mess around launching origin with a different shortcut to set the arg.

**Comment by K0bin** [comment]
[burnout_bt_all.txt](https://github.com/ValveSoftware/Proton/files/10052043/burnout_bt_all.txt)

Backtrace of all threads of the hang before the menu.

**Comment by gbdrbob** [comment]
According to reports [here](https://gist.github.com/Decclo/da097b504ccbc61514926ae2d96350ef) users with a Steam licence to the game cannot set launch arguments within the EA app, which means the -skipvideos workaround is unavailable to them.

Users with a non-steam licence can successfully run the game by setting the launch argument within the EA app. 

There are also reports that setting -skipvideos as a launch option in Steam works under Windows for the _Steam_ version of the game, 

However I have found that on my Windows 10 system with a non-steam version launch options set within Steam are not passed to the exe. So it's unclear to me whether the problem lies with the EA app or Proton.

**Comment by andres-asm** [comment]
Yes I can confirm this.
Thing is, when you run the non-steam version, you can add the skip videos on the EA app
When you run the steam version, that option is missing on the EA app

But for some reason the parameter isn't forwarded from steam to the game.

I tried many things, including mfplat to no avail.

**Comment by frederikheld** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/3960#issuecomment-864568160

I have exactly the same error - but how would I unplug my camera on a laptop. It's built in :-P Is there any way to make it "invisible" to the game via launch options?

**Comment by ArtyIF** [comment]
> > Replying to [#3960 (comment)](https://github.com/ValveSoftware/Proton/issues/3960#issuecomment-864568160)
> 
> I have exactly the same error - but how would I unplug my camera on a laptop. It's built in :-P Is there any way to make it "invisible" to the game via launch options?

Try using [this Ask Ubuntu answer](https://askubuntu.com/a/166821). Should work on other Linux distros, too, both modprobe and uvcvideo seem common.

**Comment by ArtyIF** [comment]
Disabling the camera with `sudo modprobe -r uvcvideo` made the game crash after the Loading screen faded out as opposed of it doing it before that. Installing Media Foundation with protontricks did nothing. I can't access launch options on the new EA App, unfortunately.

**Comment by gbdrbob** [comment]
> I can't access launch options on the new EA App, unfortunately.

If it’s the steam version the only known workaround is to rename BurnoutPR.exe (e.g to `BurnoutPR.orig.exe`), create a batch file that calls it with the -skipvideos option (i.e `start E:\steamapps\common\BurnoutPR\BurnoutPR.orig.exe -skipvideos`) and then convert the batch file to an exe which you name `BurnoutPR.exe`

Full details in the [comments here](https://gist.github.com/Decclo/da097b504ccbc61514926ae2d96350ef) . You’ll also need the save file from there to skip an otherwise unskippable video that plays when you start the game for the first time. 

Online play will still be broken but you should be able to get in-game for single player.

**Comment by hilts-vaughan** [comment]
I can confirm that trying to join a game online still causes the main thread to completely halt. It does not seem like blacklisting the module helps.

**Comment by QueDemais** [comment]
Hello, here the game does not start, it is not possible to play since I bought the game.
![1](https://github.com/ValveSoftware/Proton/assets/141298203/be1a720c-eb6e-4ed2-aadb-71a7422ce62f)
![2](https://github.com/ValveSoftware/Proton/assets/141298203/12c783c0-45a6-4531-976b-2d86ac837ca8)
![3](https://github.com/ValveSoftware/Proton/assets/141298203/f0930b46-176d-4c42-8635-453dc4e80724)
![4](https://github.com/ValveSoftware/Proton/assets/141298203/d3668949-bf57-472e-b522-506c83aab11e)
![5](https://github.com/ValveSoftware/Proton/assets/141298203/084f8157-7a42-42d5-86b7-20f6498fdb71)


when I started steam through the terminal, it generated all of these.

Kubuntu lts
proton 8.0-3
i3 1115G4

Thank you very much in advance

**Comment by ghost** [comment]
Hello, I used the option to verify the authenticity of files, in all games, a while after going to proton rc.

 In Burnout Paradise Remastered (EA Play) the main menu is not reaching, and the Ea play app is freezing, the screens have no information, only once it appeared correctly for login, etc. 
And Steam always restarts after the game does not open

The EA application also does not appear on the desktop.

When using the delete proton files option, in the big picture, restart the system.  Check the authenticity of the files, restart the system, using the big picture, and then try to start the game, the app does not install and the game does not start. (Kubuntu 23.04, wayland)

 Proton rc 8.0-4
Kubuntu lts
Steam .deb

👍😄

**Comment by X-m7** [comment]
The changelog for the latest Proton Experimental update says that this game is now playable, but for me it still crashes if I don't use any tricks to skip videos or whatever, so what's supposed to be improved with the latest update? Or is it referring to a different game?

My system has a Ryzen 7 6800H APU, with both a Radeon 680M iGPU and a Radeon RX 6650M dGPU, running Arch Linux with kernel 6.5.7 and Mesa 23.2.1. Using either GPU (switching using the DRI_PRIME environment variable) doesn't change anything.

I'd attach the log file but it's over 600MB of `trace:unwind:dump_unwind_info` type stuff, even zipped it's still 44MB (which is above the 25MB size limit GitHub has).

**Comment by ArtyIF** [comment]
> I'd attach the log file but it's over 600MB of `trace:unwind:dump_unwind_info` type stuff, even zipped it's still 44MB (which is above the 25MB size limit GitHub has).

You can probably upload it to something like Google Drive and link it here. Or maybe pastebin or a similar service, but idk if they support 600+ MB files

**Comment by K0bin** [comment]
@X-m7 The bug that was blocking it until now has been fixed. The problem is that the game is running out of address space now. It does work on the Steam Deck though, presumably because the smaller screen resolution requires less memory for the video decoding.

**Comment by X-m7** [comment]
Oh yeah, I just got around to trying it on my Deck, even after having wiped the savegame I was able to see the intro videos and get into the gameplay part, neat!

It did crash once after dropping the graphics settings down and applying it, but otherwise it worked for the short time I tried it.

**Comment by Bitwolfies** [comment]
Doesn't work on my deck unfortunately, and I'm using bleeding edge.

**Comment by X-m7** [comment]
For what it's worth my Deck is running SteamOS 3.5.1 preview, with no CryoUtilities or anything like that (I don't even have a root password set on it), and the Proton version selected was already Experimental so I didn't have to change it myself.

**Comment by Bitwolfies** [comment]
Got on my Desktop and tested it, works but I had to unplug my index as it has a V4l2 camera which crashes it during the loading screen, so that bug still exists.

**Comment by ArtyIF** [comment]
On my desktop PC (R5 2600, RX 570 8GB, 16GB RAM, Fedora 39, single 1920x1080 display) at least the singleplayer works well as long as you unplug the camera. However, on my laptop (MSI Modern 14 C12M-233XRU: i3-1215U, no discrete GPU, 8GB RAM, Fedora 39, single 1920x1080 display) the EA App outright refuses to install. The installation window pops up for a second and disappears, and no other window pops up again, after which other dependencies are installed and the game refuses to start. It might be me using mobile internet instead of home Wi-Fi, though. Both setups were using the latest Proton Experimental version.

UPD: tested on my laptop on my home Wi-Fi, the app still doesn't install.

**Comment by hifron** [comment]
Maybe D9 driver problem with no native D9 hw on modern intel gpu...

**Comment by ArtyIF** [comment]
What's D9?

**Comment by ArtyIF** [comment]
> Maybe D9 driver problem with no native D9 hw on modern intel gpu...

If by D9 you mean DirectX 9, it all gets converted to Vulkan to run on non-Windows platforms anyway. Also, not sure how the EA App installer is affected by the lack of DX9, it's a separate thing entirely.

**Comment by gbdrbob** [comment]
On my Steam deck with the latest Proton experimental, online play seems to be fixed. Whereas previously It would hang, now I can enter a game (I’ve tested freeburn mode so far) and play with others.

**Comment by ghost** [comment]
Hello, leaving my feedback:
Here the game is not working. The Ea app does not install.
If you do a direct and clean installation of the latest Proton 8.0-4, the app does not install.
If it is for rc 8.0-5 or experimental, the app does not install.
But if you go to Proton 7, try to start the game, the app installs it, but there is no information on the screen, and the app is not created on the desktop.
If you switch to Proton 8, the app shows information, opens the game on the first home screen, and then closes the game, and during the first screen of the game, if you configure the ea app with alt+tab, the app closes along with the game.
And if you return to the experimental version, without uninstalling Protons 7, 8, the game goes to the first initial screen, and then closes.

I use ufw firewall, in the standard that comes

Kubuntu, kde plasma, 23.10, wayland
Intel i3 1115G4
4GB RAM, 32GB swap
btrfs
ptbr utf8 abnt2
generic usb joystick

Thank you very much in advance

**Comment by ArtyIF** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/3960#issuecomment-1871504156

I have the same issue on my laptop with Intel integrated graphics and no discrete GPU, but I don't have it on my desktop with a discrete AMD GPU. Might be Intel-related?

**Comment by ghost** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/3960#issuecomment-1872059548

Hi, it could be. It could be some library on Proton, to open the ea app, Burnout paradise remastered on onboards, perhaps. 😅

**Comment by NerosTie** [comment]
Can you try with Proton-GE?

You also need to unplug your webcam when you launch the game.

**Comment by hifron** [comment]
@kisak-valve If there is need to unplug a webcam, Proton needs settings for this or patch for game, its weird fix

**Comment by K0bin** [comment]
@hifron You also need to unplug your webcam on Windows. It's a game bug, not an issue with Proton.

**Comment by giantplaceholder** [comment]
Hi all.

As of right now, Burnout Paradise is crashing 100% of time after 5-10 seconds of displaying initial load screen because of EA launcher app's overlay being funky.

The only solution is to disable overlay manually via launcher's config file editing: https://www.protondb.com/app/1238080#BbaTyoZHkG. 

The issue is reproducible as of this morning on Proton Experimental (bleeding-edge branch) on Manjaro Linux, as well as on an unmodded Steam Deck as well.

**Comment by waspennator** [comment]
I can also confirm the same on my oled deck, game launches up fine now until the first loading screen, then after that, it seems to crash.

[steam-1238080.log](https://github.com/user-attachments/files/16099816/steam-1238080.log)

**Comment by gofman** [comment]
This should hopefully work better with the [bleeding-edge] branch of Proton Experimental (not in Proton Experimental default branch yet).

**Comment by AJuujarvi** [comment]
@giantplaceholder @waspennator This should now be working with the Experimental release that was just shipped.

**Comment by waspennator** [comment]
Tested it on my end, game now gets past the first loading screen with the ea overlay on.

**Comment by giantplaceholder** [comment]
> @giantplaceholder @waspennator This should now be working with the Experimental release that was just shipped.

I can confirm that this is fixed as of now. Works on Deck out of the box.

**Comment by Z3em** [comment]
Still crashes on first loading screen for me
[Uploading steam-1238080.log…]()

**Comment by K0bin** [comment]
@Z3em Make sure you don't have a webcam connected. The game crashes when it detects a webcam. That's a game bug that happens on Windows as well.

**Comment by waspennator** [comment]
> Still crashes on first loading screen for me Uploading steam-1238080.log…

I think you accidentally posted before your log finished uploading. I can't view it on my end.

**Comment by Z3em** [comment]
> @Z3em Make sure you don't have a webcam connected. The game crashes when it detects a webcam. That's a game bug that happens on Windows as well.

Yes, that was the issue. After disabling webcam the game launched normally and I played it for a few hours without any issues, although I haven't tested the multiplayer yet.

**Comment by giantplaceholder** [comment]
> > @Z3em Make sure you don't have a webcam connected. The game crashes when it detects a webcam. That's a game bug that happens on Windows as well.
> 
> Yes, that was the issue. After disabling webcam the game launched normally and I played it for a few hours without any issues, although I haven't tested the multiplayer yet.

Multiplayer should be working out of the box, I've tried it today.

**Comment by Leandro599** [comment]
[steam-1238080.log](https://github.com/user-attachments/files/16972711/steam-1238080.log)

**Comment by Leandro599** [comment]
[steam-1238080.log](https://github.com/user-attachments/files/16995886/steam-1238080.log)
Debian 12

**Comment by Leandro599** [comment]
[steam-1238080.log](https://github.com/user-attachments/files/17029912/steam-1238080.log)

**Comment by LazyHatGuy** [comment]
The game was working and then it stopped. Tried many different version of Proton and can't get it to run again

[steam-1238080.log](https://github.com/user-attachments/files/21456562/steam-1238080.log)
