### ISSUE TITLE
All my Games running at way too fast speed in Proton Experimental

### ISSUE THREAD

**Issue by TimestaticYT** [ValveSoftware/Proton#4719]
# Compatibility Report
- Name of the game with compatibility issues: Rocket League, Among Us, Pummel Party (These are the only ones I tested so far and all have this issue)
- Steam AppID of the game: 252950, 945360, 880940

## System Information
- GPU: GTX 1080 TI
- Driver/LLVM version: 4.6.0 NVIDIA 460.56
- Kernel version: 5.11
- Link to full system information report as [Gist](https://gist.github.com/TimestaticYT/4b2d4af28a2cc5053d46ead31013b1f9):
- Proton version: Proton Experimental

## I confirm:
- [ ] that I have checked whether there are updates for my system available.

## Symptoms 
The games are running at a way too fast speed

## Reproduction
Open a game with the Proton Experimental version

**Comment by pizzamig** [comment]
Same here. With Path Of Exile the login doesn't work anymore, Linux 5.11.
It seems something broken with timers.

**Comment by rgehlen** [comment]
Confirmed, Path of Exile login screen makes this very obvious.

**Comment by josepapaianni** [comment]
+1

**Comment by rbernon** [comment]
Thanks for the report, I'm aware of the problem and it should be fixed soon. As far as I know this will only happen on Intel CPUs.

**Comment by phush0** [comment]
Confirm same effect on Intel CPU and Nvidia, also DXVK is completely broken, no game starts with experimental but all start with 6.3-1

**Comment by aeikum** [comment]
Hey everyone. We've just pushed a new build live on the Experimental app which should fix this (version experimental-6.3-20210402). Please retest after updating to confirm it's fixed.

**Comment by kodatarule** [comment]
Now the games don't work anymore 
[steam-10090.log](https://github.com/ValveSoftware/Proton/files/6249968/steam-10090.log)
[steam-257420.log](https://github.com/ValveSoftware/Proton/files/6249969/steam-257420.log)

**Comment by pizzamig** [comment]
Updated and the I can confirm this issue (about speed and timers) is solved.
There are other rendering problems introduced with the new version (also present in 6.3) that are more game specific and should be targeted in a new specific issue. Thanks for the fast new release, tho.

**Comment by rbernon** [comment]
Yes it still happens in some cases, sorry. We'll push a fix soon to use the same code path for all CPU models and try to fix it properly later. Thanks for the reports.

**Comment by kodatarule** [comment]
I tested two more games both hang on the launch after the proton-experimental update.
[steam-782330.log](https://github.com/ValveSoftware/Proton/files/6250007/steam-782330.log)
[steam-302510.log](https://github.com/ValveSoftware/Proton/files/6250008/steam-302510.log)

**Comment by aeikum** [comment]
A new build is up. Please update and retest.

**Comment by kodatarule** [comment]
Yeah now everything's working properly, thanks for the fast update

**Comment by josepapaianni** [comment]
Everything seems to be fixed with the last update, thanks for the quick response!

**Comment by Vladislavuz** [comment]
+

**Comment by aeikum** [comment]
Thanks for flying Proton Experimental!

**Comment by zarkone** [comment]
try to press TURBO
