### ISSUE TITLE
Occasional failure to launch games (... primarily UE4 engine), fixed by reboot

### ISSUE THREAD

**Issue by V1del** [ValveSoftware/Proton#5068]
## System Information
- GPU: RX6900 XT
- Driver/LLVM version: Mesa 21.1.6  LLVM 12.0.1
- Kernel version: 5.13.9-zen1-1-zen Arch packages
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/V1del/37fbea6c181ced09f2129352e5c89880
- Proton version: 6.3-5

This is probably one of the weirdest issues I've ever ran into. I have occasional failures to launch technically supported titles like Street Fighter V,Guilty Gear Strive or AoE II DE. When the issue occurs I can't get the games to run no matter to which proton version I switch or how often I delete their prefixes. Without doing any change on my installed software all of these will eventually work on subsequent reboots and during that session will continue working as expected. So it's basically a toss up on whether the  games will work on any given boot. 

Some things I've tried:
- Disabling Shader Pre-Caching (... have to do that anyways, as there seems to be a bug in the used mesa version which leads to errors on the amdgpu kernel module parser that basically breaks the entire Xorg session)
- Manually removing DXVK caches and mesa/radv in ~/.cache
- Restarting steam a few times

Some other things of potential relevance:
- Games in question are shared with Windows and thus on a NTFS drive, I'm aware of the implications of that and have read and applied the suggestion in the wiki. But I've ran with that kind of setup for as long as Proton is a thing and while I've acquired a new computer and new HW in the meantime, this has never been an issue or was a logically explainable breakage if anything happened due to that.
- I have Nintendo WiiU GC Adapter connected to the computer and I'll occasionally use wii-u-gc-adapter to enable them as normal joystick but generally keep that disabled. I notice that steam tries to access them in some way via a dmesg message reading: 
 
```
[12972.229749] hid-generic 0003:057E:0337.0009: pid 19056 passed too short report
[34453.742699] hid-generic 0003:057E:0337.0009: pid 40098 passed too short report
[34666.321828] hid-generic 0003:057E:0337.0009: pid 41672 passed too short report
[34758.929581] hid-generic 0003:057E:0337.0009: pid 42742 passed too short report
[35069.324003] hid-generic 0003:057E:0337.0009: pid 43934 passed too short report
[35076.396020] hid-generic 0003:057E:0337.0009: pid 44266 passed too short report
[35078.416563] hid-generic 0003:057E:0337.0009: pid 44300 passed too short report
[36554.269713] hid-generic 0003:057E:0337.0009: pid 50169 passed too short report
[36561.349207] hid-generic 0003:057E:0337.0009: pid 50534 passed too short report
[36625.821023] hid-generic 0003:057E:0337.0009: pid 51161 passed too short report
[36632.936279] hid-generic 0003:057E:0337.0009: pid 51536 passed too short report
```

but unplugging them during an erroneous situation doesn't make a difference, nor does having them plugged in during the working setup.
- Native games and normal wine work normally. Not all Proton games seem to be affected, from the set I've currently installed, Hades is an example of a game that works regardless.

Attached is a PROTON_LOG=1 of a working and a broken run of SFV respectively.

[steam-310950-working.log](https://github.com/ValveSoftware/Proton/files/6983864/steam-310950-working.log)
[steam-310950-broken.log](https://github.com/ValveSoftware/Proton/files/6983866/steam-broken-310950.log)

**Comment by NyaomiDEV** [comment]
It does not only happen with UE4 games and in my system the problem persists between reboots.

Yakuza 4 Remastered can spawn the fullscreen window but it loops afterwards. (for those watching and wondering how I got that to work, originally, you have to re-encode the startup cutscene or swap it out with the one from Yakuza 3 btw)

[steam-1105500.log.gz](https://github.com/ValveSoftware/Proton/files/6985260/steam-1105500.log.gz)

This is on Artix Linux, by the way, running on those specs: https://gist.github.com/AryToNeX/d23a1cedb94e5e8c3dd3451bad5ac5e4

Bet my ass it has to do with Arch having bleeding edge packages; vulkan-icd-loader did update at around the same time this issue started on my machine.

**Comment by V1del** [comment]
I don't get any window at all, and I somewhat doubt that it's graphics related. And if it consistently doesn't work, then it's very likely you do not have the same issue.

**Comment by NyaomiDEV** [comment]
> I don't get any window at all, and I somewhat doubt that it's graphics related. And if it consistently doesn't work, then it's very likely you do not have the same issue.

@V1del I believe it is the same issue though. UE4 games crash without spawning a window, exactly like you pointed out. Also, I wiped off my entire Steam installation and games and began from scratch (after a reboot) and those games worked again for two, three days, then they stopped working again, which again, it may suggest we have the same issue.

**Comment by V1del** [comment]
Ah yeah that does sound samey, it's seriously weird, right now everything is fine again here, for now

**Comment by NyaomiDEV** [comment]
> Ah yeah that does sound samey, it's seriously weird, right now everything is fine again here, for now

I noticed that too! Today Yakuza 4 started fine...

**Comment by jarrard** [comment]
(ARCH repo) I can only get amdvlk driver working atm. 
Radeon vulkan driver has all sorts of problems, from games saying no dx11 device to some games having limited resolution options or inability to click anything due to incorrect window-space configuration (mouse pointer seems to be clicking elsewhere).

As for NTFS issues, well I've been through that with xanmod and ntfs3. Newer sub release kernels should fix most the issues (I'm using xxxx-10 release atm)

UPDATE: It's possible I stumbled upon a different Steam UI bug which breaks proton version selection thus everything was installing old proton versions regardless of selection. (not 100% sure that was it tho)

UPDATE: I fixed my issues, was related to corrupt files somewhere and amdvlk giving me issues all of a sudden (I switched to amdgpu-pro as a alternative for select games). I can't be %100 sure this was my issue but everything is working again..

**Comment by JokerGermany** [comment]
Same Problem here WITHOUT USING NTFS.
Sometimes it can be fixes by a Steam restart, sometimes a reboot and sometimes Voodoo after hours of restarting steam and rebooting.
It's a really nasty bug...

Would be great if you could activate in Steam throwing error messages...

(native games still work)

Your system information

    Steam client version (build number or date): Jul 20 2021, at 22:25:57
    Distribution (e.g. Ubuntu): Ubuntu Mate 20.04
    Opted into Steam client beta?: Problem occurs with both
    Have you checked for system updates?: yes

Sample Proton_Log Output:
```
======================
Proton: 1624629470 proton-6.3-5
SteamGameId: 252950
Command: ['/home/jokergermany/.steam/steam/steamapps/common/rocketleague/Binaries/Win64/RocketLeague.exe']
Options: {'forcelgadd'}
depot: 0.20210723.18
pressure-vessel: 0.20210722.0
scripts: v0.20210722.0-0-gb142f90
soldier: 0.20210719.0 soldier 0.20210719.0
======================
```
I hope this don't occur, when i have a circuit match...

The problem didn't occur on every game.
Prominence Poker and Rocket League isn't working, Witch it works...

**Comment by JokerGermany** [comment]
Workarround:
Delete the compatdata directory of the game.
(Don't forget to save changes you made or game related things like savegames...)

**Comment by V1del** [comment]
That was one of the first things I tried and it didn't work which is why I
think this issue is so weird, and if it was some inherent corruption in the
prefix it shouldn't spontaneously decide to work again

**Comment by NyaomiDEV** [comment]
> Workarround:
> Delete the compatdata directory of the game.
> (Don't forget to save changes you made or game related things like savegames...)

This is, like, the ABC of Proton games troubleshooting. We did it, it did not work. I went all my way to wipe the entire Steam installation and reinstall it, and the problem persists.

**Comment by jarrard** [comment]
> This is, like, the ABC of Proton games troubleshooting.

You'd be surprised at how many people don't even do this. Its worth a try before reporting a issue.
Valve need to make it a steam play option so its easier for people to do. Some people get lost with the compatdata folder and its ID system.

**Comment by NyaomiDEV** [comment]
In the hopes to be more useful, I report here some of my tests done with Guilty Gear Strive:
- With Proton Experimental, it does not work
- With Proton 6.3 RC, it does not work
- Trying to disable the Steam Runtime did not help with the issue
- The game doesn't work using AMDVLK nor using RADV
- Trying custom Proton versions (like GloriousEggroll) does not work
- DXVK logs are always empty (zero bytes)
- The game writes no logs to its logs folder

I suspected it to have something to do with the Steam Runtime; while this may also hold true, it does seem more to be a graphics driver issue (eg. the Vulkan driver having problems of some sort?)

**Comment by jarrard** [comment]
For ARCH this should cover most things. Be VERY sure you don't use AMDVLK package, it will cause issues.

Sync:
sudo pacman -Scc
sudo pacman -Syy

Dependencies: 
sudo pacman -S wine-staging giflib lib32-giflib libpng lib32-libpng libldap lib32-libldap gnutls lib32-gnutls \
mpg123 lib32-mpg123 openal lib32-openal v4l-utils lib32-v4l-utils libpulse lib32-libpulse libgpg-error \
lib32-libgpg-error alsa-plugins lib32-alsa-plugins alsa-lib lib32-alsa-lib libjpeg-turbo lib32-libjpeg-turbo \
sqlite lib32-sqlite libxcomposite lib32-libxcomposite libxinerama lib32-libgcrypt libgcrypt lib32-libxinerama \
ncurses lib32-ncurses opencl-icd-loader lib32-opencl-icd-loader libxslt lib32-libxslt libva lib32-libva gtk3 \
lib32-gtk3 gst-plugins-base-libs lib32-gst-plugins-base-libs vulkan-icd-loader lib32-vulkan-icd-loader

AMDGPU users:
sudo pacman -S lib32-gnutls lib32-libldap lib32-libgpg-error lib32-sqlite lib32-libpulse lib32-alsa-plugins
for amd graphics: sudo pacman -S lib32-mesa vulkan-radeon lib32-vulkan-radeon vulkan-icd-loader lib32-vulkan-icd-loader mesa

I use this following package for amdgpu-pro which doesn't c onflict with radv, to use it you just use the ICD loader. I'm told its the windows vulkan driver...

https://github.com/Frogging-Family/amdgpu-pro-vulkan-only

If your using a different distro then you'll need to figure out the package names for said distro. You can also install the lutris-wine-meta package that checks/pulls in dependencies like the above.

**Comment by kisak-valve** [comment]
Hello @jarrard, Proton 5.13 and newer runs inside the Steam Linux Runtime - Soldier container environment. With Proton 6.3 being the focus of this issue report, all of those dependencies don't make sense *except* for the suggestions directly involving the graphics stack.

Advice for Lutris does not unconditionally apply to Proton.

**Comment by jarrard** [comment]
Well I use Steam-Native which I do believe depends on system dependencies, at least some. If he's using Steam runtime then try native.

**Comment by kisak-valve** [comment]
Arch's `steam-native` script disables the LD_* style steam runtime (scout) that Steam itself runs in. This is not (and can't be) supported by Valve, and also is completely separate from the `Steam Linux Runtime - Soldier` container environment that Proton is run inside.

**Comment by jarrard** [comment]
Ok fair enough; I'm not having any issues thought :)

**Comment by NyaomiDEV** [comment]
> Ok fair enough; I'm not having any issues thought :)

This contributes nothing to the issue at hand. We can safely assume it has to do with AMD graphics cards, as no one on Nvidia (even personal friends on Arch and derivatives) have this issue as of now.

I tried `steam-native`, however that only makes the launcher work with the system libraries and it has no relevance to this issue (of course it did not work).

All those dependencies you listed are not necessary and anyway I have them installed.

**Comment by jarrard** [comment]
> All those dependencies you listed are not necessary and anyway I have them installed.

Then feel tree to remove them all... Fortunately I listed them in a easy to digest way so you can just reverse the command. 
I've removed the suggestion since I don't want to be yelled at over breaking peoples system.

**Comment by NyaomiDEV** [comment]
Tried to reinstall Steam Runtime Soldier, and it did not fix the issue either.

This is getting more and more depressing day after day...

**Comment by jarrard** [comment]
Try a LIVE Linux distro of your choice, install steam and drivers and test in a clean environment. 
(use a fast usbpen and be sure its  LIVE build or changes after reboot won't save)

Also some people install steam into a container like flatpak in order to keep the gaming stuff separated from their system. I've never done it but I hear its a good idea as when you get major issues like this, you can rule out your current linux install as being the problem.

**Comment by V1del** [comment]
Thanks for the suggestion. But again - this is pretty important to why this so strange - both of us can - without a single change on our installed environment/general system or any adjustment with anything that's remotely related to steam, fix the issue by rebooting. It's just a 50/50 chance whether it will work on the next boot. There's as far as we can tell, nothing inherently wrong with our environments.

**Comment by NyaomiDEV** [comment]
> Try a LIVE Linux distro of your choice, install steam and drivers and test in a clean environment.
> (use a fast usbpen and be sure its LIVE build or changes after reboot won't save)

The only really close live system I can think of is Manjaro Linux; but again, is that a thing you want to do while debugging a software? It doesn't give you any clues on what's going on. Plus, a live installation generally contains older software that is known to work, so the odds of that live kernel working with Steam Proton games are pretty high.

> Also some people install steam into a container like flatpak in order to keep the gaming stuff separated from their system. I've never done it but I hear its a good idea as when you get major issues like this, you can rule out your current linux install as being the problem.

This is probably worth looking at; but I do not know to which extent this might help us in finding out the cause.

@V1del would you mind trying the LTS kernel? I'd do it myself, but my configuration right now is far from ideal to do that kinda stuff

**Comment by NyaomiDEV** [comment]
@V1del I think it is the NTFS partition failing on us.... moved an UE4 game (GGST) to the root filesystem (ext4) and it worked.

OR

it can be an error with externally mounted partitions at all. Who knows?

(For context I did symlink compatdata to the ext4 compatdata folder and the game did not run; plus, I think that Tekken 7 still running on Proton 3.16 is really odd as it should've crashed and it indeed crashes if you force any other version of Proton)

**Comment by jarrard** [comment]
Yeah except Joker said he wasn't using NTFS. 
I've already dealt with the ntfs issue several times. Also be sure your symlinks for compatdata aren't broken. 

Using NTFS3 driver atm. (paragon)

**Comment by V1del** [comment]
A NTFS induced prefix breakage  doesn't randomly decide to fix itself (these can happen, but after e.g.  a chkdsk   from a Windows run, which could delete the windows incompatible filenames for example, I haven't booted Windows in a couple weeks this shouldn't be the case here) 

It feels like this is some cache somewhere, that potentially gets invalidated under not yet clear terms

**Comment by NyaomiDEV** [comment]
> A NTFS induced prefix breakage doesn't randomly decide to fix itself (these can happen, but after e.g. a chkdsk from a Windows run, which could delete the windows incompatible filenames for example, I haven't booted Windows in a couple weeks this shouldn't be the case here)
> 
> It feels like this is some cache somewhere, that potentially gets invalidated under not yet clear terms

I just think that the mere fact that ntfs-3g kinda works is already a blessing. I look forward to moving my library to another filesystem which can be used by both systems reliably.

We just need plug and play ext4 compatibility on Microsoft's side. A shame it still hasn't happened.

EDIT: As @jarrard nonchalantly said, the ntfs3 driver from Paragon is indeed working (lol?)

**Comment by V1del** [comment]
hmm... seems definitely related, somehow. Based on what we've talked here I just tried to remount the ntfs partition and it came right back up. Which is still weird but better than a full reboot. Race condition putting it into a slightly weird state if mounted during boot? Every other access works without issue from what I can tell. Might give paragons ntfs3 a shot as well, I didn't really actively consider it yet because I never had an issue with ntfs-3g

**Comment by jarrard** [comment]
Yeah. However I was advised to boot into windows and perform a disk check & fix on my NTFS drives by xanmod dude, and lo and behold there were mismatch errors. 

Currently I mount my NTFS3 drives (note this is not fuse but paragon driver) with the below options. Some are to increase windows filesystem compatibility, others like big_writes or noatime improve performance. 

But I don't think the below would help you in your situation unless you have a read-write issue or the USER ID does not match the drive permissions (which is why I had uid and gid stated below).

noatime,inherit,windows_names,big_writes,streams_interface=windows,norecover,uid=1000,gid=1000,rw,exec,umask=000 0 0,x-gvfs-show

There is a paragon ntfs3 dkms driver you can install which should inject it into most recent kernel releases. Xanmod kernels come with it already.

**Comment by NyaomiDEV** [comment]
> noatime,inherit,windows_names,big_writes,streams_interface=windows,norecover,uid=1000,gid=1000,rw,exec,umask=000 0 0,x-gvfs-show

`windows_names` is not supported in ntfs3 afaik

**Comment by jarrard** [comment]
Yeah, but I left it there as it causes no error I don't think. Some may also be system level flags and not driver related?

**Comment by NyaomiDEV** [comment]
> Yeah, but I left it there as it causes no error I don't think. Some may also be system level flags and not driver related?

Nope, it is a `ntfs-3g` feature not found in `ntfs3`; but to be clear, Windows is totally fine even if you create files with names that only comply with POSIX standards. Some apps on Windows can crash or get very confused, though.

**Comment by ipr** [comment]
Regarding the UE4 engine, I've found one game (We Happy Few) where display does not update when game has Vsync ON and it is running on second screen of a dual screen setup. Turning Vsync OFF in game makes display update correctly when on second screen. This happens on Gnome, but various games have similar issue on KDE as well.

**Comment by ryliejamesthomas** [comment]
I've just run into this same issue with Rocket League. I'm not using NTFS, but am using AMD.
