### ISSUE TITLE
Back 4 Blood (924970)

### ISSUE THREAD

**Issue by vercingetorx** [ValveSoftware/Proton#5206]
# Compatibility Report
- Name of the game with compatibility issues: Back 4 Blood
- Steam AppID of the game: 924970

## System Information
- GPU: nvidia geforce gtx 1070
- Driver/LLVM version: nvidia 470.63.01
- Kernel version: 5.11.0-37-generic
- Link to full system information report as [Gist](https://gist.github.com/xioren/099160bd3ff701530ca340033ace5896):
- Proton version: Experimental / 6.3-7

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 

The game hangs at the loading screen.

## Reproduction
Start the game with either experimental or 6.3-7.

## Note
There is an abandoned issue for the beta, but not for the full game.
[steam-924970.log](https://github.com/ValveSoftware/Proton/files/7306678/steam-924970.log)

**Comment by vercingetorx** [comment]
After today's Steam update rolling back some changes, the game now crashes with a "fatal error" at the splash screen.

**Comment by vercingetorx** [comment]
Incidentally the GE version of Proton now works again after the steam update; albeit with constant server disconnects.

**Comment by christoph-k** [comment]
Same issue here. Freeze on loading screen with 6.3.7 and experimental.
With GE the tutorial seems to run fine but playing online fails. Maybe EAC issues?
Distro: Ubuntu 20.04 / CPU: AMD Ryzen 5 2600 / GPU: Radeon RX 570

**Comment by xsellier** [comment]
Works well with [Proton GE](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/6.19-GE-2), but I keep getting disconnected when trying to play online. Seems to be a EAC related issue.

I can still play offline with bots, but it is a very meh for me.

**Comment by xsellier** [comment]
Hey,

I don't own the game anymore, so I cannot test it, I noticed on steamdb that there is a command to launch B4B without EAC, do you guys mind try it out please?
( https://steamdb.info/app/924970/config/ )

Does the binary `Gobi/Binaries/Win64/Back4Blood.exe` exists?

**Comment by BuyMyMojo** [comment]
experimental still has freezing issue and EAC support is still not enabled on B4B's side

**Comment by urbenlegend** [comment]
Now that EAC support is enabled, I can confirm that joining a multiplayer game works. However, the in-game chat seems to keep disconnecting. There are a lot of "lost connection with chat server" messages that pop up in the game. Not sure if that's a Proton issue or a B4B issue though.

**Comment by soulchainer** [comment]
I also can confirm that now EAC support works... but game doesn't detect any controller, so unplayable for me (forces you to play only with keyboard).

Tried with (all wired):

- PS5 official controller
- Blackfire Wired Pro controller (Nintendo Switch layout)
- PowerA XBox controller (purchased just to check if it was a controller issue, will need to refund also this controller, as the controller is not the issue here).

Al controllers works perfectly fine with my other games ran with Proton.
Tried with Proton Experimental, 7.0-1,  proton-ge-custom in Garuda Linux (based on Arch Linux).
Same thing happens for «Midnight: Ghost hunt».

**Comment by nightsky30** [comment]
I'm now getting errors which state my game is in violation of anti-cheat and online games are not available. This game was working very well with proton last week :/

EDIT: Last game load I received a file error that probably contributed to the anti-cheat error. Restarted the game, and suddenly everything is fine again. :man_shrugging:

**Comment by bernharl** [comment]
Anti cheat seems to not work for me anymore. I get the error shown in the screenshot I attached.
![screenshot_2022-06-26_21-15-58_846428440](https://user-images.githubusercontent.com/42568221/175830323-e0ed3cd1-1579-43a9-a16e-64d5d4037f6e.png)

EDIT: I also attached the proton log from PROTON_LOG=1 
[steam-924970.log](https://github.com/ValveSoftware/Proton/files/8987358/steam-924970.log)

**Comment by kisak-valve** [comment]
UI element from one game showing up in a completely different game

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5970.
@nightsky30 posted on 2022-07-05T16:03:19:

Back 4 Blood (924970) #5206
World of Warships (552990) #333
Proton Version: 6.3-8

I'm seeing a skill icon/image/texture/something from World of Warships inside the UI of Back4Blood. It appears in the upper left corner. This seems to happen intermittently, and I'm not sure what causes it. But I haven't even played World of Warships recently. It has been weeks or months since playing World of Warships, and the image still shows up every once in a while and persists in Back4Blood the entire game.

### 30 May 2022
![Screenshot_2022-05-30_10-44-53](https://user-images.githubusercontent.com/6024315/177368467-56edcc1c-5408-4b6e-9687-8e3bc7eb5c91.png)
![Screenshot_2022-05-30_10-31-08](https://user-images.githubusercontent.com/6024315/177368471-9478e651-2f1a-4403-9ac0-efaf428da7c9.png)
![Screenshot_2022-05-30_10-18-50](https://user-images.githubusercontent.com/6024315/177368474-e7b8ca0d-fcaf-4fab-9864-78890c16dc7e.png)

### 4 July 2022
![Screenshot_2022-07-04_21-22-25](https://user-images.githubusercontent.com/6024315/177368518-74ea7f83-1553-4bf6-a632-336123b3fc43.png)
![Screenshot_2022-07-04_21-22-11](https://user-images.githubusercontent.com/6024315/177368524-08afc33a-6505-49da-b12a-0d1a4839c24f.png)
![Screenshot_2022-07-04_21-21-47](https://user-images.githubusercontent.com/6024315/177368529-f4143d2d-88cf-4c0a-a547-148d2e763e47.png)
***
@CSahajdacny commented on 2022-07-05T16:11:29:

That happened to me on a Windows 10 machine, playing the game on PC GAMEPASS, so is not a PROTON or Steam issue.
***
@nightsky30 commented on 2022-07-05T16:18:14:

> That happened to me on a Windows 10 machine, playing the game on PC GAMEPASS, so is not a PROTON or Steam issue.

That is very interesting. Thanks for the info. Maybe a driver issue? For reference:
```
Video Card:
    Driver:  NVIDIA Corporation NVIDIA GeForce GTX 1070/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 510.73.05
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1b81
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 1440
    Primary Display Size: 23.62" x 13.39" (27.13" diag)
                                            60.0cm x 34.0cm (68.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 8192 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
```

**Comment by Flaburgan** [comment]
Hello! I just bought it and I had to set proton to experimental for the game to launch (otherwise I was stuck on the launch screen). I had a crash while trying to launch the campaign, speaking at the guy before the first level. See the logs: [steam-924970.log](https://github.com/ValveSoftware/Proton/files/9316170/steam-924970.log)

Also movies between levels are lagging after 30 sec, so you have to skip them

**Comment by CSahajdacny** [comment]
Suddenly, I am having wrong audio language on pre-rendered cutscenes...
Anyone else?

**Comment by CSahajdacny** [comment]
Here is the log with GST_DEBUG=4
[steam-924970.log](https://github.com/ValveSoftware/Proton/files/9824072/steam-924970.log)

it seems Proton can not identify the audio streams properly on pre-rendered cutscenes.

**Comment by Dehir** [comment]
> Suddenly, I am having wrong audio language on pre-rendered cutscenes... Anyone else?

Yep having the same issue. Also after yesterday game doesn't wanna launch anymore.

-----------------------------------
Edit

Launching issue was fixed by dropping  off pre-compiled shader cache from settings.

**Comment by CSahajdacny** [comment]
Pre-rendered cutscenes doesn't show at all when running the game via PROTON EXPERIMENTAL
[steam-924970.log](https://github.com/ValveSoftware/Proton/files/10038802/steam-924970.log)

**Comment by rcbevans** [comment]
# Compatibility Report
- Name of the game with compatibility issues: Back 4 Blood
- Steam AppID of the game: 924970

## System Information
- GPU: Nvidia RTX 3090
- Driver/LLVM version: nvidia 525.85.05
- Kernel version: 6.1.11-76060111-generic
- Link to full system information report as [Gist](https://gist.github.com/rcbevans/954e2a90ee518421eb171bfda4bf3503):
- Proton version: Proton Experimental
- In case relevant, my display is a 5120x1440 gsync enabled display with refresh rate set to 120Hz.

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
In game cutscenes start playback fine but after a period of 1-2 minutes, the audio and video desync, with the video stuttering and appearing somewhat slow motion and the audio becoming unintelligible and playing back even slower.  The cutscene ends when it should, assuming it was playing back correctly at normal speed, whilst the actual rendered video and audio are still midway through. Mangohud reports that the frametime is steady with a consistent 120fps (the refresh rate my monitor is set to) with no CPU spikes, but high GPU utilization.

## Reproduction
Play any in-game cutscene.

**Comment by PickMeNow** [comment]
Anyone having problem with anti-cheat module:

![image](https://github.com/ValveSoftware/Proton/assets/29429513/cf289b58-30e9-46a9-8ecd-be45fa5a0a50)

I could play the game in the last 2 weeks, tried today, having this issue... I already redid the proton prefix still doesn't work.

**Comment by Leopard1907** [comment]
> Anyone having problem with anti-cheat module:
> 
> ![image](https://private-user-images.githubusercontent.com/29429513/302063204-cf289b58-30e9-46a9-8ecd-be45fa5a0a50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMDAyMjQsIm5iZiI6MTcwNjk5OTkyNCwicGF0aCI6Ii8yOTQyOTUxMy8zMDIwNjMyMDQtY2YyODliNTgtMzBlOS00NmE5LThlY2QtYmU0NWZhNWEwYTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDIyMzg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNGU5YTFmMTI0OWRhMTkxODllMTM1ZTZhMDAyMDQzMmJjMmQ1MDE2OWViYzhmMDI0ZjUxMmUzODQwY2UyMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3QZGOnFCINqvTiskPuDeZS5vSTFwR2tiWbjIZvdEYIs)
> 
> I could play the game in the last 2 weeks, tried today, having this issue... I already redid the proton prefix still doesn't work.

What is your distro? You would at least give that info...

**Comment by PickMeNow** [comment]
My machine details:

OS: Arch Linux
KERNEL: 6.7.3-zen1-1-zen
CPU: AMD Ryzen 7 5800X3D 8-Core
GPU: AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 16.0.6, DRM 3.57, 6.7.3-zen1-1-zen)
GPU DRIVER: 4.6 Mesa 23.3.5-arch1.1
RAM: 32 GB

**Comment by Leopard1907** [comment]
@PickMeNow https://gitlab.archlinux.org/archlinux/packaging/packages/glibc/-/commit/83899c6e216ef04a56f16faaa19fcbf84bd0f799

You're probably affected by this.

**Comment by PickMeNow** [comment]
I heard something about this, guess I just need to wait :/

**Comment by the-linck** [comment]
The problem wth GlibC stiil goes on on Arch and derivatives, even with the patched glibc-eac from Garuda Linux chaotic-aur (the same version of Arch's AUR but pre-compiled).
That version of the lib was made to keep the DT_HASH patch, which should solve the issue in this case, but even using it the game still stuck on "failed to load anti-cheat module" - regardless of using EAC through Proton or enabling the flag to use the Steam EAC Runtime (PROTON_USE_EAC_LINUX=1).

Those are my PC spec:
OS: Garuda Linux
Kernel: Linux 6.7.9-zen1-1-zen
CPU: AMD Ryzen™ 7 3700U (4-core APU)
GPU: AMD Radeon 540X Series  / AMD Radeon Vega 10 (amdgpu, LLVM 17.0.6)
GPU DRIVER: mesa radv v: 24.0.2-arch1.2
RAM: 16 GB
Desktop: GNOME v: 45.4

**Comment by ShadowX117** [comment]
# Compatibility Report
- Name of the game with compatibility issues: Back 4 Blood
- Steam AppID of the game: 924970

## System Information
- GPU: AMD Radeon RX 6600 XT
- Video driver version: Mesa 25.1.4
- Kernel version: 6.15.6
- Link to full system information report as [[Gist]:](https://gist.github.com/ShadowX117/9ef838413b84deb363fbff155b611986)
- Proton version: 10.0-1(beta)

## Symptoms 
If you try to watch any pre-rendered cutscene it begins to stutter/lag about half way through

## Reproduction
Play any in-game pre-rendered cutscene

[steam-924970.log](https://github.com/user-attachments/files/21410755/steam-924970.log)
