### ISSUE TITLE
Titan Quest Anniversary Edition (475150)

### ISSUE THREAD

**Issue by teldon** [ValveSoftware/Proton#567]
It seems the only thing that needs to be done to get this game working is to set the windows version to xp in winecfg.

**Comment by d10sfan** [comment]
That worked for me as well.

**Comment by FreeSevenSix** [comment]
i just installed it without any tinkering and it worked fine (played around 15min)

**Comment by fesm0750** [comment]
I've Installed it on my system and it ran out of the box. However, the game stutters if I try to rise detail and shadow settings even though the fps counter seems ok (above 30 fps), running on a Intel HD 4000 though.

**Comment by liberodark** [comment]
#MaxXor is not same for me Titan Quest Anniversary edition not run

**Comment by teldon** [comment]
I wonder, what graphics card/driver is everyone using? I'm using gtx 1060 6gb with 396.54 drivers

**Comment by Mat24** [comment]
It works fine in my laptops 
laptop 1: Dell Latitide 7480 -> Ubuntu 16.04.3, i7 7600U, HD Graphics 620, 16GB RAM
laptop 2: HP Pavillion G4 -> Ubuntu 18.04, i7 2640m, HD Graphics 3000, 8GB RAM

But, in my gaming desktop, loads the game, plays the intro videos and finally shows a black screen with the game cursor :(

[Desktop config](https://gist.github.com/Mat24/15dfcabb8c466daacc15741a3d38fa0d)
Using proton 3.7-3 (on steam play settings menu)

**Comment by HyperEye** [comment]
I am running Nvidia 396.54 drivers with a GTX 1070 8GB on Gentoo amd64 (4.17.6). I was getting the black screen when the game got to the menu until I set the windows version to winxp. Now it works fine.

**Comment by teldon** [comment]
I'm starting to see a bit of a pattern. It may be an issue with an issue with NVidia drivers.

**Comment by HyperEye** [comment]
A bit more info on this problem. I believe that the windows version fix is incidental. An alternative is to set the video memory size in the registry. When I set it to 2GB or 4GB the game worked regardless of windows version. When I tried setting it to 6GB or 8GB I got the black screen.

**Comment by lieff** [comment]
Hmm, worked for me with Proton 3.7-5 Beta without any changes.

**Comment by mayjs** [comment]
On my machine, singleplayer seems to work pretty much without any flaws (played about 30 minutes), but I can't join multiplayer. Can anyone confirm that multiplayer works?

**Comment by abienz** [comment]
I also had to change my Windows version to XP to get it working past the black screen. Using Nvidia 396.53 on GTX 1070

**Comment by fesm0750** [comment]
I couldn't play on multiplayer as well.

**Comment by kelnmaari** [comment]
yep, i cant go in multyplayer too.
game freezing after click "Connect"

**Comment by liberodark** [comment]
Work on proton 3.7-7 but have little bug and lan work

**Comment by Sbte** [comment]
To work around invisible characters, the registry key `CheckFloatConstants` has to be set to true.

**Comment by abienz** [comment]
I started a new character a few weeks ago and had a relatively bug free play through with intermittent crashes after extended play and some alt-tab issues.

I played all the way through Normal.

Upon starting again in the next difficulty mode Epic I frequently get crashes that I would say the game is unreliable. 

Unsure of the cause of the issue or how to report further.

**Comment by diraven** [comment]
Same thing with multiplayer. Clicking "connect" does nothing other then turning the button gray.

**Comment by diraven** [comment]
Relevant piece of log: https://gist.github.com/diraven/3decbfbef50054f34bfb43b1edd1a320

**Comment by abienz** [comment]
Latest updates to Proton and graphics drivers have the game running very well for me even in Epic mode, haven't experienced as many crashes.

On another note I still don't get any text for the place names, or when you press 'Space' to pause for example, you just see the bookend graphics, anyone found a workaround?

**Comment by lucifertdark** [comment]
> Latest updates to Proton and graphics drivers have the game running very well for me even in Epic mode, haven't experienced as many crashes.
> 
> On another note I still don't get any text for the place names, or when you press 'Space' to pause for example, you just see the bookend graphics, anyone found a workaround?

Installing Corefonts might fix that.

**Comment by abienz** [comment]
> > Latest updates to Proton and graphics drivers have the game running very well for me even in Epic mode, haven't experienced as many crashes.
> > On another note I still don't get any text for the place names, or when you press 'Space' to pause for example, you just see the bookend graphics, anyone found a workaround?
> 
> Installing Corefonts might fix that.

Unfortunately that hasn't made a difference, I checked with the latest Proton beta (3.16-2) also.

**Comment by xsgb** [comment]
> Same thing with multiplayer. Clicking "connect" does nothing other then turning the button gray.

Same here, I did not managed to play in LAN too, other game clients don't see the server and vice/versa. No firewalling enabled on the hosts and on the LAN.

**Comment by Steedalion** [comment]
> To work around invisible characters, the registry key `CheckFloatConstants` has to be set to true.

This worked for me and the hollow/invisible man problem. According to [wine](https://wiki.winehq.org/Useful_Registry_Keys) this results in a small performance hit. I think it should be enabled by start for this game. 

Also I think this problem occurs with low-end GPUs. I'm using nvs4200m.

More detail here: https://www.gamingonlinux.com/forum/topic/3538/post_id=17811

**Comment by moll** [comment]
For those interested, WINE v4.2 as Windows 7 or Windows 10 gets passed the black startup screen if you set the video memory, for example, to 2GB through `winetricks videomemorysize=2048`. Courtesy of someone on https://www.protondb.com/app/475150.

**Comment by oysstu** [comment]
Network game issue may be related to #2613

**Comment by HonkingGoose** [comment]
Could somebody upload a Proton log? There's no log yet.

**Comment by AwesamLinux** [comment]
- GPU: RX VEGA 56
- Driver/LLVM version: Mesa 19.2.0-devel/9.0.0
- Distro version: Linux Mint 19.1 Tessa (64 bit) (Cinnamon Desktop)
- Proton version: 4.2-4

@HonkingGoose here is a log of launching the game and trying to join a multiplayer game. Game did not find any servers. I could not see any mentions about steam2.dll in the logs.

[steam-475150.log](https://github.com/ValveSoftware/Proton/files/3184110/steam-475150.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3184111/system_info.txt)

**Comment by oysstu** [comment]
Unable to reproduce the Steam2.dll messages in proton-4.2-4. I have a log that complains that Steam2.dll is missing from proton-4.2-3b, but I suppose this is no longer relevant for this issue since it is gone
[steam-475150_proton-4.2-3b.log](https://github.com/ValveSoftware/Proton/files/3193945/steam-475150_proton-4.2-3b.log)
[steam-475150_proton-4.2-4.log](https://github.com/ValveSoftware/Proton/files/3193946/steam-475150_proton-4.2-4.log)
[systemreport.log](https://github.com/ValveSoftware/Proton/files/3193948/systemreport.log)


.

**Comment by philipjohnbarlow** [comment]
Apologies for resurrecting such an old thread but has anyone been able to get Titan Quest AE multiplayer to work? I tried it on my laptop, running Linux Mint 19.1, recently and observed the same as @diraven.

**Comment by moll** [comment]
@philipjohnbarlow, I played through the GOG DRM-free version and that played fine against the Windows version. Did occasionally crash on the Linux side, but not too often to prevent enjoyment. :P

If you're having connection problems, check out if you're not using multiple network cards on the Windows side. I remember Titan Quest getting confused and sending its connection UDP packets out from the wrong interface, thereby failing to connect.

**Comment by Kron4ek** [comment]
Here is the fix for multiplayer:

1. Download attached ws2_32.dll.zip archive, extract it
2. Put ws2_32.dll into the game directory
3. Change launch options for the game to this:

 `WINEDLLOVERRIDES="ws2_32=n" %command%`

4. Done!

[ws2_32.dll.zip](https://github.com/ValveSoftware/Proton/files/3670245/ws2_32.dll.zip)

p.s. This dll is for the Proton 4.11-6, but it will probably work with older/newer versions too.

**Comment by philipjohnbarlow** [comment]
> Here is the fix for multiplayer:
> 
> Download attached ws2_32.dll.zip archive, extract it
> Put ws2_32.dll into the game directory
> Change launch options for the game to this:
> 
> WINEDLLOVERRIDES="ws2_32=n" %command%
> 
> Done!
> 
> ws2_32.dll.zip
> p.s. This dll is for the Proton 4.11-6, but it will probably work with older/newer versions too.

Brilliant, I'll give this a go later.

**Comment by sharkguto** [comment]
> Here is the fix for multiplayer:
> 
>     1. Download attached ws2_32.dll.zip archive, extract it
> 
>     2. Put ws2_32.dll into the game directory
> 
>     3. Change launch options for the game to this:
> 
> 
> `WINEDLLOVERRIDES="ws2_32=n" %command%`
> 
>     1. Done!
> 
> 
> [ws2_32.dll.zip](https://github.com/ValveSoftware/Proton/files/3670245/ws2_32.dll.zip)
> 
> p.s. This dll is for the Proton 4.11-6, but it will probably work with older/newer versions too.

it is working great, thanks !!! 

`WINEDLLOVERRIDES="ws2_32=n" PROTON_USE_D9VK=1 %command%`

![image](https://user-images.githubusercontent.com/3118165/66050664-fa638700-e503-11e9-8edc-b49538926c34.png)

**Comment by at46** [comment]
@Kron4ek thanks for posting the multiplayer solutions. Works fine for me.
In addition I recommend to limit the fps to avoid lags (see also: https://www.pcgamingwiki.com/wiki/Titan_Quest_Anniversary_Edition#Large_bursts_of_lag_in_multiplayer)

**Comment by cvignal** [comment]
- GPU : GeForce GTX 970M 
- Driver : 440.44
- Kernel version : 5.4.12-arch1-1
- Proton version : 4.11.12

I'm constantly crashing after killing a few mobs in the Nerthus Sanctuary from the Atlantis DLC. It's the only place in the game where it happens, most of the times after 7-8 mobs killed. I tried to play at normal speed, lowered the graphics settings but to no avail.

[steam-475150.log](https://github.com/ValveSoftware/Proton/files/4092843/steam-475150.log)

**Comment by soredake** [comment]
Game works fine with proton 5.0-2.

**Comment by kisak-valve** [comment]
Titan Quest Anniversary Edition crashes immediately without error message.

Issue transferred from https://github.com/ValveSoftware/Proton/issues/3596.
@Logicisart posted on 2020-03-03T16:27:25:

# Compatibility Report
- Name of the game with compatibility issues: Titan Quest Anniversary Edition
- Steam AppID of the game: 475150

## System Information
- GPU: AMD Ryzen 3500U
- Driver/LLVM version: AMD RAVEN (DRM 3.33.0, LLVM 9.0.0 
- Kernel version: 5.3.0-40-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 5.0-3

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms:

Game crashes immediately after I press "start" without further notice. Has been working fine a few months ago. 


## Reproduction

Just press "start" and the game attempts to launch, only to crash right back to steam.


[steam-475150.log](https://github.com/ValveSoftware/Proton/files/4282403/steam-475150.log)

**Comment by kisak-valve** [comment]
Hello @Logicisart, these look like the lines of interest from your log:
`info:  Required Vulkan extension VK_KHR_surface not supported`
`terminate called after throwing an instance of 'dxvk::DxvkError'`

This tells us the Vulkan render stack didn't initialize properly for some reason.

Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by ghost** [comment]
Hello @kisak-valve , thank you for your suggestion. If I'm not mistaken, this link should provide you with all the content from the system information report:
https://gist.github.com/Logicisart/c62b771f695faf0fbb0b7050c3e23fc6

**Comment by ghost** [comment]
Thank you for editing. Don't know what went wrong with my link.

**Comment by kisak-valve** [comment]
If I'm reading the s-r-t-info correctly, you have no vulkan drivers installed, so it gave us `vulkaninfo.c:812: failed with VK_ERROR_INCOMPATIBLE_DRIVER`.

Please check that you have `mesa-vulkan-drivers` and `mesa-vulkan-drivers:i386` installed with something like `apt policy mesa-vulkan-drivers mesa-vulkan-drivers:i386` and install them if they're not already.

**Comment by ghost** [comment]
Thank you for editing. Don't know what went wrong with my link.

> If I'm reading the s-r-t-info correctly, you have no vulkan drivers installed, so it gave us `vulkaninfo.c:812: failed with VK_ERROR_INCOMPATIBLE_DRIVER`.
> 
> Please check that you have `mesa-vulkan-drivers` and `mesa-vulkan-drivers:i386` installed with something like `apt policy mesa-vulkan-drivers mesa-vulkan-drivers:i386` and install them if they're not already.

These drivers weren't installed, for whatever reason. Did install them, and after a reboot everything works just fine. Thank you for you help, and have a nice day!

**Comment by at46** [comment]
@Abilbel got Atlantis now and was able to play through it without any crashes with proton 5.0-9.

**Comment by sonnyp** [comment]
The fix for multiplayer described in https://github.com/ValveSoftware/Proton/issues/567#issuecomment-536495333 broke with Proton `5.13-1` - the game displayed some kind of error when trying to host a multiplayer LAN game.

However it seems that it isn't necessary anymore with Proton `5.13-1` but you'll have to remove the launch option, the `.dll` file and use "verify integrity of game files" to get rid of it.

EDIT Tested so far with Proton `5.13-1` without tricks:

* Hosting a LAN multiplayer :+1: 
* Joining Internet multiplayer :+1: 
* Alt+tab / game looses focus :-1:  - game freezes (On Proton `5.0-9` it wouldn't freeze but no way to re-gain focus)

**Comment by at46** [comment]
@sonnyp any chance you are talking about `5.13-1` instead of `5.3-1`? I haven't seen a `5.3-1` version so far only `5.13-1` which appears to be a beta with some regressions https://github.com/ValveSoftware/Proton/issues/4289 
The multiplayer fix from https://github.com/ValveSoftware/Proton/issues/567#issuecomment-536495333 only seems to be necessary for proton 4.x. Since proton `5.0` at least online-multiplayer worked fine for me without it.

**Comment by sonnyp** [comment]
@at46 

> any chance you are talking about 5.13-1

Indeed - I fixed the typos.

> The multiplayer fix from #567 (comment) only seems to be necessary for proton 4.x. 

Pretty sure the fix was required for LAN on Proton 5.0-9. Could be wrong.

**Comment by at46** [comment]
Is there anything I can do to be able to see the whole text in the start options window? The window isn't resizable and I haven't found any option to change it's size or the font size. As far as I know the first one (which I normally use) is DX11 and the second one is DX9 but I've no idea what the others (especially the last two) are used for.
![tq](https://user-images.githubusercontent.com/6986646/99826929-497dd880-2b59-11eb-87a6-756609ddf456.png)

**Comment by soredake** [comment]
> Is there anything I can do to be able to see the whole text in the start options window? The window isn't resizable and I haven't found any option to change it's size or the font size. As far as I know the first one (which I normally use) is DX11 and the second one is DX9 but I've no idea what the others (especially the last two) are used for.
> ![tq](https://user-images.githubusercontent.com/6986646/99826929-497dd880-2b59-11eb-87a6-756609ddf456.png)

https://steamdb.info/app/475150/config/

**Comment by at46** [comment]
@soredake thanks. I didn't know that steamdb shows the launch options.

**Comment by tmespe** [comment]
Still crashes on window losing focus as of Proton 6.3.6/Experimental. I was hoping it would be affected by "Improve input handling after focus loss in some games like Project Cars 3, Warhammer: Chaosbane, and Far Cry Primal.", but no go.

**Comment by minisori** [comment]
I had to use the flag PROTON_FORCE_LARGE_ADDRESS_AWARE=1 to avoid crashes with DX11 version in Proton 6.3-7.
For now seems to work ok even the multiplayer.
Still crashes whit ALT+TAB.

**Comment by at46** [comment]
> I had to use the flag PROTON_FORCE_LARGE_ADDRESS_AWARE=1 to avoid crashes with DX11 version in Proton 6.3-7. For now seems to work ok even the multiplayer.

Isn't PROTON_FORCE_LARGE_ADDRESS_AWARE=1 the default? At least in the [readme](https://github.com/ValveSoftware/Proton#runtime-config-options) it is noted that:

> Force Wine to enable the LARGE_ADDRESS_AWARE flag for all executables. **Enabled by default.**

**Comment by minisori** [comment]
> Isn't PROTON_FORCE_LARGE_ADDRESS_AWARE=1 the default? At least in the [readme](https://github.com/ValveSoftware/Proton#runtime-config-options) it is noted that:
> 
> > Force Wine to enable the LARGE_ADDRESS_AWARE flag for all executables. **Enabled by default.**

Hmm it looks like so.
It doesn't make any sense. I retested and now it doesn't crash with or without it, before it was consistently crashing with DX11 in the first fountain, so i was playing with DX9 until i remembered that some 32b games could have problems with memory and decided to give it a try, not knowing that it was already defaulted.
The only thing that changed between is that i bought the Atlantis DLC.

**Comment by Zlopez** [comment]
I played only the single player, but it works great (I'm already in second act). Only issue I have is with the freeze happening on ALT+TAB.

**Comment by screwylightbulb** [comment]
The alt-tab thing seems to be that the game does not refocus.

**Comment by Leopard1907** [comment]
Issues with this game seems to be purely windowing related at this point.

1-) Toggling Fullscreen breaks the game. To a point that game throws an error that says my gpu is not DX11 supported. Borderless and windowed works fine, borderless is default.

2-) Alt tabbing just breaks this game, after that interacting with game window is not possible and game just stays there like a dead process.

**Comment by Leopard1907** [comment]
https://github.com/doitsujin/dxvk/issues/2395

Filed an issue about it on upstream DXVK.

With using wine dxgi game can be toggled to fullscreen without issues:

```WINEDLLOVERRIDES="dxgi=b" %command%```

**Comment by Wedge009** [comment]
I only just started playing for the first time today. Most things seemed to work just fine without any manual tinkering under Proton 6.3-8. As others have mentioned, losing focus - eg via Alt-Tab window switching - results in the game hanging/freezing. The aforementioned Wine DLL Override didn't work for me.

The other major issue I found is battle sound effects seem to be non-existent. It doesn't appear to be an issue with volume - background music, button clicks, dialogue speech, even the low health warning, I can hear all those. There's just no sound effects in combat, which is rather disconcerting. I confirm I can hear battle sound effects when playing on Windows 7.

**Comment by Leopard1907** [comment]
@Wedge009 Mentioned winedlloverride is for being able to set game to fullscreen. Not related to alt tabbing.

**Comment by Wedge009** [comment]
Got it. Sorry for the misunderstanding.

**Comment by Leopard1907** [comment]
https://github.com/doitsujin/dxvk/commit/b53c3057e1005b0eba38b5a4542f1c78353b3a73

Fullscreen fix is in master now.

**Comment by Wedge009** [comment]
Still seems okay with Proton 7.0-1. I forgot to clarify that I resolved my aforementioned volume issue, it wasn't related to Proton just the game's internal mixing.

**Comment by subwaystation** [comment]
Using either Proton 7.0-1 or 6.3-8, the game will launch to black screen for a second and then crash.
Any ideas how to fix this? Thanks!

**Comment by Wedge009** [comment]
Is mesa-vulkan-drivers:i386 or distribution-equivalent installed?

**Comment by subwaystation** [comment]
I am running ArchLinux. https://wiki.archlinux.org/title/Vulkan. Already installed are [vulkan-icd-loader](https://archlinux.org/packages/?name=vulkan-icd-loader), [lib32-vulkan-icd-loader](https://archlinux.org/packages/?name=lib32-vulkan-icd-loader), [nvidia-utils](https://archlinux.org/packages/?name=nvidia-utils), and [lib32-nvidia-utils](https://archlinux.org/packages/?name=lib32-nvidia-utils). I can run e.g. Dota2 using Vulkan without any problems.

**Comment by Wedge009** [comment]
I only suggested that because when DXVK became the default over WineD3D with Proton 5.0, nearly everything broke for me with the symptoms you describe. I had 64-bit mesa-vulkan-drivers installed, but not 32-bit. Installing the 32-bit drivers resolved those issues for me. Not sure, but I wonder if DotA2 would run on the 64-bit drivers.

It might not be applicable to you, just offering what I know.

**Comment by subwaystation** [comment]
Thanks! Maybe it is still related: 
```
ls /usr/share/vulkan/icd.d/
amd_icd32.json  nvidia_icd.json
```
I don't understand why AMD would pop up here. Reinstalling all packages mentioned above did not change this. So I assume it's fine.

**Comment by subwaystation** [comment]
I don't know for what reasons, but there was also the AMD 32-bit driver for Vulkan installed. This confused Proton. Uninstalling of the AMD package and Reinstalling all Vulkan and Nvidia packages solved the issue. Thanks for the tips @Wedge009!

**Comment by Wedge009** [comment]
Glad you got it working! Perhaps AMD packages are installed by default by the distribution since I understand they're usually open-source.

**Comment by Cederick** [comment]
Works flawlessly on Steam Deck out of the box without any issues. Controller support is working and in-game dialog fields open the keyboard automatically.

I don't know why it still says unsupported and I'd like to request whitelisting and/or retesting of the game.

**Comment by Wedge009** [comment]
The main problem for me was on a desktop Alt-Tab switching breaks the game when returning to it. But checking just now on vanilla Proton 8.0-3, no command-line options, that problem seems to be resolved now. So I agree, this seems worth white-listing to me.

**Comment by Espionage724** [comment]
Does anyone notice lines in grass in Act 1 with DX9? It's almost subtle-enough to look intentional with small grass patches, but I played mostly on Windows without the lines.

With Intel UHD 630 I get noticeable lines DX9 with and without DXVK on Wine on Linux, but DX9 was fine on Windows. DX9 give me better performance to meet Vsync.

**Comment by kisak-valve** [comment]
[Titan Quest - AE] Proton 10 regression when attempting to switch out of the game

Issue transferred from https://github.com/ValveSoftware/Proton/issues/8733.
@git-f0x posted on 2025-05-25T13:44:45:

OS: Bazzite 42
Kernel: 6.14.6-105.bazzite.fc42.x86_64
Mesa: 25.1.0
GPU: Radeon RX 570
Proton version: Experimental, also happens on Proton GE 10.3 (doesn't with wine wayland)

When pressing the Super key (or Alt Tab) on Proton 10 in Titan Quest Anniversary Edition, the interface that should show up only flashes briefly, and nothing can display over the game window.
The game even prevents switching to a different virtual desktop (at least on Plasma), immediately switching back to the desktop the game is on.

Some other games also have slightly weird behavior, but aren't disruptive (e.g. Grim Dawn has a very weird minimize animation when pressing Super, and the Civ VI window occasionally shrinks slightly to the top right with the same action).

It doesn't seem to be a dxvk regression (checked multiple older versions). On Proton 9, things work as expected.

**Comment by kisak-valve** [comment]
Hello @git-f0x, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by git-f0x** [comment]
System information: https://gist.github.com/git-f0x/ab0b04e9200f602778ec2938548fba0f

[steam-475150.log](https://github.com/user-attachments/files/20431254/steam-475150.log)

**Comment by alasky17** [comment]
@git-f0x Thank you for reporting this! I could reproduce the problem and we will investigate.  These issues can be hard to fix, so it might take a while 😅
