### ISSUE TITLE
F1® 22 (1692250)

### ISSUE THREAD

**Issue by macaquinyho** [ValveSoftware/Proton#5963]
# Compatibility Report
- Name of the game with compatibility issues: F1 22
- Steam AppID of the game: 1692250

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nvidia 515.57
- Kernel version: 5.18.7-200.fc36.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Toomoch/f69cf23ba76f670b015b24382531a1d5
- Proton version: 7.0-3

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1692250.log](https://github.com/ValveSoftware/Proton/files/9034894/steam-1692250.log)
## Symptoms 

The game crashes on the initial supercar purchase. If I skip it by doing the tutorial on another machine and syncing the cloud save, it then crashes in the loading screen in a race or time trial.

## Reproduction

Load the game, begin the tutorial and try to buy a supercar.

**Comment by kisak-valve** [comment]
Hello @Toomoch, it might be interesting to test how this game behaves with Proton Experimental.

**Comment by macaquinyho** [comment]
> Hello @Toomoch, it might be interesting to test how this game behaves with Proton Experimental.


Same crash: [steam-1692250.log](https://github.com/ValveSoftware/Proton/files/9035214/steam-1692250.log)

**Comment by macaquinyho** [comment]
It may be an Nvidia issue, specifically with pre Turing cards. In https://www.protondb.com/app/1692250 there are only reports of the issue with < RTX 2000 cards

**Comment by one-and-only** [comment]
I'm having the same issue. GTX 1060-6GB with latest Nvidia DKMS and custom Proton GE. I'm an avid f1 game player and I really want this working.

**Comment by one-and-only** [comment]
This issue also happens with F1 2021

**Comment by ReazerDev** [comment]
The game runs perfectly fine for me. However, when launching it in VR, there's no image inside of my VR Headset (Valve Index), it's just displaying black (the screens are not turned off).
I have a small window on my monitor, which displays the game and when I start a Session, the VR Tracking also works perfectly fine. It's just not displaying inside my VR Headset.

Any Idea what I can try? ACC for example runs inside of my Headset
[steam-1692250.log](https://github.com/ValveSoftware/Proton/files/9066495/steam-1692250.log)

I've got an RX 6900 XT and I tried using Proton Experimental as well.

Just as info: On Windows, there is a Window displaying the game on my Monitor too, but the game is also being displayed inside of my Headset.

**Comment by one-and-only** [comment]
You've already gotten farther than me 😆 I believe it's an issue with older GPUs (for nvidia pre-turing). Every loading spinner there is after launching causes a system-wide lockup, after which EGO Dumper pops up.

**Comment by ReazerDev** [comment]
You, it's probably the same Nvidia-Driver issue as with F1 2021.
The game was constantly crashing on me. Once I got my AMD GPU it ran (almost) perfectly.

**Comment by one-and-only** [comment]
On protondb there are people with ampere and Turing cards that have gotten the game to work fine. All of the F1 22 and F1 2021 issues relating to proton come from pre-Turing nvidia card owners. I don't think it's a coincidence and a large number of people own these cards, so I would like this to gain higher priority.

**Comment by ReazerDev** [comment]
Doesn't look like a proton issue to me, since it's only a few Nvidia cards. It's probably a driver issue.
F1 2021 didn't work on any Nvidia card until Nvidia released a driver update which made the game work on some cards.

(Note that I don't know a lot about proton and this is just me guessing and repeating what other people in the F1 2021 Issue said)

**Comment by one-and-only** [comment]
Can't remember where I saw it, and I think it was from the f1 2021 issue, but one user had issues with a pascal card, switched it for a 3070, and it instantly worked without updating drivers. Then again, it could be a driver issue that doesn't allow f1 22 or f1 2021 to run well on older cards. If it's that, I would lose hope all together imho, since nvidia isn't known for adopting linux all that much.

**Comment by one-and-only** [comment]
Nvidia has already release a Game-Ready driver for f1 22, still doesn't work on linux. Before I updated to the game ready driver, f1 22 ran perfectly fine anyway (in windows), so I don't think game ready or not is going to make any difference.

**Comment by one-and-only** [comment]
If one day I can run all my games on linux, I can migrate away from windows. That's the only thing holding me back. It's annoying having to dual boot just for one app 🙄

**Comment by ReazerDev** [comment]
Let's not spam this Issue too much, but I can recommend getting an AMD card. It solved a lot of my problems

**Comment by one-and-only** [comment]
Sorry, good idea. Can't afford another GPU atm, maybe in the future.

**Comment by plasmamax1** [comment]
I recently got this game and it seems that my wheel (T300RS) isn't detected by the game. A little surprised since F1 2020 works fine with a wheel on proton 7.0-3.  I tried proton 7.0-3 and Experimental for F1 22, but it makes no difference.

**Comment by one-and-only** [comment]
Have you tried Proton GE?

**Comment by Xyon** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/5963#issuecomment-1178075012

I have the exact same issue and we're on the same GPU. Please let me know if you find a solution!

**Comment by plasmamax1** [comment]
> Have you tried Proton GE?

I recently tried GE-Proton7-24, but the wheel is still undetected by the game.

Edit (15Jul2022): I downloaded Thrustmaster's drivers from their [website](https://ts.thrustmaster.com/download/pub/webupdate/T500RS/2022_TTRS_1.exe), and used my system wine (Wine 7.12-1 on Arch Linux) to the F1 2022 proton prefix. Now my T300 RS is properly detected by the game and usable.

**Comment by Raboebie** [comment]
> > Have you tried Proton GE?
> 
> I recently tried GE-Proton7-24, but the wheel is still undetected by the game.
> 
> Edit (15Jul2022): I downloaded Thrustmaster's drivers from their [website](https://ts.thrustmaster.com/download/pub/webupdate/T500RS/2022_TTRS_1.exe), and used my system wine (Wine 7.12-1 on Arch Linux) to the F1 2022 proton prefix. Now my T300 RS is properly detected by the game and usable.

I honestly did not expect this to work but it did. Thanks!

**Comment by impactgs** [comment]
I also have the same issue as @ReazerDev https://github.com/ValveSoftware/Proton/issues/5963#issuecomment-1180789152 and @Xyon https://github.com/ValveSoftware/Proton/issues/5963#issuecomment-1180789152. The game seems to run just fine, but in VR there is no image displayed in the headset, only a window on my tv/monitor. It does show a warning message when not wearing the headset, though.

log: [steam-1692250.log](https://github.com/ValveSoftware/Proton/files/9226550/steam-1692250.log)
system report: https://gist.github.com/impactgs/3de67b8ab4f2ea772f08f0157a5a3666

**Comment by chnagy** [comment]
log: [steam-1692250-7_04.log](https://github.com/ValveSoftware/Proton/files/9410773/steam-1692250-7_04.log)

With the newest patch 1.09 the game won't start anymore. It crashes as soon as you press "any button to continue" in the splash screen.
This occurred for some windows users too which did not update their system for a while. But got fixed by updating and resetting their game hardware settings.

There are a lot of people with the issue with steamdeck since it is supposed to be a verified game.
I tested this on an Linux 5.19.3 with Proton 7.0-4 and GE-Proton7-30 on two different hardware which both resulted with the crash.
Windows 11 on the same hardware works.

Sadly this is out of my knowledge. So maybe someone here can take a look into this. If I can help in any way feel free to ask.

**Comment by CatalinPuscoci** [comment]
From what I'm gathering there are windows users affected by this too, I was told the game had the same crash after "press x to continue" until they updated their OS
> Replying to https://github.com/ValveSoftware/Proton/issues/5963#issuecomment-1224903243

Edit: The devs are working on it I suppose
 https://answers.ea.com/t5/General-Discussion/F1-22-Patch-1-09-Discussion-Thread/m-p/11761926#M13183
 
![image](https://user-images.githubusercontent.com/32127810/187052935-7ef13359-0d11-4947-9c2f-fea29a6feb35.png)
![image](https://user-images.githubusercontent.com/32127810/187052894-5925b7f4-e69f-4e04-82b8-5351c1c3522d.png)

Later edit:September 1st "hotfix" did not fix anything for me btw

**Comment by davidjmemmett** [comment]
After this morning's update, using Proton Experimental, the game still crashes after the title screen. Log: [steam-1692250.log](https://github.com/ValveSoftware/Proton/files/9525113/steam-1692250.log)

**Comment by CatalinPuscoci** [comment]
After patch 1.10 I get a crash before the title screen with proton experimental and with 7.0-4 it crashes my whole system.

<details><summary>Apologies for the picture but the whole thing locked up</summary>

![D83C1918-1513-4855-9753-0ED150538A30](https://user-images.githubusercontent.com/32127810/189731444-39f5927d-dfae-4bc6-9902-274e4b4b5ec7.jpeg)

</details>

**Comment by CatalinPuscoci** [comment]
https://reddit.com/r/F1Game/comments/xjei3x/f1_22_now_works_on_steam_deck_again/

Also works on Arch with mesa-git and Proton-GE 7.35 now I can confirm

**Comment by davidjmemmett** [comment]
Good news, using Proton Experimental now works!

**Comment by leillo1975** [comment]
Someone knows if online multiplayer works? Yesterday I couldn't join to any online race

**Comment by bit-stone** [comment]
Update about the compatibility: 
Game runs flawlessly now. 

Just one thing:
Prior to the last patch I was able to use Logitech G29 just fine. 
Now it does not detect any steering or pedal movement and some buttons are weirdly flipped (circle and square for example). 
No idea, if that is fixable.

**Comment by CatalinPuscoci** [comment]
> Update about the compatibility: Game runs flawlessly now.
> 
> Just one thing: Prior to the last patch I was able to use Logitech G29 just fine. Now it does not detect any steering or pedal movement and some buttons are weirdly flipped (circle and square for example). No idea, if that is fixable.

It's being tracked at https://github.com/ValveSoftware/Proton/issues/6323

**Comment by lobneroO** [comment]
I still have the same problem with the supercars menu, using a GTX 1060 and both Protn experimental as well as 7.0.5. However, I noticed that I could get further by just pressing enter very fast and then I tried getting through all of it by hammering enter. It seemed to work. It blocked once after I pruchased whatever super car was on the first slot, but after a restart I got into the main menu.
Alt tabbing seems to be a bad idea though, it froze my PC. 

I have not yet started a race or career, but I'll try it now.


Update1: The avatar menu freezes the game as well, so try to avoid any such menus ...

Update2: I got to a the menu where I could choose the team. This menue worked, I could choose any of the teams. Following is a menu to choose a team mate and here it froze again. I'll try again to see if I can "outrun" that one, too.

Update3: I could outrun the team mate menu. I "started" the season, with the car reveal working. Upon starting the first race weekend, the loading screen for the practice 1 freezes. I don't see a possibility to avoid that at the moment. I'll see if there is a way to do a casual race rather than a career.

Update4: The Solo menu is also a freezing one.

Update5: I bit the bullet and bought a Radeon 6650 XT (which I was thinking about for half a year anyway). With that, it now works.

**Comment by guustflater** [comment]
The game doesn´t start at all. Any ideas here? Dirt Rally 2.0 and al other games work..

Edit: I've tried with proton expiremental, GE 7-51,  7.0-6. All the same issue

Computer Information:
CPU Brand:  AMD Ryzen 5 1600 Six-Core Processor            
Operating System Version:     Ubuntu 22.04.2 LTS (64 bit)
Kernel Version:  6.2.5-x64v1-xanmod1
Driver:  AMD AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.2.5-x64v1-xanmod1)
Driver Version:  4.6 (Compatibility Profile) Mesa 23.0.0 - kisak-mesa PPA
RAM:  15944 MB
VR Hardware: Headset: HTC Vive MV (lighthouse)

Log file attached:
[steam-1692250.log](https://github.com/ValveSoftware/Proton/files/11002493/steam-1692250.log)

**Comment by kisak-valve** [comment]
F1 22 just wont launch 

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6621.
@Colon101 posted on 2023-03-18T00:49:52:

im using proton experimental  but i tried like almost all versions but it just wont start heres what im seeing 

https://user-images.githubusercontent.com/99831740/226074281-f9fd51a9-f46c-4959-8029-ee2fcf35d7c3.mp4

i have an i5-8400
and a rx 6600

**Comment by kisak-valve** [comment]
Hello @Colon101, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Colon101** [comment]
[steam-1692250.log](https://github.com/ValveSoftware/Proton/files/11007869/steam-1692250.log)

idk why but i cant like copy the text from the system information window and its like 1 thousand lines so if something there is important tell me and ill provide it to you

**Comment by kisak-valve** [comment]
Thanks, a header only Proton log hints that something happened before the actual game had a chance to start. If you completely close Steam, then run `steam` from a terminal, there might be a hint in the terminal spew when you tell Steam to start the game.

What filesystem are you using with `/run/media/kfir/Slow HDD/SteamLibrary/`? The likely scenario is that partition is formatted to use NTFS and Proton is known to be finicky with non-Linux native filesystems. If that's true, the general recommendation is to use a Linux native filesystem instead.

**Comment by Colon101** [comment]
oh i didnt know ntfs was really problematic i just assumed that drivers can fix that cause i am dual booting and i cant manage to get exfat permissions right
also i did what you told me and i saw ThreadGetProcessExitCode: no such process 22909
ThreadGetProcessExitCode: no such process 22908
ThreadGetProcessExitCode: no such process 22907
ThreadGetProcessExitCode: no such process 22795
ThreadGetProcessExitCode: no such process 22794
Uploaded AppInterfaceStats to Steam
i dont really know what it wants from me tbh but yeah

**Comment by Colon101** [comment]
turns out the ntfs partition was the issue i moved game files to a btrfs partition and now it works perfectly im just really sad that ill need to reformat my drives in ext4 or understand exfat

**Comment by kisak-valve** [comment]
Regarding exFAT, please give #3835 a read. Also, the workarounds at https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows might interest you.

**Comment by guustflater** [comment]
No NTFS here. Checked the files via Steam and also moved it it another disc. 
It still won´t start, only these kind of errors from proton log:

1280.370:0120:0124:trace:unwind:RtlVirtualUnwind type 0 rip 000000007B62D759 rsp 0000000001E1FF80
1280.370:0120:0124:trace:unwind:dump_unwind_info **** func 2d750-2d762
1280.370:0120:0124:trace:unwind:dump_unwind_info unwind info at 000000007B63E5B0 flags 0 prolog 0x4 bytes function 000000007B62D750-000000007B62D762
1280.370:0120:0124:trace:unwind:dump_unwind_info     0x4: subq $0x28,%rsp
1280.370:0120:0124:trace:unwind:RtlVirtualUnwind type 0 rip 000000017005F8D7 rsp 0000000001E1FFB0
1280.370:0120:0124:trace:unwind:dump_unwind_info **** func 5f8c0-5f8d8
1280.370:0120:0124:trace:unwind:dump_unwind_info unwind info at 0000000170086CA4 flags 1 prolog 0x4 bytes function 000000017005F8C0-000000017005F8D8
1280.370:0120:0124:trace:unwind:dump_unwind_info     0x4: subq $0x28,%rsp
1280.370:0120:0124:trace:unwind:dump_unwind_info     handler 000000017005FF40 data at 0000000170086CB0
1280.587:0120:0124:warn:seh:RtlLookupFunctionEntry no exception table found for 50c91195
pid 22392 != 22391, skipping destruction (fork without exec?)

**Comment by sigzegv** [comment]
Cannot connect to coop mode since 2 days from now when gaming with proton  (I'm using a debian 12).. Did something changed in the game ? It's still ok under windows, so I believe there is no ban on things like that.

**Comment by kisak-valve** [comment]
f1 2022 camera problem

Issue transferred from https://github.com/ValveSoftware/Proton/issues/7493.
@lucada30 posted on 2024-02-11T21:00:04:

steam version : 1705108172

Thanks to steam and proton I can play formula 1 on linux!!! 
Unfortunately I have an annoying problem when replaying F1 22.
For example, when I make a mistake on the track and I want to fix it, I pause and then choose the item "INSTANT REPLAY FLASHBACK" and the game goes back, unfortunately I can only choose cameras that look backwards (I attach photos of the available shots).
If I play with Windows the problem doesn't exist.

I also tried:
1) reinstall F1 22
2) reinstall steam
3) reinstall linux
but nothing worked for me.
Can anyone help me ???
![20240211200341_1](https://github.com/ValveSoftware/Proton/assets/60314104/9015a41f-2044-4e5c-90eb-9883290e663d)
![20240211200344_1](https://github.com/ValveSoftware/Proton/assets/60314104/1a64a439-1986-4bc8-ac8c-ba18d64160fb)
![20240211200346_1](https://github.com/ValveSoftware/Proton/assets/60314104/c47212c0-558a-4bdf-8bd8-387486e5846b)
![20240211200348_1](https://github.com/ValveSoftware/Proton/assets/60314104/854310a4-ee1e-42dd-96cf-258cb287db76)
![20240211200330_1](https://github.com/ValveSoftware/Proton/assets/60314104/486f1707-fb0f-4a5a-922d-fa2dbdbde826)

**Comment by CatalinPuscoci** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/5963#issuecomment-1937886785

@lucada30

Try to see if the issue persists when you only have a keyboard and mouse. Try moving the camera by pressing the pedals.


Afaik at least when I had the logitech, the pedals were mapped to camera controls in a weird way, and I believe the clutch would be used to look up and down when you were in the car before a race and in some other places.

It's just a weird way the camera works with the input, and while I haven't tested it on windows, I kinda doubt it's anyone else's fault but the game's.

Hopefully this helps.
