### ISSUE TITLE
Far Cry 3 - Blood Dragon (233270)

### ISSUE THREAD

**Issue by cretsiah** [ValveSoftware/Proton#6514]
![Directx_11_Error](https://user-images.githubusercontent.com/124935134/217941983-ea9c229b-7462-4388-bad5-1cc7a5025bf3.png)
![File_Failure](https://user-images.githubusercontent.com/124935134/217942008-25e8038e-3808-468c-8f70-5964faf94cd4.png)

assuming corrupted storage area from where game is downloaded from

Steam Support said to drop a line here
![Screenshot from 2023-02-10 08-24-09](https://user-images.githubusercontent.com/124935134/217942438-89299d38-405e-4b99-a532-24d6be9f60d9.png)

**Comment by cretsiah** [comment]
honestly no idea what im doing so here is log
[steam-233270.log](https://github.com/ValveSoftware/Proton/files/10701676/steam-233270.log)

**Comment by kisak-valve** [comment]
Hello @cretsiah, please grab the compatibility report template from https://github.com/ValveSoftware/Proton/issues/new?template=compatibility-report.md, copy it here, and fill it out.

**Comment by kisak-valve** [comment]
Also, can you test how the game behaves with Proton 6.3?

**Comment by cretsiah** [comment]
> Also, can you test how the game behaves with Proton 6.3?

on my old system when i could get around this these 2 issues i used to use proton 6.03-8 however i would have to contact steam support to get the files to become downloadable and launch the game... but would also require having to copy and paste the ubisoft launcher  from another working ubisoft game.

i will try again to test the game under 6.3 

---

Far Cry 3 Blood Dragon

Issue transferred from https://github.com/ValveSoftware/Proton/issues/6519.
@cretsiah posted on 2023-02-10T23:12:38:

# Compatibility Report
- Name of the game with compatibility issues: Far Cry 3 Blood Dragon 
- Steam AppID of the game: 233270

## System Information
- GPU: RX 550 4gig 
- Driver/LLVM version: driver: amdgpu, chip ID: 1002:699f, POLARIS12 DRM 3.40.0 5.10.0-21-amd64 LLVM 11.0.1 Mesa 20.3.5
- Kernel version: 5.10.0-21-amd64 x86_64
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/cretsiah/9168c43fef5166f295626dcd9720a858
- Proton version: 6.3-8

## I confirm:
- [ yes] that I haven't found an existing compatibility report for this game.
- [ yes] that I have checked whether there are updates for my system available.


[steam-233270.log](https://github.com/ValveSoftware/Proton/files/10711825/steam-233270.log)


## Symptoms 
- Under proton 6.3-8 missing uplay / ubisoftconnect comes up with Error Code: 1
- 53 missing files 
- re-install doesnt work
- clearing cache doesnt work

## Reproduction

**Comment by alasky17** [comment]
@cretsiah ~~Regarding the missing uplay/ubisoft connect launcher - it might be easier to use protontricks to install it into the prefix instead of needing to copy it from another game?  Once you have protontricks installed (https://github.com/Matoking/protontricks), you can use "protontricks 233270 uplay" to install the ubisoft launcher into your game prefix.~~
Edit: I just tried the game myself, and it does install the Uplay launcher, so you will not need to do that.  It looks like it needs 2 launches to work, which is pretty standard for uplay games.  
Also, Uplay pushed an update which broke their launcher recently.  We pushed an update to 7.0-6 to fix this, but older versions of Proton will not work with the Uplay launcher. 

I think that the error you are seeing with the Uplay launcher (Ubisoft Game Launcher: Error Code is 1) is a result of you trying different proton versions without properly cleaning.  You can "fix" the error by deleting the prefix  folder (located by default in ~/.steam/steam/steamapps/compatdata/233270) and then launching the game 2x on Proton 7.0 again.  It might actually benefit you to just uninstall the game entirely and then reinstall and launch directly with Proton 7.0-6.

I didn't have much luck trying to launch on 6.3-8 because of the aforementioned Uplay update, but hopefully the game will just work on 7.0-6 with a fresh install.  It is working for me :)

**Comment by cretsiah** [comment]
i had completely deleted / purged steam and all games 
redownloaded all
and still not work, same 2 errors 53 failed files and directx 11
tried all 3 protons 6.3-8, 7.6 and experimental

so i got no idea whats going on

**Comment by intelligentgaming** [comment]
I can confirm that the game no-longer works using Steam Proton Experimental or 9.0.1.

Ubuntu 24.04 - Nvidia RTX 3080 - 535.171.04

Clicking the Play button should initially start the installation process for Ubisoft Connect, but this never happens, I see the processing Vulkan shaders and then it returns to the Play button again.

Native Steam package with the game installed on an Ext4 formatted partition.

**Comment by intelligentgaming** [comment]
OK, so I managed to get it working.

Install UbisoftConnectInstaller.exe as a non-steam game using Proton Experimental.

Then launch the game again, and it correctly will launch Ubisoft Connect and load the game.

You still need to disable the Steam Overlay however.

**Comment by kisak-valve** [comment]
Far Cry 3: Blood Dragon unplayable at startup

Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/13189.
@falconico posted on 2026-05-12T12:20:54:

#### Your system information

* Steam client version: 1778281814
* Distribution: Linux Mint 22.3 (kernel: 6.17.0-23-generic)
* Opted into Steam client beta?: No
* Have you checked for system updates?: No (latest version)
* CPU: i5 9600KF
* GPU: NVIDIA GTX 1660 Super

#### Please describe your issue in as much detail as possible:
Everytime I open Far Cry 3: Blood Dragon, the game is running at 4FPS (was 7 at first, but changed the resolution and it got worse) and it just stays like that; tried using Proton 9.0.4, Experimental and did not help. I'm also new to the Linux space, just barely got the Mint distro.

#### Steps for reproducing this issue:

1. Open Far Cry 3: Blood Dragon using Proton Experimental or Proton 9.0.4
2. Check the FPS (using Steam Overlay)

**Comment by falconico** [comment]
Sorry, it wasn't really an issue related to Proton, but to the **NVIDIA 595** drivers. Installing version **580** worked.

**Comment by PotatoAndSickle** [comment]
If people are having issues with performance I’ve found that using the launch option `WINE_CPU_TOPOLOGY=4:1,3,5,7 %command%` made the game run 20-40 better on average. (no idea what it does but i saw it on proton.db)

However the `-offline` launch argument doesn’t force the game to an offline mode, as every time i open the pause menu, it keeps trying and failing to connect to ubisoft servers.

**Before tweak**

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/13bfdaf7-932b-473c-ba99-443799e9907e" />

**After tweak**

<img width="2558" height="1439" alt="Image" src="https://github.com/user-attachments/assets/0532cae4-8bca-430e-90c9-2d89e5f7185a" />
