### ISSUE TITLE
Atomic Heart (668580)

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/Proton#6554]
# Compatibility Report
- Name of the game with compatibility issues: [Atomic Heart](https://store.steampowered.com/app/668580/Atomic_Heart/?snr=1_4_4__118)
- Steam AppID of the game: 668580

## System Information
- GPU: Steam Deck
- Driver/LLVM version: Steam Deck
- Kernel version: Steam Deck
- Proton version: Proton 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Log file: [steam-668580.log](https://github.com/ValveSoftware/Proton/files/10795381/steam-668580.log) that goes up to the difficulty selection where the first missing videos are.

## Symptoms 

None of the in-game videos work. There should be some on difficulty selection but they're blank.

There should also be videos on various screens on the game, they also don't play but you do hear the audio.

## Reproduction

Just try it with Proton, get to the difficulty screen when starting a new game, and notice the black boxes above the options.

It has also now been given a "Steam Deck Playable" rating, but since videos in-game are broken, it shouldn't even be set as Playable should it?

**Comment by kzdixon** [comment]
> None of the in-game videos work. There should be some on difficulty selection but they're blank.

<details><summary>The difficulty screen videos worked for me but none of the others seem to work.</summary>

![2023-02-21-13:35:29-screenshot](https://user-images.githubusercontent.com/10300293/220430382-8cbd7c6b-4362-4c53-9fe0-085e1fc52bb7.png)

</details>

Double-checking all of the files in the game directory, they are all mp4 and play fine in mpv of course.

<details><summary>I get weird artifacting and broken viewport rendering in specific areas, but this may be an RDNA3 quirk.</summary>

![2023-02-20-23:46:38-screenshot](https://user-images.githubusercontent.com/10300293/220430612-2ec167e2-dc96-4fa9-b46b-7120b3165238.jpg)
![2023-02-20-23:46:42-screenshot](https://user-images.githubusercontent.com/10300293/220430617-5be8c2c0-00d7-4b07-97aa-7b2a51e40657.jpg)
![2023-02-20-23:47:05-screenshot](https://user-images.githubusercontent.com/10300293/220430622-c5ad93b8-d5ba-40e8-915f-59e08499c4d7.jpg)

</details>

## System Information
- GPU: AMD Radeon RX 7900 XTX
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 23.1.0-devel (git-af19762935), LLVM 15.0.7
- Kernel version: 6.2.0-zen1-znver3-o3-pds, also using latest amd-drm-next lately
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/kzdixon/c41c048bda27febebb530e6d6846684a
- Proton version: Experimental (Bleeding-Edge), also tried GE 7-49

**Comment by JCDentonCore** [comment]
Same here, no videos!

System Information:

   - CPU: AMD Ryzen 5800x
   - GPU: Nvidia RTX 3070 8 GB
   - Driver: nvidia 525.47.07
   - Kernel version: 6.2.0-1-MANJARO


  - Proton bleeding edge

  Proton log: https://gist.githubusercontent.com/AceroRomano/266b78f5dd594300bf0accd01ef922d5/raw/6429fd3a67f8328c9afd6288d1896da40a96ab39/atomicheartlog.txt

**Comment by joni999** [comment]
I have the same issue on Proton 7.0-6

But videos not working ingame is (at least AFAIK) a well known, long standing issue with proprietary video codecs and the like.
This issue does not occur on GE-Proton7-49, but there's a different issue for me on that version: "Out of video memory trying to allocate rendering resource" - GE-Proton7-49 worked fine the first time I played the game (30mins) but on next boot this error popped up after the intro cutscene:
![image](https://user-images.githubusercontent.com/58270144/221416831-7e4a602e-3d1a-4e86-a805-561eff418b5b.png)

**Comment by alutarius** [comment]
With GE-Proton7-49 the difficulty select videos play alright, but everything in-game still is b0rked for me, like skill upgrade and game over screen videos. No improvement with a fresh prefix either.
Not getting the out of video memory error mentioned by @joni999 so far, but I'm using a current build of vkd3d as GE 49's is already relatively old.

**Comment by mercifulboss** [comment]
I am having random drops in fps in weapon upgrade menu and during cutscenes. It will go from 60fps down to 5 fps and then not go up after. 

Also start with 60fps and then the fps degrades over time from 60 (solid) down to 30 with extreme lagging.

OS: Arch Linux x86_64 
Kernel: 6.2.2-arch1-1
CPU: Intel i7-10750H (12) @ 5.000GHz
GPU: NVIDIA GeForce RTX 2060 Mobile
Memory: 3122MiB / 23903MiB

Example
https://imgur.com/a/Yzgc17a

https://imgur.com/a/pOikg1h

**Comment by niveK77pur** [comment]
> I am having random drops in fps in weapon upgrade menu and during cutscenes. It will go from 60fps down to 5 fps and then not go up after.

@mercifulboss I had the EXACT same issue and weirdly enough found nobody else complain about it. In my case, the issue with drops to 5 fps was mostly resolved by using `gamemoderun`. I have the impression the game's window loses focus (causing this behaviour) and cannot get it back. I don't know if gamemode is an ideal solution but it does the job for now.

**Comment by mbriar** [comment]
> It will go from 60fps down to 5 fps and then not go up after.

sounds like you're running out of vram.

**Comment by mercifulboss** [comment]
> > I am having random drops in fps in weapon upgrade menu and during cutscenes. It will go from 60fps down to 5 fps and then not go up after.
> 
> @mercifulboss I had the EXACT same issue and weirdly enough found nobody else complain about it. In my case, the issue with drops to 5 fps was mostly resolved by using `gamemoderun`. I have the impression the game's window loses focus (causing this behaviour) and cannot get it back. I don't know if gamemode is an ideal solution but it does the job for now.

I am using gamemoderun. Here are my launch options:

`PROTON_HIDE_NVIDIA_GPU=0 PROTON_ENABLE_NVAPI=1 gamemoderun mangohud %command% -dx12`


> > It will go from 60fps down to 5 fps and then not go up after.
> 
> sounds like you're running out of vram.

I thought so too, but the issue persists even when setting the game to `low` settings

Indeed when switching to `low` preset and then restarting the game, the performance on the title screen is atrocious

![Screenshot_20230309_154849](https://user-images.githubusercontent.com/90151527/224154084-6a7306ae-e83e-4602-b0c0-8023b29dd8ec.png)



Does running out of vram cause this issue?

**Comment by alexzk1** [comment]
Try degrade kernel to 6.1.
I just updated today to 6.2.2 from 6.1.x and ALL games stopped to load at all.
Also new feature "split lock detector" breaks FPS heavily, should be disabled for the gaming.

**Comment by JCDentonCore** [comment]
Same error, out of video memory but only with new nvidia vulkan drivers 525.47.13

System Information:

    -CPU: AMD Ryzen 5800x

    -GPU: Nvidia RTX 3070 8 GB

    -Driver: nvidia 525.47.13

    -Kernel version: 6.1.18-1-MANJARO

    -Proton bleeding edge
-------------------------------------------------------------------------------------------------------------------------------------


    *Proton Log: https://gist.github.com/AceroRomano/f780cfb127f6db3de98576aac62af152

**Comment by JCDentonCore** [comment]
> Try degrade kernel to 6.1. I just updated today to 6.2.2 from 6.1.x and ALL games stopped to load at all. Also new feature "split lock detector" breaks FPS heavily, should be disabled for the gaming.

@alexzk1 Try this kernel variable on boot: "split_lock_detect=off"

**Comment by JCDentonCore** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6554#issuecomment-1462770229

@mercifulboss You have Resize Bar activated on Bios?

**Comment by ffrasisti** [comment]
is this working now on deck?

**Comment by anat0lius** [comment]
The difficulty menu videos play fine, but the weapon/skill upgrade menu videos are blank.

Proton 8.0-1
Mesa 23.0.2
Kernel 6.2.11

Otherwise, everything is fine, no performance issues.

update: 

The videos do play ok in the Steam Deck. I don't get it, why there is an issue in desktop only?

Ok, I saw this in the logs:
`winegstreamer: failed to create h264parse, are 64-bit GStreamer "base" plugins installed?`

But I do have installed `gstreamer-plugins-base, gstreamer-plugins-bad, gstreamer-plugins-ugly`, for arch `x86_64` and `i686`.

**Comment by anat0lius** [comment]
Looks like latest `GE-Proton8-4` does make some progress. 

![imagen](https://github.com/ValveSoftware/Proton/assets/4255121/82d4a642-e7a1-4862-94ea-c4a026ea1c02)

Even though the **audio is not synchronized**...

I see several warnings displayed:

![imagen](https://github.com/ValveSoftware/Proton/assets/4255121/42e1f402-e7de-4fbd-9a77-5e5ef48b92dc)

**Comment by NextWork123** [comment]
Hello, with proton-cachyos (based on proton-experimental) i fixed all without having issue with sync audio with installing VLC on the system and i disabled the runtime of lutris

Best Regards,
NextWorks

Update: if you run the game with wayland you need to set SDL_VIDEODRIVER="wayland,x11" or ffmpeg it gonna try to play with x11 the videos, instead we need ffmpeg to play with wayland :)

**Comment by neurolag** [comment]
After waiting for 24 hours (fy, Denuvo), I sadly do have to disagree:
Both `proton-cachyos` (`1732968145 cachyos-9.0-20241123`) and the current `Proton Experimental` (`1732205522 experimental-9.0-20241121b`) still don't work properly.

Here is what happens when playing the "SHOK"-, the "FROSTBITE"-, the "MASS TELEKINESIS"-, the "POLYMERIC JET" and the "POLYMERIC SHIELD" videos in the glove upgrade menus:

  - ***Proton 8.0-5:***
    The preview of the videos is blank. When opening the video fullscreen (by clicking on it), the screen area where the video is supposed to be fades to white
  - ***Proton 9.0-3:***
    The previews work properly, the video plays fine but the audio is lagging behind by multiple seconds
  - ***`proton-cachyos` at `1732968145 cachyos-9.0-20241123`:***
    ***Proton Experimental at `1732205522 experimental-9.0-20241121b`:***
    The videos run with audio **in sync** for 20 seconds. After that, the audio continues playing but the video is frozen for another 20 seconds. Lastly, the remainder of the video plays through. Throughout playing the video, a few debug messages are printed. One that strikes out weird says: `1502282 ERROR gstaacparse.c:358:gst_aac_parse_sink_setcaps:<aacparse64> Need codec_data for raw AAC`

The full log of playing one video with launch args `WINEDEBUG=fixme+mfplat %command%` dumps the following to the console running `steam`:

```log
0:08:01.697249441 1502282 0x7284041719f0 ERROR               aacparse gstaacparse.c:358:gst_aac_parse_sink_setcaps:<aacparse64> Need codec_data for raw AAC
0:08:01.697263638 1502282 0x7284041719f0 ERROR               aacparse gstaacparse.c:358:gst_aac_parse_sink_setcaps:<aacparse64> Need codec_data for raw AAC
062c:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000000.
062c:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000003.
0700:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000002.
0700:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000000.
0700:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000003.
06fc:fixme:mfplat:transform_GetAttributes iface 00000000CFB93158, attributes 00000000D44BFDA8 semi-stub!
0700:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000002.
0700:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000000.
0700:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000003.
0:08:03.571521608 1502282 0x72858407e4b0 ERROR               aacparse gstaacparse.c:358:gst_aac_parse_sink_setcaps:<aacparse66> Need codec_data for raw AAC
0:08:03.571554470 1502282 0x72858407e4b0 ERROR               aacparse gstaacparse.c:358:gst_aac_parse_sink_setcaps:<aacparse66> Need codec_data for raw AAC
06fc:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000000.
06fc:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000002.
0700:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000000.
0700:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000003.
062c:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000002.
062c:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000000.
062c:fixme:mfplat:transform_ProcessMessage Ignoring message 0x10000003.
0:08:31.437675945 1502282 0x7284041719f0 ERROR               aacparse gstaacparse.c:358:gst_aac_parse_sink_setcaps:<aacparse68> Need codec_data for raw AAC
0:08:31.437691755 1502282 0x7284041719f0 ERROR               aacparse gstaacparse.c:358:gst_aac_parse_sink_setcaps:<aacparse68> Need codec_data for raw AAC
```

**Comment by NextWork123** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6554#issuecomment-2509550879

The error seem having issue with the AAC track not with video idk why and seem calling the gstreamer. As i said on my comment i was using vlc and not gstreamer

**Comment by neurolag** [comment]
How do I use vlc instead of gstreamer?
Are there some configurations, env variables or packages I need to install on my Arch system?

Thanks a lot for your response!

**Comment by NextWork123** [comment]
> How do I use vlc instead of gstreamer? Are there some configurations or env variables or packages I need to install on my Arch system?
> 
> Thanks a lot for your response!

The thing i was using lutris and it was fallbacking to vlc with steam i don't know because i bought on vkplay :/

**Comment by neurolag** [comment]
Sadly, I wasn't able to find such an option for Lutris' Steam launcher.
But at least something changed so work that affects it is being done :smile:

Thanks for sharing your experience with me!

**Comment by der-joel** [comment]
I have the same issue using `PROTON-GE10-4`. The log shows `aacparse gstaacparse.c:358:gst_aac_parse_sink_setcaps:<aacparse15> Need codec_data for raw AAC`. I already tried installing `gst-plugins-bad` and `gst-plugins-ugly` as well as different proton versions.

**Comment by kisak-valve** [comment]
after resuming from sleep some games register no input on the Lenovo legion go 2

Issue transferred from https://github.com/ValveSoftware/SteamOS/issues/2390.
@slimsha3 posted on 2026-04-23T16:25:59:

#### Your system information

* Steam client version: 1776812172
* SteamOS version: 3.9 20260421.1000
* Opted into Steam client beta?: Yes
* Opted into SteamOS Main: yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
When playing atomic heart and putting the device into sleep, after resuming the game doesn't register any buttons except for the scroll wheel

#### Steps for reproducing this issue:

1. Own a Lenovo legion go 2
2. Play atomic heart and press the power button to put it to sleep
3. After resuming no buttons except for the scroll wheel works

**Comment by kisak-valve** [comment]
Atomic heart tv audio bug report

Issue transferred from https://github.com/ValveSoftware/Proton/issues/10144.
@Amaderis posted on 2026-09-13T18:14:29:

# Compatibility Report

**Name of the game with compatibility issues:** Atomic Heart
**Steam AppID of the game:** 668580

## System Information

- **GPU:** Gigabyte RTX 4070 Windforce
- **Driver/LLVM version:** NVIDIA 615.71.09
- **Kernel version:** 7.2.4-3-cachyos
- **Distro:** CachyOS (Arch-based)
- **Proton versions tested:** proton-cachyos-11.0-20260703-slr, Proton Experimental (Valve, stock), GE-Proton (latest) - **all three show identical behavior**

## I confirm:

- [x] This report is not for a duplicate issue. I have checked the open and closed issues.
- [x] This report is not for a third-party program, such as ReShade, ENB, DXVK-Async, EAC, BattlEye, or anything else not part of Steam Play or Steam Linux Runtime.

## Symptoms

Cartoon videos ("Nu, Pogodi!") played on the in-world TVs inside save rooms display video correctly but have **no audio**, on all Proton builds tested. All other game audio (SFX, music, dialogue, menu sounds) works normally.

Reported by other users as **not reproducible on native Windows** (Focus/VK Play build) - unconfirmed by me directly, but consistent across multiple people I've talked to.

## Steps to reproduce

1. Launch Atomic Heart, reach any save room with a working TV screen.
2. Interact with / walk into view of the TV so the "Nu, Pogodi!" cartoon starts playing.
3. Video plays normally. No audio is heard, on any output device or channel configuration.

## What I've already ruled out

- **The media file itself is not the problem.** Extracted the relevant `Nu_Pogodi_*.mp4` asset (H.264 + AAC-LC, 48kHz stereo, standard MP4/`mp42` container, Mainconcept encoder) and confirmed via `ffprobe` and direct local playback (`mpv`) that the audio track is valid and plays correctly outside the game.
- **Re-encoding the audio track** (forcing ffmpeg to rewrite a clean `esds`/`codec_data` atom) made no difference in-game, even though it eliminated an early, apparently non-fatal `aacparse` warning (see below).
- **Not a Proton-fork-specific patch.** Tested proton-cachyos, Valve's stock Proton Experimental, and GE-Proton - identical symptom on all three, which rules out downstream fork patches as the cause.
- **Not the `PROTON_USE_PIPEWIRE` audio driver setting.** Tested with `PROTON_USE_PIPEWIRE=0` (falls back off `winepipewire.drv`) - no change.
- **In-game "Streamer Mode" toggle** - tried both on and off, no change.

## Log analysis (`WINEDEBUG=+mfplat,+quartz,+wmvcore,+strmbase,+xaudio2,+dsound PROTON_LOG=1`)

- The GStreamer `aacparse` element logs `Need codec_data for raw AAC` on its first negotiation attempt for the TV's AAC stream, but subsequently **renegotiates successfully** with the correct `codec_data` and produces valid output caps.
- A `wg_transform` (Wine's MFT wrapper) is created for this exact stream with:
  ```
  input caps audio/mpeg, channels=2, codec_data=(buffer)1190, stream-format=raw, mpegversion=4
  output caps audio/x-raw, format=S16LE, channels=2, rate=48000
  ```
  i.e. decoding to valid PCM completes successfully.
- Despite this, **no activity is logged on the `xaudio2`, `dsound`, or `mmdevapi` channels** for this stream at any point (only DLL load/unload boilerplate and one unrelated `mmdevapi:SAC_GetMaxDynamicObjectCount` fixme). This holds regardless of which audio backend (pipewire/pulse) is active.

**Conclusion so far:** decoding is not the bottleneck - the decoded PCM samples from the Media Foundation source reader for this specific media playback path never reach any Windows audio API call that Wine would need to service. Whatever mechanism the game uses to route this particular `MediaPlayer`/`MediaSoundComponent` audio into its own mixer does not appear to fire under Proton, on any tested build. I cannot go further without either game-engine source access or a Wine-side debugger, which is why I'm filing this upstream.

## Related existing reports

- #6554 (this repo) - describes the inverse symptom on Proton 7.0-6 (video missing, audio present) for the same category of in-world screens in this game, suggesting this asset-playback path has been fragile across multiple Proton versions since launch.
- Steam Community reports from launch week describing the same "white screen, audio-only" inverse symptom on various Proton versions.

## Attachments

- `relevant2.log` - filtered log excerpt (grep on `aacparse|codec_data|xaudio|dsound|wmardev|IMFSample|audio.*sink|audio.*device`) from a repro session with the above WINEDEBUG channels enabled.

[relevant2.log](https://github.com/user-attachments/files/32165799/relevant2.log)
