### ISSUE TITLE
Add a proton prefix using newly completed Wine WOW64 mode

### ISSUE THREAD

**Issue by theofficialgman** [ValveSoftware/Proton#6889]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I would like for a proton version to be added using the Wine WOW64 mode. PE conversion has been recently completed (https://www.winehq.org/news/2023012401) and now Wine with WOW64 can be used to run x86 and x86_64 programs on Linux without any i386 Linux userspace.

The mode can be enabled during the configuration of wine at build time with
`--enable-archs=i386,x86_64`
The latest wine staging version (currently 8.12) should be used for this as it has the highest game compatibility with this new mode in use.
## Justification [optional] 
Integration is in Wine but not enabled by default since the mode is still considered experimental. This is extremely useful for the growing number of Linux distros dropping i386 userspace and users not wishing to install i386 userspace to run steam. This is also useful for running windows x86 games on macos x86_64 since MacOS dropped i386 support many years ago. https://github.com/ValveSoftware/Proton/issues/1344

## Risks [optional]
None since this would be an additional proton experimental version.

**Comment by jams3223** [comment]
Great feature request it would greatly benefits distros that stopped using the 32-bit i386 userspace.

**Comment by gabriele2000** [comment]
A quick note on this: trying to build proton-bleeding-edge with this option fails to work as intended, since it's still based on wine-stable.
What you would get is an empty syswow64 folder, and that problem was fixed in wine-staging-8.12 I guess.
Basically we have to wait until wine-9 at this point, since we're near 2024.

Also, let's not forget that Valve hopefully will notice that winewayland.drv development is going really smoothly, I sense a good usability with wine-9

**Comment by Spidy123222** [comment]
> I would like for a proton version to be added using the Wine WOW64 mode. PE conversion has been recently completed (https://www.winehq.org/news/2023012401) and now Wine with WOW64 can be used to run x86 and x86_64 programs on Linux without any i386 Linux userspace.

This would be nice since I would be able to play some games I couldn't on steamdeck that aren't setup via steam like cd version of worms Armageddon which expects WOW64 stuff seems like as some setup sides to have it work is to use proton. 

> Integration is in Wine but not enabled by default since the mode is still considered experimental. This is extremely useful for the growing number of Linux distros dropping i386 userspace and users not wishing to install i386 userspace to run steam. This is also useful for running windows x86 games on macos x86_64 since MacOS dropped i386 support many years ago. https://github.com/ValveSoftware/Proton/issues/1344

Also hopefully get proton on macOS as it's more capable than it was 5 years ago and has translation layers for both vulkan (moltenvk) and OpenGL(zink or just what macOS supports). Crossover and game porting tool kit also shows it that it's very capable when it is setup correctly which imo proton has some magic using steam to have games setup perfectly for proton.

**Comment by theofficialgman** [comment]
Wine 9.0 has released. Hoping Valve decides to make this a reality at least as an option.

While at it, why not make the steam launcher itself native 64bit only and only use 32bit when necessary to run 32bit Linux.

**Comment by dxgldotorg** [comment]
Wine 9.0 is still not 100% on WOW64.  Specifically, OpenGL has degraded performnace and lacks the ARB_buffer_storage extension in Wine WOW64 as opposed to Wine bi-arch.

**Comment by m1m1k4tz** [comment]
I’m pretty sure proton uses DXVK by default so OpenGL performance shouldn’t matter. I’ve been testing the new wow64 mode and I got the steam app working by working around an existing issue with libcef https://bugs.winehq.org/show_bug.cgi?id=44985  and gotten a AAA 32 bit game working perfectly (Fallout 3)

**Comment by m1m1k4tz** [comment]
The libcef thing isn’t an issue with DXVK though

**Comment by dxgldotorg** [comment]
> I’m pretty sure proton uses DXVK by default so OpenGL performance shouldn’t matter. I’ve been testing the new wow64 mode and I got the steam app working by working around an existing issue with libcef https://bugs.winehq.org/show_bug.cgi?id=44985 and gotten a AAA 32 bit game working perfectly (Fallout 3)

It does when a game uses OpenGL; Wine forwards OpenGL to the host.

**Comment by KyunLFA** [comment]
Giving my +1 to this because trying to make Proton build wine in wow64 mode has been horrendous; If anyone has been successful with it, I urge you to ping me.

**Comment by m1m1k4tz** [comment]
> > I’m pretty sure proton uses DXVK by default so OpenGL performance shouldn’t matter. I’ve been testing the new wow64 mode and I got the steam app working by working around an existing issue with libcef https://bugs.winehq.org/show_bug.cgi?id=44985 and gotten a AAA 32 bit game working perfectly (Fallout 3)
> 
> It does when a game uses OpenGL; Wine forwards OpenGL to the host.

Proton is already built with DXVK though right?

**Comment by m1m1k4tz** [comment]
> > I’m pretty sure proton uses DXVK by default so OpenGL performance shouldn’t matter. I’ve been testing the new wow64 mode and I got the steam app working by working around an existing issue with libcef https://bugs.winehq.org/show_bug.cgi?id=44985 and gotten a AAA 32 bit game working perfectly (Fallout 3)
> 
> It does when a game uses OpenGL; Wine forwards OpenGL to the host.

With these patches I think it would help a lot plus the old 32 bit stuff should perform pretty well I’m thinking 
https://gitlab.winehq.org/wine/wine/-/merge_requests/4019
https://gitlab.winehq.org/wine/wine/-/merge_requests/5145

**Comment by m1m1k4tz** [comment]
Box64 is quite close to being able to run the Linux steam app through box32 as well

**Comment by dxgldotorg** [comment]
> > > I’m pretty sure proton uses DXVK by default so OpenGL performance shouldn’t matter. I’ve been testing the new wow64 mode and I got the steam app working by working around an existing issue with libcef https://bugs.winehq.org/show_bug.cgi?id=44985 and gotten a AAA 32 bit game working perfectly (Fallout 3)
> > 
> > 
> > It does when a game uses OpenGL; Wine forwards OpenGL to the host.
> 
> With these patches I think it would help a lot plus the old 32 bit stuff should perform pretty well I’m thinking https://gitlab.winehq.org/wine/wine/-/merge_requests/4019 https://gitlab.winehq.org/wine/wine/-/merge_requests/5145

Does it allow for full OpenGL 4.4+ support in games that use GL?  ARB_buffer_storage is a core extension since 4.4.  Not sure if I'll personally be using it in my own project, but since most Wine installs are still multiarch I might support it anyway if there are benefits.

**Comment by m1m1k4tz** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/6889#issuecomment-2393939485

How many games require that and are also 32 bit? And I think making it an experimental version is a good idea at first. In the big picture I’m looking at running this on Asahi Linux which has no support at all for 32 bit using muvm and hangover with box64 to get the most performance with the smallest disk and battery usage eventually

![](https://raw.githubusercontent.com/AndreRH/hangover/refs/heads/master/benchmarks/2023-10-12/yquake2.exe.png)

**Comment by m1m1k4tz** [comment]
Okay now it runs thru wine with wow64 krun and box64 but it crashes sometimes the problem is going to be proton once the native version runs thru box32 though 
![6CD0E88B-36B3-47E2-9DA7-A113B16B1127](https://github.com/user-attachments/assets/41d5c4c1-a448-4e8d-88a4-560d652fc7e7)

**Comment by artemyto** [comment]
Seems like WOW64 is available in Proton 10 and Proton Experimental. You can try it with PROTON_USE_WOW64 env var: https://github.com/ValveSoftware/Proton/blob/f6c21557315ca695f0e0ca1b2460b7edd18a5e9b/proton#L533
