### ISSUE TITLE
Pioneers of Pagonia (2155180)

### ISSUE THREAD

**Issue by Somamint** [ValveSoftware/Proton#7339]
# Compatibility Report
- Name of the game with compatibility issues: Pioneers of Pagonia
- Steam AppID of the game:2155180

## System Information
Operating System Version: "Pop.OS" (64 bit)
GPU: NVIDIA Corporation NVIDIA GeForce RTX 2060  
Video driver version: 4.6.0 NVIDIA 545.29.06
Proton version: 8.0-4 
## I confirm:

- [ x] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 
The game starts like normal. But once you wanna build something, the game crashes. 

## Reproduction

1. Start Pioneers of Pagonia 
2. Start a new map.
3. Try to build something
4. Game will crash

-->
[steam-2155180.log](https://github.com/ValveSoftware/Proton/files/13659991/steam-2155180.log)
[System Information.txt](https://github.com/ValveSoftware/Proton/files/13659999/System.Information.txt)

**Comment by CubieMedia** [comment]
Same Problem here, also tried with Proton-Experimental.

**Comment by zocker-160** [comment]
I am pretty sure this is still the same issue as I have reported some time ago for the demo: 
https://github.com/HansKristian-Work/vkd3d-proton/issues/1719

It seems that nothing has changed on the game side since then.

**Comment by monarc99** [comment]
It works on my Nvidia 1060, but crashes on e.g. Nvidia 2060 and 3060.

**Comment by Somamint** [comment]
[steam-2155180.log](https://github.com/ValveSoftware/Proton/files/13665731/steam-2155180.log) new log

**Comment by racsnet** [comment]
looked a litle closer. (PROTON_LOG=1 VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation  VKD3D_CONFIG=vk_debug %command%)

Seems like on crash it throws the following (last line repeats endless)

```
19274.146:0140:019c:trace:seh:RtlRestoreContext returning to 000000017000F1EA stack 000000002563E3A0
19274.146:0140:019c:err:seh:KiUserCallbackDispatcher ignoring exception
19274.146:0140:019c:err:vkd3d-proton:vkd3d_debug_messenger_callback: Validation Error: [ VUID-VkRenderingInfo-pDepthAttachment-06088 ] Object 0: handle = 0x7fa1500f6990, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x584a50000002448, type = VK_OBJECT_TYPE_IMAGE_VIEW; Object 2: handle = 0x4f75530000000238, name = Committed Texture (zeroed) (cookie 184), type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x1a3ac387 | vkCmdBeginRendering(): pRenderingInfo->pDepthAttachment->imageView internal image must have been created with VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT. The Vulkan spec states: If pDepthAttachment is not NULL and pDepthAttachment->imageView is not VK_NULL_HANDLE, pDepthAttachment->imageView must have been created with VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkRenderingInfo-pDepthAttachment-06088)
19274.146:0140:019c:err:vkd3d-proton:vkd3d_debug_messenger_callback: Validation Error: [ VUID-VkImageMemoryBarrier2-oldLayout-01659 ] Object 0: handle = 0x4f75530000000238, name = Committed Texture (zeroed) (cookie 184), type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x920e207e | vkCmdPipelineBarrier2(): pDependencyInfo->pImageMemoryBarriers[0].oldLayout (VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL) is not compatible with VkImage 0x4f75530000000238[Committed Texture (zeroed) (cookie 184)] usage flags 0x7. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, and oldLayout or newLayout is VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL then image must have been created with VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier2-oldLayout-01659)
19274.163:0140:0144:warn:vkd3d-proton:d3d12_fence_set_native_sync_handle_on_completion_explicit: Event completion for native sync handle is already in the list.
```

and a dmesg shows:
`NVRM: Xid (PCI:0000:2d:00): 109, pid=437650, name=Pioneers of Pag, Ch 00000076, errorString CTX SWITCH TIMEOUT, Info 0x3c046`

maybe related to https://forums.developer.nvidia.com/t/multiple-cuda-rtx-vulkan-application-crashing-with-xid-13-109-errors/235459/221 ?

**Comment by CubieMedia** [comment]
So it looks like @zocker-160 posted it at the correct address?

**Comment by Somamint** [comment]
> So it looks like @zocker-160 posted it at the correct address?

yes but it got not fixed for everybody.

**Comment by zocker-160** [comment]
If I understood this issue correctly, there are actually two separate problems at play here.

One was caused by vkd3d which got fixed (see the linked issue) and the other one reported here is - [according to the vkd3d devs](https://github.com/HansKristian-Work/vkd3d-proton/issues/1725#issuecomment-1750502414) - caused by an app bug.

I also have to add, that on devices which don't crash, the performance when placing buildings tanks heavily (from over 60fps to 22fps on the Steam Deck for example), so there is something weird going on.

On other AMD based devices (Vega GPU) the game causes my entire system to hang up.

**Comment by Somamint** [comment]
> If I understood this issue correctly, there are actually two separate problems at play here.
> 
> One was caused by vkd3d which got fixed (see the linked issue) and the other one reported here is - [according to the vkd3d devs](https://github.com/HansKristian-Work/vkd3d-proton/issues/1725#issuecomment-1750502414) - caused by an app bug.
> 
> I also have to add, that on devices which don't crash, the performance when placing buildings tanks heavily (from over 60fps to 22fps on the Steam Deck for example), so there is something weird going on.
> 
> On other AMD based devices (Vega GPU) the game causes my entire system to hang up.

so you mean, we can not fix it. The dev need to fix it?

**Comment by zocker-160** [comment]
I am just quoting the devs of vkd3d saying that, which to me sounds like they are probably not willing to implement some kind of hack / workaround to make it run.

This however does not mean that no solution exists outside of the game fixing it (which probably won't happen anytime soon given that it is early access).

My hope is that some wine ace like GloriousEggroll might be able to find a fix for this.

**Comment by Somamint** [comment]
Ok but should be contact GloriousEggroll somehow or just wait in this post?

**Comment by Somamint** [comment]
Its just so strange. That you can play on older GPUS so there must be a way to get it work.

**Comment by u42671** [comment]
Today's Manjaro updates fixed the crashes/freezes which I experienced before, when building something!
I suspect the fix came with the update of Mesa from 23.1 to 23.3.3-1. Maybe also the kernel update from 6.6 to 6.7 is involved.

The game is now running without issues for me with good performance on high graphic settings. I still need Proton Experimental (Some DirectX12 error message when running with Proton 8), but no special commandline settings are required.

Though I'm using a Radeon RX 5700. Any feedback from owners of Nvidia cards, whether Mesa 23.3.3-1 / Kernel 6.7 also fixes this issue for Nvidia?

**Comment by lindesbs** [comment]
No. Manjaro with actual Mesa 23.3.3.1 and nvidia-545.29.06 (RTX 2070) still hangs

**Comment by Somamint** [comment]
So any news about this problem, when the game hangs, when you try to build something?

**Comment by RobertZenz** [comment]
It's still there with Pioneers of Pagonia 0.4.1 (nVidia RTX 3060, 545.29.06), if that is of any help.

**Comment by Root-Core** [comment]
This still is a problem with Nvidia driver 550.67-6 on Manjaro. PoP Version 0.4.3 / 0.5.0 Beta.
The proton log doesn't really help. The only thing that looks strange:

```
18902.293:0110:0530:warn:vkd3d-proton:d3d12_resource_QueryInterface: {6b3b2502-6e51-45b3-90ee-9884265e8df3} not implemented, returning E_NOINTERFACE.
18902.293:0110:0554:warn:vkd3d-proton:d3d12_resource_QueryInterface: {6b3b2502-6e51-45b3-90ee-9884265e8df3} not implemented, returning E_NOINTERFACE.
18902.293:0110:0558:warn:vkd3d-proton:d3d12_resource_QueryInterface: {6b3b2502-6e51-45b3-90ee-9884265e8df3} not implemented, returning E_NOINTERFACE.
18941.424:0110:0558:warn:vkd3d-proton:d3d12_resource_QueryInterface: {6b3b2502-6e51-45b3-90ee-9884265e8df3} not implemented, returning E_NOINTERFACE.
18941.424:0110:0558:warn:vkd3d-proton:d3d12_resource_QueryInterface: {6b3b2502-6e51-45b3-90ee-9884265e8df3} not implemented, returning E_NOINTERFACE.
```

It is also present if you launch the app, before you even load a game. So I think it is unrelated.

**Comment by Matthias-C** [comment]
It's still there with Pioneers of Pagonia 0.5.0-3718+148081 (nVidia RTX 4080, 550.67), if that is of any help.

**Comment by megian** [comment]
https://github.com/HansKristian-Work/vkd3d-proton/issues/1725#issuecomment-2058452620

**Comment by RobertZenz** [comment]
A [fix for the crashes on NVIDIA GPUs seems to be underway](https://github.com/HansKristian-Work/vkd3d-proton/issues/1725#issuecomment-2078660424) and is currently included in the Vulkan developer beta driver branch, and it will land in the next release according to @esullivan-nvidia:

 > The issue with Pioneers of Pagonia freezing on NVIDIA GPUs is currently fixed in the Vulkan developer beta driver branch. It will also be fixed in the upcoming release branch drivers, but the developer beta is the the only public release that has the fix for now.

**Comment by depate** [comment]
Hello!

~I am still experiencing this game crash on AMD based graphics.~

~What is your opinion on the implications on [Mesa][1] and [AMD Vulkan drivers][2] with respect to the Nvidia [fix](https://github.com/ValveSoftware/Proton/issues/7339#issuecomment-2078719158)?~

~Do we have to make mesa or AMD OpenGPU developers aware?~

The issue resolved on my AMD based system using the latest upstream mesa. For more info see this [comment](https://github.com/HansKristian-Work/vkd3d-proton/issues/1725#issuecomment-2184087952).

[1]: https://gitlab.freedesktop.org/mesa/mesa/-/issues
[2]: https://github.com/GPUOpen-Drivers/AMDVLK/issues?q=is%3Aopen

**Comment by RobertZenz** [comment]
The crashes with NVIDIA are resolved with the 555 driver (555.42+), for those curios. 555.58 is the latest release of that series as of right now.

**Comment by torgeros** [comment]
Independently, I was able to run PoP with the latest experimental proton and the 550 driver, even though it used to crash before. I do not know what was updated in the mean time, but my nvidia driver is at 550.

**Comment by zocker-160** [comment]
Can confirm, Nvidia 550.90.07 + Proton Experimental works for me on Ubuntu 22.04.

**Comment by Mershl** [comment]
The new beta version `0.8.0-5072` of Pioneers of Pagonia  introduces movies in tutorial popups which crash on Proton 9.0-2 but work without problems on Proton Experimental and Proton-GE 9-13
