### ISSUE TITLE
Fate/Samurai Remnant (1902690)

### ISSUE THREAD

**Issue by Galmteam** [ValveSoftware/Proton#7412]
# Compatibility Report
- Fate/Samurai Remnant
- 1902690

## System Information
Steam Deck OLED 
Stock SteamOS 3.5.7 stable
Experimental+Proton 8.0-4

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

[steam-1902690.log.zip](https://github.com/ValveSoftware/Proton/files/13943559/steam-1902690.log.zip)

## Symptoms 
Game regularly fully freezes when viewing pre-rendered videos like in the in-game skill menu

## Reproduction
Launch the game on a Steam Deck OLED and go to the in game skill menu or stats screen where it plays a pre-rendered video in the menu and move the cursor around rapidly. The screen will freeze but the game underneath you can tell is still running due to sound effects playing as you navigate around. 

(it seems like it has to be an OLED for some reason? LCD deck users reporting that it only artifacts on LCD)

**Comment by Galmteam** [comment]
Continued testing and playing the game in desktop mode seems to show the white flashing/artifacts that LCD users were describing. Also i haven't had a crash at all so far.

**Comment by ajz34** [comment]
As player, I've also encountered this problem!

I havn't played on PC (Windows or Linux) or Deck LCD currently. But for the description of Deck OLED, it is virtually the same.
Not only the game graphics will be frozen, the information of `Performance Overlay` (Level 2 tested) will also be frozen. However, the game seems to be still running properly (with the sound behaves correctly; and while pressing buttons, the game gives the correct sound effects).

**Comment by SolidSnackDrive** [comment]
I also have the same behavior described by ajz34 on my OLED model, using recommended proton version.

**Comment by Eulenberg** [comment]
This is a SteamOS/GameMode bug, not a Proton bug. Its fixed in the Beta branch of SteamOS (at least 3.5.13)

**Comment by ajz34** [comment]
@Eulenberg Hi!

I tried this game once with SteamOS 3.5.13. I found that screen may flash (white) when switching skill demo videos often. Flashing won't causes fatal screen locked-up.

However, if constantly switching these demo videos very quickly, the screen still have some chance to be locked-up. So (perhaps) chance to be locked-up decreases after upgrading to 3.5.13, this problem probably still exists.

**Comment by SolidSnackDrive** [comment]
Not sure if it's of interest, but I tried playing this game on my Windows 10 PC to see what happens with these videos and it does behave somewhat similarly in that the game will often lock up when hovering over icons that play a video, but unlike the steam deck it does seem to recover without issue.

**Comment by Mirodir** [comment]
I just tried playing it on my Steam Deck for the first time and this issue still persists even with SteamOS 3.5.19 and any Proton version I tried (too many to list them all or remember) from latest all the way back to 7.0-6.

**Comment by shockclown** [comment]
Any update on this? Experiencing the same issue on the skill tree... crashes every time. Gutted. Bought this game after playing on the Switch, to play again with better graphics etc. Currently unplayable. How it gets Steam Verified is baffling.
