### ISSUE TITLE
Assassin's Creed Shadows (3159330)

### ISSUE THREAD

**Issue by ecrevisseMiroir** [ValveSoftware/Proton#8543]
# Compatibility Report
- Name of the game with compatibility issues: Assassin's creed shadows
- Steam AppID of the game: 3159330

## System Information
- GPU: RTX 3080
- Video driver version: Nvidia 570.86.16
- Kernel version: 6.12.6
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: recomended, experimental, 9.0.4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Cannot attach logs as the game blocked me from switching proton versions many times. 

## Symptoms 
Game freezes before accessing the main menu

## Reproduction
1. Run the game
2. Can't access main menu

**Comment by gfrooo1989** [comment]
Same issue on Ubuntu 22.04 with a RTX 3060. Also, here is a video that shows exactly what happens : https://www.reddit.com/r/linux_gaming/comments/1jfdzc9/ac_shadows_cant_access_main_menu_fedora_41_nvidia/

**Comment by c0depath** [comment]
Yeah, I have the same issue on Arch Linux with RTX 4090, also blocked by denuvo after switching proton version too many times in 24h.

**Comment by kerberizer** [comment]
The freeze might be connected to the well known [Xid109 CTX SWITCH TIMEOUT](https://forums.developer.nvidia.com/t/xid109-ctx-switch-timeout-driver-crashes-in-many-applications/283722/16) problem:
> I get the same error with Assassin’s Creed Shadows :
> Game crashes during the after introduction loading screen with
> Xid (PCI:0000:2d:00): 109, pid='<unknown>', name=<unknown>, Ch 00000014, errorString CTX SWITCH > TIMEOUT, Info 0x7c011
> On 560.35.03 and 570.124.04
> Lutris with Proton-GE 9.26, vkd3d 2.14.1, dxvk 2.6

I also have it in the logs (3080 12G, 6.13.7-arch1-1, 570.124.04, Proton Experimental):
```
NVRM: Xid (PCI:0000:08:00): 109, pid=437293, name=ACShadows.exe, Ch 00000034, errorString CTX SWITCH TIMEOUT, Info 0x2ec037
```

On a side note, @benmoussatMouad, you might want to rename the issue to `Assassin’s Creed Shadows (3159330)`, in line with all specific game related issues here.

**Comment by HansKristian-Work** [comment]
Known driver bug.

I made a Pyroveil configuration here: https://github.com/HansKristian-Work/pyroveil/tree/master/hacks/ac-shadows-nvidia-570-stable

See the FF VII Rebirth issue for how people got it to work if the [README](https://github.com/HansKristian-Work/pyroveil/blob/master/README.md) doesn't work.

Another option is to install the latest NVIDIA Vulkan beta driver 570.123.06 which seems to have a fix for it. At least I got past those hangs, but didn't play the game for extended periods to verify or anything. Note that this is not the normal beta driver. The Vulkan beta drivers have different numbering: https://developer.nvidia.com/vulkan-driver (Vulkan Developer Beta Driver Release Updates).

**Comment by FloBEAUG** [comment]
> I made a Pyroveil configuration here: https://github.com/HansKristian-Work/pyroveil/tree/master/hacks/ac-shadows-nvidia-570-stable

Seams to work well. Therefore I had to disable in-game DLSS related options to prevent more craches during cinematics.

Edit:
It's not the DLSS option that craches the game but the VRAM usage.
I have no problem with medium graphics (5500Mo/8000Mo) settings but it crashes when I set the game on high preset (6500Mo/8000Mo)

**Comment by realbardia** [comment]
> I made a Pyroveil configuration here: https://github.com/HansKristian-Work/pyroveil/tree/master/hacks/ac-shadows-nvidia-570-stable

Same Issue on Debian 12
Linux kernel 6.6.80
Nvidia 3080 RTX
Nvidia driver 570.124.06

## Update

After installing Pyroveil patch, I could run and play game successfully with below flags

```bash
PROTON_HIDE_NVIDIA_GPU=1 PROTON_ENABLE_NVAPI=1 PYROVEIL_CONFIG=/home/user/.local/share/pyroveil/hacks/ac-shadows-nvidia-570-stable/pyroveil.json PYROVEIL=1 %command%
```

Thanks to @HansKristian-Work for the patch

**Comment by RespiceFinem** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-2742509737

Can confirm that this works on EndeavourOS, kernel version 6.12.19-1-lts with an RTX 2080, Nvidia Driver Version 570.124.04 running in Proton Experimental. 

Thanks to [@HansKristian-Work](https://github.com/HansKristian-Work) !

**Comment by howels** [comment]
For anyone checking about AMD graphics, it's working great on 7000 series cards. Stock config in Steam and no issues. Ubuntu 24.04 with 6.11 HWE kernel.

**Comment by hiroi-p** [comment]
Hi, I am using a 9070XT and the game runs very well, except for a pretty significant visual bug. The ground textures look like tiles. Similar to a grid with big black lines. 

This looks like a pretty common issue with the gpu, and also I tried multiple proton versions. All of them are like this. I also tried it on my steamdeck and it works fine there.

I am using a ryzen 5800X with the latest bazzite os release  (latest mesa and linux version).

**Comment by MurderFromMars** [comment]
> For anyone checking about AMD graphics, it's working great on 7000 series cards. Stock config in Steam and no issues. Ubuntu 24.04 with 6.11 HWE kernel.

Great thanks for the info bud that's a super helpful contribution to a thread about the issues the game is currently having with nvidia drivers.  you're an absolute legend

**Comment by howels** [comment]
> > For anyone checking about AMD graphics, it's working great on 7000 series cards. Stock config in Steam and no issues. Ubuntu 24.04 with 6.11 HWE kernel.
> 
> Great thanks for the info bud that's a super helpful contribution to a thread about the issues the game is currently having with nvidia drivers. you're an absolute legend

I check these threads before buying games, as I am sure others do also. Therefore it helps prospective buyers. Please keep your responses polite and helpful.

**Comment by sophie-la-li** [comment]
Is the Pyroveil patch working for 550, too?

**Comment by kudlatyamroth** [comment]
CPU: AMD 5800
GPU: Nvidia 3080
Kernel: 6.13
System: manjaro

Pyroveil and nvidia beta drivers fix problem with crash in menu

but i have stuttering/freezes every few seconds... its unplayable that way...
even ubisoft logo stuttering...

**Comment by esullivan-nvidia** [comment]
Thanks for the reports everyone. A fix for the GPU hang in the main menu with NVIDIA drivers will release in the next r570 driver.

**Comment by th3siggy** [comment]
OS: Ubuntu 24.04.2 LTS x86_64 
Host: 83GS LOQ 15IAX9 
Kernel: 6.11.0-21-generic 
Resolution: 1920x1080 
CPU: 12th Gen Intel i5-12450HX (12) @ 4.400GHz 
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU 
Memory: 5669MiB / 64079MiB 
NVidia driver version  570.124.04
The game freezes right before the menu. Any idea which driver version is the right one? I tried to install 570.123.06 but haven't been able to make it work properly. The current version i have is higher but it may not have the fix mentioned?

**Comment by evilangel89** [comment]
Sadly pyroveil doesn't fix the issues for me either. I am running the game on a bazzite-deck-nvidia:testing branch on a Lenovo Legion 7 on RTX 3070 with nvidia driver 570.133.07. The game has lots of freezing, stuttering and artifacts 

Please see the video below.  
https://youtube.com/shorts/Dut3b14MBmE?si=rUIQXF6CeS4mBqI8

Any pointers in resolving ?

**Comment by rafalcieslak** [comment]
It used to run perfectly fine for me, thanks to Pyroveil, until today. But after the recent game update it is back to freezing as soon as intro videos stop and 3d character models appear. Could it be that the Pyroveil config needs an update for game version 1.0.2?

**Comment by FloBEAUG** [comment]
I can confirm it's broken again in 1.0.2 of the game.

Edit : I tried disabling the pyroveil hack but no success either.
Edit2 : I tried installing beta driver 570.123.07 (latest one) but it broke my system and I had to revert back to vanilla driver (No luck here I may retry tonight)

**Comment by Amaderis** [comment]
Yes this is broken again on version 1.0.2

**Comment by Amaderis** [comment]
Issue solved.
https://github.com/HansKristian-Work/pyroveil/issues/9

**Comment by praz01** [comment]
> Known driver bug.
> 
> I made a Pyroveil configuration here: https://github.com/HansKristian-Work/pyroveil/tree/master/hacks/ac-shadows-nvidia-570-stable
> 
> See the FF VII Rebirth issue for how people got it to work if the [README](https://github.com/HansKristian-Work/pyroveil/blob/master/README.md) doesn't work.
> 
> Another option is to install the latest NVIDIA Vulkan beta driver 570.123.06 which seems to have a fix for it. At least I got past those hangs, but didn't play the game for extended periods to verify or anything. Note that this is not the normal beta driver. The Vulkan beta drivers have different numbering: https://developer.nvidia.com/vulkan-driver (Vulkan Developer Beta Driver Release Updates).

Patch 1.0.2 seems to have borked this on my system. Is anyone else seeing the return of the hanging bug when the main menu loads? Perhaps the pyroveil config needs to be updated to counteract whatever douchebaggery Ubisoft put into this patch?:(

EDIT: Please ignore, just seen above https://github.com/HansKristian-Work/pyroveil/issues/9 :)

**Comment by Amaderis** [comment]
> Perhaps the pyroveil config needs to be updated

Literally my last posting.

**Comment by pquerner** [comment]
Hey,

after starting a new game I immediately get a game crash.

I have to use pyroveil since I am using a Nvidia 3080 card with driver 570.133.07.

pyroveil is at `59370a3ad7688e044d917e10f006f90702885925` (for AC 1.0.2 patch)

Game startup command: `mangohud PROTON_LOG=1 PYROVEIL=1 PYROVEIL_CONFIG=/home/paco/programs/pyroveil/hacks/ac-shadows-nvidia-570-stable/pyroveil.json %command%`

Log:
[steam-3159330.log](https://github.com/user-attachments/files/19758580/steam-3159330.log)

What else is wierd:
Sometimes I can only get to the main menu if I delete the `dlc_10` folder (from the games installation directory), else I get stuck at "memory something something at 93%" and then get a game crash aswell.
Sometimes it works with the folder in place tho.

However, I am for now `always` receiving a game crash when starting a new game.

Looking at protondb it seems nobody else has this problem.

Kernel: Linux 6.14.2-arch1-1
OS: EndeavourOS x86_64
DE: KDE Plasma 6.3.4
WM: KWin (X11)
CPU: 12th Gen Intel(R) Core(TM) i7-12700K (20) @ 5.00 GHz

**Comment by praz01** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-2804995375 

Have you tried clearing vkd3d-proton.cache and vkd3d-proton.cache.write again? I've read that others have had luck clearing the entire Steam cache (bit extreme).

I'm on Flatpak and latest pyrovile but my driver is older and have not had any issues other than horse jumping around in the spot while area loads, but I think that's a game bug.

**Comment by pquerner** [comment]
Yes I tried that aswell. Also in the Documents dir (prefix) I've deleted the ACShadows folder and in the Uplay directory I've deleted the savegames folders. (As per instruction given here: https://steamcommunity.com/app/3159330/discussions/1/612032512885029086/?l=english&ctp=2)

Some comments say this is due to framegen and DLSS. But right now I dont get to see the main menu anymore, so I cant even go to the graphics options to change any thing. And I didnt figure out what line I need to change or add in the ACShadows.ini confuguration file to switch that setting.

**Comment by peterhuene** [comment]
I can confirm that the title screen hang observed with an Nvidia card (I was previously using driver `570.133.07`) has been fixed with today's released beta version `575.51.02`.

**Comment by realbardia** [comment]
> I can confirm that the title screen hang observed with an Nvidia card (I was previously using driver `570.133.07`) has been fixed with today's released beta version `575.51.02`.

I confirm too. It fixed and runs great without pyroveil now \\:D/

**Comment by pquerner** [comment]
For me it still crashes. :(
I've updated to nvidia beta 575.51.02 drivers and restarted my pc.

run command: `mangohud PROTON_LOG=1 WINEDLLOVERRIDES=libglesv2.dll=d DXVK_FRAME_RATE=60 %command%`

[steam-3159330 (1).zip](https://github.com/user-attachments/files/19811778/steam-3159330.1.zip)
[steam-3159330_after_clear_protoncachefiles.zip](https://github.com/user-attachments/files/19811777/steam-3159330_after_clear_protoncachefiles.zip)
[steam-3159330_after_clear_settings_and_savegames.zip](https://github.com/user-attachments/files/19811779/steam-3159330_after_clear_settings_and_savegames.zip)
[steam-3159330_after_patch.zip](https://github.com/user-attachments/files/19811780/steam-3159330_after_patch.zip)

Symptoms:
After the game verifies that I am online, I am getting a message about "Memory add-ons (...) 94%" (sometimes 93, or 96%) and then the game crashes.
I've tried other tips such as running in windowed mode (ALT+ENTER) and ALT-Tabbing when the check occurs, but I couldnt make it.

**Comment by praz01** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-2815260700

Sorry, silly question, did you blow away the cache?

**Comment by pquerner** [comment]
The only cache files I cleared were `vkd3d-proton.cache` in the game installation folder.

**Comment by jaredturck** [comment]
I'm running game with command `PYROVEIL=1 PYROVEIL_CONFIG=/home/jared/Downloads/AC_config.json %command%`

Below is my JSON config
```
{
        "version": 2,
        "type": "pyroveil",
        "matches": [
                { "opStringSearch": "ba0972137f375df0", "action": { "glsl-roundtrip": true } },
                { "opStringSearch": "e609bfa36b9bc424", "action": { "glsl-roundtrip": true } }
        ],
        "disabledExtensions": [ "VK_NV_raw_access_chains" ]
}
```
i'm using Proton 9.0-4, game loads fine and i can play for a bit with pyroveil, but as soon as I enter a cut scene the game freezes.

OS: `linux 6.14.2.arch1-1`
Driver: `nvidia 570.133.07-5`
GPU: RTX 2080 SUPER

**Comment by notFunnys** [comment]
> Hi, I am using a 9070XT and the game runs very well, except for a pretty significant visual bug. The ground textures look like tiles. Similar to a grid with big black lines. 
> 
> This looks like a pretty common issue with the gpu, and also I tried multiple proton versions. All of them are like this. I also tried it on my steamdeck and it works fine there.
> 
> I am using a ryzen 5800X with the latest bazzite os release  (latest mesa and linux version).

The problem is unfortunately still there and no fix has been found yet 

mesa 1:25.0.4-1

**Comment by FloBEAUG** [comment]
[Logs-lutris.txt](https://github.com/user-attachments/files/20540096/Logs-lutris.txt)

The game works fine but I still encounter random craches (cf full logs).

Bellow the capture of the crach:
```11339.403:0660:07a4:err:vkd3d-proton:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
11339.403:0660:07a4:err:vkd3d-proton:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
11339.403:0660:07a4:err:vkd3d-proton:dxgi_vk_swap_chain_submit_blit: Failed to submit swapchain blit, vr -4.
11339.403:0660:07a4:err:vkd3d-proton:dxgi_vk_swap_chain_present_signal_blit_semaphore: Failed to submit present discard, vr = -4.
11339.403:0660:07a4:err:vkd3d-proton:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
11339.403:0660:07a4:err:vkd3d-proton:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
11339.403:0660:07a4:err:vkd3d-proton:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
11339.403:0660:07a4:err:vkd3d-proton:dxgi_vk_swap_chain_submit_blit: Failed to submit swapchain blit, vr -4.
11339.403:0660:07a4:err:vkd3d-proton:dxgi_vk_swap_chain_present_signal_blit_semaphore: Failed to submit present discard, vr = -4.```
```

Here relevent system information :
```
System:
  Kernel: 6.8.0-60-generic arch: x86_64 bits: 64 compiler: gcc v: 13.3.0 clocksource: tsc
  Desktop: Cinnamon v: 6.4.8 tk: GTK v: 3.24.41 wm: Muffin v: 6.4.1 vt: 7 dm: LightDM v: 1.30.0
    Distro: Linux Mint 22.1 Xia base: Ubuntu 24.04 noble

CPU:
  Info: 6-core model: AMD Ryzen 5 3600 bits: 64 type: MT MCP smt: enabled arch: Zen 2 rev: 0 cache:
    L1: 384 KiB L2: 3 MiB L3: 32 MiB
  Speed (MHz): avg: 2200 high: 2201 min/max: 2200/4208 boost: enabled cores: 1: 2200 2: 2201
    3: 2200 4: 2201 5: 2200 6: 2200 7: 2199 8: 2201 9: 2200 10: 2200 11: 2200 12: 2200
    bogomips: 86402
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA TU104 [GeForce RTX 2080] vendor: Micro-Star MSI driver: nvidia v: 570.153.02
    arch: Turing pcie: speed: 5 GT/s lanes: 16 ports: active: none off: DP-1,DP-3,HDMI-A-1
    empty: DP-2 bus-ID: 2d:00.0 chip-ID: 10de:1e82 class-ID: 0300
  API: EGL v: 1.5 hw: drv: nvidia platforms: device: 0 drv: nvidia device: 2 drv: swrast gbm:
    drv: nvidia surfaceless: drv: nvidia x11: drv: nvidia inactive: wayland,device-1
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 570.153.02 glx-v: 1.4
    direct-render: yes renderer: NVIDIA GeForce RTX 2080/PCIe/SSE2
  API: Vulkan v: 1.3.275 layers: 9 surfaces: xcb,xlib device: 0 type: discrete-gpu driver: N/A
    device-ID: 10de:1e82 device: 1 type: cpu driver: N/A device-ID: 10005:0000

  Memory: total: 32 GiB available: 31.26 GiB used: 3.02 GiB (9.7%)
  Processes: 356 Power: uptime: 3h 14m states: freeze,mem,disk suspend: deep wakeups: 0
    hibernate: platform Init: systemd v: 255 target: graphical (5) default: graphical
  Compilers: clang: 14 alt: 18 gcc: 13.3.0 alt: 6/7/9/10/11/12 Client: Cinnamon v: 6.4.8
    inxi: 3.3.34

NVIDIA-SMI 570.153.02             Driver Version: 570.153.02     CUDA Version: 12.8 
Proton-GE 9.27 (wanted to try with Proton-GE 10.3 but uplay doesn't launch)
```

**Comment by FloBEAUG** [comment]
I made some more tests with the in-game benchmark , it looks like DXVK NVAPI version+ Graphic options have a role to play :

DXVK NVAPI 0.9.0 + Graphics Low --> Crash on first few frames
DXVK NVAPI 0.8.0 + Graphics Low --> PASS (55 FPS 4500MB/7800MB VRAM)
DXVK NVAPI 0.8.0 + Graphics Medium --> (PASS 50 FPS 4800MB/7800MB VRAM)
DXVK NVAPI 0.8.0 + Graphics  High --> (PASS 45 FPS 5200MB/7800MB VRAM)
DXVK NVAPI 0.8.0 + Graphics Very High --> Crash on first few frames

Under NVAPI 0.8.0, the game still crashes  randomly in cut scenes or when quitting the inventory, but less often compared when running with NVAPI 0.9.0

**Comment by kisak-valve** [comment]
Assassin's Creed Shadows (3159330) crashes before main menu on Fedora 42 with AMD GPU

Issue transferred from https://github.com/ValveSoftware/Proton/issues/9049.
@TheVodouch posted on 2025-09-16T21:39:00:

# Compatibility Report
- Name of the game with compatibility issues: Assassin's Creed Shadows
- Steam AppID of the game: 3159330

## System Information
- GPU: AMD RX 9070 XT
- Video driver version: Mesa 25.1.7
- Kernel version: Linux 6.16.7-200.fc42.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): [Gist](https://gist.github.com/TheVodouch/c2604a54af33a1cc1d2b8bb15d2b31bd)
- Proton version: Experimental/9.0-4/10.0-2/GE-Proton10-15

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.



[steam-3159330.log](https://github.com/user-attachments/files/22371980/steam-3159330.log)

## Symptoms 

Game launches, before accessing the main menu the game warns me about having the game installed on a HDD (I do not it's on a samsung NVMe SSD.) After clicking OK the game crashes. You can also see the main menu just for a split second before the crash.

## Reproduction
Start game
Wait for intro to finish
CRASH

**Comment by theHamsta** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-3300442211

I'm seeing the same issue as in this report. I also saw this line in the PROTON_LOG. Having this issue since applying the 1.1.1 patch 
```
wine: Unhandled page fault on read access to 0000000000000000 at address 0000000141B10197 (thread 04e0), starting debugger...
```
There are also several reports on protondb describing the problem with the 1.1.1 patch https://www.protondb.com/app/3159330

**Comment by dylanmtaylor** [comment]
This is crashing for me on Nvidia driver 580.82.07, 

```
PYROVEIL=1 PYROVEIL_CONFIG=/home/dylan/pyroveil/hacks/ac-shadows-nvidia-570-stable/pyroveil.json %command%
```

does not work

**Comment by theHamsta** [comment]
I saw some indicating at  https://www.protondb.com/app/3159330 to check game files for integrity or copying files over from a Windows installation. Checking for integrity detected corrupt files and redownloaded them. Now the crash is gone. On the very first launch after the integrity check I accidentally started with SW rendering which required incredible amounts of RAM but made it until the title screen.

**Comment by zeinoux** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-3358089161

So, we have to copying the save game from windows to `"$HOME/.local/share/Steam/steamapps/compatdata/3159330/pfx/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/savegames/"

Or any another method for run this game without dual booting?

**Comment by praz01** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-3404694298

This game runs perfectly under Ubisoft launcher in Lutris. You won't even have to move the game files. My game files are on an NTFS partition and I use the import game functionality of Ubisoft Game Launcher.

**Comment by zeinoux** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-3404764732

Unfortunately i bought this game from steam not from unplay store

**Comment by praz01** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-3404902998

My understanding of the handover between Steam and Ubisoft is through a Ubisoft account. You would have had to create one when you first installed the game and associate it with Steam. This account can then be used for accessing all your Ubisoft titles directly from Ubisoft launcher. You can check the account details in the linked account section of Steam. You would also have received an email from Ubisoft when you registered the game purchase.

**Comment by Blisto91** [comment]
The issue with the game silently shutting down before menu should be fixed on [Proton Bleeding Edge](https://github.com/ValveSoftware/Proton/wiki/Proton-Versions#proton-bleeding-edge). Thank you for the reports.

**Comment by zeinoux** [comment]
> The issue with the game silently shutting down before menu should be fixed on [Proton Bleeding Edge](https://github.com/ValveSoftware/Proton/wiki/Proton-Versions#proton-bleeding-edge). Thank you for the reports.


EDIT: 
It worked as a charm!!

Thank you @Blisto91

**Comment by LordDaveTheKind** [comment]
I was able to play the game in March/April. Now I am facing an unhandled exception issue:

`Unhandled exception: page fault on read access to 0x0000000000000018 in 64-bit code (0x0000014254ad55).`

I tried with all versions of Proton, including Experimental (Bleeding Edge). My system settings are the following:
OS: Manjaro Linux
KERNEL: 6.17.6-1-MANJARO
CPU: AMD Ryzen 7 5800X 8-Core
GPU: AMD Radeon RX 9070 XT (radeonsi, gfx1201, LLVM 21.1.4, DRM 3.64, 6.17.6-1-MANJARO)
GPU DRIVER: 4.6 Mesa 25.2.6-arch1.1
RAM: 64 GB

I uploaded the full log at the link [steam-3159330.log](https://raw.githubusercontent.com/LordDaveTheKind/log-dumps/refs/heads/main/steam-3159330.log).

**Comment by owen7900** [comment]
This issue is still occurring for me on Experimental (Bleeding Edge)

**Comment by pollux78** [comment]
> This issue is still occurring for me on Experimental (Bleeding Edge)

PROTON_LOG=1 %command% as the launch command on the game in steam, game, proprieties, upload the log from the home folder to here with core information about the system you have aswell like distro, kernel, drivers, GPU.  

And of course what problem is still occuring for you.

**Comment by owen7900** [comment]
The game locks up just before loading the main menu. 

I have uploaded the full log (50 MB) [here](https://raw.githubusercontent.com/owen7900/log_dumps/refs/heads/master/AC_Shadows/steam-3159330.log).
```
======================
Proton: 1745943995 experimental-bleeding-edge-9.0-191846-20250429-p965305-wfc8c710-d27b71a-v4ec9ec
SteamGameId: 3159330
Command: ["/home/owen/.local/share/Steam/steamapps/common/Assassin's Creed Shadows/ACShadows.exe", '-uplay_steam_mode']
Options: {'forcelgadd'}
depot: 3.0.20250929.168600
pressure-vessel: 0.20250926.0 scout
scripts: 0.20250926.0
sniper: 3.0.20250929.168600 sniper 3.0.20250929.168600
Kernel: Linux 6.8.0-86-generic #87-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep 22 18:03:36 UTC 2025 x86_64
Language: LC_ALL None, LC_MESSAGES None, LC_CTYPE None
Effective WINEDEBUG: +timestamp,+pid,+tid,+seh,+unwind,+threadname,+debugstr,+loaddll,+mscoree
======================
```

**Comment by Sharps97** [comment]
I have the same issue as above.  Used to run fine, now it doesn't start up (ubi launcher never pops and the game doesn't start up).

**Comment by eyenalxai** [comment]
> I have the same issue as above. Used to run fine, now it doesn't start up (ubi launcher never pops and the game doesn't start up).

i had the same issue and installing lib32-vulkan-radeon fixed it for me.

**Comment by praz01** [comment]
Are people still experiencing issues with this game? I've been playing this game without any issues on latest proton without needing Pyroveil since the release of patch 1.0.4. Now I'm running 1.1.8 with manual jumping and everything works great. Happy to walk through with anyone still struggling.

**Comment by ssareta** [comment]
> I have the same issue as above. Used to run fine, now it doesn't start up (ubi launcher never pops and the game doesn't start up).

I suddenly started having this issue after updating my GPU drivers to the 595 beta (nvidia), but just deleting the entire proton prefix in compatdata fixed it for me.

**Comment by Blcktape** [comment]
Does the issue still persists with the RTX 3080?

**Comment by wolf0403** [comment]
# Compatibility Report
- Name of the game with compatibility issues: Assasin's Creed Shadows
- Steam AppID of the game: 3159330

## System Information
- GPU: AMD AMD Radeon 8060S Graphics
- Video driver version: 4.6 (Compatibility Profile) Mesa 26.0.5
- Kernel version:  6.19.14-ogc5.1.fc44.x86_64
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: 1780064122 experimental-11.0-20260529

[steam-3159330.log](https://github.com/user-attachments/files/28707329/steam-3159330.log)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.



## Symptoms 
When I select "Quit to Desktop" from the game, the game exists but Steam doesn't detect that and still considers the game running (the launch button shows as "Stop" rather than "Play"

## Reproduction

Go into game page in Library, press "Play"
Wait for game launch, go into main menu
Select "Quit to Desktop", wait for game to quit.

Observe that Steam library page still shows the button as "Stop" (blue) and game time is still counting.

**Comment by kisak-valve** [comment]
Assassin's Creed Shadows (3159330) hangs on RTX 5080 / NVIDIA open 610.43.02, stuck in vkd3d waits

Issue transferred from https://github.com/ValveSoftware/Proton/issues/9863.
@ragne1d posted on 2026-06-09T10:28:21:

# Compatibility Report

- Name of the game with compatibility issues: Assassin's Creed Shadows
- Steam AppID of the game: 3159330

## System Information

- GPU: NVIDIA GeForce RTX 5080
- Video driver version: NVIDIA open kernel module / NVIDIA driver 610.43.02
- Kernel version: linux-cachyos 7.0.11-1 and linux-cachyos-lts 6.18.34-1 tested
- Desktop/session: KDE Plasma on Wayland
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ragne1d/8bfb16a41c98b622c543e403250d4a4c
- Proton version: Proton Experimental, Proton Hotfix, GE-Proton10-34, Proton 10.0-4, proton-cachyos-11.0-20260521

## I confirm:

- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms

Assassin's Creed Shadows hangs reproducibly on my system when loading a save and walking toward a specific city/area. The screen freezes, audio continues briefly, then stops. The process does not crash by itself and remains killable from a TTY with:

`pkill -f ACShadows`

This does not look like a normal crash, OOM, or NVIDIA Xid/GPU reset. Multiple hang captures taken while the game was frozen show:

- ACShadows.exe still alive
- State: S / sleeping
- GPU utilization: 0%
- GPU memory used by ACShadows: around 7-9 GiB depending on settings
- System RAM used by ACShadows: around 9 GiB resident
- No OOM killer activity found
- No segfault found
- No useful NVIDIA NVRM/Xid GPU error found

The process appears stuck in Wine/Proton waits with vkd3d-related threads involved. Repeatedly visible in the captures/backtraces:

- vkd3d_fence
- vkd3d_queue
- vkd3d-swapchain
- linux_wait_objs
- NtWaitForAlertByThreadId
- NtWaitForSingleObject
- fsync_wait_objects / ntsync ioctl depending on Proton/sync mode

NVIDIA Streamline / NVAPI / CUDA libraries are loaded in the process even when DLSS/frame generation are disabled or minimized in the game UI:

- NVStreamline/production/sl.reflex.dll
- NVStreamline/production/sl.pcl.dll
- NVStreamline/production/sl.common.dll
- NVStreamline/production/sl.interposer.dll
- NVStreamline/production/sl.dlss.dll
- NVStreamline/production/sl.dlss_g.dll
- NVStreamline/production/nvngx_dlss.dll
- NVStreamline/production/nvngx_dlssg.dll
- nvapi64.dll
- libcuda.so.610.43.02
- libnvidia-glcore.so.610.43.02

The hang occurs across several Proton versions:

- Proton Experimental
- Proton Hotfix
- GE-Proton10-34
- Proton 10.0-4
- proton-cachyos-11.0-20260521

The hang also occurs with both higher and reduced graphics settings.

Reduced settings tested:

- Preset: Very High
- Ray tracing: Only Hideout / minimum available option
- Frame generation: Off
- Upscaling/AA: TAA Native
- FPS cap: 60
- Cinematic FPS cap: 30

The hang still occurred with the same route/scene. This makes it unlikely to be simply Ultra settings, high FPS, frame generation, or pure VRAM exhaustion.

Things tested / ruled out:

- No useful NVIDIA Xid / GPU reset found
- No OOM found
- No segfault found
- Tried disabling NTSYNC / FSYNC / ESYNC; still hangs
- Tried split_lock_mitigate=0; still hangs
- Tested with Steam overlay removed from the process; still hangs
- Tested with Steam Fossilize / shader pre-cache Vulkan layer not loaded; still hangs
- Forced NVIDIA Vulkan ICD to avoid Radeon/Mesa ICD from AMD iGPU; still hangs
- Tested linux-cachyos 7.0.11 and linux-cachyos-lts 6.18.34; still hangs
- KDE Wayland was used for the tests. I did not test a full X11 session.

I also tested with Proton logging previously, but the Proton log did not show an obvious crash/error at the moment of the hang. The attached emergency captures were taken from TTY while the process was still frozen/alive.

Important NVIDIA driver note:

I attempted to test the proprietary 580xx NVIDIA DKMS driver, but the RTX 5080 refused it with:

`NVRM: The NVIDIA GPU 0000:01:00.0 (PCI ID: 10de:2c02) installed in this system requires use of the NVIDIA open kernel modules.`

So the system was restored to NVIDIA open 610.43.02.

Main launch options used for the relevant tests:

`VK_DRIVER_FILES=/usr/share/vulkan/icd.d/nvidia_icd.json VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json %command%`

## Reproduction

1. Start Assassin's Creed Shadows from Steam.
2. Load the affected save.
3. From the loaded position, walk forward toward a specific city/area.
4. Within a few seconds, the game freezes.
5. Audio continues briefly, then stops.
6. The process remains alive and must be killed manually from a TTY.

Interesting observation:

If I walk in the opposite direction from the same save, the game may not hang immediately. The issue appears route/scene/workload dependent rather than completely random. However, it can also hang later in other areas.

## Attachments

I am attaching hang captures generated while the game was frozen, before killing it:

- acs-emergency-2026-06-09-114150.tar.gz - Proton Experimental, route/scene that reproduces the hang quickly.
- acs-emergency-2026-06-09-114911.tar.gz - Reduced graphics settings: Very High, RT minimum available option, frame generation off, TAA Native, FPS capped to 60. Same route/scene still hangs.
- acs-emergency-2026-06-09-115613.tar.gz - Proton Hotfix. Same hang pattern.
- acs-emergency-2026-06-09-120048.tar.gz - GE-Proton10-34. Same hang pattern. The game warned about unsupported drivers but allowed gameplay.
- acs-emergency-2026-06-09-120507.tar.gz - Proton 10.0-4. Same route/scene and same hang pattern.

## Request

Could this be investigated as a possible vkd3d-proton / NVIDIA open 610.43.02 / Streamline-CUDA-NVAPI deadlock?

The most suspicious repeated pattern is that the process does not crash but gets stuck in waits involving vkd3d fence/queue/swapchain, while NVIDIA Streamline/CUDA/NVAPI libraries are loaded, with no NVIDIA Xid, no OOM, and no segfault.

[acs-emergency-2026-06-09-114150.tar.gz](https://github.com/user-attachments/files/28750766/acs-emergency-2026-06-09-114150.tar.gz)

[acs-emergency-2026-06-09-114911.tar.gz](https://github.com/user-attachments/files/28750765/acs-emergency-2026-06-09-114911.tar.gz)

[acs-emergency-2026-06-09-115613.tar.gz](https://github.com/user-attachments/files/28750768/acs-emergency-2026-06-09-115613.tar.gz)

[acs-emergency-2026-06-09-120048.tar.gz](https://github.com/user-attachments/files/28750767/acs-emergency-2026-06-09-120048.tar.gz)

[acs-emergency-2026-06-09-120507.tar.gz](https://github.com/user-attachments/files/28750764/acs-emergency-2026-06-09-120507.tar.gz)

**Comment by defhed** [comment]
> Assassin's Creed Shadows (3159330) hangs on RTX 5080 / NVIDIA open 610.43.02, stuck in vkd3d waits

Any update on this? I haven't been able to play in like a month. Happens on 595 drivers for me too, hoped the 610 would fix it but didn't. The crashes happen at the same spots every time.

**Comment by ssareta** [comment]
A workaround I have been using for the exact above issue is to manually make a debug build of vkd3d-proton, replace the proton d3d12 dlls with these, and set `VKD3D_CONFIG=descriptor_heap,breadcrumbs VKD3D_DEBUG=err` in launch options. 

I guess something in the debug/breadcrumbs takes care of the fence issues, because I was getting many freezes in many different areas in AC Shadows (exact same symptoms as @ragne1d), but this basically took care of them all, lets me play for hours without crashing. 

The original goal of the debug build was to capture some more useful logs, but it ended up solving the issues, so... at least it works on 595 drivers (although I haven't checked 595.84 yet, but it worked with the older 595 releases, including the vulkan betas). Doesn't seem to cause much perf loss either, so it's ok as a workaround for now (using RTX 5000 series so the `descriptor_heap` is needed on 595 drivers to not get Xid 109s instead).

Some related discussion here on the nvidia forums: https://forums.developer.nvidia.com/t/595-release-feedback-discussion/362561/140

**Comment by Jakeshadow** [comment]
For anyone landing here in 2026 — this issue has evolved across multiple game patches and driver versions, so scroll to the most recent comments for your GPU generation. A few patterns that keep coming up:

- **Nvidia (pre-5000 series):** The original Xid 109 hang was fixed in driver 575.51.02+. If you're still on 570.x, upgrading the driver is the first step.
- **Nvidia 5000 series (open kernel):** The vkd3d fence/swapchain hang described by @ragne1d is still being investigated. @ssareta's workaround (debug build of vkd3d-proton with `VKD3D_CONFIG=descriptor_heap,breadcrumbs`) is the best known fix for now — see [comment above](https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-4826067179).
- **AMD 9000 series:** The tiled ground texture bug on 9070 XT is a Mesa issue, not Proton — track it on the Mesa GitLab.
- **Denuvo lockouts:** If you switch Proton versions too many times in 24h, Denuvo rate-limits you. Only fix is to wait. This is anti-cheat / DRM policy, not a Proton bug per se — some games have stricter limits than others.

Also worth noting: if you're evaluating whether to buy a game primarily for Linux/Steam Deck, checking its anti-cheat compatibility upfront saves the "bought it and it won't launch" frustration. Community-maintained lists exist that track which anti-cheat systems work under Proton and which don't.

**Comment by Saancreed** [comment]
> * **Nvidia 5000 series (open kernel):** The vkd3d fence/swapchain hang described by [@ragne1d](https://github.com/ragne1d) is still being investigated. [@ssareta](https://github.com/ssareta)'s workaround (debug build of vkd3d-proton with `VKD3D_CONFIG=descriptor_heap,breadcrumbs`) is the best known fix for now — see [comment above](https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-4826067179).

@Jakeshadow That's not exactly correct, this issue is not limited to "5000 series". Well, the `descriptor_heap` part of the workaround is, but the original workaround I came up with (just `breadcrumbs` on debug build) was for my Ada GPU. On Ada, there's little to no difference between `VKD3D_CONFIG=descriptor_heap,breadcrumbs` and `VKD3D_CONFIG=breadcrumbs`.

**Comment by praz01** [comment]
> > * **Nvidia 5000 series (open kernel):** The vkd3d fence/swapchain hang described by [@ragne1d](https://github.com/ragne1d) is still being investigated. [@ssareta](https://github.com/ssareta)'s workaround (debug build of vkd3d-proton with `VKD3D_CONFIG=descriptor_heap,breadcrumbs`) is the best known fix for now — see [comment above](https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-4826067179).
> 
> [@Jakeshadow](https://github.com/Jakeshadow) That's not exactly correct, this issue is not limited to "5000 series". Well, the `descriptor_heap` part of the workaround is, but the original workaround I came up with (just `breadcrumbs` on debug build) was for my Ada GPU. On Ada, there's little to no difference between `VKD3D_CONFIG=descriptor_heap,breadcrumbs` and `VKD3D_CONFIG=breadcrumbs`.

I can verify this. It's not just a "5000 series" issue. I have the following setup.

- Nvidia RTX 3060 12GB
- CachyOS Kernel Version 7.1.2-2-cachyos
- Lutris 0.5.22 (Flatpak)
- OpenGL Version 4.6.0 NVIDIA 610.43.02
- Vulkan Version 1.4.321

It took some effort as Lutris kept replacing the d3d12.dll/d3dcore.dll files and in the end dropping the debug files directly into the `Assassin's Creed Shadows` Game folder got the correct dlls loaded. However the crashes were still occurring with `VKD3D_DEBUG=err` and only went away when debug was set to `trace` at significant drop in frame rates.

**Comment by praz01** [comment]
In my case the crash does occur even with `trace` enabled, just not immediately as it does otherwise. Not really sure any of this is significant but here are debug outputs. When I have time I dig deeper.

1st Error:
```
130633.202:0614:0754:err:vkd3d-proton:vk_image_memory_barrier_for_initial_transition: Application uses placed resource (1 subresource) (cookie 54846, fmt: DXGI_FORMAT_R16G16B16A16_FLOAT, flags: #5) that must be initialized explicitly.
```
<details><summary>1st `breadcrumbs` traces:</summary>

```
130712.914:0614:0750:err:vkd3d-proton:vkd3d_wait_for_gpu_timeline_semaphore: Failed to wait for Vulkan timeline semaphore, vr 2.
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_device_lost: Device lost observed, analyzing breadcrumbs ...
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_queue_nv: Found pending command list context [5938, 5938] in executable state, TOP_OF_PIPE marker 17, BOTTOM_OF_PIPE marker 17.
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list_linked: === Replaying earlier command list #0 (context 5859) in submission for clarity ===
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Cookie: 54973 (#d6bd)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 4294967295 (#ffffffff)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 2755 (#ac3)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 1024 (#400)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:      Tag: Resource Transition
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:   Command: barrier
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:      Tag: Buffer -> Image
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:      Tag: BufferDesc [VkBuffer VA, SuballocatedOffset, Cookie, GlobalCookie, Size, Flags]
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_ligamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
00d8:err:ole:start_rpcss Failed to open service manager
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directoryst:  Set arg: 5249171456 (#138e00000)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 0 (#0)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Cookie: 51321 (#c879)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Cookie: 51320 (#c878)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 67108864 (#4000000)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 0 (#0)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:      Tag: ImageDesc [Cookie, DXGI_FORMAT, D3D12_RESOURCE_DIMENSION, width, height, DepthOrArraySize, MipLevels, Flags]
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Cookie: 54973 (#d6bd)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 41 (#29)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 3 (#3)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 64 (#40)
130712.914:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 2 (#2)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 1 (#1)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 1 (#1)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 0 (#0)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:      Tag: SubresourceLayers [mipLevel, baseArrayLayer, layerCount, aspectMask]
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 0 (#0)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 0 (#0)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 1 (#1)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 1 (#1)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:      Tag: ImageOffsetExtent [offset, extent, bufferOffset, bufferRowLength, bufferImageHeight]
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 0 (#0)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 0 (#0)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 0 (#0)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 64 (#40)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 2 (#2)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 1 (#1)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 60865024 (#3a0ba00)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 64 (#40)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 2 (#2)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:   Command: copy
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Cookie: 54973 (#d6bd)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 4294967295 (#ffffffff)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 1024 (#400)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 2755 (#ac3)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:      Tag: Resource Transition
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Cookie: 665 (#299)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 4294967295 (#ffffffff)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 0 (#0)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 4 (#4)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:      Tag: Resource Transition
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:   Command: barrier
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list_linked: =====================================================
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list_linked: === Replaying earlier command list #1 (context 5882) in submission for clarity ===
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Cookie: 55156 (#d774)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 0 (#0)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 2755 (#ac3)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:  Set arg: 1024 (#400)
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:      Tag: Resource Transition
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:   Command: barrier
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:      Tag: Buffer -> Buffer
130712.915:0614:0750:err:vkd3d-proton:vkd3d_breadcrumb_tracer_report_command_list:      Tag: BufferDesc [VkBuffer VA, SuballocatedOffset, Cookie, GlobalCookie, Size, Flags]
```

</details>

<details><summary>Last error:</summary>

```
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
00d8:err:ole:start_rpcss Failed to open service manager
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
```

</details>

**Comment by praz01** [comment]
Played today for about 5 hours without crashing. 

- `--buildtype=debugoptimized` built dlls
- Following overrides:
  - `VKD3D_CONFIG=descriptor_heap,breadcrumbs`
  - `PROTON_VKD3D_HEAP=1`
  - `VKD3D_DEBUG=err`
  - `WINEDLLOVERRIDES=d3d12,d3d12core=n`

**Comment by ragne1d** [comment]
Hello everyone,

I tested the workaround mentioned by @ssareta above: building vkd3d-proton in debug mode, replacing Proton’s D3D12 DLLs with the newly built ones, and adding the following environment variables to the launch options:

`VKD3D_CONFIG=descriptor_heap,breadcrumbs VKD3D_DEBUG=err`

It worked very well. I played for around six hours yesterday without encountering any deadlocks (RTX 5080, latest CachyOS version).

That said, I hope the team can provide an official fix soon.

**Comment by Qbsoon** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-4956994379

For me currently happens even when tried this fix.
Fedora 44 KDE, 610 driver from rawhide repo, latest cachyos-proton, Heroic Launcher -> Ubisoft Connect
With RTX4070Ti Super && Ryzen 7600X.
Tried also with praz01 arguments and debugoptimized build instead of debug build. Same thing, game just freezes always in certain areas.

**Comment by praz01** [comment]
> > Replying to [#8543 (comment)](https://github.com/ValveSoftware/Proton/issues/8543#issuecomment-4956994379)
> 
> For me currently happens even when tried this fix. Fedora 44 KDE, 610 driver from rawhide repo, latest cachyos-proton, Heroic Launcher -> Ubisoft Connect With RTX4070Ti Super && Ryzen 7600X. Tried also with praz01 arguments and debugoptimized build instead of debug build. Same thing, game just freezes always in certain areas.

What are you breadcrumbs trace output before the crash? Which location are you experiancing the issue in?

**Comment by Saancreed** [comment]
Might as well post here, in case not everyone is watching vkd3d-proton repo issues…

I got somewhat tired of waiting for this hang on NV 595+ to be investigated and resolved, so I did some absolutely stupid shotgun debugging: https://github.com/HansKristian-Work/vkd3d-proton/compare/master...Saancreed:ac-shadows

This makes the game stable _on my system_, including on release builds with breadcrumbs disabled, but I'm not sure if it's just pure luck, or the issue really is somewhere in there. Feel free to give this a try; rebuild vkd3d-proton with changes I linked above then attempt to reproduce the hang, maybe it will fix them for you as well.

**Comment by ForgotMyOwnPassword** [comment]
Confirming this also reproduces on RTX 3070 (Ampere) with NVIDIA open 610.57.04, CachyOS, COSMIC Wayland, Proton Hotfix hotfix-20260828-ptr — scene-dependent (a specific questline and fast travel to the area), no Xid, no OOM. One possibly useful difference to the earlier reports: in my case the Proton log does show an explicit device loss rather than only silent waits:

err:vkd3d-proton:vkd3d_wait_for_gpu_timeline_semaphore: Failed to wait for Vulkan timeline semaphore, vr -4.
warn:vkd3d-proton:d3d12_device_mark_as_removed: Device ... is lost (reason 0x887a0005, "VK_ERROR_DEVICE_LOST").

Full log attached. (Pyroveil ac-shadows-nvidia-570-stable confirmed loaded but ineffective — expected, since that targets the old pre-575 menu hang.) Will report back whether downgrading to proprietary 580xx avoids it.

[acshadows-hang.zip](https://github.com/user-attachments/files/31877923/acshadows-hang.zip)





Follow-up: downgrading from NVIDIA open 610.57.04 to the proprietary 580.178.04 driver resolves the hang for me. Several hours of play including the previously 100% reproducible trigger spots (questline, fast travel, the affected save) with no freezes. Same system otherwise (RTX 3070, CachyOS, Proton Hotfix), Pyroveil removed, shader caches cleared after the driver switch.

The intermittent mouse-look issue I mentioned as "possibly unrelated" in my first comment has also not reoccurred since the downgrade — so it was likely a symptom of the same driver problem rather than a compositor issue.

So for pre-Blackwell cards, staying on/downgrading to 580xx appears to be a viable workaround for this issue

**Comment by ForgotMyOwnPassword** [comment]
Same hang now reproduces on AMD RDNA4 / RADV — GPU page fault from vkd3d_queue thread

Following up on my earlier report (hang with VK_ERROR_DEVICE_LOST in Assassin's Creed Shadows on NVIDIA). I have since replaced the GPU entirely and the same hang occurs on completely different hardware and a different driver stack, which suggests this is not vendor-specific.

Previous setup (where the hang was first seen)

NVIDIA RTX 3070, open kernel module 610.57.04 (later proprietary 580.178.04)

Current setup (hang still occurs)

GPU: AMD Radeon RX 9070 XT (PowerColor Reaper), RADV GFX1201
CPU: AMD Ryzen 7 5800X, 32 GB DDR4
Distro: CachyOS, kernel 7.2.5-1-cachyos
Mesa 26.2.2, LLVM 22.1.8, DRM 3.64
Desktop: COSMIC 1.0 (Wayland)
Proton: Proton Hotfix
Game: Assassin's Creed Shadows (AppID 3159330)

Symptom
Game hangs after a short session (<1h uptime in this instance). Rendering stops, the process has to be killed.

What the kernel log shows

The AMD driver reports a GPU page fault attributed directly to the vkd3d queue thread, followed by ring timeouts and resets:

```
amdgpu 0000:09:00.0: [gfxhub] page fault (src_id:0 ring:24 vmid:5 pasid:748)
amdgpu 0000:09:00.0:  Process ACShadows.exe pid 72678 thread vkd3d_queue pid 72766
amdgpu 0000:09:00.0:   in page starting at address 0x00008004d0fae000 from client 10
amdgpu 0000:09:00.0: GCVM_L2_PROTECTION_FAULT_STATUS:0x00501031
amdgpu 0000:09:00.0:          Faulty UTCL2 client ID: TCP (0x8)
amdgpu 0000:09:00.0:          MORE_FAULTS: 0x1
amdgpu 0000:09:00.0:          WALKER_ERROR: 0x0
amdgpu 0000:09:00.0:          PERMISSION_FAULTS: 0x3
amdgpu 0000:09:00.0:          MAPPING_ERROR: 0x0
amdgpu 0000:09:00.0:          RW: 0x0
...
amdgpu 0000:09:00.0: ring comp_1.1.1 timeout, signaled seq=339353, emitted seq=339356
amdgpu 0000:09:00.0: Starting comp_1.1.1 ring reset
amdgpu 0000:09:00.0: Ring comp_1.1.1 reset succeeded
amdgpu 0000:09:00.0: ring gfx_0.0.0 timeout, signaled seq=37498891, emitted seq=37498894
amdgpu 0000:09:00.0: Ring gfx_0.0.0 reset succeeded
```

RW: 0x0 indicates a read access, TCP is the shader texture cache, and PERMISSION_FAULTS: 0x3 indicates the access was not permitted — consistent with an out-of-bounds read from a shader.

What the Proton log shows

Nothing unusual in the seconds leading up to the fault — only routine seh:NtGetContextThread tracing. Then the device is lost without warning:

```
29427.118:04c4:05c8:warn:vkd3d-proton:d3d12_device_mark_as_removed: Device is lost (reason 0x887a0005, "VK_ERROR_DEVICE_LOST").
29427.118:04c4:05c4:err:vkd3d-proton:vkd3d_wait_for_gpu_timeline_semaphore: Failed to wait for Vulkan timeline semaphore, vr -4.
29427.118:04c4:06a0:err:vkd3d-proton:dxgi_vk_swap_chain_wait_semaphore: Failed to wait for present semaphore, vr -4.
29427.127:04c4:05c8:err:vkd3d-proton:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
```

The kernel page fault timestamp matches the DEVICE_LOST timestamp in the Proton log.

Full Proton log available (14 MB). A devcoredump was generated but expired before I could capture it; I will attach one if the hang reproduces.

[acs-hang-2026-09-16-kernel.log](https://github.com/user-attachments/files/32310830/acs-hang-2026-09-16-kernel.log)
[acs-hang-2026-09-16.log.gz](https://github.com/user-attachments/files/32310831/acs-hang-2026-09-16.log.gz)



Notes

Identical failure mode across NVIDIA (Ampere, proprietary driver) and AMD (RDNA4, RADV/Mesa)
I have not yet been able to narrow down a reliable trigger.

**Comment by Guitto** [comment]
<details><summary>Summary
Assassin's Creed Shadows (Steam, AppID 3159330) freezes during the loading
screen ("Initializing memories") on an Intel Arc A770 8GB. The kernel logs a
GPU hang on the render engine, and vkd3d-proton reports VK_ERROR_DEVICE_LOST
about 60-70s after the D3D12 device is created. The game has never run
successfully on this machine. It hangs the same way with both the i915 and
xe kernel drivers.</summary>

System


        
      GPU: Intel Arc A770 8GB (DG2, device ID 56a0), Resizable BAR enabled
(xe reports 8 GB visible VRAM)

        
      OS: Bazzite (Fedora 44 based)

        
      Kernel: 7.2.4-ogc3.1.fc44.x86_64

        
      Mesa: 26.2.2 (anv)

        
      GuC firmware: dg2_guc_70.bin 70.53.0

        
      Proton: Proton Hotfix (hotfix-20260828-ptr) and Proton Experimental
[version], DXVK 3.1, vkd3d-proton 3.1.0 (build 7a0ea880e74ffaf)

Steps to reproduce


        
      Launch Assassin's Creed Shadows through Steam with Proton.

        
      Wait at the "Initializing memories" loading screen.

        
      After roughly 1-3 minutes the screen freezes.

Expected / actual
Expected: the game reaches the menu.
Actual: the GPU hangs and the game stays frozen.
Logs
i915 (same ecode on every run, ~9 runs):
Fence expiration time out i915-0000:0c:00.0:ACShadows.exe[...]
GPU HANG: ecode 12:1:85def5fb, in ACShadows.exe [...]
ACShadows.exe[...] context reset due to GPU hang
xe:
Tile0: GT0: Engine reset: engine_class=rcs, logical_mask: 0x1, guc_id=129, state=0x3
Tile0: GT0: Timedout job: seqno=8295, lrc_seqno=8295, guc_id=129, flags=0x80 in ACShadows.exe [...]
Xe device coredump has been created
vkd3d-proton (Proton log):
err:vkd3d-proton:vkd3d_wait_for_gpu_timeline_semaphore: Failed to wait for Vulkan timeline semaphore, vr -4.
warn:vkd3d-proton:d3d12_device_mark_as_removed: Device ... is lost (reason 0x887a0005, "VK_ERROR_DEVICE_LOST").
vkd3d-proton reports DXR 1.1, EXT_device_generated_commands and
EXT_descriptor_buffer as enabled, and disables mesh shaders (barycentrics
not supported).
Attached: xe devcoredump [and i915 error state if available], kernel log,
vulkaninfo, Proton log.
What I tried


        
      Switching from i915 to xe: same hang

        
      Proton Hotfix and Proton Experimental: same hang

        
      VKD3D_CONFIG=nodxr: same hang

        
      VKD3D_DISABLE_EXTENSIONS for VK_EXT_device_generated_commands and
VK_EXT_descriptor_buffer (one at a time): same hang

</details>

**Comment by Blisto91** [comment]
Link to the mesa issue for the above https://gitlab.freedesktop.org/mesa/mesa/-/work_items/16368

**Comment by Guitto** [comment]
> Link to the mesa issue for the above https://gitlab.freedesktop.org/mesa/mesa/-/work_items/16368

Yeah, i opened that issue
