### ISSUE TITLE
Wreckfest 2 (1203190)

### ISSUE THREAD

**Issue by saroman2** [ValveSoftware/Proton#8547]
# Compatibility Report
- Wreckfest 2
- 1203190

## System Information
- GPU: AMD Radeon RX 6900 XT
- Video driver version: Mesa 25.0~git2503180600.d2e943~oibaf~n
- Kernel version: 6.13.6-061306-generic
- Proton version: Proton Experimental / Hotfix / 9.0-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Terrain rendering corruption with black squares as seen in screenshot:

![Image](https://github.com/user-attachments/assets/75316dda-8616-4d29-8ea8-2243d730e62c)

Apparently also happening on Steam Deck as reported by others in general discussions thread.

## Reproduction

- Launch game
- Join any race
- Changing terrain rendering or other ingame settings does not appear to make a difference

[steam-1203190.log](https://github.com/user-attachments/files/19376094/steam-1203190.log)

**Comment by SneakiestDuke68** [comment]
I have same problem. RX 6800 XT and tried Proton-GE 9-26 & Proton Experimental.

**Comment by Sp4rkR4t** [comment]
Same issue 7800XT and tried a few different proton versions, also happens no matter what settings are used in game.

**Comment by Turbo49** [comment]
In addition to this issue, i also get fps reduced from 100 to 20 after changing map, whether it is by going to the menu or in a multiplayer lobby. using an rx 6600

**Comment by belozer** [comment]
Same, 7900xtx. Tested on Proton 9.0-4, Proton Experemental and proton-cachyos. 

P.S. There is no such problem on windows 11.

**Comment by SecularSteve** [comment]
It's especially problematic on the Steam Deck. Even though the game is somehow playable.

Though I also think it serves as a testament that the Deck is probably hitting it's wall.

**Comment by nyannoying1337** [comment]
Terrain rendering corruptions also happen on Windows. Its uncommon but a big problem on Arc GPUs. i would believe thats on the game for now

**Comment by belozer** [comment]
> Terrain rendering corruptions also happen on Windows. Its uncommon but a big problem on Arc GPUs. i would believe thats on the game for now

In this case, we are talking about AMD. I tested the game on Windows and there are no problems with it. However, when I run it on Linux, there is a problem that is persistent. I have tried the latest RADV and AMDVLK drivers.

**Comment by belozer** [comment]
7900xtx, proton 9.0-4, proton-experemental

![Image](https://github.com/user-attachments/assets/71132748-39af-4aa8-9387-7c60e9cab995)

**Comment by nyannoying1337** [comment]
> > Terrain rendering corruptions also happen on Windows. Its uncommon but a big problem on Arc GPUs. i would believe thats on the game for now
> 
> In this case, we are talking about AMD. I tested the game on Windows and there are no problems with it. However, when I run it on Linux, there is a problem that is persistent. I have tried the latest RADV and AMDVLK drivers.

im aware you re talking about AMD. im just saying that other people have such issue on Windows too. so this may not be exactly a Proton issue

**Comment by simifor** [comment]
The amd terrain rendering issue should be fixed on proton experimental bleeding edge, to select it you go to your library, look for proton experimental, go to its properties then beta, and select bleeding edge  in the drop down

**Comment by Sp4rkR4t** [comment]
Confirmed it's fixed in experimental:bleeding-edge

**Comment by SneakiestDuke68** [comment]
Also confirmed, Proton Experimental bleeding-edge fixed a problem.

**Comment by SecularSteve** [comment]
> The amd terrain rendering issue should be fixed on proton experimental bleeding edge, to select it you go to your library, look for proton experimental, go to its properties then beta, and select bleeding edge  in the drop down

Nice 👍

I am curious to know the technical details.
What caused it, and how was it fixed?

**Comment by belozer** [comment]
Also confirmed fix, Proton Experimental:bleeding-edge

**Comment by SecularSteve** [comment]
New issue to report on the Steam Deck (OLED).

The game completely freezes if the cars load in with the texture quality set to anything above Low.
Have to quit using "Steam + B" every single time.

Also, the "bleeding-edge" thing does not fix the ground issue on it.
If anything, it's worse.
And yes, I did check.

![IMG-022204501f1c3ed124822105a38e97fa-V.jpg](https://github.com/user-attachments/assets/013e7ce9-dea3-4ecf-8eab-293810305500)
![IMG-03e0457e7ca2250fc3bc83b5817a0632-V.jpg](https://github.com/user-attachments/assets/ee3363c7-c221-4441-9f53-4d0145e43d02)

**Comment by sandervalcke** [comment]
For those interested, this was probably the fix: https://github.com/HansKristian-Work/vkd3d-proton/pull/2410

**Comment by SecularSteve** [comment]
Good news and Bad news.

Good news.
It's finally fixed.

Bad news.
The performance is even worse.

The game can barely break by 20 FPS with all cars on screen at the lowest settings. With an average of 25 when it gets less packed. Spiking up to 60 with no cars.

I was thinking of getting rid of a ProtonDB review I've had earlier, but that "The Deck can't catch up" fear is getting justified again.

I'd categorise it as "Unsupported" until further notice.
