### ISSUE TITLE
My Summer Car (516750)

### ISSUE THREAD

**Issue by cagelight** [ValveSoftware/Proton#880]
[System Info](https://gist.github.com/cagelight/48eae70b75659c0b4bec2b1af6208149)
Proton 3.7-4

Game seems to work fine except for a pretty severe issue where any mouse movements have a hard tendency to veer down-right diagonally, makes the game virtually unplayable.

**Comment by kisak-valve** [comment]
My Summer Car (516750)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/1108.
@NaltanHusky posted on 2018-09-01T03:23:39:

Crashes on startup, no window appears.

I'm running debian 9, and the latest version of Steam and Proton (as of 8/31/18 11:25 PM)

Output for when its run:
```Mono path[0] = 'Z:/home/naltan/.steam/steam/steamapps/common/My Summer Car/mysummercar_Data/Managed'
Mono path[1] = 'Z:/home/naltan/.steam/steam/steamapps/common/My Summer Car/mysummercar_Data/Mono'
Mono config path = 'Z:/home/naltan/.steam/steam/steamapps/common/My Summer Car/mysummercar_Data/Mono/etc'
Initialize engine version: 5.0.0f4 (5b98b70ebeb9)
GfxDevice: creating device client; threaded=1
Crash!!!
SymInit: Symbol-SearchPath: '.;Z:\home\
altan\.steam\\steam\\steamapps\\common\\My Summer Car;Z:\\home\
altan\.steam\\steam\\steamapps\\common\\My Summer Car;C:\\windows;C:\\windows\\system32;SRV*c:\\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'steamuser'
OS-Version: 6.1.7601 (Service Pack 1) 0x0-0x1
Z:\home\
altan\.steam\\steam\\steamapps\\common\\My Summer Car\\mysummercar.exe:mysummercar.exe (0000000140000000), size: 19509248 (result: 0), SymType: '-nosymbols-', PDB: 'Z:\\home\
altan\.steam\\steam\\steamapps\\common\\My Summer Car\\mysummercar.exe', fileVersion: 5.0.0.39095
C:\windows\\system32\
tdll.dll:ntdll.dll (000000007BC20000), size: 1122304 (result: 0), SymType: 'DIA', PDB: 'C:\windows\\system32\
tdll.dll', fileVersion: 6.1.7601.24059
C:\windows\\system32\\KERNEL32.dll:KERNEL32.dll (000000007B420000), size: 4132864 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\KERNEL32.dll', fileVersion: 5.1.2600.2180
C:\windows\\system32\\hid.dll:hid.dll (00007F0687D40000), size: 57344 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\hid.dll', fileVersion: 10.0.0.0
C:\windows\\system32\\ws2_32.dll:ws2_32.dll (00007F0687C00000), size: 212992 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\ws2_32.dll', fileVersion: 5.1.2600.5512
C:\windows\\system32\\user32.dll:user32.dll (00007F06879B0000), size: 2367488 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\user32.dll', fileVersion: 5.1.2600.2180
C:\windows\\system32\\gdi32.dll:gdi32.dll (00007F0687830000), size: 1449984 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\gdi32.dll', fileVersion: 10.0.0.0
C:\windows\\system32\\advapi32.dll:advapi32.dll (00007F0687790000), size: 540672 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\advapi32.dll', fileVersion: 5.1.2600.2180
C:\windows\\system32\\version.dll:version.dll (00007F0687770000), size: 73728 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\version.dll', fileVersion: 5.1.2600.2180
C:\windows\\system32\\ole32.dll:ole32.dll (00007F06875F0000), size: 1536000 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\ole32.dll', fileVersion: 10.0.0.0
C:\windows\\system32\pcrt4.dll:rpcrt4.dll (00007F0687540000), size: 540672 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\pcrt4.dll', fileVersion: 5.1.2600.2180
C:\windows\\system32\\shlwapi.dll:shlwapi.dll (00007F06874B0000), size: 503808 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\shlwapi.dll', fileVersion: 6.0.2800.1692
C:\windows\\system32\\shell32.dll:shell32.dll (00007F06871D0000), size: 2928640 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\shell32.dll', fileVersion: 6.0.2900.6242
C:\windows\\system32\\opengl32.dll:opengl32.dll (000000007A850000), size: 1785856 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\opengl32.dll', fileVersion: 5.1.2600.2082
C:\windows\\system32\\winmm.dll:winmm.dll (00007F06870F0000), size: 774144 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\winmm.dll'
C:\windows\\system32\\msacm32.dll:msacm32.dll (00007F06870C0000), size: 159744 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\msacm32.dll'
C:\windows\\system32\\oleaut32.dll:oleaut32.dll (00007F0686F60000), size: 1413120 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\oleaut32.dll', fileVersion: 6.0.6001.18000
C:\windows\\system32\\imm32.dll:imm32.dll (00007F0686F20000), size: 131072 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\imm32.dll', fileVersion: 5.1.2600.2180
C:\windows\\system32\\dnsapi.dll:dnsapi.dll (00007F0686F00000), size: 94208 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\dnsapi.dll', fileVersion: 5.2.3790.4318
C:\windows\\system32\
etapi32.dll:netapi32.dll (00007F0686CB0000), size: 188416 (result: 0), SymType: 'DIA', PDB: 'C:\windows\\system32\
etapi32.dll'
C:\windows\\system32\\iphlpapi.dll:iphlpapi.dll (00007F0686C80000), size: 159744 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\iphlpapi.dll', fileVersion: 5.1.2600.2180
C:\windows\\system32\\winhttp.dll:winhttp.dll (00007F0686C40000), size: 225280 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\winhttp.dll', fileVersion: 5.1.2600.2180
C:\windows\\system32\\jsproxy.dll:jsproxy.dll (00007F0686C20000), size: 77824 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\jsproxy.dll'
Z:\home\
altan\.steam\\steam\\steamapps\\common\\My Summer Car\\mysummercar_Data\\Mono\\mono.dll:mono.dll (0000000180000000), size: 2990080 (result: 0), SymType: '-nosymbols-', PDB: 'Z:\\home\
altan\.steam\\steam\\steamapps\\common\\My Summer Car\\mysummercar_Data\\Mono\\mono.dll'
C:\windows\\system32\\psapi.dll:psapi.dll (00007F0686240000), size: 36864 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\psapi.dll', fileVersion: 5.1.2600.3264
C:\windows\\system32\\mswsock.dll:mswsock.dll (00007F0686230000), size: 20480 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\mswsock.dll', fileVersion: 4.0.0.0
C:\windows\\system32\\winex11.drv:winex11.drv (00007F0686190000), size: 589824 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\winex11.drv', fileVersion: 10.0.0.0
C:\windows\\system32\\d3d9.dll:d3d9.dll (00007F0685490000), size: 315392 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\d3d9.dll', fileVersion: 5.3.1.904
C:\windows\\system32\\wined3d.dll:wined3d.dll (00007F0685340000), size: 1351680 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\wined3d.dll', fileVersion: 10.0.0.0
C:\windows\\system32\\dxgi.dll:dxgi.dll (000000006F200000), size: 1622016 (result: 0), SymType: '-nosymbols-', PDB: 'C:\\windows\\system32\\dxgi.dll'
C:\windows\\system32\\vulkan-1.dll:vulkan-1.dll (00007F067D4A0000), size: 81920 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\vulkan-1.dll', fileVersion: 10.0.0.0
C:\windows\\system32\\winevulkan.dll:winevulkan.dll (00007F067D460000), size: 241664 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\winevulkan.dll', fileVersion: 10.0.0.0
C:\windows\\system32\\msvcrt.dll:msvcrt.dll (00007F067D150000), size: 749568 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\msvcrt.dll', fileVersion: 7.0.2600.2180
C:\windows\\system32\\openvr_api_dxvk.dll:openvr_api_dxvk.dll (0000000003230000), size: 618496 (result: 0), SymType: '-nosymbols-', PDB: 'C:\\windows\\system32\\openvr_api_dxvk.dll', fileVersion: 1.0.10.0
C:\windows\\system32\\api-ms-win-core-synch-l1-2-0.dll:api-ms-win-core-synch-l1-2-0.dll (00007F067D120000), size: 73728 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\api-ms-win-core-synch-l1-2-0.dll'
C:\windows\\system32\\api-ms-win-core-fibers-l1-1-1.dll:api-ms-win-core-fibers-l1-1-1.dll (00007F067D110000), size: 53248 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\api-ms-win-core-fibers-l1-1-1.dll'
C:\windows\\system32\\api-ms-win-core-localization-l1-2-1.dll:api-ms-win-core-localization-l1-2-1.dll (00007F067D100000), size: 36864 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\api-ms-win-core-localization-l1-2-1.dll'
C:\windows\\system32\\api-ms-win-core-file-l2-1-1.dll:api-ms-win-core-file-l2-1-1.dll (00007F067D0F0000), size: 16384 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\api-ms-win-core-file-l2-1-1.dll'
C:\windows\\system32\\dbghelp.dll:dbghelp.dll (00007F067D080000), size: 393216 (result: 0), SymType: 'DIA', PDB: 'C:\\windows\\system32\\dbghelp.dll', fileVersion: 6.1.7601.17514

========== OUTPUTING STACK TRACE ==================

  ERROR: SymGetSymFromAddr64, GetLastError: 'Success.' (Address: 0000000140041233)
0000000140041233 (mysummercar) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Success.' (Address: 000000014004228D)
000000014004228D (mysummercar) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Success.' (Address: 000000014060ABE6)
000000014060ABE6 (mysummercar) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Success.' (Address: 0000000140608AF7)
0000000140608AF7 (mysummercar) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Success.' (Address: 000000014064780E)
000000014064780E (mysummercar) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Success.' (Address: 00000001406474BD)
00000001406474BD (mysummercar) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Success.' (Address: 0000000140163E4A)
0000000140163E4A (mysummercar) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Success.' (Address: 0000000140215949)
0000000140215949 (mysummercar) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Success.' (Address: 00000001401FEECE)
00000001401FEECE (mysummercar) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Success.' (Address: 00000001402C0DAC)
00000001402C0DAC (mysummercar) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Success.' (Address: 00000001406918E8)
00000001406918E8 (mysummercar) 
Crash in winutils::ProcessInternalCrash(PEXCEPTION_POINTERS pExInfo)
```
***
@daasuharo commented on 2018-09-01T03:28:36

Make sure to add appid to title (516750)
***
@NaltanHusky commented on 2018-09-01T03:31:14

Done, sorry

**Comment by Quinnux** [comment]
Additionally to confirming the mouse drifting down-right, I've been unable to get any controller support in this game at all.

[edit] For me, the mouse drift happens upon clicking either mouse button, or mousewheel scrolling. It happens on both laptop touchpad, and USB mouse.

XBox 360, Steam Controller, Driving Force GT. No controller is recognised from the initial "Unity Input" menu onwards. It's been the same on Proton 3.7.3 - 3.7.6beta.

- OS: Ubuntu 18.04
- Processor: Intel i5-4210H
- GPU: Nvidia GTX 960M
- Driver: nVidia 390.48 (I know this isn't the most up to date, but I don't believe it will affect this)

**Comment by cagelight** [comment]
I can confirm that Proton 3.7-7 fixed the mouse issue for me. The game has no serious issues anymore as far as I can tell, just minor stuttering and poor performance.

**Comment by Quinnux** [comment]
Not sure if something selected wrong - I have "use this tool instead of game specific selections from Steam" ticked, and Proton 3.7.7beta selected but I still have the mouse moving down-right whenever using the scroll wheel i.e. tightening a bolt/turning on the sauna etc. Also, there still appears to be no controller support (have you tried driving the Satsuma with keyboard?). Is there some settings file or something that needs deleting? It appears to have made no difference whatsoever in my case.

**Comment by daprice** [comment]
Using Proton 3.7.6 I had two mouse-related issues:

1. the down & right drift on every mouse movement, click, or scroll
2. that all mouse movements below a certain speed/distance were completely ignored and faster movements were jerky (probably the same issue described in #147).

3.7.7beta fixed that second issue for me, but not the first. As a workaround for the first issue, I was able to mostly compensate by turning down the game's mouse sensitivity and turning up the sensitivity/DPI in the OS and on the mouse itself.

Also it still doesn't seem to be getting any controller input (joystick axes show up in the game's launcher but can't be reassigned, calibrated, or used in-game).

**Comment by wadtech** [comment]
I've managed to get the game to launch by using `PROTON_USE_WINED3D11=1 %command%` as my launch params, but now I can't actually begin a new game. In the `/tmp/dumps/` log it says:

```
ArgumentException: Path is empty
  at System.IO.Directory.CreateDirectory (System.String path) [0x00000] in <filename unknown>:0 
  at ES2DirectoryUtility.CreateDirectory (System.String path) [0x00000] in <filename unknown>:0 
  at ES2FileStream.CreateStorageStream () [0x00000] in <filename unknown>:0 
  at ES2FileStream.Store () [0x00000] in <filename unknown>:0 
  at ES2Writer.Save (Boolean checkForOverwrite) [0x00000] in <filename unknown>:0 
  at ES2Writer.Save () [0x00000] in <filename unknown>:0 
  at ES2.Save[Single] (Single param, System.String identifier) [0x00000] in <filename unknown>:0 
  at HutongGames.PlayMaker.Actions.SaveFloat.OnEnter () [0x00000] in <filename unknown>:0 
  at HutongGames.PlayMaker.FsmState.ActivateActions (Int32 startIndex) [0x00000] in <filename unknown>:0 
  at HutongGames.PlayMaker.FsmState.OnEnter () [0x00000] in <filename unknown>:0 
  at HutongGames.PlayMaker.Fsm.EnterState (HutongGames.PlayMaker.FsmState state) [0x00000] in <filename unknown>:0 
  at HutongGames.PlayMaker.Fsm.SwitchState (HutongGames.PlayMaker.FsmState toState) [0x00000] in <filename unknown>:0 
  at HutongGames.PlayMaker.Fsm.UpdateStateChanges () [0x00000] in <filename unknown>:0 
  at HutongGames.PlayMaker.Fsm.UpdateState (HutongGames.PlayMaker.FsmState state) [0x00000] in <filename unknown>:0 
  at HutongGames.PlayMaker.Fsm.Update () [0x00000] in <filename unknown>:0 
  at PlayMakerFSM.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```

Not sure where to look from here.

**Comment by wadtech** [comment]
Sorted it: on Linux Mint I had to go to `$HOME/.local/share/Steam/steamapps/compatdata/516750/pfx/drive_c/users/steamuser` and create the directories `AppData/LocalLow/Amistech/My Summer Car/` myself.

**Comment by echozio** [comment]
The game runs fine for me now without any tweaks. The mouse issue is no longer present with Proton 4.2.
Performance is also decent and doesn't negatively impact the experience, although you could easily expect more given how the game actually looks. This is probably just because the game is poorly optimized, though.

The only thing that doesn't work is gamepads. I've tried with a PS4 controller, G29 steering wheel in G29 and G27 mode and never been able to assign any buttons or axes.

**Comment by echozio** [comment]
My G29 steering wheel now works with FFB with proton 4.2-5.

**Comment by moggesmith10** [comment]
I am having problems with using my Logitech G29 wheel with the latest version of proton. However running with the latest 4.x version works.

The problem seems to be with the available turning range of the wheel. Let's say that my wheel can turn - 360 to +360 degrees. Then the game is only registering it when I have it turned to >=0 degrees, with +180 being centered in the game. I can try to see if I can pin down which version of proton this problem shows up in.

**Comment by UselessAqua98** [comment]
Encountering the same rotation issue with the Logitech G920.
In addition, 50% physical pedal input give you 100% in-game and anything above 50% pedal input give you 0% in-game.

The Proton version that works for me is 4.2-9.

**Comment by LuanVSO** [comment]
g29 wheel only works properly on proton 6.3-8 or lower, 7.0-6 and above has the problem described by @UselessAqua98
