### ISSUE TITLE
Bloons TD 5 (306020)

### ISSUE THREAD

**Issue by nentibusarchitectura** [ValveSoftware/Proton#937]
Bloons TD 5, a cute and very entertaining tower defense game works perfectly except for the sound, there are no music or effects at all.

Here's the gist to my system's setup: https://gist.github.com/nentibusarchitectura/652dbdaecc32f3ca5f625a0e921c96c9#file-gistfile1-txt

**Comment by DarkoGNU** [comment]
I can say that it's a pretty old Wine bug - I played BTD5 using PlayOnLinux a few months ago and I also had no sound
And it's spelled Bloons, not Blooms :P

**Comment by liberodark** [comment]
same for me on manjaro

**Comment by nsivov** [comment]
Please retest with 3.16-7, this should be fixed now with Valvesoftware/wine@7af2914.

**Comment by kisak-valve** [comment]
Bloons TD5 (306020)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/2453.
@Newbie13XD posted on 2019-03-25T14:40:13:

# Whitelist Request
- Name of the game to be whitelisted: Bloons TD5
- Steam AppID of the game: 306020

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 418.43
- Distro version: Fedora Workstation 29
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Newbie13XD/a119a36b89e1481dbfae1d6f8e463392
- Proton version: Proton 3.16-8 beta

## I confirm:
- [X] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [X] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by kisak-valve** [comment]
Hello, is anyone seeing any issues with this game and Proton 3.16-8 that would block it from being whitelisted?

**Comment by nentibusarchitectura** [comment]
Hi Kisak, It works 100% now, can't find any fault whatsoever.
This game can be whitelisted IMHO.

**Comment by MollyMaclachlan** [comment]
I actually still have an issue with this game. For every version of Proton I've tried this with, it takes about 5-10 minutes of play time for it to simply crash for no reason.

**Proton Versions Tested**

- 3.7-8
- 3.16-4
- 3.16-8
- 4.2-2
- 4.2-3

It's the only issue I experience, but it does make it impossible to play the game.


<details><summary>Here's my system information</summary>
<p>

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD A6-6400K APU with Radeon(tm) HD Graphics   
    CPU Family:  0x15
    CPU Model:  0x13
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3900 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux 4.4 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.38
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  KWin
    Steam Runtime Version:  jenkins-steam-runtime-beta-release_0.20190320.2

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 410.78
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1c82
    Revision Not Detected
    Number of Monitors:  1
    Number of Video Cards Not Detected
    Primary Display Resolution:  1600 x 900
    Desktop Resolution: 1600 x 900
    Primary Display Size: 17.44" x 9.80" (20.00" diag)
                                            44.3cm x 24.9cm (50.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7914 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US
    Total Hard Disk Space Available:  830498 Mb
    Largest Free Hard Disk Block:  123823 Mb
    VR Headset: None detected

Recent Failure Reports:
```

</p>
</details>

**The only log of any kind** I could see was "runprocess_log.txt", inside "/steam/steamapps/compatdata/306020/pfx/drive_c/users/steamuser/My Documents"

09/06/18 05:54:10 [AppID 306020] Exit Code (0) :  "Z:\home\murdo\.local\share\Steam\steamapps\common\BloonsTD5\_CommonRedist\vcredist\2013\vcredist_x86.exe" /quiet /norestart GLE 0
09/06/18 05:54:12 [AppID 306020] Exit Code (0) :  "Z:\home\murdo\.local\share\Steam\steamapps\common\BloonsTD5\_CommonRedist\vcredist\2013\vcredist_x64.exe" /quiet /norestart GLE 0
09/06/18 05:54:12 [AppID 306020] Exit Code (1) :  "Z:\home\murdo\.local\share\Steam\steamapps\common\BloonsTD5\_CommonRedist\vcredist\2015\Microsoft Visual C++ 2015 x86.cmd"  GLE 0
09/06/18 05:54:13 [AppID 306020] Exit Code (1060) :  "Z:\home\murdo\.local\share\Steam\steamapps\common\BloonsTD5\_CommonRedist\vcredist\2015\Microsoft Visual C++ 2015 x64.cmd"  GLE 0
09/06/18 05:54:34 [AppID 306020] Exit Code (0) :  "Z:\home\murdo\.local\share\Steam\steamapps\common\BloonsTD5\_CommonRedist\DirectX\Jun2010\DXSETUP.exe" /silent GLE 0
11/14/18 20:05:26 [AppID 306020] Exit Code (1) :  "Z:\home\murdo\.local\share\Steam\steamapps\common\BloonsTD5\_CommonRedist\vcredist\2015\Microsoft Visual C++ 2015 x86.cmd"  GLE 0
11/14/18 20:05:27 [AppID 306020] Exit Code (0) :  "Z:\home\murdo\.local\share\Steam\steamapps\common\BloonsTD5\_CommonRedist\vcredist\2015\Microsoft Visual C++ 2015 x64.cmd"  GLE 0

**Comment by kisak-valve** [comment]
Hello @MurdoMaclachlan, with Proton 3.16-8+, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the crash, and drag and drop the generated $HOME/steam-$APPID.log into the comment box. If it's a large log, you may need to throw it into an archive.

It may be worthwhile to retest with nvidia's 418 series of driver.

**Comment by MollyMaclachlan** [comment]
Here you go, @kisak-valve.
[steam-306020.log](https://github.com/ValveSoftware/Proton/files/3105072/steam-306020.log)

I'll look into the 418 driver. Thanks for the suggestion.

**Comment by MollyMaclachlan** [comment]
@kisak-valve 
I updated my driver to 418.56, I'm still experiencing the crash. Here's the newest version of the log in case anything changed there.
[steam-306020.log](https://github.com/ValveSoftware/Proton/files/3108864/steam-306020.log)

**Comment by nsivov** [comment]
You got this in your log:

> eventfd: Too many open files
> x11drv: Can't allocate handle for display fd
> 44496.170:0027:002c:trace:module:LdrShutdownProcess ()

You could try to disable ESYNC to see if it gets any better.

**Comment by kisak-valve** [comment]
Also, please run [`ulimit -Hn`](https://github.com/ValveSoftware/Proton/wiki/Requirements#fd-limit-requirements-systemd--240) and verify it gives you a high value and not 4096.

**Comment by MollyMaclachlan** [comment]
I did the ulimit-Hn command, and it returned 4096. I went in and changed it to 65536, and now I haven't had another crash in BTD5 after the best part of an hour of playing. Seems to be all fixed.

**Comment by ghost** [comment]
https://www.protondb.com/app/306020 Seems to be trending towards platinum except for a tweak for some people
```
Out of the box game crashed after exactly 6 minutes, in order to fix that i needed to add "* hard nofile 1048576" into /etc/security/limits.conf and relog into my session, after that game ran perfectly.
```

Can someone confirm that this is no longer needed for the latest release?

**Comment by kisak-valve** [comment]
Hello @rogersachan, a high file descriptor limit is a requirement for [esync](https://github.com/zfigura/wine/blob/esync/README.esync) which is included in Proton and not a game-specific issue. If you have a FUTEX_WAIT_MULTIPLE-enabled kernel, then Proton should perfer to use fsync instead of esync, and use much less file descriptors.

**Comment by GeneticaROMD** [comment]
> Also, please run [`ulimit -Hn`](https://github.com/ValveSoftware/Proton/wiki/Requirements#fd-limit-requirements-systemd--240) and verify it gives you a high value and not 4096.

Hi there, I have exactly the same issue, where the game crashes after 6 minutes. I have done the following:

1. Raised the limit and rebooted my session, as described [here](https://github.com/zfigura/wine/blob/esync/README.esync#L28) 
To raise the limit you'll want to edit
/etc/security/limits.conf and add a line like
`* hard nofile 1048576
2. Added "WINEESYNC=1" to Bloon's "Launch Options" on Steam
3. Verified with ulimit -Hn, which outputs 1048576
[steam-306020.log](https://github.com/ValveSoftware/Proton/files/5756222/steam-306020.log)

Please help @kisak-valve or @nsivov , if you guys know what's happening. Thanks

**Comment by ghost** [comment]
The game is completely broken, crashes immediately after the NK screen goes away. Tried every proton version, nothing.

**Comment by Newbytee** [comment]
Still works for me here. Can you send a log? (add `PROTON_LOG=1 %command%` to launch options and send the log created in your home)
