### ISSUE TITLE
Hellblade: Senua's Sacrifice (414340)

### ISSUE THREAD

**Issue by lieff** [ValveSoftware/Proton#943]
Distro: Ubuntu 18.04
GPU: GTX 980, Nvidia proprietary driver 390.48
Resolution: 2560x1440
RAM: 16GB
Proton 3.7-4 Beta

Played around hour, some audio stutter (not painful). Probably because of high resolution and max graphics settings. All other is fine.

**Comment by Cevantime** [comment]
Played today too (not the VR version). 

Distro: Linux Mint 19
GPU: GTX 1060, Nvidia proprietary 
Driver: 396.54
Resolution: 1920x1080
RAM: 16GB
Proton 3.7

Conclusions :
- Looks not as good as windows version : textures, water etc. (maybe it's normal)
- Lesser Performance comparing to windows (some FPS falls, not a big deal)
- Many sounds problems and audio is a very important part of this game : noises, delay between mouth movement and speech (in cinematics), bad audio "mixing" (some sounds are too loud, some other too low, depending on where you look)

The game is playable as such but I won't call it perfect.

**Comment by DesNZ** [comment]
Also had a go today.

Distro: Kubuntu 18.04
GPU: GTX 1070, Nvidia proprietary
Driver: 396.54
Resolution: 1920x1080
RAM: 16GB
Proton 3.7-Beta

Conclusions :
Haven't played on windows yet, so no comparisons here. I did have the occasional fps freeze (drops to two fps for a second then a couple more stuttering) then goes back to normal).

Sound doesn't seem right, whispers are (although they're whispers) too quiet and some sounds (like the flags waving and water fall) appear to cut in at full volume then cut out instantly. It feels like there's supposed to be a gradual volume increase and subsequent decrease (Faudio maybe??).

As mentioned above there can be some decent delay with audio playback. It appears as though it isn't a delay over the entire play time, but with each sound 'bite'.

There also appears to be some popping with the ambient sound, not sharp or too high pitched so could be a part of the original game, just doesn't feel right.

Apart from the fps drops, the game ran at ultra settings with my 1070 at 1080p 60fps -5fps and plus around 10fps. I'd consider this fps very playable especially for a game like this.

Stable but not completely, playable.

**Comment by lieff** [comment]
Yes, seems I was too haste about audio.

**Comment by mysticfall** [comment]
I had a similar problem with crackling audio, but overriding `xaudio_2_7` to `native, builtin` with `winecfg` fixed it for me.

**Comment by Cevantime** [comment]
@mysticfall Thanks. That fixed audio problems for me too. For guys wondering how to complete this magic, let me give some explanations : 
- run winecfg with the right prefix : 
  ```bash 
     env WINEPREFIX="~/.steam/steam/steamapps/compatdata/[HELLBLADE_PREFIX]/pfx" WINEPATH="~/.steam/steam/steamapps/common/Proton 3.7/dist/bin/wine64" winecfg
  ```
   You may have to install your own wine to make `winecfg` available.
- Go to `Library` tab and in the first dropdown, select `xaudio_2_7` and click on `Add`
- Relaunch the game
- Enjoy a now very playable game !

**Comment by DesNZ** [comment]
Very nice, thanks for the fix! Looking forward to Faudio being included, hopefully alleviating some issues like this in a much nicer way...

**Comment by kisak-valve** [comment]
Hellblade: Senua's Sacrifice Crashes When Starting New Game (414340)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/1292.
@Simmonz posted on 2018-09-06T23:02:40:

I tried running Hellblade: Senua's Sacrifice through Proton and it launches fine but when starting a new game it crashes seconds later before getting to any intro cinematic, level, etc. The Steam AppID of the game: 414340. I added `PROTON_LOG=1 %command%` to the game's launch options but no log was generated. I haven't found an existing compatibility report for this game and I have checked whether there are updates for my system available.

## System Information
- OS: Solus
- GPU: RX 580 8GB
- Driver/LLVM version: Mesa 18.1.6
- Kernel version: 4.18.5-90.current
- Proton version: 3.7-3

- https://gist.github.com/Simmonz/ee96fbeb3d32de20b2ebea979bf1746f

**Comment by jarrard** [comment]
To get audio working for my little issue(DRG), I had to install the whole xact via winetricks using the same method mentioned by Cevantime, but with winetricks xact instead. 

Valve should probably consider xact as a default install ?

**Comment by lieff** [comment]
There already issue about this https://github.com/ValveSoftware/Proton/issues/54

**Comment by DePingus** [comment]
I also had to override xaudio2_7 to Native because the sound was clipping and the volume on the effects were way off. BUT that caused the game to crash after the opening cutscene or when loading my previous save game. To fix this crash I had to add the launch option:

`PROTON_NO_ESYNC=1 %command%`

After these two changes I was able to play for 45 minutes without issue. Though, my system couldn't handle max settings, even with Feral GameMode.

Fedora 28 / GTX 1060 6gb / NVIDIA 396.54 drivers / AMD FX-8320 8gb

**Comment by jarrard** [comment]
what does ulimit -aH say your open files limit is?

**Comment by DePingus** [comment]
@jarrard 
```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31624
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 4096
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31624
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Not sure if the soft limit matters. I'm running a fresh install of Fedora 28.
```
[user@pc ~] $ ulimit -Hn
4096
[user@pc ~] $ ulimit -Sn
1024
```

**Comment by jarrard** [comment]
Yep there is ya problem, 

https://github.com/zfigura/wine/blob/esync/README.esync

Something that should be possibly fixed in protons documentation, its kinda critical for its function yet most people don't know about it (I didnt)

**Comment by DePingus** [comment]
@jarrard What should increase them to?

**Comment by jarrard** [comment]
I have all 3 files on my system mentioned in the esync readme so I just made the edit to all 3 of the files as suggested.  (1048576 is what is suggested)

**Comment by DePingus** [comment]
@jarrard Excellent!

Here is the esync readme for future readers...
https://github.com/zfigura/wine/blob/esync/README.esync

I made the changes to the 3 files, restarted, then removed the PROTON_NO_ESYNC from my launch options. Now the game runs normally...actually even better. Thanks!

**Comment by lavadrop** [comment]
Installing xact doesn't fix anything regarding sound. I keep hearing a constant rythmic pulsating sound with distortions. During the intro, when there are more than 2 voices, all sorts of sounds start playing that make the voices incomprehensible and sound like wood crashing with rocks.

*** What actually works is overriding the xaudio_2_7 library ***

I don't understand why the suggestion to install xact; it doesn't do anything for Skyrim:SE or this game.

OS: Kubuntu 18.04.1
Kernel: 4.18.5-041805-generic 
Resolution: 2560x1080 
DE: KDE / WM: KWin 
CPU: AMD Ryzen 5 1600 (12) @ 3.200GHz / GPU: AMD Radeon RX 580 8 Gb
System Memory: 1748MiB / 7970MiB 
Proton 3.7.6 Beta

**Comment by DePingus** [comment]
@lavadrop You have to install xact and then open winecfg to create an override for xaudio2_7, set that to Native. Both @mysticfall and @Cevantime mentioned it in this thread.

**Comment by lavadrop** [comment]
Although they both mention the override, they never mention that you have to install xact and then do the override.

**Comment by Gravemind** [comment]
FWIW, I play with a custom wine build and **custom wineprefix**, and `winetricks xact`+native xaudio did not fix the audio for me either (actually it's worst), but **installing prerequisites provided by Steam Hellblade fixed it**:
```bash
export WINEPREFIX=...my/hellblade/wine/prefix...
cd ...my/steam/library.../steamapps/common/Hellblade/_CommonRedist
wine "vcredist/2012/vcredist_x86.exe" /quiet /norestart
wine "vcredist/2012/vcredist_x64.exe" /quiet /norestart
wine "vcredist/2013/vcredist_x86.exe" /quiet /norestart
wine "vcredist/2013/vcredist_x64.exe" /quiet /norestart
wine "vcredist/2015/vc_redist.x86.exe" /quiet /norestart
wine "vcredist/2015/vc_redist.x64.exe" /quiet /norestart
wine "DirectX/Jun2010/DXSETUP.exe" /silent
```
Then still **adding `xaudio2_7` as `native, builtin`** (`WINEDLLOVERRIDES="xaudio2_7=n,b"`), and it's fixed, no more constant audio rhythmic crackling/fluttering.
I'm thinking winetricks' and steam's vcredist/directx installers might differs ?! ... or missed something...

(Found this by looking at `appmanifest_414340.acf` and its `installscript.vdf`. Someday could be automated...)

So @lavadrop, if you use a custom wineprefix, or not afraid of command-lines, this might help... or try to "verify integrity of game files" and/or somehow re-install the prerequisites from steam (still in addition to setup `xaudio2_7` as native)...

EDIT: It seems `winetricks xact` does not install 64-bit dlls since winetricks 20180513 (https://github.com/Winetricks/winetricks/commit/f2b3d268d941120d13b4c3c3960b78a879d37761)

**Comment by lavadrop** [comment]
Yesterday I tested my theory with The Turing test: Valve includes libraries for unreal engine games. You just need to do the xaudio_2_7. It worked. No need to install xact.

**Comment by ibrokemypie** [comment]
even with xact installed and the override set to xaudio2_7, the mixing is terrible (six plays way too loud even on the minimum volume) and in cinematic the audio is out of sync from the video by a good 5 seconds or so. Playable, but annoying

**Comment by lavadrop** [comment]
I’ll have to revisit the game. Fortunately Ethan Lee now works with Codeweavers and should contribute to solving these kinds of audio issues.

**Comment by NTMan** [comment]
AMD GPU open source stack needs this patch https://gitlab.freedesktop.org/xorg/xserver/merge_requests/48 for working this game.

**Comment by ibrokemypie** [comment]
is there some problem with it on wayland? graphically it is fine on xorg for me on amdgpu

**Comment by NTMan** [comment]
> is there some problem with it on wayland? graphically it is fine on xorg for me on amdgpu

On my Vega 56 and Vega 64 many Games under steam play stuck immediately after start no matter which gnome session was launched by X or Wayland. 
This patch fixes this. For Wayland have another big benefit because make picture smoothness same as X session if enable Vsync in game. This make possible play in 4K in games such as Shadow of the Tomb Rider on Linux via steam play on my PC.

**Comment by LuFlo** [comment]
> @mysticfall Thanks. That fixed audio problems for me too. For guys wondering how to complete this magic, let me give some explanations :
> 
>     * run winecfg with the right prefix :
>       ```shell
>          env WINEPREFIX="~/.steam/steam/steamapps/compatdata/[HELLBLADE_PREFIX]/pfx" WINEPATH="~/.steam/steam/steamapps/common/Proton 3.7/dist/bin/wine64" winecfg
>       ```
>       
>       
>       You may have to install your own wine to make `winecfg` available.
> 
>     * Go to `Library` tab and in the first dropdown, select `xaudio_2_7` and click on `Add`
> 
>     * Relaunch the game
> 
>     * Enjoy a now very playable game !

How do I determine the right HELLBLADE Prefix? I have 3 prefixes and I don't see any possibility in steam to determine the right one
EDIT: I "guessed" it by the "last edited" attribute in the OS and the game is now indeed very playable, thanks a lot! It would be quite handy to determine somehow where the right prefix is though :)

**Comment by Cevantime** [comment]
The prefix is often given in the issue title, and this one is no exception! :)

**Comment by LuFlo** [comment]
I installed the title via Steam, so the prefixes are just numbers :( But I've just realized that you can determine the right one by scrapping the appmanifest files in the steamapps folder :)

**Comment by ibrokemypie** [comment]
the faudio patch fixes the audio mixing, though it is still out of time with the cutscenes,  a second or so faster than the visual now

**Comment by Geradot** [comment]
> @mysticfall Thanks. That fixed audio problems for me too. For guys wondering how to complete this magic, let me give some explanations :
> 
> * run winecfg with the right prefix :
>   ```shell
>      env WINEPREFIX="~/.steam/steam/steamapps/compatdata/[HELLBLADE_PREFIX]/pfx" WINEPATH="~/.steam/steam/steamapps/common/Proton 3.7/dist/bin/wine64" winecfg
>   ```
>   
>   
>   You may have to install your own wine to make `winecfg` available.
> * Go to `Library` tab and in the first dropdown, select `xaudio_2_7` and click on `Add`
> * Relaunch the game
> * Enjoy a now very playable game !

I did it, but the issue still exists... why? I keep hearing the crisp sound

**Comment by Geradot** [comment]
> FWIW, I play with a custom wine build and **custom wineprefix**, and `winetricks xact`+native xaudio did not fix the audio for me either (actually it's worst), but **installing prerequisites provided by Steam Hellblade fixed it**:
> 
> ```shell
> export WINEPREFIX=...my/hellblade/wine/prefix...
> cd ...my/steam/library.../steamapps/common/Hellblade/_CommonRedist
> wine "vcredist/2012/vcredist_x86.exe" /quiet /norestart
> wine "vcredist/2012/vcredist_x64.exe" /quiet /norestart
> wine "vcredist/2013/vcredist_x86.exe" /quiet /norestart
> wine "vcredist/2013/vcredist_x64.exe" /quiet /norestart
> wine "vcredist/2015/vc_redist.x86.exe" /quiet /norestart
> wine "vcredist/2015/vc_redist.x64.exe" /quiet /norestart
> wine "DirectX/Jun2010/DXSETUP.exe" /silent
> ```
> 
> Then still **adding `xaudio2_7` as `native, builtin`** (`WINEDLLOVERRIDES="xaudio2_7=n,b"`), and it's fixed, no more constant audio rhythmic crackling/fluttering.
> I'm thinking winetricks' and steam's vcredist/directx installers might differs ?! ... or missed something...
> 
> (Found this by looking at `appmanifest_414340.acf` and its `installscript.vdf`. Someday could be automated...)
> 
> So @lavadrop, if you use a custom wineprefix, or not afraid of command-lines, this might help... or try to "verify integrity of game files" and/or somehow re-install the prerequisites from steam (still in addition to setup `xaudio2_7` as native)...
> 
> EDIT: It seems `winetricks xact` does not install 64-bit dlls since winetricks 20180513 ([Winetricks/winetricks@f2b3d26](https://github.com/Winetricks/winetricks/commit/f2b3d268d941120d13b4c3c3960b78a879d37761))

I did as you wrote, but the sound still crunches...

**Comment by ibrokemypie** [comment]
xaudio does not solve the issue, however faudio does. Try TKG's pkgbuild to get wine with faudio

**Comment by mysticfall** [comment]
> I did it, but the issue still exists... why? I keep hearing the crisp sound

Actually, the issue came back to me as well after some time, possibly with an WINE update. So it's possible the suggested fix wouldn't work anymore.

Maybe you could have a better luck with what ibrokemypie suggested above.

**Comment by Geradot** [comment]
> xaudio does not solve the issue, however faudio does. Try TKG's pkgbuild to get wine with faudio

Can you write, how to use it or some good details about it?

**Comment by RussianNeuroMancer** [comment]
How this game works in Proton 3.16-5 if no workarounds applied? 

Edit: oh, seems like my question is already answered: https://www.protondb.com/app/414340

**Comment by NTMan** [comment]
> How this game works in Proton 3.16-5 if no workarounds applied?

For me it already work without any tricks with Proton 3.16-4, but I am on AMD.

**Comment by Geradot** [comment]
> > How this game works in Proton 3.16-5 if no workarounds applied?
> 
> For me it already work without any tricks with Proton 3.16-4, but I am on AMD.

Can you have any issues with sound?

**Comment by Geradot** [comment]
> > How this game works in Proton 3.16-5 if no workarounds applied?
> 
> For me it already work without any tricks with Proton 3.16-4, but I am on AMD.

Can you have any issues with sound?

**Comment by ziabice** [comment]
This game works perfectly with Proton 3.16-5. I played at very high graphic detail and everything was perfect. There are some slowdowns here and there due to the shaders compilation, but apart from that I can rate this game as Platinum: it just works out of the box!

Audio was perfect and impressive: I played with earphones as suggested and it was fantastic.

My specs: [https://gist.github.com/ziabice/8c19008e58f82b16a62f7ab65ba235d4](https://gist.github.com/ziabice/8c19008e58f82b16a62f7ab65ba235d4)

**Comment by Geradot** [comment]
> This game works perfectly with Proton 3.16-5. I played at very high graphic detail and everything was perfect. There are some slowdowns here and there due to the shaders compilation, but apart from that I can rate this game as Platinum: it just works out of the box!
> 
> Audio was perfect and impressive: I played with earphones as suggested and it was fantastic.
> 
> My specs: https://gist.github.com/ziabice/8c19008e58f82b16a62f7ab65ba235d4

Thanks, it works for me!

**Comment by ziabice** [comment]
> the faudio patch fixes the audio mixing, though it is still out of time with the cutscenes, a second or so faster than the visual now

I'm experiencing the same problem, only in cutscenes. But I see also a FPS drop, so maybe on my end the problem is due to my PC specs

**Comment by seeeeew** [comment]
Installing the latest FAudio build (currently [19.02](https://github.com/Kron4ek/FAudio-Builds/releases/tag/19.02)) from [Kron4ek/FAudio-Builds](https://github.com/Kron4ek/FAudio-Builds/releases) fixed the audio lag in cutscenes for me.

**Comment by AwesamLinux** [comment]
**Problem:** The game crashes before getting to the main menu, during the splash screens a window with error message pops up "fatal error!" and when clicking ok the game exits. 

I have tried this game with every Proton version available through the Steam client since release. With the very first Proton version I was able to get into gameplay (but audio and video had issues). Ever since then I can no longer even get so far as to get to the main menu. This problem occurs also on different dists, like tried it on elementary and  budgie.

Distro: Linux Mint 19.1 Tessa (64 bit)
GPU: Vega 56
Driver/LLVM version: Mesa 19.1.0-devel/9.0.0
Kernel version: 5.0.5-050005-generic
Proton version: 4.2-2

Included log of when launching the game, getting the error message window to pop up, and then just clicking Ok on the window and the game exits.
[steam-414340_Proton2.log](https://github.com/ValveSoftware/Proton/files/3070335/steam-414340_Proton2.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3070336/system_info.txt)

**Comment by DFOXpro** [comment]
Before white list this game:
1) (With proton 3.16-9 & AMD) found some [funny(colour changes)](https://steamcommunity.com/sharedfiles/filedetails/?id=1742963798), [weird(light changes)](https://steamcommunity.com/sharedfiles/filedetails/?id=1742963081) and [annoying(geometry corruption)](https://steamcommunity.com/sharedfiles/filedetails/?id=1743002915) glitches

2) (With proton 4.2-4 & AMD) --The game crash--
Update: with latest lunar-vulkan driver the game runs with 4.2-4 but still have the [funny(colour changes) glitch](https://steamcommunity.com/sharedfiles/filedetails/?id=1742963798) with postprocess medium or higher. 

So, what info/logs do you need to improve this post?
[steamSystemInfo.txt](https://github.com/ValveSoftware/Proton/files/3188444/steamSystemInfo.txt)
[hellbladeError.txt](https://github.com/ValveSoftware/Proton/files/3188451/hellbladeError.txt)

**Comment by AwesamLinux** [comment]
- GPU: RX VEGA 56
- Driver/LLVM version: 19.0.1 - padoka PPA/8.0.0
- Kernel version: 5.0.13-050013-lowlatency
- Distro version: Linux Mint 19.1 Tessa (64 bit) (Cinnamon Desktop)
- Proton version: 4.2-7
- System information: [system_info.txt](https://github.com/ValveSoftware/Proton/files/3291709/system_info.txt)


The game works for me now out of the box, and no longer crashes during launch.

It started working after I upgraded my system from 2x8GB to 4x8GB. Also, this fixed Tekken 7 that always crashed during launch for me too, but works without issues after the RAM upgrade. Also one thing these games have in common is that they run on Unreal 4.

I doubt the games require more than 16GB to play. so I suspect that this is a Threadripper specific issue that only occurs when using dual-channel memory instead of quad-channel. Most people with Threadripper CPU's would be using quad-channel memory. 

Including logs of launching the game and playing for a bit.

[steam-414340-proton-3.16-9.log](https://github.com/ValveSoftware/Proton/files/3291725/steam-414340-proton-3.16-9.log)
[steam-414340-proton-4.2-7.log](https://github.com/ValveSoftware/Proton/files/3291726/steam-414340-proton-4.2-7.log)

**Comment by sebastian-de** [comment]
For anyone with an AMD card, I can highly recommend to test ACO:
https://steamcommunity.com/app/221410/discussions/0/1640915206474070669/

Using ACO instead of LLVM fixes the stuttering and audio-sync issues on my end. Finally, Hellblade runs completely flawless on Linux for me (applies to the GOG version as well).

**Comment by puleglot** [comment]
```WINEDLLOVERRIDES="xaudio2_7=n,b"``` have fixed audio in cutscenes for me (Proton 4.11.x)

**Comment by jeroenev** [comment]
I can't even get audio crackling to stop on Windows
weird you guys manage to fix it on Linux

**Comment by neur0mancer746** [comment]
Problem: The game crashes with grahpic artifact seems due to resettting of the GPU. 

During the crash i entered in a TTY to see dmesg with [drm:amdgpu_cs_ioctl [amdgpu]] ERROR Failed to initialited parser -125 in a great number of lines. Reserching this issue i found this bug with my same exactly issue stating about resetting of GPU with a certain kernel version here, resolved with a newer kernel version (actually not included on Ubuntu 18.04.4 HWE stack, 5.4 it's for now on 20.04 but for 18.04 users upgrade will be available withing a month) https://bugzilla.kernel.org/show_bug.cgi?id=205089

My hw:
Distro: Ubuntu 18.04.4 LTS with HWE 
GPU: Radeon RX560
Driver/LLVM version: Mesa 19.2.8 (padoka PPA stable)/9.0.0
Kernel version: 5.3.0-61-generic
Proton version:5.0-9

**Comment by astatide** [comment]
I had similar threadripper issues (as reported by AwesamLinux) that seem 'fixed' when running in a VM without any NUMA topology.

Launching Hellblade resulted in a "Fatal error!" crash.  I virtualized the install with qemu/kvm (using cpu model passthrough) and GPU passthrough using 42 pinned cores, but specifically did not give the VM a numa topology.  Hellblade works as expected.  Modifying the VM to passthrough a virtual NUMA topology results in Fatal Error appearing again.

Unlike AwesamLinux, I'm running 64 GB of quad channel memory out of the gate and still hit this problem.  This suggests NUMA-related issues somehow.  For now I'm just leaving the NUMA topology disabled.  I suspect that disabling cores on the kernel launch options would workaround this problem but specifically disabling cores isn't a great solution (and I didn't try it anyway).

Distro: Arch Linux
CPU: TR 2970WX
GPU: Radeon VII
Driver/LLVM: Mesa 20.1.4-3
Kernel: 5.7.12
Proton: 5.09

**Comment by kapsh** [comment]
## System Information
- GPU: RX 5700XT
- Driver/LLVM version: mesa 20.2.2, LLVM 11.0
- Kernel version: 5.9.10-zen1
- Link to full system information report: https://gist.github.com/kapsh/384d662389acc59d29095cbbfcb08588
- Proton versions: Proton 5.0.10 from Steam, Proton 5.9-GE-8-ST

[steam-414340_proton-5.log](https://github.com/ValveSoftware/Proton/files/5610547/steam-414340_proton-5.log)
[steam-414340_proton-ge.log](https://github.com/ValveSoftware/Proton/files/5610548/steam-414340_proton-ge.log)


## Symptoms 

When starting new game, briefly shows splashscreen, then crashes to desktop.

**Comment by kisak-valve** [comment]
Hello @kapsh, your log indicates a video driver issue:
```eGame\Binaries\Win64\HellbladeGame-Win64-Shipping.exe: ../mesa-20.2.2/src/compiler/nir/nir.h:2352: nir_instr_as_alu: Assertion `parent && parent->type == nir_instr_type_alu' failed.``` leading to `wine: Assertion failed at address 00007F62D74FC945 (thread 0180), starting debugger...` and `Unhandled exception: assertion failed in 64-bit code (0x00007f62d74fc945).`

**Comment by kapsh** [comment]
@kisak-valve oh, silly me. Gotta admit I only scanned log quickly and misread it as segfault in wine. Checked another time with mesa from git master (namely https://github.com/mesa3d/mesa/commit/b3504f41733a55c7680fbd2f6240df2c0e9f8c3d): it does run (at least 5 minutes after first cutscene).

**Comment by hakzsam** [comment]
Are you still experimenting issues with RADV?

**Comment by kapsh** [comment]
@hakzsam are you asking anyone in particular? Personally I can install and test in on available mesa 20.3.3 if you need status on current release.

**Comment by hakzsam** [comment]
Yes, anyone.

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX 5700
- GPU Driver: Mesa 20.3.3 - kisak-mesa PPA
- Kernel version: 5.11.0-051100rc4-generic
- Distro version: Mint 20.1 (64bit) (Cinnamon)
- Proton version: 5.13-5

**Retest Compatibility Report**

The game still works for me with my current setup (with quad channel memory, did not try with dual channel). I did notice some blocky graphics (see the distant trees) at the intro of the game in all proton versions I tried
![screenshot3](https://user-images.githubusercontent.com/43387963/106037348-dbb0d880-60d6-11eb-9b2a-bf832d31bf0d.jpg)

This is probably completely normal just that I haven't noticed it ever before, mentioning it just in case and including a screenshot of the settings used:
![settings](https://user-images.githubusercontent.com/43387963/106038068-c1c3c580-60d7-11eb-858a-92c161a62210.jpg)

Logs:
[steam-414340-experimental-5.13-20210126.log](https://github.com/ValveSoftware/Proton/files/5882361/steam-414340-experimental-5.13-20210126.log)
[steam-414340-proton-3.16-9.log.tar.gz](https://github.com/ValveSoftware/Proton/files/5882362/steam-414340-proton-3.16-9.log.tar.gz)
[steam-414340-proton-5.13-5.log](https://github.com/ValveSoftware/Proton/files/5882363/steam-414340-proton-5.13-5.log)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/5882364/system_info.txt)

**Comment by kisak-valve** [comment]
"Hellblade Senua's Sacrifice" stopped to work after 2021 Update

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5356.
@spagoc posted on 2021-11-28T11:21:03:

On my PC, after the 2021 November update, "Hellblade Senua's Sacrifice" stopped to work giving the following error:

DX12 is not supported on your system. Try running without the -dx12 or -d3d12 command line argument.

I don't know if there is a workaround to solve the problem.
My conf:
Ryzen 3600, Nvidia 2060 Super GPU with v. 470.82.00 driver
Proton 6.3-8 and Proton Experimental
Ubuntu 21.10 with X11

**Comment by spagoc** [comment]
The game works  again with "-d3d11" as start option.
It appears that the two patches of 2021 (November and 7th December) have ported the game to DirectX 12 API in a way that is not yet compatible with Proton.

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX 5700
- GPU Driver: Mesa 21.3.1 - kisak-mesa PPA
- Kernel version: 5.13.0-22-generic
- Distro version: Mint 20.1 (64bit) (Cinnamon)
- Proton version: 6.3-8

App ID: 414340
Build ID: 7800612

Game with the most recent update is working on my setup with DX12

As for the blocky graphics issue that I previously pointed out, I have checked occured on different system on Windows too (you just have to pay close attention to spot it). So that was not a Proton/driver issue.

**Comment by RobinMorrisLuo** [comment]
System Information:

- GPU: AMD Radeon RX 6900 XT
- GPU Driver: AMDVLK
- Kernel version: 6.6.0
- Distro version: Ubuntu 22.04
- Proton version : Proton Experimental

Hi , this Game observed crash or hang in Proton Experimental, while works well under Proton 8.0-4. 
And the rendered scene looks very slowly on Radv under Proton experimental, while looks better under Proton 8.0-4.


Could anyone have a look  ?  : )

Thanks

There attached the crash and hang info.

Crash Info:

![image](https://github.com/ValveSoftware/Proton/assets/51236171/aa782573-99d9-4a0d-ba80-cfe48b9227c0)


<details><summary>Hang Info:</summary>

```
[166713.308969] amdgpu 0000:09:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:88 vmid:4 pasid:32781, for process HellbladeGame-W pid 2538499 thread HellbladeGame-W pid 2538499)
[166713.308978] amdgpu 0000:09:00.0: amdgpu:   in page starting at address 0x0000000000000000 from client 0x1b (UTCL2)
[166713.308982] amdgpu 0000:09:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x004012B0
[166713.308985] amdgpu 0000:09:00.0: amdgpu:     Faulty UTCL2 client ID: SQC (inst) (0x9)
[166713.308987] amdgpu 0000:09:00.0: amdgpu:     MORE_FAULTS: 0x0
[166713.308990] amdgpu 0000:09:00.0: amdgpu:     WALKER_ERROR: 0x0
[166713.308992] amdgpu 0000:09:00.0: amdgpu:     PERMISSION_FAULTS: 0xb
[166713.308994] amdgpu 0000:09:00.0: amdgpu:     MAPPING_ERROR: 0x0
[166713.308996] amdgpu 0000:09:00.0: amdgpu:     RW: 0x0
[166713.309118] amdgpu 0000:09:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:88 vmid:4 pasid:32781, for process HellbladeGame-W pid 2538499 thread HellbladeGame-W pid 2538499)
[166713.309123] amdgpu 0000:09:00.0: amdgpu:   in page starting at address 0x0000000000000000 from client 0x1b (UTCL2)
[166713.309126] amdgpu 0000:09:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x004012B0
[166713.309128] amdgpu 0000:09:00.0: amdgpu:     Faulty UTCL2 client ID: SQC (inst) (0x9)
[166713.309131] amdgpu 0000:09:00.0: amdgpu:     MORE_FAULTS: 0x0
[166713.309133] amdgpu 0000:09:00.0: amdgpu:     WALKER_ERROR: 0x0
[166713.309135] amdgpu 0000:09:00.0: amdgpu:     PERMISSION_FAULTS: 0xb
[166713.309137] amdgpu 0000:09:00.0: amdgpu:     MAPPING_ERROR: 0x0
[166713.309139] amdgpu 0000:09:00.0: amdgpu:     RW: 0x0
[166713.309152] amdgpu 0000:09:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:88 vmid:4 pasid:32781, for process HellbladeGame-W pid 2538499 thread HellbladeGame-W pid 2538499)
[166713.309156] amdgpu 0000:09:00.0: amdgpu:   in page starting at address 0x0000000000000000 from client 0x1b (UTCL2)
[166713.309159] amdgpu 0000:09:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x004012B1
[166713.309161] amdgpu 0000:09:00.0: amdgpu:     Faulty UTCL2 client ID: SQC (inst) (0x9)
[166713.309163] amdgpu 0000:09:00.0: amdgpu:     MORE_FAULTS: 0x1
[166713.309165] amdgpu 0000:09:00.0: amdgpu:     WALKER_ERROR: 0x0
[166713.309167] amdgpu 0000:09:00.0: amdgpu:     PERMISSION_FAULTS: 0xb
[166713.309169] amdgpu 0000:09:00.0: amdgpu:     MAPPING_ERROR: 0x0
[166713.309171] amdgpu 0000:09:00.0: amdgpu:     RW: 0x0
[166713.309177] amdgpu 0000:09:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:88 vmid:4 pasid:32781, for process HellbladeGame-W pid 2538499 thread HellbladeGame-W pid 2538499)
[166713.309180] amdgpu 0000:09:00.0: amdgpu:   in page starting at address 0x0000000000000000 from client 0x1b (UTCL2)
[166713.309182] amdgpu 0000:09:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x004012B0
[166713.309184] amdgpu 0000:09:00.0: amdgpu:     Faulty UTCL2 client ID: SQC (inst) (0x9)
[166713.309187] amdgpu 0000:09:00.0: amdgpu:     MORE_FAULTS: 0x0
[166713.309189] amdgpu 0000:09:00.0: amdgpu:     WALKER_ERROR: 0x0
[166713.309191] amdgpu 0000:09:00.0: amdgpu:     PERMISSION_FAULTS: 0xb
[166713.309193] amdgpu 0000:09:00.0: amdgpu:     MAPPING_ERROR: 0x0
[166713.309195] amdgpu 0000:09:00.0: amdgpu:     RW: 0x0
[166713.309200] amdgpu 0000:09:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:88 vmid:4 pasid:32781, for process HellbladeGame-W pid 2538499 thread HellbladeGame-W pid 2538499)
[166713.309204] amdgpu 0000:09:00.0: amdgpu:   in page starting at address 0x0000000000000000 from client 0x1b (UTCL2)
[166713.309206] amdgpu 0000:09:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x004012B1
[166713.309208] amdgpu 0000:09:00.0: amdgpu:     Faulty UTCL2 client ID: SQC (inst) (0x9)
[166713.309210] amdgpu 0000:09:00.0: amdgpu:     MORE_FAULTS: 0x1
[166713.309212] amdgpu 0000:09:00.0: amdgpu:     WALKER_ERROR: 0x0
[166713.309214] amdgpu 0000:09:00.0: amdgpu:     PERMISSION_FAULTS: 0xb
[166713.309216] amdgpu 0000:09:00.0: amdgpu:     MAPPING_ERROR: 0x0
[166713.309218] amdgpu 0000:09:00.0: amdgpu:     RW: 0x0
[166713.309224] amdgpu 0000:09:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:88 vmid:4 pasid:32781, for process HellbladeGame-W pid 2538499 thread HellbladeGame-W pid 2538499)
[166713.309227] amdgpu 0000:09:00.0: amdgpu:   in page starting at address 0x0000000000000000 from client 0x1b (UTCL2)
[166713.309230] amdgpu 0000:09:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x004012B1
[166713.309232] amdgpu 0000:09:00.0: amdgpu:     Faulty UTCL2 client ID: SQC (inst) (0x9)
[166713.309234] amdgpu 0000:09:00.0: amdgpu:     MORE_FAULTS: 0x1
[166713.309236] amdgpu 0000:09:00.0: amdgpu:     WALKER_ERROR: 0x0
[166713.309238] amdgpu 0000:09:00.0: amdgpu:     PERMISSION_FAULTS: 0xb
[166713.309240] amdgpu 0000:09:00.0: amdgpu:     MAPPING_ERROR: 0x0
[166713.309242] amdgpu 0000:09:00.0: amdgpu:     RW: 0x0
[166713.309247] amdgpu 0000:09:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:88 vmid:4 pasid:32781, for process HellbladeGame-W pid 2538499 thread HellbladeGame-W pid 2538499)
[166713.309251] amdgpu 0000:09:00.0: amdgpu:   in page starting at address 0x0000000000000000 from client 0x1b (UTCL2)
[166713.309253] amdgpu 0000:09:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x004012B1
[166713.309255] amdgpu 0000:09:00.0: amdgpu:     Faulty UTCL2 client ID: SQC (inst) (0x9)
[166713.309257] amdgpu 0000:09:00.0: amdgpu:     MORE_FAULTS: 0x1
[166713.309259] amdgpu 0000:09:00.0: amdgpu:     WALKER_ERROR: 0x0
[166713.309261] amdgpu 0000:09:00.0: amdgpu:     PERMISSION_FAULTS: 0xb
[166713.309263] amdgpu 0000:09:00.0: amdgpu:     MAPPING_ERROR: 0x0
[166713.309265] amdgpu 0000:09:00.0: amdgpu:     RW: 0x0
[166713.309270] amdgpu 0000:09:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:88 vmid:4 pasid:32781, for process HellbladeGame-W pid 2538499 thread HellbladeGame-W pid 2538499)
[166713.309274] amdgpu 0000:09:00.0: amdgpu:   in page starting at address 0x0000000000000000 from client 0x1b (UTCL2)
[166713.309276] amdgpu 0000:09:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x004012B1
[166713.309278] amdgpu 0000:09:00.0: amdgpu:     Faulty UTCL2 client ID: SQC (inst) (0x9)
[166713.309280] amdgpu 0000:09:00.0: amdgpu:     MORE_FAULTS: 0x1
[166713.309282] amdgpu 0000:09:00.0: amdgpu:     WALKER_ERROR: 0x0
[166713.309284] amdgpu 0000:09:00.0: amdgpu:     PERMISSION_FAULTS: 0xb
[166713.309286] amdgpu 0000:09:00.0: amdgpu:     MAPPING_ERROR: 0x0
[166713.309289] amdgpu 0000:09:00.0: amdgpu:     RW: 0x0
[166713.309294] amdgpu 0000:09:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:88 vmid:4 pasid:32781, for process HellbladeGame-W pid 2538499 thread HellbladeGame-W pid 2538499)
[166713.309297] amdgpu 0000:09:00.0: amdgpu:   in page starting at address 0x0000000000000000 from client 0x1b (UTCL2)
[166713.309300] amdgpu 0000:09:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x004012B1
[166713.309302] amdgpu 0000:09:00.0: amdgpu:     Faulty UTCL2 client ID: SQC (inst) (0x9)
[166713.309304] amdgpu 0000:09:00.0: amdgpu:     MORE_FAULTS: 0x1
[166713.309306] amdgpu 0000:09:00.0: amdgpu:     WALKER_ERROR: 0x0
[166713.309308] amdgpu 0000:09:00.0: amdgpu:     PERMISSION_FAULTS: 0xb
[166713.309310] amdgpu 0000:09:00.0: amdgpu:     MAPPING_ERROR: 0x0
[166713.309312] amdgpu 0000:09:00.0: amdgpu:     RW: 0x0
[166713.309318] amdgpu 0000:09:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:88 vmid:4 pasid:32781, for process HellbladeGame-W pid 2538499 thread HellbladeGame-W pid 2538499)
[166713.309321] amdgpu 0000:09:00.0: amdgpu:   in page starting at address 0x0000000000000000 from client 0x1b (UTCL2)
[166713.309323] amdgpu 0000:09:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x004012B1
[166713.309325] amdgpu 0000:09:00.0: amdgpu:     Faulty UTCL2 client ID: SQC (inst) (0x9)
[166713.309328] amdgpu 0000:09:00.0: amdgpu:     MORE_FAULTS: 0x1
[166713.309330] amdgpu 0000:09:00.0: amdgpu:     WALKER_ERROR: 0x0
[166713.309332] amdgpu 0000:09:00.0: amdgpu:     PERMISSION_FAULTS: 0xb
[166713.309334] amdgpu 0000:09:00.0: amdgpu:     MAPPING_ERROR: 0x0
[166713.309336] amdgpu 0000:09:00.0: amdgpu:     RW: 0x0

```

</details>

**Comment by Blisto91** [comment]
@MrRobbin Hi there.
Experimental have enabled the support for Ray Tracing out of the box so i assume radv is slow there because the game turns it on in the options. As for the crash or hang when using amdvlk if the same doesn't happen with radv then it is probably better to report at the amdvlk tracker.

**Comment by kisak-valve** [comment]
[Regression] Hellblade Senoa's sacrifice (414340)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/7488.
@HarissaHero posted on 2024-02-09T19:12:42:

# Compatibility Report
- Name of the game with compatibility issues: Hellblade Senoa's sacrifice
- Steam AppID of the game: 414340

## System Information
- GPU: RX 650 XT
- Video driver version: Mesa 23.2.0-devel
- Kernel version: Ubuntu 23.10
- Proton version: 8.0-5 and Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Crash on startup with error 
![image](https://github.com/ValveSoftware/Proton/assets/99407640/bfb83df0-531a-4b8f-89f1-66f113cc7260)

Works fine with Proton 7, according to other's tests seems to work with proton 8.0-4

## Reproduction
Run the game with compatibility

**Comment by kisak-valve** [comment]
Hello @HarissaHero, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by lyingpasta** [comment]
Hi @kisak-valve, sure here are the files: 
[Steam Runtime Diagnostics](https://gist.github.com/HarissaHero/9d0879618d4b6f3a1fdfcf57baaf9f84)
[steam-414340.log](https://github.com/ValveSoftware/Proton/files/14233429/steam-414340.log)

**Comment by kisak-valve** [comment]
Thanks, the extended diagnostics tells us that you're using mesa/RADV 23.2.1 (https://gist.github.com/HarissaHero/9d0879618d4b6f3a1fdfcf57baaf9f84#file-gistfile1-txt-L310) and `warn:seh:handle_syscall_fault backtrace: --- Exception 0xc0000005 at 0x7ff9a08c3d34: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/vulkan/08/libvulkan_radeon.so + 0x2c3d34.` hints that there was an access violation (c0000005) in the video driver.

Mesa 23.2.1 was the first point release that enabled raytracing by default with RADV. I'd test how the game behaves with a newer build of mesa from a PPA like [oibaf](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) or [kisak-mesa](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa), but I'm also seeing there's mesa installed in `/opt/amdgpu` (https://gist.github.com/HarissaHero/9d0879618d4b6f3a1fdfcf57baaf9f84#file-gistfile1-txt-L998) and we've seen driver dependency problems between stuff in /opt and PPAs so some extra care is needed there.
